### ISSUE TITLE
Support API 23

### ISSUE THREAD

**Issue by erd** [robolectric/robolectric#1865] opened 2015-06-04 02:05 UTC
Add support for Android M.

**Comment by jaredsburrows** [comment] 2015-06-04 02:09
+1

**Comment by nasahapps** [comment] 2015-06-08 22:46
Or just, idk, stop putting a limit on the SDK version it's compatible with.  We can't keep waiting around every time Google releases a new SDK version for you guys at Roboletric to change a hard-coded number.

**Comment by jaredsburrows** [comment] 2015-06-09 01:13
+1

**Comment by jongerrish** [comment] 2015-06-09 02:19
@nasahapps - Any specific suggestions?

We could allow you to specify sdk = 23, and if its not supported pick the maximum supported version but still set Build.VERSION.SDK_INT = 23. We could do the same with the minimum version also. The downside is that in a not supported version you are taking a risk and the behaviour is not necessarily obvious to the developer.

Thoughts?

**Comment by jaredsburrows** [comment] 2015-06-09 02:25
+3 @jongerrish  I am a fan of that.

**Comment by mag** [comment] 2015-06-09 14:43
Seems reasonable. I can think of two solutions to the non-obviousness: 1) print a big fat warning that Robolectric is actually running against an older SDK than intended, or 2) fail unless the developer sets another config variable specifically allowing Robolectric to run in this inconsistent state. Even if we implement the latter, a warning is probably appropriate.

**Comment by erd** [comment] 2015-06-10 00:48
@jongerrish I'm on the fence. Yes, it would be nice, but it may not be obvious that Robolectric would be using a sdk other than the one the user specified. Even if we print a warning, my experience leads me to believe that few will read it, and most people will just open an issue here. I think that we should just throw an exception if a user specifies an sdk that we don't support with instructions on how to run against a different version.

**Comment by erd** [comment] 2015-06-10 00:50
> We can't keep waiting around every time Google releases a new SDK version for you guys at Roboletric to change a hard-coded number.

Maybe if more people helped out with PR's, it wouldn't take as long :)

**Comment by jongerrish** [comment] 2015-06-10 02:20
I actually agree with Erich.

I remember having to integrate the reportSdk / emulateSdk -> sdk change into our codebase at Google which was a huge job. There were many cases where the test author was obviously confused about the difference. Some tests with only reportsSdk when they clearly get better testing fidelity by using emulateSdk and other times setting both reportSdk and emulateSdk to the same value and other times still when different arbitrary values were chosen. I think removing reportSdk was a good thing and I'm a little hesitant to have special behavior when you are outside the set of supported sdks.

The current workaround is to explicitly use ReflectionHelper to set Build.VERSION.SDK_INT which forces the test writer to think about what they are doing.

Perhaps we could do a better job with supporting API 22 earlier, but as Erich says, this is a free, community project, so the best thing to do is contribute Pull Requests.

**Comment by jaredsburrows** [comment] 2015-06-10 02:30
@jongerrish This is interesting. Does Google use Robolectric for testing all of their apps?

**Comment by jongerrish** [comment] 2015-06-10 02:33
Each team is free to pursue their own testing strategy but I can say that Robolectric is used widely by many apps teams at Google.

It has its wrinkles and quirks but its better than any alternative that I know of.

**Comment by jaredsburrows** [comment] 2015-06-10 02:38
I'd say, everyones best bet is to use Robolectric(with Mockito sometimes for listeners, etc) for Unit testing + Espresso for Instrumentation testing.

@jongerrish Thanks for your insights. I sorta wish Google would pick up/support Robolectric just like they did for Espresso.

**Comment by mag** [comment] 2015-06-10 03:59
@jaredsburrows +1

**Comment by hamen** [comment] 2015-10-05 15:38
Hi all
The project I'm working on is targeting API 23 and I was hoping that a
```java
@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 23)
```
and a 
```
testCompile "org.robolectric:robolectric:3.1-SNAPSHOT"
``` 
could work. Instead I'm getting:
```java
Exception in thread "main" java.lang.annotation.AnnotationFormatError: Invalid default: public abstract java.lang.Class org.robolectric.annotation.Config.application()
```
if I run the tests in Android Studio and a
```java
java.lang.UnsupportedOperationException: Robolectric does not support API level 23.
```
if I run them with `gradlew`. Any news on the topic, please?

**Comment by jongerrish** [comment] 2015-10-05 15:56
We can't support api 23 until Google release the aosp code, which should be
soon.

It took me just a few days to add 22 support to Robolectric so I don't
think you'll be waiting too long. As I've blocked off some time to work on
this.

**Comment by hamen** [comment] 2015-10-05 15:59
Jonathan, this is great news! I know, this API version compatibility issue is a pain in neck for you. Thanks, man.

**Comment by jongerrish** [comment] 2015-10-05 23:16
So Google released the AOSP code today:-

https://github.com/android/platform_frameworks_base/tree/marshmallow-release

I'll try and start this week.

**Comment by erd** [comment] 2015-10-11 20:29
@jongerrish I've built an android-all jar for M and pushed a branch (`support-api-23`) that configures robolectric to build against the jar. Feel free to check out this branch and push commits to it as you get tests working. I'd like to hold off releasing the android-all jar to maven central until we get all the tests passing.

**Comment by hamen** [comment] 2015-10-30 11:28
Any news, guys?

**Comment by jongerrish** [comment] 2015-10-30 18:06
Haven't had a chance to work on it yet, sorry. Maybe next week.

**Comment by hk0i** [comment] 2015-11-03 21:31
Next week is this week, I hope? :)

**Comment by gustavkarlsson** [comment] 2015-11-23 14:02
Any news on this? Is it just around the corner or far away?

**Comment by Nolanus** [comment] 2015-12-01 18:52
+1

**Comment by justinharrison** [comment] 2015-12-16 20:10
Any update on SDK 23 support?

**Comment by jaredsburrows** [comment] 2015-12-23 08:09
@jongerrish Hey how are you doing with API 23? :)

**Comment by jongerrish** [comment] 2015-12-23 16:28
Tom and I have made good progress. Just three classes of failing tests
left. We should hopefully have the branch with all tests passing and ready
to merge in a week if all goes well.

**Comment by mag** [comment] 2015-12-23 17:42
@jongerrish :sparkling_heart:

**Comment by jongerrish** [comment] 2015-12-23 17:57
For those interested, the work is taking place on the following branch:-

https://github.com/robolectric/robolectric/tree/support-api-23

The remaining work is:-

1 Animation Test (forget which) is failing.
ShadowCookieManager tests are failing due (removed in api 23) dependency on
apache. Tom is reimplementing without apache.
2 date tests failing due to missing tz data resources that need to be
included in the android jar.

**Comment by jongerrish** [comment] 2015-12-26 00:01
Just fixed #1

**Comment by erd** [comment] 2015-12-26 18:36
I've been working on building a new android-all, but keep running into issues. I'll should be able to work through it when I get back home from vacation.

**Comment by jaredsburrows** [comment] 2015-12-26 20:25
@jongerrish @erd Thanks for you hard work!

@erd Relax and enjoy your vacation!

**Comment by Teejay005** [comment] 2016-01-10 07:28
@jongerrish Please do you have any update on this fix?

**Comment by erd** [comment] 2016-01-12 04:44
@jongerrish Is there a target I can use to only build the java code in AOSP? I'm trying to build with `ANDROID_COMPILE_WITH_JACK=false make -j8` but it keeps failing when running ProGuard on the Gallery app. Is there a more appropriate target I should be using?

**Comment by tmrudick** [comment] 2016-01-12 23:50
@erd I think the Gallery app is in the generic_no_telephony make file which is the base for most things (including aosp_base). I remember seeing this issue before but thought it got checked in.

I will take a look at it tomorrow and figure out why we would be getting the proguard errors.

**Comment by tmrudick** [comment] 2016-01-13 16:10
I'm not sure if there is a non-Jack friendly lunch target with Marshmallow. I will investigate a bit more this week (or see if we can add one).

In the meantime, is it possible to tapas all of the required artifacts and build them separately? For example:
```bash
$ tapas core-libart services services.accessibility telephony-common framework ext icu4j-icudata-jarjar
$ ANDROID_COMPILE_WITH_JACK=false make -j8
```

Running all of the tests now building android-all this way. With this, you will have to change the location that the script expects tzdata to reside (generic_x86 -> generic).

Looking through my bash history it looks like I was previously, lunching aosp_full and building with Jack, then using tapas to build any leaf dependencies which only had .jack outputs with Jack disabled.

**Comment by tmrudick** [comment] 2016-01-13 20:07
It appears that all of the expected tests pass when using tapas instead of lunch to build android-all artifacts without Jack.

**Comment by erd** [comment] 2016-01-17 19:44
I re-built the jar with tapas (including the path fix for the tzdata file), but am seeing a few test failures:

Failed tests:
  ShadowDateUtilsTest.formatDateTime_worksSinceKitKat:24 expected:<"1/1[]"> but was:<"1/1[/2015]">
  ShadowDateUtilsTest.formatDateTime_worksSinceKitKat:24 expected:<"1/1[]"> but was:<"1/1[/2015]">
  ShadowDateUtilsTest.formatDateTime_worksSinceKitKat:24 expected:<"1/1[]"> but was:<"1/1[/2015]">

Tests in error:
  ShadowDateIntervalFormatTest.testDateInterval_FormatDateRange:34 » Verify clas...
  ShadowDateUtilsTest.formatDateTime_worksSinceKitKat:23 » Verify class android....

Tests run: 14552, Failures: 3, Errors: 2, Skipped: 21

Is there anything else I could be missing?

**Comment by tmrudick** [comment] 2016-01-17 23:07
There are these 3 tests which are still failing with the 6.0 jar. @erd, unsure if you have see the Verify class error before? It is caused by an instrumented class overriding a final method. I figure this has something to do with how the class loader is handling final methods + inheritance but haven't yet had a chance to dive into the code.

**Comment by tmrudick** [comment] 2016-01-17 23:07
I will take a look at the 1/1 vs 1/1/2015 errors tomorrow/tuesday.

**Comment by tmrudick** [comment] 2016-01-21 14:22
Rebasing the support-api-23 branch should fix the ShadowDateUtilsTest.formatDateTime_worksSinceKitKat tests on L and lower. @erd or @jongerrish can you rebase?

**Comment by tmrudick** [comment] 2016-01-21 15:35
Just sent out https://github.com/robolectric/robolectric/pull/2219 to fix the class verification issue. It is a short-term fix but will unblock supporting API 23 for now.

**Comment by tmrudick** [comment] 2016-01-21 15:57
Also https://github.com/robolectric/robolectric/pull/2220 to update the build-android script with the instructions above for M+ targets.

**Comment by jongerrish** [comment] 2016-01-21 18:40
Merged both of these PRs.

Erich, can we try merging this into master?

**Comment by erd** [comment] 2016-01-21 19:28
I'm going to rebase it against master and make sure that all the tests pass before merging.

**Comment by erd** [comment] 2016-01-21 23:04
I rebuilt the android-all jar with @tmrudick's additions and released it into Maven Central. After rebasing the branch, I still kept seeing a failure with `ShadowDateUtilsTest.formatDateTime_withCurrentYear_worksSinceKitKat` (I confirmed that the tzdata file is included in the jar). There's a chance that I screwed up the rebase, but since that's the only failure, I don't want to hold up merging this branch. I went ahead and removed `M` from the list of sdks used to run the test.

Thanks for all the hard work!

**Closed** 2016-01-22 01:20 UTC
Labels: 3.1, enhancement

**Comment by tmrudick** [comment] 2016-01-22 11:12
Thanks @erd! It is strange that those tests are failing for M. With the android-all jar that I have built, they are passing. I do see them failing with the jar in maven. It doesn't look like there are any huge differences.

**Comment by ksprash** [comment] 2016-02-11 15:13
I am new to Roboelctric and encountered this issue "Robolectric does not support API level 23". Looking at this thread the fix has been done. Do I need to build roboelectric of the support-sdk-23 branch or is there a repository version that I can download from?

**Comment by erd** [comment] 2016-02-11 17:38
You'll need to use `3.1-SNAPSHOT` instead of the released version if you need API 23 support. Instructions on how to use the snapshot build are in the README.

**Comment by RayConnolly** [comment] 2016-03-14 12:23
Hi @erd....Is it still the case that the 3.1-SNAPSHOT must be used to support API 23, and if so what other steps are needed to use this build, as i can't see anything in the README about this, cheers!

**Comment by IgorGanapolsky** [comment] 2016-03-31 16:59
When I try to use 3.1-SNAPSHOT, I get a build error:
> Error:Conflict with dependency 'com.google.guava:guava'. Resolved versions for app (18.0) and test app (19.0-rc2) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

**Comment by alxndrsn** [comment] 2016-05-02 14:07
@RayConnolly `3.1-rc1` is working for me.

**Comment by alxndrsn** [comment] 2016-05-03 17:48
`3.1-rc1` was working for me... but due to #2429 I can't use it.
