### ISSUE TITLE
Can not change default repository config to local repository.

### ISSUE THREAD

**Issue by Sydmoon** [robolectric/robolectric#5801] opened 2020-07-29 02:47 UTC
Hello，

I'm using Robolectric 4.3.1, Android Gradle Plugin Version 3.4.0. While changing default to my local repositories it doesn't work as your guide. Here is my code.

```
  testOptions {
    unitTests.all {
      systemProperty 'robolectric.dependency.repo.url', 'https://local-mirror/repo'
      systemProperty 'robolectric.dependency.repo.id', 'local'
    }
  }
```

I found there are some other ways to solve this problem like manually downloading android-all-10-robolectric-5803371 or extending RobolectricTestRunner. But it is not very convenient to let others to use. Could you offer me more advices.

**Comment by hoisie** [comment] 2020-08-09 06:26
Seems like this could be a dupe of https://github.com/robolectric/robolectric/issues/5305

**Closed** 2020-09-08 08:46 UTC
