### ISSUE TITLE
TabHost's getTabWidget() returns null although the object contains mTabWidget

### ISSUE THREAD

**Issue by apex39** [robolectric/robolectric#1980] opened 2015-08-07 10:14 UTC
In my Robolectric test I run my fragment by:

```
sut = new TestedFragment();
SupportFragmentTestUtil.startFragment(sut);
```

In fragment's `onCreateView` I have `android.support.v4.app.FragmentTabHost` on which I try to get its `tabWidget` using:

```
inflatedView = inflater.inflate(R.layout.some_layout, container, false);
tabHost = (FragmentTabHost) inflatedView.findViewById(android.R.id.tabhost);
fragmentManager = getChildFragmentManager();
tabHost.setup(getActivity(), fragmentManager, android.R.id.tabcontent);
tabHost.getTabWidget(); //returns null
```

This line returns null although set up breakpoint on this line shows me that `tabHost`'s `mTabWidget` has value of 
`android.widget.TabWidget{7a4d42e6 V.E..... ......I. 0,0-0,0 #1020013 android:id/tabs}` so why do I get `null`?

**Comment by jaredsburrows** [comment] 2015-08-27 00:52
Use `TabLayout`, not tabhosts.

**Comment by jacksparser** [comment] 2016-09-09 06:34
Does this mean that since TabHost is deprecated, it is not supported in Robolectric?

**Comment by jongerrish** [comment] 2018-11-05 00:48
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

**Closed by jongerrish** 2018-11-05 00:48 UTC
