### ISSUE TITLE
mockito+realm: Cannot convert type DeferredElementImpl to type org.w3c.dom.Node

### ISSUE THREAD

**Issue by drofnnuD** [robolectric/robolectric#2944] opened 2017-03-03 11:53 UTC
Updated to Robolectric 3.3 today because I was having the issues with powermock that 3.3 fixed, upon running the test I get the following stacktrace.

```
com.thoughtworks.xstream.converters.ConversionException: Cannot convert type com.sun.org.apache.xerces.internal.dom.DeferredElementImpl to type org.w3c.dom.Node
---- Debugging information ----
message             : Cannot convert type com.sun.org.apache.xerces.internal.dom.DeferredElementImpl to type org.w3c.dom.Node
class               : org.robolectric.manifest.AndroidManifest
required-type       : org.robolectric.manifest.AndroidManifest
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /org.powermock.modules.junit4.rule.PowerMockStatement$1/outer-class/fNext/next/val$roboMethod/appManifest/applicationNode
line number         : 760
class[1]            : org.robolectric.RobolectricTestRunner$RobolectricFrameworkMethod
class[2]            : org.robolectric.RobolectricTestRunner$HelperTestRunner$1
class[3]            : org.junit.internal.runners.statements.RunBefores
class[4]            : org.powermock.modules.junit4.rule.PowerMockStatement
class[5]            : org.powermock.modules.junit4.rule.PowerMockStatement$1
version             : not available
-------------------------------

	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:456)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1230)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1214)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1085)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1076)
	at org.powermock.classloading.DeepCloner.clone(DeepCloner.java:55)
	at org.powermock.classloading.AbstractClassloaderExecutor.executeWithClassLoader(AbstractClassloaderExecutor.java:56)
	at org.powermock.classloading.SingleClassloaderExecutor.execute(SingleClassloaderExecutor.java:67)
	at org.powermock.classloading.AbstractClassloaderExecutor.execute(AbstractClassloaderExecutor.java:43)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:75)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:209)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)`
```

The test itself is fairly simple just checking that an Activity is not Null, below this is the activity code, and the test for that activity.

```java
public class SecondActivity extends BaseActivity {

    private Realm realm;

    private User user;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_second);

        Realm.init(this);

        realm = Realm.getDefaultInstance();

        getUser();
    }

    private void getUser(){
        RealmResults<User> realmUsers = realm.where(User.class).findAll();
        user = realmUsers.first();
        Log.d("Test", user.getFirstName() + " " + user.getLastName() + " Null Maybz");
    }
}
```

and the test.

```java
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, sdk = Build.VERSION_CODES.LOLLIPOP, manifest = "AndroidManifest.xml")
@PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*"})
@PrepareForTest({Realm.class, RealmConfiguration.class,
        RealmQuery.class, RealmResults.class, RealmCore.class, RealmResults.class})
public class SecondActivityTest {`

    @Rule
    public PowerMockRule rule = new PowerMockRule();

    private SecondActivity activity;

    private RealmResults<User> realmUsers;

    @Before
    public void setUp(){
        MockitoAnnotations.initMocks(this);

        // Setup Realm + Mock
        mockStatic(Realm.class);
        mockStatic(RealmConfiguration.class);
        mockStatic(RealmCore.class);
        mockStatic(RealmQuery.class);

        final Realm mockRealm = mock(Realm.class);
        doNothing().when(RealmCore.class);
        RealmCore.loadLibrary(any(Context.class));

        when(Realm.getDefaultInstance()).thenReturn(mockRealm);
        when(mockRealm.createObject(User.class)).thenReturn(new User());

        User userOne = new User("Matt", "Dunn");
        User userTwo = new User("Michael", "Stoddart");

        List<User> userList = Arrays.asList(userOne, userTwo);

        RealmQuery<User> realmQuery = mockRealmQuery();
        RealmResults<User> mockResults = mockRealmResults();

        when(mockResults.iterator()).thenReturn(userList.iterator());
        when(mockResults.size()).thenReturn(userList.size());

        when(mockResults.first()).thenReturn(userList.get(0));

        activity = Robolectric.setupActivity(SecondActivity.class);
    }

    @Test
    public void checkActivityNotNull(){
        Assert.assertNotNull(activity);
    }

    @SuppressWarnings("unchecked")
    private <T extends RealmObject> RealmQuery<T> mockRealmQuery() {
        return mock(RealmQuery.class);
    }

    @SuppressWarnings("unchecked")
    private <T extends RealmObject> RealmResults<T> mockRealmResults() {
        return mock(RealmResults.class);
    }
}
```

I've followed Realms example for writing a unit test with Robo and Mockito that can be found here. 

https://github.com/realm/realm-java/blob/master/examples/unitTestExample/src/test/java/io/realm/examples/unittesting/ExampleActivityTest.java

Obviously that can be considered a little out of date, what with the update to Robo 3.3.

Using Robolectric 3.3 and min SDK version of 17, and a target SDK version of 25

Cheers.

**Comment by jongerrish** [comment] 2017-03-03 18:49
Can you put a break point in and see what classloader loaded each of those
two classes? They should be assignment compatible but obviously they are
not. I suspect it is because they are loaded from different classloaders.

`com.thoughtworks.xstream.converters.ConversionException: Cannot convert
type com.sun.org.apache.xerces.internal.dom.DeferredElementImpl to type
org.w3c.dom.Node

**Comment by ch-vadim-maximov** [comment] 2017-03-03 23:01
+1 I'm getting the same error.

**Comment by jongerrish** [comment] 2017-03-03 23:03
Ok, can someone check the classloaders for these classes then, we'll work
on a follow up fix for this.

It's actually a bunch of classes are probably getting loaded from the wrong
place so it's def. Something we want to fix asap.

**Comment by ch-vadim-maximov** [comment] 2017-03-04 00:52
@jongerrish Could you clarify where you want to breakpoint? This is happening before setUp() is executed.

**Comment by yharsh** [comment] 2017-03-04 04:18
+1 I am also facing the same issue.

**Comment by yharsh** [comment] 2017-03-04 05:13
This [classpath.txt](https://github.com/robolectric/robolectric/files/818426/classpath.txt) provides the maven classpath used during test run.

**Comment by sureshjoshi** [comment] 2017-03-04 22:54
Oh how I wish I read this 3 hours ago - just got knocked over the head with this one too. Not sure where you'd like breakpoint info from.

**Comment by jongerrish** [comment] 2017-03-04 23:22
Can we get a simple test case the illustrates this failure please? If you
can get us this we'll work on a fix and a 3.3.1 release asap.

On Mar 4, 2017 2:54 PM, "Suresh Joshi" <notifications@github.com> wrote:

Oh how I wish I read this 3 hours ago - just got knocked over the head with
this one too. Not sure where you'd like breakpoint info from.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/robolectric/robolectric/issues/2944#issuecomment-284190778>,
or mute the thread

**Comment by sureshjoshi** [comment] 2017-03-04 23:39
Roger. Coming up in a few minutes - was able to reproduce in a trivial app. Just cutting out yet more code to see what happens.

**Comment by sureshjoshi** [comment] 2017-03-04 23:49
Here is a trivial project which reproduces the problem.

[Robo2944.zip](https://github.com/robolectric/robolectric/files/819011/Robo2944.zip)

## Executive Summary

### LoginActivity.java

    public class LoginActivity extends AppCompatActivity {
        public static int foo() {
            return 1;
        }

### build.gradle

    testCompile 'junit:junit:4.12'
    testCompile 'org.robolectric:robolectric:3.3'
    testCompile 'org.mockito:mockito-core:2.7.13'
    testCompile "org.powermock:powermock-api-mockito2:1.7.0RC2"
    testCompile "org.powermock:powermock-module-junit4:1.7.0RC2"
    testCompile "org.powermock:powermock-module-junit4-rule:1.7.0RC2"
    testCompile "org.powermock:powermock-classloading-xstream:1.7.0RC2"

### LoginActivityTest.java

    @RunWith(RobolectricTestRunner.class)
    @Config(constants = BuildConfig.class, sdk = 21)
    @PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*"})
    @PrepareForTest(LoginActivity.class)
    public class LoginActivityTest {

        @Rule
        public PowerMockRule rule = new PowerMockRule();

        @Before
        public void setup() {
            PowerMockito.mockStatic(LoginActivity.class);
            PowerMockito.when(LoginActivity.foo()).thenReturn(9999);
        }

        @Test
        public void foo_returns9999_hopefully() {
            assertEquals(LoginActivity.foo(), 9999);
        }

        @Test
        public void foo_doesNotReturn1() {
             assertNotEquals(LoginActivity.foo(), 1);
        }

**Comment by drofnnuD** [comment] 2017-03-06 08:14
I've created a repo here that shows the problem I'm having, will play around with debug and some breakpoints today and update you as and when I can. 

https://github.com/drofnnuD/realmtest

**Comment by xian** [comment] 2017-03-06 22:02
Thanks @drofnnuD and @sureshjoshi for the examples!

Can you give it a try with the current `3.3.1-SNAPSHOT` build?

```groovy
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}

dependencies {
    testCompile "org.robolectric:robolectric:3.3.1-SNAPSHOT"
}
```

**Comment by drofnnuD** [comment] 2017-03-06 22:05
@xian Will do this first thing tomorrow and let you know the result.

**Comment by sureshjoshi** [comment] 2017-03-06 22:07
@xian Will try in approx 1h and report back.

**Comment by xian** [comment] 2017-03-06 23:03
@sureshjoshi thanks! I'm not too familiar with PowerMock, so it's not immediately obvious to me how to diagnose this issue.

The exception says, when resolving method `Activity.onCreateView(String, Context, AttributeSet)`,
`android.content.Context` is declared by multiple class loaders:
* via `android.app.Activity` (`org.powermock.core.classloader.MockClassLoader`),
* via `android.view.LayoutInflater$Factory` (`org.robolectric.internal.bytecode.SandboxClassLoader`)

... so it seems that PowerMock is failing to delegate loading of `Activity` to Robolectric (as `@PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*"})` seems to imply it should?).

Maybe I'm misunderstanding what `@PowerMockIgnore` does?

**Comment by sureshjoshi** [comment] 2017-03-06 23:10
@xian I'm not entirely sure... Just following this: https://github.com/robolectric/robolectric/wiki/Using-PowerMock

**Comment by xian** [comment] 2017-03-07 01:16
Keeping this open till fix is confirmed.

**Comment by thuonglv** [comment] 2017-03-07 07:42
Yesterday, I faced the same issue with the same stack trace. Today, I used version 3.3.1 and this issue went away. Thank you for your great fast fixing. 👍

**Comment by drofnnuD** [comment] 2017-03-07 08:31
Changing to 3.3.1-SNAPSHOT changed the stacktrace I get over to what is below. I'm not sure if this is because I'm not mocking things correctly. 

`
java.lang.NullPointerException
	at com.example.mathewdunn.realmtest.activity.SecondActivity.getUser(SecondActivity.java:33)
	at com.example.mathewdunn.realmtest.activity.SecondActivity.onCreate(SecondActivity.java:29)
	at android.app.Activity.performCreate(Activity.java:5933)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:231)
	at org.robolectric.android.controller.ActivityController$1.run(ActivityController.java:140)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:362)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:137)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:147)
	at org.robolectric.android.controller.ActivityController.setup(ActivityController.java:245)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:97)
	at com.example.mathewdunn.realmtest.SecondActivityTest.setUp(SecondActivityTest.java:85)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.powermock.modules.junit4.rule.PowerMockStatement$1.run(PowerMockRule.java:83)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1899)
	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:801)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:666)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
	at org.powermock.classloading.AbstractClassloaderExecutor.getResult(AbstractClassloaderExecutor.java:69)
	at org.powermock.classloading.AbstractClassloaderExecutor.executeWithClassLoader(AbstractClassloaderExecutor.java:59)
	at org.powermock.classloading.SingleClassloaderExecutor.execute(SingleClassloaderExecutor.java:67)
	at org.powermock.classloading.AbstractClassloaderExecutor.execute(AbstractClassloaderExecutor.java:43)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:75)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:209)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
`

However if I add the following line,

`when(mockRealm.where(User.class).findAll()).thenReturn(realmUsers);`

I get the following stack trace


`
java.lang.NullPointerException
	at com.example.mathewdunn.realmtest.SecondActivityTest.setUp(SecondActivityTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.powermock.modules.junit4.rule.PowerMockStatement$1.run(PowerMockRule.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1899)
	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:801)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:666)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
	at org.powermock.classloading.AbstractClassloaderExecutor.getResult(AbstractClassloaderExecutor.java:69)
	at org.powermock.classloading.AbstractClassloaderExecutor.executeWithClassLoader(AbstractClassloaderExecutor.java:59)
	at org.powermock.classloading.SingleClassloaderExecutor.execute(SingleClassloaderExecutor.java:67)
	at org.powermock.classloading.AbstractClassloaderExecutor.execute(AbstractClassloaderExecutor.java:43)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:75)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:209)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
`

Again, I'm not sure if this is just my error or something wrong with Robo and Powermock, my set up method looks like this

`
    private Realm mockRealm;
    private RealmResults<User> mockResults;

    @Before
    public void setUp(){
        MockitoAnnotations.initMocks(this);

        // Setup Realm + Mock
        mockStatic(Realm.class);
        mockStatic(RealmConfiguration.class);
        mockStatic(RealmCore.class);
        mockStatic(RealmQuery.class);

        final Realm mockRealm = mock(Realm.class);
        doNothing().when(RealmCore.class);
        RealmCore.loadLibrary(any(Context.class));

        when(Realm.getDefaultInstance()).thenReturn(mockRealm);
        when(mockRealm.createObject(User.class)).thenReturn(new User());

        User userOne = new User("Matt", "Dunn");
        User userTwo = new User("Michael", "Stoddart");

        List<User> userList = Arrays.asList(userOne, userTwo);

        RealmQuery<User> realmQuery = mockRealmQuery();
        RealmResults<User> mockResults = mockRealmResults();

        when(realmQuery.findAll()).thenReturn(realmUsers);

        when(mockResults.iterator()).thenReturn(userList.iterator());
        when(mockResults.size()).thenReturn(userList.size());

        when(mockResults.first()).thenReturn(userList.get(0));

        this.mockRealm = mockRealm;
        this.mockResults = mockResults;

        activity = Robolectric.setupActivity(SecondActivity.class);
    }
`

@thuonglv Could you possibly post your setup method or some code so we can see why your tests are passing and mine are failing?

**Comment by ch-vadim-maximov** [comment] 2017-03-07 18:05
The last error went away, but now I'm getting
```java.lang.IllegalStateException: Failed to transform class with name io.realm.Realm. Reason: rx.Observable```

Same as in:
https://github.com/robolectric/robolectric/issues/2208

**Comment by xian** [comment] 2017-03-07 22:10
This works for me:

```java
    @Before
    public void setUp(){
        MockitoAnnotations.initMocks(this);

        // Setup Realm + Mock
        mockStatic(Realm.class);
        mockStatic(RealmConfiguration.class);
        mockStatic(RealmCore.class);
        mockStatic(RealmQuery.class);

        final Realm mockRealm = mock(Realm.class);
        doNothing().when(RealmCore.class);
        RealmCore.loadLibrary(any(Context.class));

        when(Realm.getDefaultInstance()).thenReturn(mockRealm);
        when(mockRealm.createObject(User.class)).thenReturn(new User());

        User userOne = new User("Matt", "Dunn");
        User userTwo = new User("Michael", "Stoddart");

        List<User> userList = Arrays.asList(userOne, userTwo);

        RealmQuery<User> realmQuery = mockRealmQuery();
        when(mockRealm.where(User.class)).thenReturn(realmQuery);

        RealmResults<User> mockResults = mockRealmResults();
        when(realmQuery.findAll()).thenReturn(mockResults);

        when(mockResults.iterator()).thenReturn(userList.iterator());
        when(mockResults.size()).thenReturn(userList.size());

        when(mockResults.first()).thenReturn(userList.get(0));

        activity = Robolectric.setupActivity(SecondActivity.class);
    }
```

**Comment by kwalker-git** [comment] 2017-03-07 22:51
When will 3.3.1 be pushed to jcenter?

**Comment by ch-vadim-maximov** [comment] 2017-03-07 23:29
@xian  Could you post your dependencies?

**Comment by drofnnuD** [comment] 2017-03-08 08:09
@xian That seems to have fixed my problem when using 3.3.1 Snapshot

**Comment by xian** [comment] 2017-03-09 00:45
@ch-vadim-maximov -- dependencies are unchanged from this project: https://github.com/drofnnuD/realmtest

Rolling up the `3.3.1` release now. Thanks all!

**Closed by xian** 2017-03-09 00:45 UTC
Labels: defect, tools integration

**Comment by Zhuinden** [comment] 2017-05-24 08:46
@ch-vadim-maximov for that one, you need to create a package named `rx` and an empty class in it called `Observable`
