### ISSUE TITLE
java.lang.VerifyError: class org.robolectric.android.fakes.RoboMonitoringInstrumentation overrides final method specifyDexMakerCacheProperty.()V

### ISSUE THREAD

**Issue by WatchhWordd** [robolectric/robolectric#3839] opened 2018-03-28 06:32 UTC
AndroidStudio3.1

androidTestImplementation('com.android.support.test.espresso:espresso-core:3.0.1', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
 androidTestImplementation 'com.android.support.test:monitor:1.0.2-alpha1'
testImplementation 'org.robolectric:robolectric:3.7.1'

ava.lang.VerifyError: class org.robolectric.android.fakes.RoboMonitoringInstrumentation overrides final method specifyDexMakerCacheProperty.()V

**Comment by muthenberg** [comment] 2018-03-28 08:30
Same here. The problem seems to be, as the error suggest, that [this class](https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/android/fakes/RoboMonitoringInstrumentation.java) overrides the final method specifyDexMakerCacheProperty from [this class](https://android.googlesource.com/platform/frameworks/testing/+/master/support/src/android/support/test/runner/MonitoringInstrumentation.java).

**Comment by jrodbx** [comment] 2018-03-30 05:55
Possible duplicate of https://github.com/robolectric/robolectric/issues/3613?

**Comment by Arvalon** [comment] 2018-03-30 13:39
Android Studio 3.1
build.gradle:

`configurations.all { config ->`
`    if (config.name.contains('UnitTest')) {`
`        config.resolutionStrategy.eachDependency { details ->`
`            if (details.requested.group == 'com.squareup.leakcanary' && details.requested.name == 'leakcanary-android') {`
`                details.useTarget(group: details.requested.group, name: 'leakcanary-android-no-op', version: details.requested.version)`
`}}}}`

`androidTestImplementation 'com.android.support.test:runner:1.0.1'`
`testImplementation "org.robolectric:robolectric:3.8"`
`debugImplementation 'com.squareup.leakcanary:leakcanary-android:1.5.4'`
`releaseImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.5.4'`

Upgrade to to `com.android.support.test:runner:1.0.2-alpha1` does not help.

**Comment by muthenberg** [comment] 2018-04-03 10:54
Question is why changing the version of `androidTestImplementation 'com.android.support.test:runner:1.0.1'` should have any effect on testImplementation "org.robolectric:robolectric:3.8". As far as I understand Gradle dependencies, Robolectric which is referenced as `testImplementation` should not be able to see anything referenced as `androidTestImplementation`.

I used to use Maven so I might be wrong here.

**Comment by muthenberg** [comment] 2018-04-04 06:33
OK. I do not really know why, but updating `androidTestImplementation 'com.android.support.test:runner:1.0.1'` to `1.0.2-alpha1` works, if you also update `androidTestImplementation "com.android.support.test:rules:1.0.1"` to `1.0.2-alpha2`.

**Comment by burningfireplace** [comment] 2018-04-05 22:29
@azizbekian 
I think he made a typo. It's `1.0.2-alpha1`. Everything works for me with:
```
testImplementation 'com.android.support.test:runner:1.0.2-alpha1'
testImplementation 'com.android.support.test:rules:1.0.2-alpha1'
```
I couldn't find `1.0.2-alpha2` in the google repo.

**Comment by muthenberg** [comment] 2018-04-10 11:55
Yeah sorry. It needs to be alpha1 of course. Just corrected it.

**Comment by WatchhWordd** [comment] 2018-04-11 02:57
@dekzitfz ,thinks,you are right.

**Comment by shadabunique** [comment] 2018-05-23 21:00
What I figured out if I upgrade my google play services from 
`  classpath 'com.google.gms:google-services:3.2.0'`
to 
`  classpath 'com.google.gms:google-services:3.3.0' `or `3.3.1`

I start getting this issue.
So I'm sticking to 3.2.0 for now.
Also I'm using -
`testImplementation 'org.robolectric:robolectric:3.8'`

**Comment by TWiStErRob** [comment] 2018-06-19 22:40
@burningfireplace @dekzitfz 1.0.2 is already released as stable, please update your comments so that people don't try to pull in an outdated version. The workaround worked with the stable version as well.

**Closed** 2018-11-10 20:13 UTC
