### ISSUE TITLE
RobolectricGradleTestRunner removed from 3.2 / PowerMock integration broken

### ISSUE THREAD

**Issue by kwalker-git** [robolectric/robolectric#2915] opened 2017-02-16 21:25 UTC
### Description
I had begun to use PowerMock in our Roboelectric tests, but my project upgraded to 3.2.2, and RobolectricGradleTestRunner has been removed. Is there an alternative to integrating with PowerMock without this class?

I was using the approach documented at https://github.com/robolectric/robolectric/wiki/Using-PowerMock .

### Steps to Reproduce
Test code no longer compiles.

### Robolectric & Android Version
Robolectric 3.2.2
compileSdkVersion 24
defaultConfig {
        minSdkVersion 19
        targetSdkVersion 24
    }

Thanks!

**Comment by xian** [comment] 2017-02-16 21:29
Hey @kwalker-git — we've got a fix for this coming soon!
Dupe of #2208.

**Closed by xian** 2017-02-16 21:29 UTC

**Comment by xian** [comment] 2017-02-16 21:31
Btw, you can try using `RobolectricTestRunner.class` in place of `RobolectricGradleTestRunner.class`, but I think you'll find you still have a problem in 3.2.2. Fix coming shortly.
