### ISSUE TITLE
onAnimationEnd not fired when more then one ValueAnimator used in test

### ISSUE THREAD

**Issue by metalhead8816** [robolectric/robolectric#1770] opened 2015-05-04 20:02 UTC
Here is an example of what doesn't work. Discovered when trying to migrate from 2.4 to 3.0

<code><pre>
  @Test
  public void start_shouldRunAnimationAndFireStartAndEndCallbacks() {
    Animator.AnimatorListener listener = mock(Animator.AnimatorListener.class);
    ShadowChoreographer.setFrameInterval(100 * TimeUtils.NANOS_PER_MS);

    final ValueAnimator animator = ValueAnimator.ofInt(0, 10);
    animator.setDuration(1000);
    animator.addListener(listener);
    animator.start();

    verify(listener).onAnimationStart(animator);

    Robolectric.flushForegroundThreadScheduler();

    verify(listener).onAnimationEnd(animator);

    reset(listener);

    final ValueAnimator animator2 = ValueAnimator.ofInt(0, 10);
    animator2.setDuration(1000);
    animator2.addListener(listener);
    animator2.start();

    verify(listener).onAnimationStart(animator2);

    Robolectric.flushForegroundThreadScheduler();

    verify(listener).onAnimationEnd(animator2); // FAILS HERE
  }
</pre></code>

And another example that should work (framework supports it), but doesn't work in Robolectric:

<code><pre>
  @Test
  public void start_shouldRunAnimationAndFireStartAndEndCallbacks() {
    Animator.AnimatorListener listener = mock(Animator.AnimatorListener.class);
    ShadowChoreographer.setFrameInterval(100 * TimeUtils.NANOS_PER_MS);

    final ValueAnimator animator = ValueAnimator.ofInt(0, 10);
    animator.setDuration(1000);
    animator.addListener(listener);
    animator.start();

    verify(listener).onAnimationStart(animator);

    Robolectric.flushForegroundThreadScheduler();

    verify(listener).onAnimationEnd(animator);

    reset(listener);

    animator.setCurrentPlayTime(0L);
    animator.setDuration(1000);
    animator.start();

    verify(listener).onAnimationStart(animator);

    Robolectric.flushForegroundThreadScheduler();

    verify(listener).onAnimationEnd(animator);  // FAILS HERE
  }
</pre></code>

Any ideas on where to start looking?

**Comment by erd** [comment] 2015-05-04 20:11
> Any ideas on where to start looking?

Probably somewhere in `ValueAnimator` or `Choreographer`. We tried to avoid shadowing any of the animation classes (since they were a lot of cases where they were horribly broken) and shadow `Choreographer` which handles scheduling animation frames.

**Comment by kriegfrj** [comment] 2015-05-15 05:52
@jongerrish spent some time looking into this in #1809 (which seems to be a duplicate of this one). The nett result of this investigation is that we think this is a manifestation of #1306.

A solution specific to this issue (and #1809) would be to change `ShadowChoreographer` so that it calls `ShadowLooper.runPaused()` or some equivalent, rather than calling `Scheduler.postXXX()` directly. I have also floated the idea of a more generic solution that would solve this issue (and other similar cases both known and unknown) in #1306.

**Comment by erd** [comment] 2015-09-30 19:32
Duplicate of #1809.

**Closed by erd** 2015-09-30 19:32 UTC
Labels: 3.0, defect
