### ISSUE TITLE
Robolectric fails to run with OpenJdk 9, 11, and 13 on Ubuntu 20.04

### ISSUE THREAD

**Issue by kingargyle** [robolectric/robolectric#5823] opened 2020-08-04 00:16 UTC
### Description

When trying to run robolectric 4.4 on Ubuntu with OpenJdk 9, 11, or 13.   It fails in trying to download the robolectric dependencies when running a test.   It works correctly on OpenJdk 8 on the same system.

### Steps to Reproduce

Clone the following repo: https://github.com/NineWorlds/serenity-android/tree/develop/
Install through apt any version of OpenJdk 9 or above.

./gradlew clean serenity-app:testDebugUnitTest

The robolectric tests will fail with some apache maven issues as they try to download the necessary requirements.   If you run the same tests under OpenJdk 8 everything works.

I've used OpenJdk on a Mac with 9, 11, and 13 and they seem to be working correctly, with out the same issue.

### Robolectric & Android Version

4.4-alpha2

### Link to a public git repo demonstrating the problem:

https://github.com/NineWorlds/serenity-android/tree/develop/

**Comment by hoisie** [comment] 2020-08-04 07:47
Tried a fresh install Ubuntu 20.04 and all artifacts download:

```
$ cat /etc/issue
Ubuntu 20.04.1 LTS \n \l

$ sudo apt-get install openjdk-11-jdk-headless

$ java --version
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

What Java version do you have (e.g. patch version)?

**Comment by hoisie** [comment] 2020-08-04 09:02
Can you verify that it's not a java certificate issue? I saw an error that looks familiar: https://bbs.archlinux.org/viewtopic.php?id=190398

**Comment by kingargyle** [comment] 2020-08-04 13:03
@hoise I'll try and update the certificates later tonight, I'm sure they haven't been updated in a while.

**Comment by hoisie** [comment] 2020-08-04 17:34
Also if you can, run tests with gradlew `-d` and paste the output to a gist or pastebin.

**Comment by hoisie** [comment] 2020-08-04 21:40
FYI I also tried to run those tests in docker:
```sh
docker run -it --entrypoint=bash openjdk:9
```

And still could not reproduce the error.

**Comment by hoisie** [comment] 2020-08-05 07:51
Mind trying https://github.com/robolectric/robolectric/issues/5456#issuecomment-669039363 also? Do any of those alternatives work?

**Comment by kingargyle** [comment] 2020-08-05 13:59
@hoisie sorry I've had some rathe busy evenings, will try and get back to verify this tonight.  I think the certificates are the root cause as I stuff works correctly on the Mac with the same openjdks.

**Comment by hoisie** [comment] 2020-08-10 06:58
Since this is just a duplicate of #5456, I'll close this and we can use that as the canonical one.

**Closed by hoisie** 2020-08-10 06:58 UTC
