### ISSUE TITLE
ViewPager IllegalStateException

### ISSUE THREAD

**Issue by eygraber** [robolectric/robolectric#1630] opened 2015-03-18 15:37 UTC
I have a problem similar to https://github.com/robolectric/robolectric/issues/1326

The stacktrace is the same, but the code is not. In my case I start a `Fragment` using `FragmentTestUtil`. That `Fragment` calls `ViewPager.setCurrentItem` when it has been started, so I can't use this fix (https://github.com/robolectric/robolectric/issues/1326#issuecomment-68306634).

**Comment by jaredsburrows** [comment] 2015-03-21 20:56
Post Exception. Post code. I use the `FragmentTestUtil` and it works just fine.

**Comment by eygraber** [comment] 2015-03-24 14:03
@jaredsburrows posting the stacktrace and some code:


```
java.lang.IllegalStateException: commit already called
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:623)
	at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:619)
	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:161)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1073)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:919)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1441)
	at android.view.View.measure(View.java:15848)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.onMeasure(SlidingUpPanelLayout.java:639)
	at android.view.View.measure(View.java:15848)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:15848)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5008)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1052)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
	at android.view.View.measure(View.java:15848)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:15848)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5008)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:15848)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2189)
	at android.view.View.measure(View.java:15848)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1905)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1104)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1284)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
	at android.view.Choreographer.doFrame(Choreographer.java:532)
	at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:664)
	at org.robolectric.shadows.ShadowHandler.routeMessage(ShadowHandler.java:127)
	at org.robolectric.shadows.ShadowHandler.access$100(ShadowHandler.java:27)
	at org.robolectric.shadows.ShadowHandler$1.run(ShadowHandler.java:112)
	at org.robolectric.util.Scheduler$PostedRunnable.run(Scheduler.java:182)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:125)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:110)
	at org.robolectric.util.Scheduler.advanceToLastPostedRunnable(Scheduler.java:86)
	at org.robolectric.util.Scheduler.unPause(Scheduler.java:26)
	at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:231)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:270)
	at org.robolectric.shadows.ShadowViewGroup.addView(ShadowViewGroup.java:34)
	at android.view.ViewGroup.addView(ViewGroup.java)
	at android.view.ViewGroup.addView(ViewGroup.java:3353)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.me.fragments.footer.ChildFragment.onCreateView(ChildFragment.java:103)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:454)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:48)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:37)
	at org.robolectric.shadows.ShadowLooper.post(ShadowLooper.java:210)
	at org.robolectric.shadows.ShadowHandler.postDelayed(ShadowHandler.java:58)
	at org.robolectric.shadows.ShadowHandler.post(ShadowHandler.java:53)
	at android.os.Handler.post(Handler.java)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1395)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:636)
	at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:619)
	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:161)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1073)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:919)
	at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:447)
	at com.me.fragments.footer.MyFragment.doSomething(MyFragment.java:126)
	at com.me.fragments.footer.MyFragment.onResume(MyFragment.java:38)
	at android.support.v4.app.Fragment.performResume(Fragment.java:1829)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:983)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:454)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:48)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:37)
	at org.robolectric.shadows.ShadowLooper.post(ShadowLooper.java:210)
	at org.robolectric.shadows.ShadowHandler.postDelayed(ShadowHandler.java:58)
	at org.robolectric.shadows.ShadowHandler.post(ShadowHandler.java:53)
	at android.os.Handler.post(Handler.java)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1395)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:636)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:615)
	at org.robolectric.util.FragmentTestUtil.startVisibleFragment(FragmentTestUtil.java:47)
	at com.me.fragments.footer.MyFragmentTest.setUpVisible(MyFragmentTest.java:269)
	at com.me.fragments.footer.MyFragmentTest.onViewCreated_doesSomething(MyFragmentTest.java:78)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

```
MyFragmentStatePagerAdapter adapter = new MyFragmentStatePagerAdapter(getChildFragmentManager());
adapter.setListOfThings(things);
pager.setAdapter(adapter);
adapter.notifyDataSetChanged();
```

**Comment by eygraber** [comment] 2015-03-24 14:13
Here's the code. The method that it is in gets called from `onViewCreated` and `onResume`.

```
MyFragmentStatePagerAdapter adapter = new MyFragmentStatePagerAdapter(getChildFragmentManager());
adapter.setListOfThings(things);
pager.setAdapter(adapter);
adapter.notifyDataSetChanged();
```

**Comment by jaredsburrows** [comment] 2015-03-24 17:20
Post the test. Why are you using `getChildFragmentManager()`?

**Comment by eygraber** [comment] 2015-03-24 17:26
There are around 35 tests failing. The code posted above is wrapped by a condition. Only tests that start that `Fragment` and set that condition to `true` get this exception.

We use `getChildFragmentManager()` because we want the `Fragment`s in the `ViewPager` to be children of the `Fragment` where the `ViewPager` lives.

**Comment by jaredsburrows** [comment] 2015-03-24 17:39
`getChildFragmentManager()` is for `Fragment`s in `Fragment`s. Just like on StackOverflow, I can't help unless I see the code.

**Comment by eygraber** [comment] 2015-03-24 17:57
I've simplified it as best as I can.

```
public class MyFragment extends RoboFragment {
  @Inject ListWrapper list;

  @InjectView(R.id.pager) ViewPager pager;

  @Override
  public void onResume() {
    super.onResume();

    doSomething();
  }
  
  @Override
  public void onViewCreated(View view, Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);

    pager.setAdapter(new MyFragmentStatePagerAdapter(getChildFragmentManager()));
    doSomething();
  }

  public void stateChange() {
    doSomething();
  }

  private void doSomething() {
    if(listWrapper.getList().size() > 0) {
      MyFragmentStatePagerAdapter adapter = new MyFragmentStatePagerAdapter(getChildFragmentManager());
      adapter.setListOfThings(listWrapper.getList());
      pager.setAdapter(adapter);
      adapter.notifyDataSetChanged();
    }
  }
}

public class MyFragmentTest {
  @InjectMock ListWrapper listWrapper;

  private MyFragment subject;

  @Before
  public void setup() {
    subject = new MyFragment();
  }

  @Test
  public void onViewCreated_doesSomething() {
    List<Thing> things = Arrays.asList(Thing.thing(), thing);
    stub(listWrapper.getList()).toReturn(things);
    subject.stateChange();

    setUpVisible();

    assertThat...
  }

  private void setUpVisible() {
    FragmentTestUtil.startVisibleFragment(subject);
  }
}
```

**Comment by jaredsburrows** [comment] 2015-03-24 18:17
I still do not know why you are using `getChildFragmentManager()`, unless your are initiating a `Fragment` within a `Fragment`.

And where is it failing exactly?

       private void doSomething() {
            if(listWrapper.getList().size() > 0) {
              MyFragmentStatePagerAdapter adapter = new MyFragmentStatePagerAdapter(getChildFragmentManager());
              adapter.setListOfThings(listWrapper.getList());
              pager.setAdapter(adapter);
              adapter.notifyDataSetChanged();
            }
          }

Are `listWrapper.getList()` other fragments? Are you using this snippet in your actual app?

**Comment by eygraber** [comment] 2015-03-24 18:59
I inherited this code, so I am not sure why `getChildFragmentManager()` is being used. 

Since the stacktrace is convoluted, I am not sure where exactly it is failing. The test failure is happening at the call to `setUpVisible()`.

`listWrapper.getListOfThings()` returns a `List` of POJOs. These POJOs are used by `MyFragmentStatePagerAdapter` to create `Fragment`s in `getItem()`.

**Comment by eygraber** [comment] 2015-03-24 19:01
Using `getFragmentManager()` instead of `getChildFragmentManager()` results in

`java.lang.IllegalStateException: Recursive entry to executePendingTransactions`

**Comment by jaredsburrows** [comment] 2015-03-24 19:06
Does the app actually run?

In order to use `MyFragmentStatePagerAdapter` with `getFragmentManager()`, it must support it in the class. There are so many reasons why this might be happening. I would have to see the project.

**Comment by eygraber** [comment] 2015-03-24 20:28
The app runs with no problem. I will look into my options for sharing code.

**Comment by eygraber** [comment] 2015-03-25 19:17
I created a project that reproduces the issue. The tests don't seem to be working from the command line, but they do work in Android Studio 1.1.0 with unit testing.

https://drive.google.com/file/d/0B80Na38AYGjVRWZoVmtabS1BUGs/view?usp=sharing

**Comment by jaredsburrows** [comment] 2015-03-25 19:19
Wait, what? The tests work fine in Android Studio but not command line? Wasn't your issue the fact they aren't working in Android Studio?

**Comment by eygraber** [comment] 2015-03-25 19:23
Meaning I can't get the tests to run from the command line (just in this little project that I made). They run in Android Studio, but they fail. My real project can run on both Android Studio and the command line.

**Comment by jaredsburrows** [comment] 2015-03-26 01:06
gradlew testDebug does not work for you?

**Comment by eygraber** [comment] 2015-03-26 16:11
Using `gradlew testDebug` does run (I was mistaken previously), and the test still fails with the `IllegalStateException`.

Have you tried running it yet?

**Comment by geekrax** [comment] 2015-04-02 00:22
@eygraber I think that the issue is happening because your underlying implementation of `doSomething` add child fragments, which starts a `FragmentTransaction`. When you call `doSomething` from `onResume`, the `FragmentManager` throws an error, because a fragment transaction can only be created/committed prior to an activity saving its state [1].

In your actual application, it might not be called from `onResume`, but in your test suite it gets executed from `com.me.fragments.footer.MyFragmentTest#onViewCreated` → `..` →  `FragmentManager#execPendingActions`.

[1]: Documentation of [`FragmentManager#beginTransaction`](http://developer.android.com/reference/android/app/FragmentManager.html#beginTransaction()) :
> Note: A fragment transaction can only be created/committed prior to an activity saving its state. If you try to commit a transaction after FragmentActivity.onSaveInstanceState() (and prior to a following FragmentActivity.onStart or FragmentActivity.onResume(), you will get an error. This is because the framework takes care of saving your current fragments in the state, and if changes are made after the state is saved then they will be lost.

**Comment by eygraber** [comment] 2015-04-02 05:54
@geekrax check out this POC project that I made (https://drive.google.com/file/d/0B80Na38AYGjVRWZoVmtabS1BUGs/view?usp=sharing). The only time `doSomething` gets called is after `onResume()` and the `IllegalStateException` is still thrown.

**Comment by geekrax** [comment] 2015-04-02 17:09
Ok, I haven't looked at it in detail, but by looking at the implementation of `doSomething`, I am pretty sure that `doSomething` should be called from `onViewCreated`. Tests should pass if it's removed from `onResume`.

**Comment by eygraber** [comment] 2015-04-02 17:38
@geekrax Maybe I'm missing something. I've been working with `Fragment`s for years, and have never had an issue with creating child fragments (or regular ones) in `onResume`. The app that these tests belong to runs perfectly whether `doSomething` is called from `onResume` or `onViewCreated`.

The POC I made uses the most minimal amount of code to demonstrate the problem. The only time `doSomething` is called is in `onResume`, and all `doSomething` does is create a `FragmentStatePagerAdapter` using `getChildFragmentManager`, and calls `ViewPager#setAdapter` with it.

The piece that you quoted from `FragmentMananger#beginTransaction`'s javadoc pertains to when the `Fragment` is being rebuilt from previous state, which shouldn't be the case in the tests because there is no previous state (I instantiate a new `Fragment` for each test). Even in that case, the javadoc says to not commit a `FragmentTransaction` until after `onResume`, which is where `doSomething` is getting called, and it still fails.

**Comment by jaredsburrows** [comment] 2015-05-20 16:22
@eygraber  What is the status of this? Can we close this now? Have you tried upgrading to Robolectric 3.0?

**Comment by eygraber** [comment] 2015-05-20 17:18
@jaredsburrows It's still broken. I moved away from the changes that were causing this, but I refactored last night, and the issue has come up again. I plan on updating to Robolectric 3 at some point; I just don't know when, since it will be a lot of work.

**Comment by jaredsburrows** [comment] 2015-05-20 17:23
It is very easy to switch to Robolectric 3.0, please see [here](https://github.com/robolectric/robolectric/wiki/2.4-to-3.0-Upgrade-Guide).

**Comment by eygraber** [comment] 2015-05-20 17:39
I tried back in February, and it was non-trivial. I hope to try again in a few weeks, but I don't expect it to be that easy (based on what I saw in the past).

**Comment by jaredsburrows** [comment] 2015-05-30 02:57
@eygraber Can you test this or close this issue? I am not seeing this with my `ViewPager` tests.

**Comment by jaredsburrows** [comment] 2015-05-31 01:10
@erd I believe we can close this. I am using Robolectric 3.0 and I test the v4 `ViewPager` in my apps.

**Comment by eygraber** [comment] 2015-05-31 03:44
@jaredburrows I will try testing my sample app with Robolectric 3 (I don't know when I'll be able to migrate my actual app) and let you know what happens.

**Comment by jaredsburrows** [comment] 2015-05-31 14:26
Sounds good. Is your project open source? or on Github? If so, post the link.

**Comment by eygraber** [comment] 2015-06-03 12:50
@jaredsburrows I posted a link to it above. I tried it with Robolectric 3.0 and I get the same failure and exception as before.

**Comment by jaredsburrows** [comment] 2015-06-04 01:30
@eygraber Ew. You have a github account but can't upload your project to Github? Ha.

**Comment by eygraber** [comment] 2015-06-04 01:45
@jaredsburrows Shame is such a powerful tool - https://github.com/eygraber/RobolectricViewPagerPOC

**Comment by jaredsburrows** [comment] 2015-06-04 01:46
Ok, just to help, I pulled your project. 

The first thing I saw was:
 - Outdated libraries
 - Outdated build tools
 - Robolectric 2.4, should be 3.0-rc3
 - Outdated Gradle plugin
 - You do not need the Robolectric plugin
 - Do not include local.properties

It would help to:
1. Put your project on Github
2. Update your project

Things to do(besides all that I listed above):
 - Remove your "android studio hack task"
 - Rename `org.robolectric.Config.properties` to 
 - Use `RobolectricGradleTestRunner.class` instead of `RobolectricTestRunner.class`
 - Robolectric 3.0 comes with a `startFragment` and `startVisibleFragment`, use those instead
 - Also, you have no assertions


@erd @eygraber  I am still looking into this.

**Comment by jaredsburrows** [comment] 2015-06-04 01:46
@eygraber Why shame? Learn to use it.

**Comment by eygraber** [comment] 2015-06-04 01:51
@jaredsburrows I should have made a Github project from the beginning but I was lazy. I'm updating the project with those points you made.

Any chance of a valid workaround for things like this on 2.4, or am I out of luck on that front?

**Comment by jaredsburrows** [comment] 2015-06-04 01:55
Ok I made all of the changes to your project and it runs just fine, like I suggested in the beginning. @erd  Can we finally close this lol? @eygraber Do you want me to make a PR to your repo?

**Comment by erd** [comment] 2015-06-04 02:02
Yep - sounds like this one is not reproducible.

**Closed by erd** 2015-06-04 02:02 UTC
Labels: 2.4

**Comment by jaredsburrows** [comment] 2015-06-04 02:03
@erd  Have you seen my License Checker PR https://github.com/erd/android-licensing/pull/2? :)

**Comment by eygraber** [comment] 2015-06-04 02:15
@jaredsburrows this POC is representative of the problem I was having with a real project that I cannot show source for. I made all of the changes you mentioned above (I renamed `org.robolectric.Config.properties` to `org.robolectric.config.properties` because you missed what to rename it to).

However, I need to be able to start a `Fragment` with `addToBackStack` in the `FragmentTransaction`, so I cannot use `FragmentTestUtil`. Is that the problem? If it is, can it be fixed?

**Comment by jaredsburrows** [comment] 2015-06-04 02:18
Rename `org.robolectric.Config.properties` to `robolectric. properties`.

I am not sure, I have not tried doing that. I simple Google search shows us:

http://stackoverflow.com/questions/11333354/how-can-i-test-fragments-with-robolectric

Some of those tests are old but are still "valid".

**Comment by eygraber** [comment] 2015-06-04 02:27
@jaredsburrows changed the filename and still get the errors. I updated the project.

I don't think this should be closed. This worked for a few months, and only stopped working when the behavior of the `ViewPager` changed.

**Comment by jaredsburrows** [comment] 2015-06-04 02:39
@eygraber I applied all of the changes to your project that you gave. Do you want me to make a PR to your repository?

**Comment by eygraber** [comment] 2015-06-04 02:39
Sure

**Comment by jaredsburrows** [comment] 2015-06-04 03:11
There was a minor confusion.

Your original test worked with `startFragment` and not `startVisibleFragment`. This was because you were trying to add `child fragments` to the stack in `onResume` vs `onCreate` or `onCreateView`(for Fragments).

**Comment by eygraber** [comment] 2015-06-04 03:23
I am slightly confused.

1. My real app needs to test a `Fragment` that has been added to the back stack. That's why `startFragment` and `startVisibleFragment` won't work for me.
2. I'm not sure why you moved the call to `doSomething` to `onViewCreated`. My app calls it in `onResume` and it is fine. If you build the app that is in the POC it works fine. If you're referring to [@geekrax's comment](https://github.com/robolectric/robolectric/issues/1630#issuecomment-88673186), see [my reply](https://github.com/robolectric/robolectric/issues/1630#issuecomment-88984906).

**Comment by jaredsburrows** [comment] 2015-06-04 03:32
>That's why startFragment and startVisibleFragment won't work for me.

`startVisibleFragment` and `startFragment` are just helper methods from Robolectric. I already gave you help here: http://stackoverflow.com/questions/11333354/how-can-i-test-fragments-with-robolectric.

> My app calls it in onResume and it is fine.

You should not be adding new fragments in `onResume` anyways. @geekrax  is correct, do not add fragments in `onResume`, use `onCreateView` instead. **Just because "something works" doesn't mean it was designed to work that way.**

Example: My pull request for your repo and here, http://stackoverflow.com/a/20041799/950427.


Stop fighting "how" Robolectric works. Stop fighting people who are trying to help you. A lot of times it is best to deign your application with testing in mind. 

This issue is becoming off topic with every new reply. Robolectric is meant to help test your application not provide every possible testing solution and/or be tailored especially for your application.

**Comment by eygraber** [comment] 2015-06-04 03:58
First off, I inherited this app, and I assure you it was designed with testing in mind (more than I would have liked, and certainly in a way that the designers of Robolectric would approve of).

I'm also not fighting how Robolectric works. I believe I found a bug, and I still haven't been given a reason to believe that it is not one. I wouldn't have wasted my time here if I didn't truly believe that.

I think you and @geekrax are talking about `Activity.onResume` while I am talking about `Fragment.onResume`. The [StackOverflow post](http://stackoverflow.com/a/20041799/950427) you mentioned regarding `onCreateView` doesn't apply here, because in that case the OP was trying to add a child `Fragment` before `onCreateView` was called. 

Here, I am adding child `Fragment`s in `onResume` which is after `onCreateView` (and `onViewCreated`) has been called. I am under the impression that there is no problem with adding a `Fragment` from another `Fragment`'s `onResume` ([see here](http://stackoverflow.com/questions/16265733/failure-delivering-result-onactivityforresult#comment27868872_18345899). If this is not the case, can you please point me to some documentation saying this?

**Comment by geekrax** [comment] 2015-06-05 00:59
Fair warning: I might be repeating myself, but there's not much clarification left after this very long discussion on this topic.
> I think you and @geekrax are talking about `Activity.onResume` while I am talking about `Fragment.onResume`.

I would add one breakpoint inside `Fragment#onResume` to realize the fact that `FragmentActivity#onResume` is called before `Fragment#onResume`, which is naturally understandable.

Now, as seen in the documentation[1] I quoted earlier, it's warned to developers that we should be doing all the `FragmentTransaction` commits before `FragmentActivity#onSaveInstanceState` (which then calls `Fragment#saveInstanceState` is called. The reason behind it is simple: _the framework takes care of saving your current fragments in the state, and if changes are made after the state is saved then they will be lost._

If you don't care about the state of fragments, you can use [`FragmentTransaction#commitAllowingStateLoss`](http://developer.android.com/reference/android/support/v4/app/FragmentTransaction.html#commitAllowingStateLoss()) and live a happy life.
This internal method ([source](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/master/v4/java/android/support/v4/app/FragmentManager.java)) is the originator of your exception:
```java
private void checkStateLoss() {
	if (mStateSaved) {
	    throw new IllegalStateException(
	            "Can not perform this action after onSaveInstanceState");
	}
	if (mNoTransactionsBecause != null) {
	    throw new IllegalStateException(
	            "Can not perform this action inside of " + mNoTransactionsBecause);
	}
}
```
I believe, you must have read [this](http://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html) blog post already. If not, please go ahead. It's a good read.

> can you please point me to some documentation saying this?

Yes, here you go:


[1]: From documentation of [`FragmentManager#beginTransaction`](http://developer.android.com/reference/android/app/FragmentManager.html#beginTransaction()) :
> Note: A fragment transaction can only be created/committed prior to an activity saving its state. If you try to commit a transaction after FragmentActivity.onSaveInstanceState() (and prior to a following FragmentActivity.onStart or FragmentActivity.onResume(), you will get an error. This is because the framework takes care of saving your current fragments in the state, and if changes are made after the state is saved then they will be lost.

[2]: From documentation of [`FragmentTransaction#commit()`](http://developer.android.com/reference/android/support/v4/app/FragmentTransaction.html#commit())
>A transaction can only be committed with this method prior to its containing activity saving its state. If the commit is attempted after that point, an exception will be thrown. This is because the state after the commit can be lost if the activity needs to be restored from its state. See commitAllowingStateLoss() for situations where it may be okay to lose the commit.

**Comment by eygraber** [comment] 2015-06-05 01:05
@geekrax I understand that, but I am referring to `Fragment.onResume` and not `FragmentActivity.onResume`.

The difference is `Fragment.onResume` gets called from `FragmentActivity.onPostResume` which happens after `FragmentActivity.onResume`.

[FragmentActivity.java](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/master/v4/java/android/support/v4/app/FragmentActivity.java)
```java
    /**
     * Dispatch onResume() to fragments.
     */
    @Override
    protected void onPostResume() {
        super.onPostResume();
        mHandler.removeMessages(MSG_RESUME_PENDING);
        onResumeFragments();
        mFragments.execPendingActions();
    }
```
