### ISSUE TITLE
NullPointerException org.robolectric.shadows.ShadowLooper.getMainLooper(ShadowLooper.java:69)

### ISSUE THREAD

**Issue by mitrejcevski** [robolectric/robolectric#1520] opened 2015-01-27 22:34 UTC
java.lang.NullPointerException
	at org.robolectric.shadows.ShadowLooper.getMainLooper(ShadowLooper.java:69)
	at android.os.Looper.getMainLooper(Looper.java)
	at org.robolectric.Robolectric.getUiThreadScheduler(Robolectric.java:1283)
	at org.robolectric.shadows.ShadowSystemClock.now(ShadowSystemClock.java:15)
	at org.robolectric.shadows.ShadowSystemClock.uptimeMillis(ShadowSystemClock.java:44)
	at org.robolectric.shadows.ShadowSystemClock.elapsedRealtime(ShadowSystemClock.java:49)
	at android.os.SystemClock.elapsedRealtime(SystemClock.java)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:137)

**Comment by NorrinRadd** [comment] 2015-02-24 01:43
I'm hitting this issue also, 100% of the time.  Maybe I can turn off shadowing of Looper somehow.  I haven't requested it and it doesn't seem necessary in my use case.  

DEBUG: Loading resources for android from jar:/Users/Norrin/.m2/repository/org/robolectric/android-all/4.3_r2-robolectric-0/android-all-4.3_r2-robolectric-0.jar!/res...
Exception in thread "Thread-2" java.lang.NullPointerException
	at org.robolectric.shadows.ShadowLooper.getMainLooper(ShadowLooper.java:69)
	at org.robolectric.shadows.ShadowLooper.doLoop(ShadowLooper.java:88)
	at org.robolectric.shadows.ShadowLooper.loop(ShadowLooper.java:75)
	at android.os.Looper.loop(Looper.java)
	at com.dmo.ampslib.DMOAssetManager$1.run(DMOAssetManager.java:108)
	at java.lang.Thread.run(Thread.java:745)
Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 68.588 sec <<< FAILURE!

**Comment by DevinShine** [comment] 2015-03-12 08:41
I'm hitting this issue also.I found the solution,but it's not work for me.Hope will help you.

**Comment by JorisBolsens** [comment] 2015-04-03 04:58
I'm also getting this error:
```
Exception in thread "pool-1-thread-2" java.lang.NullPointerException
	at org.robolectric.shadows.ShadowLooper.getMainLooper(ShadowLooper.java:69)
	at android.os.Looper.getMainLooper(Looper.java)
	at com.android.volley.Request.finish(Request.java:231)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jaredsburrows** [comment] 2015-07-02 22:52
@mitrejcevski How are you getting this error? Can you should use how to reproduce it? Do you have any code to share?

**Comment by mitrejcevski** [comment] 2015-07-06 06:24
Hi, not anymore. I'm using v3.0

On Fri, Jul 3, 2015 at 1:52 AM Jared Burrows <notifications@github.com>
wrote:

> @mitrejcevski <https://github.com/mitrejcevski> How are you getting this
> error? Can you should use how to reproduce it? Do you have any code to
> share?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robolectric/robolectric/issues/1520#issuecomment-118187711>
> .
>
-- 

Jovche

**Comment by mitrejcevski** [comment] 2015-07-06 06:27
@jaredsburrows Hi, after I switched to v3.0 everything works like charm. No longer see this issue.

**Comment by jaredsburrows** [comment] 2015-07-06 06:51
Nice! @mitrejcevski @erd  Can you close this?

**Closed** 2015-07-06 06:52 UTC

**Comment by ishan1604** [comment] 2015-10-21 08:08
I am getting this error and cannot get past it.

```
Exception in thread "NewWidgetProvider-worker" java.lang.NullPointerException
	at org.robolectric.shadows.ShadowLooper.getMainLooper(ShadowLooper.java:70)
	at org.robolectric.shadows.ShadowLooper.doLoop(ShadowLooper.java:85)
	at org.robolectric.shadows.ShadowLooper.loop(ShadowLooper.java:76)
	at android.os.Looper.loop(Looper.java)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```
I am using v3.0.

This HandlerThread is being initialised in an AppWidgetProvider Constructor.

What should I do ?

**Comment by hameno** [comment] 2015-10-27 10:18
I'm seeing this after switching to JDK/JRE8

**Comment by ishan1604** [comment] 2015-10-27 11:51
@hameno Any possible solution/fix ?

**Comment by jophde** [comment] 2015-10-27 21:48
I am also seeing this on JDK/JRE8 and Robolectric 3.0.  This should be reopened.

**Comment by hameno** [comment] 2015-10-28 08:31
@ishan1604 None that I know of

**Comment by b2mdevelopment** [comment] 2015-12-04 17:22
WARNING: no system properties value for ro.build.date.utc
Exception in thread "IntentService[com.b2msolutions.reyna.services.ForwardService]" java.lang.NullPointerException
	at org.robolectric.shadows.ShadowLooper.getMainLooper(ShadowLooper.java:69)
	at org.robolectric.shadows.ShadowLooper.doLoop(ShadowLooper.java:88)
	at org.robolectric.shadows.ShadowLooper.loop(ShadowLooper.java:75)
	at android.os.Looper.loop(Looper.java)
	at org.robolectric.shadows.ShadowHandlerThread.run(ShadowHandlerThread.java:32)
	at android.os.HandlerThread.run(HandlerThread.java)

**Comment by mag** [comment] 2015-12-16 00:50
I am running into this as well on 3.0 w/ Java 8. It doesn't fail any tests for me, but it fills my test output with errors.

And it is very surprising to me that Robolectric is allowing the `BackgroundThread` to actually run. My assumption was that be default, Robolectric prevented the BackgroundThread from starting and took over the Looper. Yet during the init cycle of my Activity, some code calls `BackgroundThread.getHandler()` and this ends up really starting a thread (I can post the stack when the HandlerThread is created and started if anybody finds it interesting).

@kriegfrj you have been overhauling threading and scheduling; does it surprise you that the background thread actually runs? I know that you are working on supporting multi-threading, but shouldn't the default be that no threads run?

**Comment by kriegfrj** [comment] 2015-12-16 01:41
Hi @mag,

I think I this issue with the NPEs on background looper threads polluting the stack trace some time ago (see #1931, in particular the last dot point in the OP), though I don't think it made it into the 3.0 release. I think if you try it with the current master (or at the least some revision that incorporates #1931), these errors will disappear from your test output.

In answer to your question about background looper threads: Robolectric has never prevented these background looper threads from *starting* - rather it prevents them from doing anything once they are started. It does this by putting the thread into an an infinite `wait()` when `loop()` is executed. Message dispatching (regardless of which `Looper` is being posted to) either happens on the thread that posted the message/runnable (if the current scheduling mode determined that it should run immediately) or on the thread that invokes one of the scheduler-advancing methods like `runNext()` or `advanceToLastPostedRunnable()`. This is of course usually the test (ie the "main") thread, but not necessarily. As I mentioned in #1931, I'm working on changing this so that messages are actually dispatched on the correct thread (though still in a predictable, controllable order), but I've been a bit short on spare time recently.

Prior to #1931 these background threads would hang around indefinitely unless the test programmer explicitly took steps to shut them down.

**Comment by mag** [comment] 2015-12-16 02:05
@kriegfrj I see - I had no idea how that the background thread was actually running! Thanks for clarification.

@erd btw, any timeline for 3.1? Anything I can do to help?

**Comment by jaredsburrows** [comment] 2015-12-23 08:13
@mag @erd  +1

**Comment by inder123** [comment] 2017-10-04 00:12
This problem has surfaced for me when using JDK 1.8 and PowerMock 1.7.3
I see that problem is in ShadowLooper.quiteUnchecked() method because getScheduler() returns null. How do I solve this problem? Thanks.

java.lang.NullPointerException
	at org.robolectric.shadows.ShadowLooper.quitUnchecked(ShadowLooper.java:129)
	at org.robolectric.shadows.ShadowLooper.quit(ShadowLooper.java:117)
	at android.os.Looper.quit(Looper.java)
	at org.robolectric.shadows.ShadowLooper.resetThreadLoopers(ShadowLooper.java:59)
	at org.robolectric.Shadows.reset(Shadows.java:1653)
	at org.robolectric.Robolectric.reset(Robolectric.java:42)
	at org.robolectric.android.internal.ParallelUniverse.resetStaticState(ParallelUniverse.java:45)
	at org.robolectric.RobolectricTestRunner.afterTest(RobolectricTestRunner.java:308)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:230)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:64)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
