### ISSUE TITLE
robolectric 3.7 fails compilation with cannot access android.content.pm.PackageParser

### ISSUE THREAD

**Issue by kageiit** [robolectric/robolectric#3758] opened 2018-02-13 20:30 UTC
### Steps to Reproduce

Using code that refers to shadow package manger - `shadowPackageManager.addPackage(packageInfo);`

### Robolectric & Android Version

Robolectric - 3.7
compile sdk - 27
target sdk - 21

**Comment by xian** [comment] 2018-02-13 20:40
Looks like dupe of #3752, closing.

**Closed by xian** 2018-02-13 20:40 UTC
