### ISSUE TITLE
Random error in CI - java.lang.NoSuchFieldError: noncompatWidthPixels

### ISSUE THREAD

**Issue by sitaram168** [robolectric/robolectric#9630] opened 2024-09-25 15:38 UTC
### Description
Randomly all tests of a module fail with following exception in CI (Bitrise).

```
java.lang.NoSuchFieldError: noncompatWidthPixels
      at org.robolectric.android.DeviceConfig.setDimensions(DeviceConfig.java:253) |  
  |   | at org.robolectric.android.DeviceConfig.applyToConfiguration(DeviceConfig.java:206) |  
  |   | at org.robolectric.android.Bootstrap.applyQualifiers(Bootstrap.java:101) |  
  |   | at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:210) |  
  |   | at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:283) |  
  |   | at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:285) |  
  |   | at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104) |  
  |   | at java.util.concurrent.FutureTask.run(FutureTask.java:264) |  
  |   | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) |  
  |   | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) |  
  |   | at java.lang.Thread.run(Thread.java:840)
```

### Robolectric & Android Version
Robolectric 4.13
Android version - not specifying anything in Config. So taking the target API version which is 33

**Comment by hoisie** [comment] 2024-09-25 16:11
This could only happen if you are using `DisplayMetrics.noncompatWidthPixels` from the Android stubs jar. But from the stack trace, it seems like you are running in a Robolectric sandbox. And `DisplayMetrics.noncompatWidthPixels` has been around since JB (or before).

I am not sure what is happening here. There may be other ClassLoader shenanigans at play here. Are you using any other mocking frameworks?

**Comment by sitaram168** [comment] 2024-09-30 07:24
Hey @hoisie 
Thanks for the reply. Yes we are using mockk (https://mockk.io/) and unmock plugin (https://github.com/bjoernQ/unmock-plugin). Can the later be the problem ? 

Also, you mentioned about SandboxRunner. Yes, we use RoboltecircTestRunner which extends SandboxRunner (https://robolectric.org/#kotlin). Is there any other option ?

**Comment by hoisie** [comment] 2024-09-30 14:53
Yeah unmock would be my guess as to what the problem is.

It is not necessary to use unmock. Robolectric gives you the same functionality.

**Comment by sitaram168** [comment] 2024-09-30 15:43
Thanks @hoisie. Will try after removing unmock if possible. Challenge is it happens randomly, which makes it difficult to conclude if it worked or not.

**Comment by hoisie** [comment] 2024-10-08 02:17
Closing this for now, I am fairly certain the issue is unmock.

**Closed** 2024-10-08 02:17 UTC

**Comment by shashachu** [comment] 2024-10-11 16:01
> This could only happen if you are using `DisplayMetrics.noncompatWidthPixels` from the Android stubs jar. But from the stack trace, it seems like you are running in a Robolectric sandbox. And `DisplayMetrics.noncompatWidthPixels` has been around since JB (or before).
> 
> I am not sure what is happening here. There may be other ClassLoader shenanigans at play here. Are you using any other mocking frameworks?

@hoisie can you give a bit more specifics about what you mean here? Do you mean this would happen if we were not correctly using Robolectric during a test? We just started seeing this occasionally on CI and I have a guess as to which PR caused it, but I'm not entirely sure how to fix it. We are using mockk in places but we are not using the unmock plugin.

**Comment by mw-c2p** [comment] 2025-02-06 13:48
Happens to me since 4.14+

**Comment by JesusOnt** [comment] 2025-02-06 16:39
Is happening to me using 4.13 on targetSDK 34 and 35 randomly on CI I'm seeing 
`java.lang.NoSuchFieldError: Class android.util.DisplayMetrics does not have member field 'float noncompatXdpi'
java.lang.NoSuchFieldError: Class android.util.DisplayMetrics does not have member field 'int noncompatWidthPixels'

`

**Comment by hoisie** [comment] 2025-02-07 00:59
If someone can put up a sample app that demonstrates this issue, that would be really helpful. Otherwise, I really have no idea what might be causing it. My only guess is that there may be some other framework that is modifying the byte code of Android classes.

**Comment by sitaram168** [comment] 2025-04-07 17:03
Still seeing the issue, and as mentioned by @JesusOnt happens more frequently in CI. The module(or gradle subproject) which is seeing this more is using mockk. but there are other modules as well, which use mockk, and don't see the issue.

**Comment by MGaetan89** [comment] 2025-04-08 06:14
@sitaram168 are you able to provide a minimal reproducer for this issue? Otherwise, as @hoisie said in a previous comment, it will be hard to debug and fix this.
