### ISSUE TITLE
Unit test failing when using Ollie

### ISSUE THREAD

**Issue by ConorGarry** [robolectric/robolectric#1882] opened 2015-06-09 19:20 UTC
Getting this stacktrace result when making a simple query using Ollie, the code itself runs fine but when unit tested with Robolectric I get this:

    Caused by: java.lang.IllegalStateException: Illegal connection pointer 1. Current pointers for thread Thread[pool-5-thread-1,5,main] []
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getConnection(ShadowSQLiteConnection.java:331)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getStatement(ShadowSQLiteConnection.java:338)
	at org.robolectric.shadows.ShadowSQLiteConnection.stmt(ShadowSQLiteConnection.java:50)
	at org.robolectric.shadows.ShadowSQLiteConnection.access$000(ShadowSQLiteConnection.java:31)
	at org.robolectric.shadows.ShadowSQLiteConnection$16.call(ShadowSQLiteConnection.java:287)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:450)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:444)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

I've tried with both 3.0-rc2 and 3.0 SNAPSHOT.

**Comment by erd** [comment] 2015-06-10 00:59
Could you dig into this a bit more? I don't use Ollie, so I don't have much context on how it works.

**Comment by nenick** [comment] 2015-06-13 16:19
@ConorGarry Please try if my answer fix this issue for you https://github.com/robolectric/robolectric/issues/1890#issuecomment-111726535

**Comment by jaredsburrows** [comment] 2015-07-01 11:11
@erd Here is another issue where someone posts an issue that we cannot reproduce and does not respond. Can we close this? If he wants to add more detail he can always update this issue.

**Comment by erd** [comment] 2015-07-02 20:31
@ConorGarry Feel free to re-open this issue if you are able to provide us with additional information.

**Closed by erd** 2015-07-02 20:31 UTC

**Comment by ConorGarry** [comment] 2015-07-11 13:21
Sorry for abandoning the thread, I had to move onto another project. I did find a fix I'll post here should anyone have the same issue.

@nenick Your solution led me on the right track, when I set the DataBase helper in Ollie, it didn't work. However there is a static boolean 'sInitialized' that when set to false that did the job. Seems like a dirty fix but now I can do multiple tests with Ollie. 

    @After
    public void resetOllieForNextTest() {
        setPrivateField(Ollie.class, "sInitialized", false);
    }

    public static void setPrivateField(Class clz, String fieldName, boolean value) {
        Field field;
        try {
            field = clz.getDeclaredField(fieldName);
            field.setAccessible(true);
            field.set(null, value);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
