### ISSUE TITLE
Cannot use mockk to mock classes, with robolectric 4.4-alpha-4 (sample project included)

### ISSUE THREAD

**Issue by calvarez-ov** [robolectric/robolectric#5848] opened 2020-08-12 15:00 UTC
### Description
Using `mockk(relaxed=true)` in a test `setUp()` results in a `ClassCastException`, when at least two test methods are run, and the second test has a `@Config(sdk=[??])` annotation.

### Steps to Reproduce
* Sample app code:
    ```kotlin
    class Foo {
        var hello = "world"
        fun speak() {
            println(hello)
        }
    }
    ```
* Sample test code:
    ```kotlin
    @RunWith(AndroidJUnit4::class)
    class ExampleUnitTest {
        private lateinit var foo: Foo

        @Before
        fun setUp() {
            foo = mockk(relaxed = true)
        }

        @Test
        fun testMockk1() {
            assertEquals(0, foo.hello.length)
        }

        @Config(sdk=[28])
        @Test
        fun testMockk2() {
            assertEquals(0, foo.hello.length)
        }
    }
    ```
* Run `./gradlew testDebugUnitTest` in the sample project linked below
* Expected behavior: tests pass
* Actual behavior: `testMockk2()` fails:
    ```
    io.mockk.MockKException: Can't instantiate proxy for class com.example.robolectricmockk.Foo
        at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:64)
        at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:29)
        at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:59)
        at com.example.robolectricmockk.ExampleUnitTest.setUp(ExampleUnitTest.kt:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: io.mockk.proxy.MockKAgentException: Instantiation exception
        at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:54)
        at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
        ... 18 more
    Caused by: java.lang.ClassCastException: Cannot cast com.example.robolectricmockk.Foo to com.example.robolectricmockk.Foo
        at java.lang.Class.cast(Class.java:3369)
        at io.mockk.proxy.jvm.ObjenesisInstantiator.instanceViaObjenesis(ObjenesisInstantiator.kt:73)
        at io.mockk.proxy.jvm.ObjenesisInstantiator.instance(ObjenesisInstantiator.kt:42)
        at io.mockk.proxy.jvm.ProxyMaker.instantiate(ProxyMaker.kt:75)
        at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:42)
        ... 19 more
    ```

### Robolectric & Android Version
Robolectric: 4.4-alpha-4

### Link to a public git repo demonstrating the problem:
https://github.com/libon/RobolectricMockkIssue

### Additional information
* Same behavior is observed using java 8 or java 14
* Same behavior if mockk is used inside `setUp()` or inside the test method directly
* Same behavior regardless of the value of the sdk in the `@Config(sdk=[??])` annotation in `testMockk2()`
  - Exception: when running with java 14, and specifying `sdk=[29]`, both tests pass
* Running `testMockk2()` in isolation works
* Remove the `@Config(sdk=[28])` annotation from `testMockk2()` and both tests will pass
* Both tests pass using robolectric 4.3.1 and java 8

**Comment by hoisie** [comment] 2020-08-17 16:32
Is it possible to show the Java equivalent of this code? Seems like using this lateinit is triggering some kind of ClassLoader issue. Also, does it work if you make `foo` a local variable in each function?

**Comment by hoisie** [comment] 2020-08-17 16:36
It's possible that this is something that has to be addressed in mockK. It could be the case that mockK expects the entire test suite to be run under one ClassLoader, which is not the case in Robolectric.

**Comment by calvarez-ov** [comment] 2020-08-17 16:53
@hoisie I'm not sure how to make java equivalent code for this. Mockk is a library that works specifically with kotlin.

There's a link to a sample reproduction project though. Please don't hesitate to check it out and fiddle with it to understand the different scenarios where the bug can occur.

Thanks!

**Comment by pavlospt** [comment] 2020-08-18 16:49
@hoisie the Java decompiled code looks like the following:

```java
public final class ExampleUnitTest {
   private Foo foo;

   @Before
   public final void setUp() {
      boolean relaxed$iv = true;
      KClass[] moreInterfaces$iv = new KClass[0];
      String name$iv = (String)null;
      boolean relaxUnitFun$iv = false;
      int $i$f$mockk = false;
      MockK this_$iv$iv = MockK.INSTANCE;
      int $i$f$useImpl = false;
      MockKGateway.Companion.setImplementation(JvmMockKGateway.Companion.getDefaultImplementationBuilder());
      int var9 = false;
      MockKDsl var10 = MockKDsl.INSTANCE;
      KClass[] moreInterfaces$iv$iv = (KClass[])Arrays.copyOf(moreInterfaces$iv, moreInterfaces$iv.length);
      int $i$f$internalMockk = false;
      Object mock$iv$iv = ((MockKGateway)MockKGateway.Companion.getImplementation().invoke()).getMockFactory().mockk(Reflection.getOrCreateKotlinClass(Foo.class), name$iv, relaxed$iv, moreInterfaces$iv$iv, relaxUnitFun$iv);
      this.foo = (Foo)mock$iv$iv;
   }

   @Test
   public final void testMockk1() {
      Integer var10000 = 0;
      Foo var10001 = this.foo;
      if (var10001 == null) {
         Intrinsics.throwUninitializedPropertyAccessException("foo");
      }

      Assert.assertEquals(var10000, var10001.getHello().length());
   }

   @Config(
      sdk = {28}
   )
   @Test
   public final void testMockk2() {
      Integer var10000 = 0;
      Foo var10001 = this.foo;
      if (var10001 == null) {
         Intrinsics.throwUninitializedPropertyAccessException("foo");
      }

      Assert.assertEquals(var10000, var10001.getHello().length());
   }
}
```

**Comment by hoisie** [comment] 2020-08-18 17:59
This is just a guess, but I noticed that MockK caches types:
https://github.com/mockk/mockk/blob/master/agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/ObjenesisInstantiator.kt

Also, in Robolectric 4.4 the ClassLoader inheritance was updated to follow the ClassLoader conventions properly:
https://github.com/robolectric/robolectric/pull/5036

Because this issue is not reproducible with Mockito, I am inclined to believe that it is a MockK type caching issue (although I could be convinced otherwise).

**Comment by pavlospt** [comment] 2020-08-18 18:28
Should we ping someone from the MockK team to weigh in on this?

**Comment by hoisie** [comment] 2020-08-18 18:48
I wonder if in MockK `ObjenesisInstantiator`, instead of doing this:
```kt
private val objenesis = ObjenesisStd(true)
```
https://github.com/mockk/mockk/blob/master/agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/ObjenesisInstantiator.kt#L17

pass false to the ObjenesisStd constructor:
```kt
private val objenesis = ObjenesisStd(false)
```

which disables the cache.

https://github.com/easymock/objenesis/blob/master/main/src/main/java/org/objenesis/ObjenesisStd.java#L40-L42

**Comment by pavlospt** [comment] 2020-08-18 18:57
I am not sure if this is controllable from the "outside world" rather than creating a new version of MockK with that modification 🤔

**Comment by hoisie** [comment] 2020-08-18 19:21
Cool, I guess this will be fixed when the new version of MockK is released :)

**Comment by pavlospt** [comment] 2020-08-18 19:41
@hoisie ok that was almost instant. Will check if there is a snapshotting pipeline in MockK to try that out 😄

**Comment by hoisie** [comment] 2020-08-18 19:43
@pavlospt there is, but you have to run `./gradlew publishToMavenLocal` in the MockK directory with Java 8 because of a doclet issue.

**Comment by hoisie** [comment] 2020-08-18 19:53
Also I had to change this
```diff
-    testImplementation "io.mockk:mockk:1.10.0"
+    testImplementation "io.mockk:mockk-jvm:1.10.1-SNAPSHOT"
```

**Comment by pavlospt** [comment] 2020-08-18 20:12
Unfortunately local publishing does not work for me 😞 It says it misses some kind of signing key!

**Comment by hoisie** [comment] 2020-08-18 20:13
Create the file `~/.gradle/gradle.properties`:
```
$ cat ~/.gradle/gradle.properties
signing.keyId=
signing.password=
signing.secretKeyRingFile=
```

**Comment by hoisie** [comment] 2020-08-18 22:28
Any luck getting the snapshot version installed?

**Comment by pavlospt** [comment] 2020-08-19 08:16
@hoisie No I couldn't do it because it now fails for a different reason :/ 
```
* What went wrong:
Execution failed for task ':mockk-agent-api:signMavenJavaPublication'.
> path may not be null or empty string. path=''
```

**Comment by hoisie** [comment] 2020-08-19 16:58
Great, I will close out this issue. Until the new version of MockK is release, I suppose the workaround is to either
1) Use another mocking library for multi-SDK tests (e.g. mockito)
2) For multi-sdk tests, use something like 'enabledSdks' to avoid running it on multiple sdks, and configure the SDK version through build files.

**Closed by hoisie** 2020-08-19 16:58 UTC

**Comment by farukprogrammer** [comment] 2020-09-17 02:03
> @hoisie No I couldn't do it because it now fails for a different reason :/
> 
> ```
> * What went wrong:
> Execution failed for task ':mockk-agent-api:signMavenJavaPublication'.
> > path may not be null or empty string. path=''
> ```
> 
> Edit: Managed to make it work 😄
> Edit 2: Yes the fix seems to be working for our test suite! Also tested it with the repro project from @calvarez-ov and it works there as well!

how you can fix this? I'm facing the same problem
