### ISSUE TITLE
Robolectric treats `array` resource differently than Android

### ISSUE THREAD

**Issue by samtstern** [robolectric/robolectric#2631] opened 2016-09-08 17:03 UTC
### Description

In my resources I had defined:

``` xml
    <array name="facebook_permissions">
    </array>
```

I was getting this as a String array in code with `activity.getResources().getStringArray(R.id.facebook_permissions)` and it works fine in my app.

In Robolectric this resulted in `Resources$NotFoundException`.

Replacing the `<array>` tag with a `<string-array>` tag fixed it.  I found the answer in [this google group thread](https://groups.google.com/forum/#!topic/robolectric/gQoY0bCguYs) after much searching.
### Steps to Reproduce

See above.
### Robolectric & Android Version

Android SDK 23
Robolectric 3.1.1

**Comment by xian** [comment] 2017-01-11 01:59
Dupe of #2064.

**Closed by xian** 2017-01-11 01:59 UTC
