### ISSUE TITLE
I am getting this error when running my test 

### ISSUE THREAD

**Issue by mostafaashraf92** [robolectric/robolectric#4604] opened 2019-02-05 21:14 UTC
### Description
I run my local unit test successfully but when i run debugUnitTest task it fails saying 

```java
java.lang.IllegalArgumentException
	at org.objectweb.asm.AnnotationVisitor.<init>(Unknown Source)
	at org.objectweb.asm.AnnotationVisitor.<init>(Unknown Source)
	at org.objectweb.asm.tree.AnnotationNode.<init>(AnnotationNode.java:77)
	at org.objectweb.asm.tree.AnnotationNode.<init>(AnnotationNode.java:63)
	at org.objectweb.asm.tree.ClassNode.visitAnnotation(ClassNode.java:208)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.robolectric.internal.bytecode.ClassInstrumentor.analyzeClass(ClassInstrumentor.java:63)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$maybeInstrumentClass$1(SandboxClassLoader.java:121)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:120)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$findClass$0(SandboxClassLoader.java:111)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:110)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.robolectric.RobolectricTestRunner.getHooksInterface(RobolectricTestRunner.java:551)
	at org.robolectric.RobolectricTestRunner.configureSandbox(RobolectricTestRunner.java:235)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:230)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
```

### Robolectric & Android Version

Roboelectric 4.1

    compileSdkVersion = 28
    buildToolsVersion = '28.0.3'
    targetSdkVersion = 28
    supportLibVersion = '28.0.0'

    minSdkVersionApp = 19
    
gradle         classpath 'com.android.tools.build:gradle:3.1.4'

**Comment by xian** [comment] 2019-02-05 21:36
What version of java are you using?

**Comment by mostafaashraf92** [comment] 2019-02-05 21:37
Java 1.7

**Comment by mostafaashraf92** [comment] 2019-02-05 21:58
Does it works with java 1.7 ?

**Comment by mostafaashraf92** [comment] 2019-02-05 22:08
@xian i have switched to Java1.8 and same error

**Comment by jongerrish** [comment] 2019-02-05 22:17
@mostafaashraf92 Do you have any other dependencies that perform byte code instrumentation in your classpath?

**Comment by mostafaashraf92** [comment] 2019-02-05 22:18
@jongerrish  yes

-  testImplementation 'org.powermock:powermock-module-junit4:1.7.0RC2',
            'org.powermock:powermock-api-mockito2:1.7.0RC2'
- testImplementation 'org.powermock:powermock-module-junit4:1.7.0RC2',
            'org.powermock:powermock-api-mockito2:1.7.0RC2'

   testImplementation 'org.mockito:mockito-all:1.8.4'
    implementation 'org.mockito:mockito-all:1.8.4'

**Comment by mostafaashraf92** [comment] 2019-02-05 22:20
Sorry         classpath 'io.fabric.tools:gradle:1.27.1'

**Comment by mostafaashraf92** [comment] 2019-02-05 22:22
And here are classpathes dependencies in project gradle

       classpath 'net.sf.proguard:proguard-gradle:5.3.3'
        classpath 'org.aspectj:aspectjtools:1.8.13'
        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.1'
        classpath 'com.soasta.mpulse:mpulse-android-gradle-plugin:2.4.2'
        classpath 'com.google.gms:google-services:4.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.archinamon:android-gradle-aspectj:3.2.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

**Comment by mostafaashraf92** [comment] 2019-02-06 21:40
@xian do you have any recommendation for this?

**Comment by jongerrish** [comment] 2019-02-06 23:52
It could well be an incompatibility in the byte code weaving both Powermock + Robolectric do.

We have a test project for Power Mock compatibility 

https://github.com/robolectric/robolectric/blob/master/integration_tests/powermock/build.gradle#L12
 
Looks like this currently uses version 1.6.6 .... I'm not sure if 2.1.7 has broken that compatibility?

It would make it easier for us to investigate if you're able to provide a reproducible test case for your issue and using the powermock test module https://github.com/robolectric/robolectric/blob/master/integration_tests/powermock would be a good place to start I think if indeed it is a powermock compatibility issue.

**Comment by mostafaashraf92** [comment] 2019-02-07 00:36
@jongerrish  What about    testImplementation 'org.mockito:mockito-all:1.8.4'
                                             implementation 'org.mockito:mockito-all:1.8.4'

**Comment by jongerrish** [comment] 2019-02-07 00:46
I'm not exactly sure what that includes, meaning, which version of
MockMaker is being used in your project and how that might affect the
bytecode generated by Robolectric. I know some versions of MockMaker use
bytebuddy which uses ASM like Robolectric, so maybe a version skew on the
classpath?

I'd suggest trying to modify our powermock or mockito or
mockito-experimental compatibility projects adding those versions of
mockito / powermock dependencies and see if you can reproduce it in one of
our tests. It may also be something weird going on with your environment so
you may have to tweak the tests, but if you can provide a repo test case
for this we'll take a look.

**Comment by mostafaashraf92** [comment] 2019-02-07 01:15
Still not fixed after adding changing versions of power mock and mockito as found in Integration_tests

**Comment by mostafaashraf92** [comment] 2019-02-07 01:16
java.lang.IllegalArgumentException
	at org.objectweb.asm.AnnotationVisitor. at this method 

 public AnnotationVisitor(final int api, final AnnotationVisitor annotationVisitor) {
    if (api != Opcodes.ASM6 && api != Opcodes.ASM5 && api != Opcodes.ASM4 && api != Opcodes.ASM7) {
      throw new IllegalArgumentException();
    }
    this.api = api;
    this.av = annotationVisitor;
  }

**Comment by jongerrish** [comment] 2019-02-07 01:52
I wonder if it could be a version skew on the Asm version on the classpath.

Could you put a breakpoint in on the line that throws the exception and
report back the value of the api parameter at that point?

Again if you can reproduce it in the integration tests modules that would
really help us track it down.

**Comment by mostafaashraf92** [comment] 2019-02-07 02:03
@jongerrish What do you mean by trying to reproduce it in the integration tests modules ? Clone the code ?

**Comment by jongerrish** [comment] 2019-02-07 03:13
Yeah, just a suggestion, or create your own repo you can share that shows
the failure.

I wonder if the issue comes from using mockito-all - doesn't that package
all the dependencies including perhaps a conflicting and older version of
ASM?

(According to https://site.mockito.org/ it is for legacy use cases and has
been discontinued in mockito 2.0+)

You can always peek inside that jar file and see if includes
org/objectweb/asm/AnnotationVisitor.class - if so that is probably the
problem, I think Robolectric requires a newer (v6.0?) version of ASM than
probably is in that mockito-all jar.

**Comment by bj0** [comment] 2019-03-19 23:27
I am also getting this exception after upgrading from `3.8` to `4.2.1`.  I am not using powermock or mockito, only junit `4.12` and robolectric.  

The only workaround I could find was this [SO question](https://stackoverflow.com/questions/53987300/robolectric-test-throwing-illegalargumentexception-with-no-message)

**Comment by xian** [comment] 2019-03-26 00:20
Yeah, it sounds like you're getting an older version of ASM on your classpath which doesn't support Java 8 bytecode... you should be able to use `./gradlew dependencies` to see the version that's being used and figure out why.

**Comment by bj0** [comment] 2019-04-11 19:11
I finally got a chance to check the project.  It looks like there's a dependency `org.ow2.asm:asm`, is that what you refer to?  It looks like robolectric uses version 7.0, `com.android.tools.build:builder` uses 6.0, and another library uses 5.0.1

Looking at the website for ASM, it seems like java 8 support was added in 5.0

**Comment by hoisie** [comment] 2020-10-14 06:16
Closing this issue as it doesn't seem to be an issue with Robolectric. Seems like you need to exclude the outdated asm version from the test classpath.

**Closed by hoisie** 2020-10-14 06:16 UTC
