### ISSUE TITLE
android.content.pm.PackageParser$PackageParserException: Failed to parse

### ISSUE THREAD

**Issue by 4mr0m3r0** [robolectric/robolectric#6737] opened 2021-09-22 19:48 UTC
### Description
**Scenario**
Whenever I run a Unit Test for Android Room, it fails.
Fragment of the code for setting up:

```
import androidx.test.ext.junit.runners.AndroidJUnit4

@RunWith(AndroidJUnit4::class)
internal class ClassImplTest {
    @get:Rule var instantTaskExecutorRule = InstantTaskExecutorRule()
    private lateinit var dao: AnyNameDao
    private lateinit var database: DatabaseBuilder
    private lateinit var cache: AnyNameCache


    @BeforeTest
    fun createDatabase() {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        database = Room
            .inMemoryDatabaseBuilder(context, DatabaseBuilder::class.java)
            .allowMainThreadQueries()
            .build()
        dao = database.anyNameDao()
        cache = AnyNameCacheImpl(database)
    }
```
**Warning before error**
`resources.arsc in APK '/<user-path>/.m2/repository/org/robolectric/android-all-instrumented/11-robolectric-6757853-i1/android-all-instrumented-11-robolectric-6757853-i1.jar' is compressed.`

**Error**

```
android.content.pm.PackageParser$PackageParserException: Failed to parse /<path-to-dynamic-feature>/build/intermediates/apk_for_local_test/dummyDebugUnitTest/apk-for-local-test.ap_
java.lang.RuntimeException: android.content.pm.PackageParser$PackageParserException: Failed to parse /<path-to-dynamic-feature>/build/intermediates/apk_for_local_test/dummyDebugUnitTest/apk-for-local-test.ap_
    at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:69)
    at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage_measured(AndroidTestEnvironment.java:386)
    at org.robolectric.android.internal.AndroidTestEnvironment.lambda$loadAppPackage$3(AndroidTestEnvironment.java:358)
    at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
    at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage(AndroidTestEnvironment.java:358)
    at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:257)
    at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$0(AndroidTestEnvironment.java:229)
    at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
    at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$1(AndroidTestEnvironment.java:226)
    at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
    at org.robolectric.RuntimeEnvironment.getApplication(RuntimeEnvironment.java:71)
    at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:194)
    at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:321)
    at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:269)
    at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: android.content.pm.PackageParser$PackageParserException: Failed to parse /<path-to-dynamic-feature>/build/intermediates/apk_for_local_test/dummyDebugUnitTest/apk-for-local-test.ap_
    at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1471)
    at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1415)
    at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:932)
    at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1140)
    at android.content.pm.PackageParser.parsePackage(PackageParser.java:1054)
    at android.content.pm.PackageParser.parsePackage(PackageParser.java:1063)
    at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:47)
    ... 18 more
Caused by: java.lang.NullPointerException
    at org.robolectric.res.android.LoadedArsc$LoadedPackage.Load(LoadedArsc.java:728)
    at org.robolectric.res.android.LoadedArsc.LoadTable(LoadedArsc.java:911)
    at org.robolectric.res.android.LoadedArsc.Load(LoadedArsc.java:957)
    at org.robolectric.res.android.CppApkAssets.LoadImpl_measured(CppApkAssets.java:266)
    at org.robolectric.res.android.CppApkAssets.lambda$LoadImpl$0(CppApkAssets.java:205)
    at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
    at org.robolectric.res.android.CppApkAssets.LoadImpl(CppApkAssets.java:202)
    at org.robolectric.res.android.CppApkAssets.Load(CppApkAssets.java:117)
    at org.robolectric.shadows.ShadowArscApkAssets9.nativeLoad(ShadowArscApkAssets9.java:264)
    at org.robolectric.shadows.ShadowArscApkAssets9.nativeLoad(ShadowArscApkAssets9.java:285)
    at android.content.res.ApkAssets.nativeLoad(ApkAssets.java)
    at android.content.res.ApkAssets.__constructor__(ApkAssets.java:291)
    at android.content.res.ApkAssets.<init>(ApkAssets.java)
    at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:140)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.robolectric.util.ReflectionHelpers.callStaticMethod(ReflectionHelpers.java:358)
    at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:56)
    at org.robolectric.shadow.api.Shadow.directlyOn(Shadow.java:61)
    at org.robolectric.shadows.ShadowArscApkAssets9.lambda$loadFromPath$3(ShadowArscApkAssets9.java:225)
    at org.robolectric.shadows.ShadowArscApkAssets9.getFromCacheOrLoad(ShadowArscApkAssets9.java:152)
    at org.robolectric.shadows.ShadowArscApkAssets9.loadFromPath(ShadowArscApkAssets9.java:222)
    at android.content.res.ApkAssets.loadFromPath(ApkAssets.java)
    at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:127)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.robolectric.util.ReflectionHelpers.callStaticMethod(ReflectionHelpers.java:358)
    at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:56)
    at org.robolectric.shadow.api.Shadow.directlyOn(Shadow.java:61)
    at org.robolectric.shadows.ShadowArscApkAssets9.lambda$loadFromPath$0(ShadowArscApkAssets9.java:164)
    at org.robolectric.shadows.ShadowArscApkAssets9.getFromCacheOrLoad(ShadowArscApkAssets9.java:152)
    at org.robolectric.shadows.ShadowArscApkAssets9.loadFromPath(ShadowArscApkAssets9.java:162)
    at android.content.res.ApkAssets.loadFromPath(ApkAssets.java)
    at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1442)
    ... 24 more

```
### Steps to Reproduce
Run a Unit Test for Android Room using Dao.

### Robolectric & Android Version
Using Dynamic Features.
Robolectric: v4.6.1
AGP: v4.2.2
minSDK: 21
targetSDK: 30
compileSDK: 30

### Link to a public git repo demonstrating the problem:
Is private.

**Comment by hoisie** [comment] 2021-09-22 21:45
Seems to be a dupe of https://github.com/robolectric/robolectric/issues/5597

I don't believe dynamic features are supported because it involves split APKs

**Comment by utzcoz** [comment] 2021-09-23 02:26
As @hoisie said, it is duplicated of https://github.com/robolectric/robolectric/issues/5597. The `Robolectric` doesn't support dynamic features with split APKs correctly now, and we are investigating this problem at https://github.com/robolectric/robolectric/issues/5597. You can post your information to mentioned issue, and I will close this issue.

**Closed by utzcoz** 2021-09-23 02:26 UTC
