### ISSUE TITLE
Application from base module used in dynamic module issue

### ISSUE THREAD

**Issue by deividasstr** [robolectric/robolectric#5106] opened 2019-06-12 15:29 UTC
### Description
2 modules - app (base module) and dynamic_feature (com.android.dynamic-feature).
dynamic_feature build.gradle contains implementation project(':app'), app knows nothing about dynamic_feature.

When robolectric tests defined in dynamic_feature module use Application defined in base package and include @Config(application = CustomApp::class),
resources belonging to base module and used in the CustomApp are not found.
```
android.content.res.Resources$NotFoundException: Resource ID #0x7f0e002f

	at org.robolectric.shadows.ShadowLegacyAssetManager.getResName(ShadowLegacyAssetManager.java:1283)
	at org.robolectric.shadows.ShadowLegacyAssetManager.resolveResourceValue(ShadowLegacyAssetManager.java:1066)
	at org.robolectric.shadows.ShadowLegacyAssetManager.resolve(ShadowLegacyAssetManager.java:1026)
	at org.robolectric.shadows.ShadowLegacyAssetManager.getAndResolve(ShadowLegacyAssetManager.java:1020)
	at org.robolectric.shadows.ShadowLegacyAssetManager.getResourceText(ShadowLegacyAssetManager.java:285)
	at android.content.res.AssetManager.getResourceText(AssetManager.java)
	at android.content.res.Resources.getText(Resources.java:225)
	at android.content.res.Resources.getString(Resources.java:313)
	at android.content.Context.getString(Context.java:292)
	at com.example.dynamicrobolectrictest.DynamicApp.onCreate(DynamicApp.kt:9)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$installAndCreateApplication$0(AndroidTestEnvironment.java:276)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:276)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:169)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:301)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:243)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### Steps to Reproduce
Run test 
```
@RunWith(AndroidJUnit4::class)
@Config(application = DynamicApp::class)
class ActivityTest {

    @get:Rule
    val actRule = ActivityTestRule(DynamicActivity::class.java)

    @Before
    fun before() {

    }

    @Test
    fun test() {
    }
}
```
where DynamicApp uses resource from its own package, like ` getString(R.string.feature1)` onCreate.

### Robolectric & Android Version
Robolectric 4.3
Android - ?

### Link to a public git repo demonstrating the problem:
https://github.com/deividasstr/robolectric-dynamic-module/tree/error-resources-in-application
run ActivityTest in dynamic_feature module.

**Comment by utzcoz** [comment] 2022-05-28 13:38
Duplicate of https://github.com/robolectric/robolectric/issues/5597. Free free to reopen it if you think this issue is another problem.

**Closed by utzcoz** 2022-05-28 13:38 UTC
