### ISSUE TITLE
NoClassDefFoundError: javax/microedition/khronos/opengles/GL

### ISSUE THREAD

**Issue by tomrozb** [robolectric/robolectric#1932] opened 2015-07-09 09:02 UTC
This issue is related to Robolectric: https://github.com/robolectric/robolectric-gradle-plugin/issues/145

It occurs when you try to mock the `Canvas` class.

A simple solution is to add `GL` interface to `src/java/test`

```
package javax.microedition.khronos.opengles;

public interface GL {
}
```

It should probably be fixed in Robolectric.

**Comment by erd** [comment] 2015-10-12 23:12
Which API level are you testing against? It looks like we do include `GL` for API 21 & 22.

**Comment by tomrozb** [comment] 2015-10-13 20:26
API 18. I'll check with API 21 or 22 tomorrow.

**Comment by tomrozb** [comment] 2015-10-15 13:40
Still the same issue with API 21.

Cannot test with API 22:
```java.lang.UnsupportedOperationException: Robolectric does not support API level 22.```

**Comment by karlicoss** [comment] 2016-01-24 18:57
Simple way to reproduce:

```
Class<Canvas> canvas = Canvas.class;
canvas.getDeclaredMethods();
```

**Comment by karlicoss** [comment] 2016-01-24 19:30
As far as I understand, the issue is due to following: the whole package "javax" is excluded from instrumentation explicitly here https://github.com/robolectric/robolectric/blob/d6481790c7d4138798a91e2650b0b6f7e86dd52b/robolectric/src/main/java/org/robolectric/internal/bytecode/InstrumentationConfiguration.java#L149, which results in `InstrumentationClassLoader` loading the class via parent classloader here https://github.com/robolectric/robolectric/blob/d6481790c7d4138798a91e2650b0b6f7e86dd52b/robolectric/src/main/java/org/robolectric/internal/bytecode/InstrumentingClassLoader.java#L121 . On android unit tests, the `android-all` artifacts are resolved in runtime and unavailable to the parent classloader, which results in the exception above.
However, in Robolectric unit tests, the parent classloader somehow has `android-all` in its classpath, which is the reason that Robolectric tests didn't crash. I wonder if it is normal, shouldn't `android-all` have provided scope everywhere?

**Comment by rafaeltoledo** [comment] 2016-04-27 21:09
It's happening with Robolectric 3.1-rc1 and SDK 23 (21 and 22 it's working)

**Comment by Bob-Gao** [comment] 2016-04-29 12:54
I can bypass this issue by creating an interface as below

```
package javax.microedition.khronos.opengles;

public interface GL { }
```

**Comment by jaredsburrows** [comment] 2016-05-06 17:42
I am seeing this with API 23 but not 22.

**Comment by rafaeltoledo** [comment] 2016-05-06 18:09
It seems to be a problem on Robolectric's Android 6 jar

**Comment by haghar** [comment] 2016-05-12 14:51
The same happen to me I added

> @Config(constants = BuildConfig.class, sdk = 22)

And it works

**Comment by nickwph** [comment] 2016-05-17 17:42
Add this to `build.gradle`'s dependencies
```
testCompile 'org.khronos:opengl-api:gl1.1-android-2.1_r1'
```

**Comment by jaredsburrows** [comment] 2016-05-19 01:09
@nickwph Thank you!

**Comment by PhilippeBoisney** [comment] 2016-07-18 07:37
@nickwph Thanks !

**Comment by jaredsburrows** [comment] 2016-08-30 05:03
@xian @jongerrish Is this missing from the API23 jar?

**Comment by fitch0726** [comment] 2016-08-31 02:00
@nickwph Thanks !

**Comment by Honghe** [comment] 2016-08-31 11:27
robolectric:3.1.2 used with API 23, occurs the same error.

**Comment by NikhilBhutani** [comment] 2016-09-10 14:03
Thanks @nickwph , this testCompile 'org.khronos:opengl-api:gl1.1-android-2.1_r1' worked seamlessly.

**Comment by shahriaranwar** [comment] 2016-09-21 13:28
@nickwph you saved my day

**Comment by bkitduy** [comment] 2016-11-02 16:53
I take a day to search this error. It's happening with Robolectric 3.1.4, sdk 23. It's ok with sdk 21 or 22

**Comment by jaredsburrows** [comment] 2016-11-02 17:00
@bkitduy Yeah, just use the fix posted in this thread.

**Comment by Kisty** [comment] 2016-11-03 17:15
I'm having a similar issue with API 25 and support library `25.0.0` and Robolectric can't find `android.graphics.Canvas` #2692. Must be related.

**Comment by jaredsburrows** [comment] 2016-11-03 17:37
@kisty You just created a duplicate.

**Comment by Kisty** [comment] 2016-11-03 17:39
Yeah, I guess I have. Could find this yesterday though. Wasn't giving same error as this one. I'll close...

**Comment by jongerrish** [comment] 2016-11-30 23:19
Tracking this issue under:- https://github.com/robolectric/robolectric/issues/2566

**Comment by emndeniz** [comment] 2017-01-30 19:23
I am observing same issue with robolectric 3.2.2 with API 23 or higher. And 
`testCompile 'org.khronos:opengl-api:gl1.1-android-2.1_r1'` workaround didn't solve the problem.

**Comment by jongerrish** [comment] 2017-01-30 19:25
Sorry you're still having this issue. We are actually working on some wider
changes right now that should hopefully fix this and avoid similar issues.
Hang tight!

**Comment by emndeniz** [comment] 2017-01-30 19:26
Thank you for your quick response. From which issue I can track this problem fixed or not ?

**Comment by Kisty** [comment] 2017-01-31 09:49
@emndeniz I think @jongerrish said this issue was being tracked on #2566, but I may be wrong.

**Comment by xian** [comment] 2017-03-09 01:13
I'm unable to reproduce this, can anyone else?

**Comment by rafaeltoledo** [comment] 2017-03-09 01:29
@xian my [example repo](https://github.com/rafaeltoledo/unified-code-coverage-android) is a reproducible one. Just run `testDebug` on it.

**Comment by xian** [comment] 2017-03-09 02:35
@rafaeltoledo thank you! Looks like the issue is that gradle is using `mockable-android-25.jar`, which doesn't have `GL`.

**Comment by neworld** [comment] 2017-03-13 13:52
For me `sdk=23` fails no matter what I did, but `sdk=24` + `testCompile 'org.khronos:opengl-api:gl1.1-android-2.1_r1'` workaround works.

**Closed** 2017-03-21 20:02 UTC
Labels: defect

**Comment by calvarez-ov** [comment] 2019-04-15 08:54
Saw this when running unit tests with the latest mapbox sdk (7.3.1). I could only avoid this by adding the `testImplementation 'org.khronos:opengl-api:gl1.1-android-2.1_r1'` dependency. Tried with sdk configs 22 through 28.
