### ISSUE TITLE
Migrate Maven continuous build system to Gradle

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#2487] opened 2016-06-03 23:50 UTC
### Description

Gradle is the standard build system for Android projects now, Robolectric still uses Maven. We should switch to Gradle because it makes it easier for us to reproduce customers issues and write tests for libraries with resources.

Some tasks:-

1) Switch from Maven to Gradle.
2) Replace build-resources.rb / checked in R.java file with switching the module to an android module and having aapt process the resources.
3) Switch all tests to GradleRobolectricTestRunner (not necessary if 
https://github.com/robolectric/robolectric/issues/2441 is done first).
4) Switch pure Java tests e.g: tests that test Robolectric resource / util modules to using @RunWith(JUnit4.class) - these don't need a Robolectric environment and tests run faster as pure JUnit.
5) Investigate refactoring scripts/install-android.sh to use the SDK Manager command line interface instead of requiring contributors to perform the updates manually (see http://tools.android.com/recent/updatingsdkfromcommand-line)

The Maven build has many disadvantages, it is slow and non-parallel and non-incremental, relying on scripts/install-robolectric.sh to build everything, install the jars in the local mvn repo and then run tests on them. We should be able to kill this script hopefully.

**Comment by jaredsburrows** [comment] 2016-06-10 17:55
This is a duplicate of https://github.com/robolectric/robolectric/issues/1854

**Comment by jongerrish** [comment] 2016-06-14 17:09
Tangential but related:

Apparently Gradle doesn't merge manifests and resources for libraries in the transitive closure.

 https://code.google.com/p/android/issues/detail?id=211351

**Comment by jongerrish** [comment] 2016-06-14 18:33
Currently there are too many steps for getting started which makes the bar for contributions rather high:-

1) check out the repo
2) Install Android SDK, including android / google repositories, support lib + google play services (see comment in scripts/install-dependencies.sh)
3) export ANDROID_HOME=....
4) run scripts/install-dependencies.sh
5) run scripts/install-robolectric.sh
6) Download IntelliJ community edition and open the project, importing it as a Maven project (note: you can't use Android Studio since it doesn't support Maven).

We should make this compatible with Android Studio, hopefully we can have something that works out of the box through New -> Project from version control -> Github setting up the modules correctly and building the project and running tests.

The Travis build should also be switched to use Gradle

**Comment by jaredsburrows** [comment] 2016-06-14 19:19
Yes. The project truly needs gradle.

**Comment by jongerrish** [comment] 2016-06-15 16:37
There are also often issues related to appcompat which is a library dependency with resources. Currently our maven build doesn't handle appcompat since we'd have to do manual trickery with generating the R files. Once we've converted to gradle we should add at least one test that uses an AppCompatActivity to ensure compatibility at least.

**Comment by jongerrish** [comment] 2016-06-18 16:45
While the core-shadows modules compile against the android-all aosp jars (they need to as they dip into the internals). The tests should be compiled against the sdj jar (android.jar) as this simulates a real test environment, i.e: compiles against the SDK + shadows, android internals are not available to the tests.

**Comment by xian** [comment] 2016-06-29 18:53
In progress at https://github.com/robolectric/robolectric/tree/build-with-gradle-31; green locally, working on Travis build.

**Comment by jaredsburrows** [comment] 2016-07-16 21:51
Most of this seems to be done.
Can we delete the rest of the maven xml files?
Can we move the gradle build commands into the `.travis.yml` and delete the `.sh` and `.bat` files?

**Closed** 2016-07-18 22:08 UTC
