### ISSUE TITLE
AsyncTask NPE

### ISSUE THREAD

**Issue by benmarten** [robolectric/robolectric#2415] opened 2016-04-15 05:43 UTC
I am running my tests with RoboelectricTestRunner and although all tests pass, when executing them from within Android Studio I see some Nullpointer exceptions happening. When debugging the test and stepping through the test code none of these exceptions occur. Again all tests pass in any case, and these exceptions are not thrown on every test case, any ideas?

```
/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/bin/java -ea -Didea.launcher.port=7535 "-Didea.launcher.bin.path=/Applications/Android Studio.app/Contents/bin" -Didea.junit.sm_runner -Dfile.encoding=UTF-8 -classpath "/Applications/Android Studio.app/Contents/lib/idea_rt.jar:/Applications/Android Studio.app/Contents/plugins/junit/lib/junit-rt.jar:/Users/Ben/Library/Android/sdk/platforms/android-23/data/res:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDKTestApp/build/intermediates/classes/test/debug:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDKTestApp/build/intermediates/classes/debug:/Users/Ben/.gradle/caches/modules-2/files-2.1/com.segment.analytics.android/analytics/4.0.4/823832b8d030b3036b860fb61dfa7350d080e045/analytics-4.0.4.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.apache.maven/maven-ant-tasks/2.1.3/b09be554228d66d208e5fef5266844aacf443abc/maven-ant-tasks-2.1.3.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.apache.ant/ant/1.8.0/7b456ca6b93900f96e58cc8371f03d90a9c1c8d1/ant-1.8.0.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.javassist/javassist/3.20.0-GA/a9cbcdfb7e9f86fbc74d3afae65f2248bfbf82a0/javassist-3.20.0-GA.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcpkix-jdk15on/1.54/b11bfee99bb11eea344de6e4a07fe89212c55c02/bcpkix-jdk15on-1.54.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/com.google.android.apps.common.testing.accessibility.framework/accessibility-test-framework/1.0/28162aae36f8ba5903adadfb570313e1f1be852e/accessibility-test-framework-1.0.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-commons/5.0.1/7b7147a390a93a14d2edfdcf3f7b0e87a0939c3e/asm-commons-5.0.1.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.apache.ant/ant-launcher/1.8.0/8b53ba16fa62fb1034da8f1de200ddc407c8381/ant-launcher-1.8.0.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-module-junit4-common/1.6.4/b0b578da443794ceb8224bd5f5f852aaf40f1b81/powermock-module-junit4-common-1.6.4.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-classloading-base/1.6.4/4c411d648d0b7d1f5f52a3dc138bbb80afe37ad5/powermock-classloading-base-1.6.4.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/xpp3/xpp3_min/1.1.4c/19d4e90b43059058f6e056f794f0ea4030d60b86/xpp3_min-1.1.4c.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm/5.0.1/2fd56467a018aafe6ec6a73ccba520be4a7e1565/asm-5.0.1.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.54/1acdedeb89f1d950d67b73d481eb7736df65eedb/bcprov-jdk15on-1.54.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.robolectric/shadows-core/3.0/9dfa881bfd1796afa28204ef1a5ed7e3de992612/shadows-core-3.0.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-reflect/1.6.4/5532f4e7c42db4bca4778bc9f1afcd4b0ee0b893/powermock-reflect-1.6.4.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcmail-jdk15on/1.54/9d9b5432b4b29ef4a853223bc6e19379ef116cca/bcmail-jdk15on-1.54.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/com.segment.analytics.android/analytics-tests/4.0.4/774309efaf41a36a701a5b7960d6dd233167e55b/analytics-tests-4.0.4.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-util/5.0.1/7c8caddfbd0b2d7b844f8fcc75175b9cb9cf4724/asm-util-5.0.1.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk16/1.46/ce091790943599535cbb4de8ede84535b0c1260c/bcprov-jdk16-1.46.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-module-junit4-rule/1.6.4/39c1f9be7963b0aeff6273033b32c4d7308c4ded/powermock-module-junit4-rule-1.6.4.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-api-support/1.6.4/314daafb761541293595630e10a3699ebc07881d/powermock-api-support-1.6.4.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.mockito/mockito-core/1.10.19/e8546f5bef4e061d8dd73895b4e8f40e3fe6effe/mockito-core-1.10.19.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.objenesis/objenesis/2.1/87c0ea803b69252868d09308b4618f766f135a96/objenesis-2.1.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/xmlpull/xmlpull/1.1.3.1/2b8e230d2ab644e4ecaa94db7cdedbc40c805dfa/xmlpull-1.1.3.1.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/com.thoughtworks.xstream/xstream/1.4.2/97e5013f391487cce4de6b0eebcde21549e91872/xstream-1.4.2.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-core/1.6.4/85fb32e9ccba748d569fc36aef92e0b9e7f40b87/powermock-core-1.6.4.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.robolectric/shadows-play-services/3.0/ac6b658b016e29c41d962a991319f157cac36f92/shadows-play-services-3.0.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/com.ibm.icu/icu4j/53.1/786d9055d4ca8c1aab4a7d4ac8283f973fd7e41f/icu4j-53.1.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.robolectric/robolectric-resources/3.0/1ab609054aab67cd13a434567467f4b4774f2465/robolectric-resources-3.0.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.robolectric/robolectric-annotations/3.0/2a6cfc072d7680694c1ff893c5dc8fec33163110/robolectric-annotations-3.0.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-classloading-xstream/1.6.4/c21f792497531ecac6982d337750c31ad1bebc51/powermock-classloading-xstream-1.6.4.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/com.almworks.sqlite4java/sqlite4java/0.282/745a7e2f35fdbe6336922e0d492c979dbbfa74fb/sqlite4java-0.282.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-tree/5.0.1/1b1e6e9d869acd704056d0a4223071a511c619e6/asm-tree-5.0.1.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-api-mockito/1.6.4/fe12509b7e9e49d25131f4155145748a31e42e40/powermock-api-mockito-1.6.4.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-analysis/5.0.1/e286fbee48efacb4e7c175f7948d9d8b2ab52352/asm-analysis-5.0.1.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.robolectric/robolectric-utils/3.0/4bcecd8115fe7296088bb1636e6cbd7ae8927392/robolectric-utils-3.0.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.3/42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest-core-1.3.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/com.ximpleware/vtd-xml/2.11/ee5bcf62c1acf76434ee9f1c67a840bafef72a6d/vtd-xml-2.11.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/junit/junit/4.12/2973d150c0dc1fefe998f834810d68f278ea58ec/junit-4.12.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-module-junit4/1.6.4/8692eb1d9bb8eb1310ffe8a20c2da7ee6d1b5994/powermock-module-junit4-1.6.4.jar:/Users/Ben/.gradle/caches/modules-2/files-2.1/org.robolectric/robolectric/3.0/f888cea3bc1a24110e315eb9827ab593610ea62f/robolectric-3.0.jar:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDK/build/intermediates/classes/debug:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDK/libs/actionbarsherlock.jar:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDK/build/intermediates/exploded-aar/com.google.android.gms/play-services-location/8.3.0/jars/classes.jar:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDK/build/intermediates/exploded-aar/com.google.android.gms/play-services-location/8.3.0/res:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDK/build/intermediates/exploded-aar/com.google.android.gms/play-services-basement/8.3.0/res:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDK/build/intermediates/exploded-aar/com.google.android.gms/play-services-basement/8.3.0/jars/classes.jar:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDK/build/intermediates/exploded-aar/com.google.android.gms/play-services-maps/8.3.0/jars/classes.jar:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDK/build/intermediates/exploded-aar/com.google.android.gms/play-services-maps/8.3.0/res:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDK/libs/android-support-v4.jar:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDK/build/intermediates/exploded-aar/com.google.android.gms/play-services-base/8.3.0/res:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDK/build/intermediates/exploded-aar/com.google.android.gms/play-services-base/8.3.0/jars/classes.jar:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDK/build/intermediates/exploded-aar/com.google.android.gms/play-services-measurement/8.3.0/jars/classes.jar:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDK/build/intermediates/exploded-aar/com.google.android.gms/play-services-measurement/8.3.0/res:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDK/build/intermediates/exploded-aar/com.google.android.gms/play-services-gcm/8.3.0/jars/classes.jar:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDK/build/intermediates/exploded-aar/com.google.android.gms/play-services-gcm/8.3.0/res:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDK/libs/android-support-v7-appcompat.jar:/Users/Ben/Library/Android/sdk/platforms/android-23/optional/org.apache.http.legacy.jar:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDKTestApp/build/intermediates/sourceFolderJavaResources/test/debug:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDKTestApp/build/intermediates/sourceFolderJavaResources/debug:/Users/Ben/dev/leanplum/Leanplum/Android/AndroidSDK/build/intermediates/sourceFolderJavaResources/debug:/Users/Ben/dev/leanplum/Leanplum/Android/build/generated/mockable-android-23.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 com.leanplum.LeanplumTest,testStart
Exception in thread "pool-3-thread-2" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
    at org.robolectric.util.SimpleFuture.run(SimpleFuture.java:61)
    at org.robolectric.shadows.ShadowAsyncTask$3.run(ShadowAsyncTask.java:112)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
    at org.robolectric.shadows.ShadowAsyncTask$1.done(ShadowAsyncTask.java:57)
    at org.robolectric.util.SimpleFuture.run(SimpleFuture.java:58)
    ... 4 more
Caused by: java.lang.NullPointerException
    at org.robolectric.shadows.ShadowAsyncTask$1.done(ShadowAsyncTask.java:38)
    ... 5 more

Process finished with exit code 0
```

**Comment by jongerrish** [comment] 2016-04-15 14:22
I seem to remember there was a possible race condition in 3.0, can try
upgrading to 3.1 snapshot.

**Comment by benmarten** [comment] 2016-04-15 16:55
Hm, which version do you refer to by 3.1? The latest I can find on bintray and also in the tags is `3.0-rc3`
The exceptions still happen with that version... any other idea?

**Comment by jongerrish** [comment] 2016-04-15 16:59
The snapshots are on sonatype.

**Comment by benmarten** [comment] 2016-04-15 17:19
Ok, got it!

For future reference:
in project build.gradle:

    maven {
      url('https://oss.sonatype.org/content/repositories/snapshots/')
    }

in app build.gradle:

    testCompile('org.robolectric:robolectric:3.1-SNAPSHOT') {
        exclude group: 'commons-logging', module: 'commons-logging'
        exclude group: 'org.apache.httpcomponents', module: 'httpclient'
    }

No regarding the exceptions, they all seem to be thrown here:

ShadowAsyncTask.java:38
            ShadowApplication.getInstance().getForegroundThreadScheduler().post(new Runnable() {

My guess is that ShadowApplication.getInstance() is null, because the application is already torn down?

**Comment by benmarten** [comment] 2016-04-15 17:36
I would probably be able to send a PR for this, unfortunately I can't edit the sources of the jar file in my Android Studio setup.

I tried adding it as Gradle module like this:

    include '../../../robolectric/:Roboelectric'

Doesn't work either... It seems the project is not in a gradle friendly structure... What's the best way to include the library for development?

**Comment by benmarten** [comment] 2016-04-15 20:02
Current workaround is to add in @After method.

    Thread.sleep(100);

**Comment by hidroh** [comment] 2016-04-26 05:07
I'm having `NullPointerException` after trying to upgrade to 3.1-rc1. The exceptions only happen if I use Java 1.8 (which I do in local CLI), but do not happen with lower versions of Java (1.6 by Android Studio or 1.7 by Travis).

For my case the exception happens with `RecyclerView.setLayoutManager()`, during which some internal state of `RecyclerView` seems to be missing.

**Comment by FlyClover** [comment] 2016-08-11 02:44
I'm still getting this crash sometimes with 3.1 and JVM 1.7. It's not a blocking issue but makes test flaky...

**Comment by jongerrish** [comment] 2018-11-05 01:14
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

**Comment by calvarez-ov** [comment] 2019-01-13 09:58
I'm seeing this with robolectric 4.1:
```
10:44:15.968 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.lang.NullPointerException
10:44:15.968 [DEBUG] [TestEventLogger]     at org.robolectric.shadows.ShadowAsyncTask$1.done(ShadowAsyncTask.java:53)
10:44:15.968 [DEBUG] [TestEventLogger]     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384)
10:44:15.968 [DEBUG] [TestEventLogger]     at java.util.concurrent.FutureTask.set(FutureTask.java:233)
10:44:15.968 [DEBUG] [TestEventLogger]     at java.util.concurrent.FutureTask.run(FutureTask.java:274)
10:44:15.968 [DEBUG] [TestEventLogger]     at org.robolectric.shadows.ShadowAsyncTask$3.run(ShadowAsyncTask.java:110)
10:44:15.969 [DEBUG] [TestEventLogger]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:44:15.969 [DEBUG] [TestEventLogger]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:44:15.969 [DEBUG] [TestEventLogger]     at java.lang.Thread.run(Thread.java:748)
10:44:15.969 [DEBUG] [TestEventLogger]     Caused by: java.lang.NullPointerException
10:44:15.969 [DEBUG] [TestEventLogger]     at org.robolectric.shadows.ShadowAsyncTask$1.done(ShadowAsyncTask.java:34)
10:44:15.969 [DEBUG] [TestEventLogger]     ... 7 more
```

I don't have a scenario or sample project to reproduce this yet.

I was initially only seeing NullPointerException, with no stack trace, in our Jenkins CI log:
```
[Tests] Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "AsyncTask #210"
```

I only saw these exceptions when running the whole test suite. Just running one or two tests at a time, which seem to be run at the same time we have these exceptions when running the whole suite, didn't reproduce it.

To see this stack trace, I added this snippet to a part of our app code which is the main point for executing asynctasks, and ran the whole test suite:
```
          try {
                Thread.setDefaultUncaughtExceptionHandler((t, e) -> {
                    Logger.v(TAG,e, "oops what's this: %s", e.getMessage());  <--- this logs the stacktrce
                });
                return mBackgroundTask.execute();
            } catch (Throwable e) {
                Logger.v(TAG, e, "Error running asynctask");
              
```

**Comment by ankit13kumar** [comment] 2019-02-05 11:05
We're facing the same issue

**Comment by xian** [comment] 2019-02-08 02:54
Ah—those appear to be caused by the `Instrumentation` having gone AWOL, presumably on a background thread after the test proper has finished?

**Comment by zgulser** [comment] 2019-07-31 10:37
Any progress/update/workaround on this issue?

**Comment by eggman87** [comment] 2020-02-12 20:39
We are seeing this as well, it seems to specifically happen on Kotlin tests - still investigating.

**Comment by mayoorrnikam** [comment] 2020-02-12 20:56
Any update on this? Kotlin tests are failing, we are still investigating

**Comment by utzcoz** [comment] 2023-04-16 14:56
Please try the latest Robolectric version to test it again, and feel free to reopen this issue if it still exists.

**Closed by utzcoz** 2023-04-16 14:56 UTC
