### ISSUE TITLE
FileNotFoundException when opening AssetFileDescriptor 

### ISSUE THREAD

**Issue by ashutoshgngwr** [robolectric/robolectric#5442] opened 2020-02-02 09:01 UTC
### Description

One of the functions in my unit tests wants to open an `AssetFileDescriptor`. I tried to use [`RuntimeEnvironment.systemContext`](http://robolectric.org/javadoc/4.0/org/robolectric/RuntimeEnvironment.html#systemContext) and [`ApplicationProvider.getApplicationContext()`](https://developer.android.com/reference/androidx/test/core/app/ApplicationProvider.html#getApplicationContext()) interchangeably.

1. Using `RuntimeEnvironment.systemContext` gives me
   ```
   java.io.FileNotFoundException: birds_or_cats_or_whatever
       at org.robolectric.shadows.ShadowArscAssetManager9.nativeOpenAssetFd(ShadowArscAssetManager9.java:722)
       at android.content.res.AssetManager.nativeOpenAssetFd(AssetManager.java)
       at android.content.res.AssetManager.openFd(AssetManager.java:768)
   ```
2. Using `ApplicationProvider.getApplicationContext()` gives me
   ```
   java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
       at org.robolectric.shadows.ShadowArscAssetManager9.ReturnParcelFileDescriptor(ShadowArscAssetManager9.java:423)
       at org.robolectric.shadows.ShadowArscAssetManager9.nativeOpenAssetFd(ShadowArscAssetManager9.java:724)
       at android.content.res.AssetManager.nativeOpenAssetFd(AssetManager.java)
       at android.content.res.AssetManager.openFd(AssetManager.java:768)
   ```

The latter error was more descriptive. Following the message from the stack-trace, I tried to disable the `aapt` resource compression for all resources using the following Gradle config but with no luck. Regardless of the compression settings, I am able to open an `AssetInputStream` to a resource with `ApplicationProvider.getApplicationContext()` context but unable to open a file descriptor to the same resource.

```groovy
android {
  aaptOptions {
    noCompress ''
  }
}
```

### Steps to Reproduce

_Already covered_

### Robolectric & Android Version

- Android SDK 29
- Robolectric 4.3.1
- Tests are targeted for SDK 21 and 28

### Link to a public git repo demonstrating the problem:

You can play around with this test. It highlights the problem. https://github.com/ashutoshgngwr/noice/blob/refactor/sound-manager/app/src/test/java/com/github/ashutoshgngwr/noice/sound/PlaybackTest.kt

Links to https://github.com/robolectric/robolectric/issues/4091

**Comment by ashutoshgngwr** [comment] 2020-09-05 07:53
Hi @hoisie 

Sorry, after receiving no reply here, I migrated those tests to Espresso and the branch got deleted. I don't know if this is fixed in 4.4 but I was able to restore the branch and find the abandoned commit (I force pushed a different HEAD).

This is the test you're looking for: https://github.com/ashutoshgngwr/noice/blob/91bf2f9fbc903c2ddb857a4237f5a4dc5d658940/app/src/test/java/com/github/ashutoshgngwr/noice/sound/PlaybackTest.kt

This is the code under test: https://github.com/ashutoshgngwr/noice/blob/91bf2f9fbc903c2ddb857a4237f5a4dc5d658940/app/src/main/java/com/github/ashutoshgngwr/noice/sound/Playback.kt#L44-L67

**Comment by hoisie** [comment] 2020-09-05 16:53
Thanks, I can repro the issue.

**Comment by xunkai55** [comment] 2021-04-25 12:07
Friendly ping :-) would like to know if there's any progress.

**Comment by hoisie** [comment] 2021-04-25 23:17
Is anyone up for investigating this and sending a PR? I have a bunch of other projects/initiatives at the moment so likely won't have time to look into this.

In principle it could be a straightforward fix that just involves decompressing some asset blobs.

**Comment by utzcoz** [comment] 2021-04-26 01:49
Hi @hoisie , you can assign it to me if it could, and I will investigate on it this week when I have time.

**Comment by hoisie** [comment] 2021-04-26 15:43
@utzcoz sounds great, that would be very helpful if you could take a look. I'll try to get a simpler repro. At a high level the problem seems to be mp3 files in the 'assets' directory. Looks like aapt2 compresses them in a way that's not currently compatible with Robolectric's binary resources. From what I understand Roboelctric has an assumption that the entries in the arsc file it reads are uncompressed. So this may either be a bug in Android Gradle Plugin (AGP) in that AGP is compressing things it shouldn't be, or it's an issue in Robolectric's binary resource parser.

**Comment by hoisie** [comment] 2021-04-26 16:18
Just realized this is a dupe of https://github.com/robolectric/robolectric/issues/4091

There is already an `@Ignore` test in Robolectric that captures the issue:
https://github.com/robolectric/robolectric/blob/master/integration_tests/ctesque/src/test/java/android/content/res/AssetManagerTest.java#L69-L75

You can run the test by removing `@Ignore` and running  `./gradlew :integration_tests:ctesque:cleanTest :integration_tests:ctesque:test`

```
--- a/integration_tests/ctesque/src/test/java/android/content/res/AssetManagerTest.java
+++ b/integration_tests/ctesque/src/test/java/android/content/res/AssetManagerTest.java
@@ -66,7 +66,7 @@ public class AssetManagerTest {
     assertThat(contents).isEqualTo("assetsHome!");
   }

-  @Test @Ignore("TODO(xian): re-enable; see https://github.com/robolectric/robolectric/issues/4091")
+  @Test
   public void openFd_shouldProvideFileDescriptorForAsset() throws Exception {
     AssetFileDescriptor assetFileDescriptor = assetManager.openFd("assetsHome.txt");
     assertThat(CharStreams.toString(new InputStreamReader(assetFileDescriptor.createInputStream(), UTF_8)))
```

Seems like this is partly an issue in AGP, I'll file a bug against that. Although it would be nice if Robolectric supported compressed assets, it seems unnecessary for AGP to compress assets during unit tests. Lots of wasted CPU time.

**Comment by hoisie** [comment] 2021-04-26 16:29
Filed https://b.corp.google.com/issues/186418206 against AGP

**Comment by utzcoz** [comment] 2021-04-27 03:01
@hoisie Thanks, I will follow your suggestion to support compressed format firstly.

**Comment by hoisie** [comment] 2021-04-27 15:47
Just some additional findings:

1) I was under the impression that assets are stored in the arsc file but this does not seem to be the case. I think they are just put in the 'assets' directory in the apk file. This makes the problem feel a little more tractable as we don't have to hack around the arsc file.

2) This may very well be a Robolectric issue and not an AGP issue. If you remove the `@Ignore` like described here and run ctesque tests and rebuild:
https://github.com/robolectric/robolectric/issues/5442#issuecomment-826971554

And then you look at the asset in the APK:
``` 
$ unzip -p ./integration_tests/ctesque/build/intermediates/apk_for_local_test/debugUnitTest/packageDebugUnitTestForUnitTest/apk-for-local-test.ap_ assets/assetsHome.txt`
assetsHome!%
```

It does not seem to be compressed.

I do not know how CppAssetManager2 works but it's possible that some of the zip file logic to read assets may have a bug.

**Comment by utzcoz** [comment] 2021-04-30 15:34
Okay, I copy the `assetsHome.txt` to a demo app, and it was compressed in generated apk file, and the following code throws the same error with the title mentioned on the official emulator:

```java
AssetManager assetManager = getResources().getAssets();
try {
      AssetFileDescriptor descriptor = assetManager.openFd("assetHome.txt");
} catch (IOException e) {
      Toast.makeText(this, "Failed to openFd " + e, Toast.LENGTH_LONG).show();
}
```

And from the AOSP source code, [`Asset.cpp`](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/libs/androidfw/Asset.cpp?q=Asset.cpp) [only implements `OpenFileDescriptor` for `_FileAsset`](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/libs/androidfw/Asset.cpp;l=662?q=Asset.cpp). So it is AGP's bug, I think, because the AOSP's source code tells me that it doesn't support compressed file in `/assets`.Hi  @hoisie , could you double check my test code to confirm it? Thanks. I will download AGP's source code to check the real reason.

**Comment by hoisie** [comment] 2021-04-30 15:41
I guess I don't understand the zip file format too well, or what
assetmanagers expectations are. Does packagemanager reprocess assets when
an APK is installed? Maybe as a workaround Robolectric (or a gradle task)
could unzip and rezip the APK with supported options?

**Comment by utzcoz** [comment] 2021-04-30 15:51
The `Defl:N` represents the [`ZipEntry`'s `DEFLATED`](https://docs.oracle.com/javase/8/docs/api/java/util/zip/ZipEntry.html#DEFLATED), and the `Robolectric` and AOSP create the compressed asset for it, that doesn't support `openFileDescriptor`. The `Stored` represents [`ZipEntry`'s `STORED`](https://docs.oracle.com/javase/8/docs/api/java/util/zip/ZipEntry.html#STORED), and the `Robolectric` and AOSP create the file asset for it, that supports `openFileDescriptor`. Although the `Robolectic` uses the [pure number](https://github.com/robolectric/robolectric/blob/7697d1217c5eb0dee454004efe60ba219f398255/resources/src/main/java/org/robolectric/res/android/ZipFileRO.java#L17-L18) for different entry compressed methods, but they are the same as `ZipEntry`'s values. And the AOSP's logic to create different asset instance based on zip entry type is here: https://cs.android.com/android/platform/superproject/+/master:frameworks/base/libs/androidfw/ApkAssets.cpp;l=164-201?q=ApkAsset, and the `Robolectric`'s logic is here: https://github.com/robolectric/robolectric/blob/7697d1217c5eb0dee454004efe60ba219f398255/resources/src/main/java/org/robolectric/res/android/CppApkAssets.java#L295-L327.

**Comment by hoisie** [comment] 2021-04-30 16:02
In real Android you don't see this error in practice? I am assuming when an
APK is copied to the device the assets are deflated?

**Comment by hoisie** [comment] 2021-04-30 16:38
Thanks @utzcoz  for the detailed investigations.

It seems like from Robolectric's perspective this is WAI.

We could probably work around the error, but that would be less realistic, and could hide problems that may occur in real Android, and give developers a false sense of security.

Also, re-reading the docs from OpenFD, it is clear that 
https://developer.android.com/reference/android/content/res/AssetManager#openFd(java.lang.String)

```
Open an uncompressed asset by mmapping it and returning an AssetFileDescriptor. This provides access to files that have been bundled with an application as assets -- that is, files placed in to the "assets" directory. The asset must be uncompressed, or an exception will be thrown.
```

So the recommendation to folks running into this issue is to use `AssetManager.open` and/or copy the data to somewhere else if needed?

**Comment by hoisie** [comment] 2021-04-30 16:43
Also, we should definitely file a bug against AAPT2 and/or AGP because these options:

```
  aaptOptions {
    noCompress ''
  }
```

seem ineffective. 

Having a real Android app that demonstrates the issue would be much more compelling to Android framework folks than a Robolectric test that demonstrates the issue.

**Comment by utzcoz** [comment] 2021-04-30 16:48
> So the recommendation to folks running into this issue is to use AssetManager.open and/or copy the data to somewhere else if needed?

That's great. We can add the notice to wiki for folks. I know you have fired a bug for AGP's `aaptOptions`, maybe I should test it with AOSP, and check the behavior of `soong` to provide more information about `aaptOptions`' `noCompress` or similar config. I am also downloading the AGP source code to try to learn and dig into this problem. If I have any update, I will notify it here.

**Comment by xunkai55** [comment] 2021-04-30 16:53
> Also, we should definitely file a bug against AAPT2 and/or AGP because these options seem ineffective.
> 
> ```
>   aaptOptions {
>     noCompress ''
>   }
> ```
> 
> Having a real Android app that demonstrates the issue would be much more compelling to Android framework folks than a Robolectric test that demonstrates the issue.

Actually `noCompress` should be working well at least with `.tflite` files in real apps, because for TFLite we recommend to use mmap and heavily rely on it. Haven't heard users complaining.

[1] AAPT options: https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/android/lib_support/build.gradle#L25
[2] The library code for opening models in the app mentioned: https://github.com/tensorflow/tflite-support/blob/master/tensorflow_lite_support/java/src/java/org/tensorflow/lite/support/common/FileUtil.java#L155

**Comment by utzcoz** [comment] 2021-04-30 17:01
I follow @xunkai55 's example, it works for `txt` as well. @hoisie Maybe what we need is to add notice for users, and find whether there is a method to `noCompress` for all files.

**Comment by hoisie** [comment] 2021-04-30 17:03
Thanks @xunkai55 that is very helpful. So it seems like the issue is passing an empty string to noCompress (`''`)

**Comment by xunkai55** [comment] 2021-04-30 17:07
@hoisie @utzcoz Well my problem (may be a bit off-topic of this one) is that we cannot open the FD of the assets in Robolectric + Bazel settings. Real world + Bazel / Real world + Gradle both work fine, but haven't tried Robolectric + Gradle.

**Comment by hoisie** [comment] 2021-04-30 17:07
This seems to be the relevant issue:

https://issuetracker.google.com/issues/70118728

**Comment by utzcoz** [comment] 2021-04-30 17:14
From https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-master-dev:build-system/gradle-core/src/main/java/com/android/build/gradle/tasks/PackageAndroidArtifact.java;l=831?q=getNoCompressPredicate&ss=android-studio
and https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-master-dev:build-system/builder/src/main/java/com/android/builder/packaging/PackagingUtils.java;l=270?q=getNoCompressPredicate&ss=android-studio, it looks like the AGP needs user adds no compressed extension explicitly.  And it [adds `tflite` default](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-master-dev:build-system/builder/src/main/java/com/android/builder/packaging/PackagingUtils.java;l=277?q=getNoCompressPredicate&ss=android-studio).

**Comment by utzcoz** [comment] 2021-04-30 17:30
@hoisie I test `noCompress ''` with `com.android.tools.build:gradle:4.1.1`, and it works fine. It https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-master-dev:build-system/builder/src/main/java/com/android/builder/internal/aapt/v2/AaptV2CommandBuilder.kt;l=227?q=getNoCompressForAapt&ss=android-studio shows it will use `--no-compress` if there is empty string for `noCompress`. Could you double check it?

**Comment by hoisie** [comment] 2021-04-30 18:13
@utzcoz i may be better if you post AGP findings on https://issuetracker.google.com/issues/70118728

**Comment by utzcoz** [comment] 2021-05-01 08:54
> @utzcoz it may be better if you post AGP findings on https://issuetracker.google.com/issues/70118728

Okay, I have sent new updates to this issue page.

**Comment by utzcoz** [comment] 2021-05-15 09:04
I created a [temp dirty patch](https://android-review.googlesource.com/c/platform/tools/base/+/1708138) for AGP to package asset without compress for unit test, and the local testing result is that the test can find `assetHome.txt`, but its read content is not correct,  it's garbled. Maybe there is a problem related to `AssetFileDescriptor`.

**Comment by utzcoz** [comment] 2021-05-15 13:18
> I created a [temp dirty patch](https://android-review.googlesource.com/c/platform/tools/base/+/1708138) for AGP to package asset without compress for unit test, and the local testing result is that the test can find `assetHome.txt`, but its read content is not correct, it's garbled. Maybe there is a problem related to `AssetFileDescriptor`.

Looks like the [offset](https://github.com/robolectric/robolectric/blob/7697d1217c5eb0dee454004efe60ba219f398255/resources/src/main/java/org/robolectric/res/android/Asset.java#L990) is incorrect.

**Comment by utzcoz** [comment] 2021-05-15 16:20
Okay, the offset is incorrect, and it is caused by [FileMap#guessDataOffsets](https://github.com/robolectric/robolectric/blob/7697d1217c5eb0dee454004efe60ba219f398255/resources/src/main/java/org/robolectric/res/android/FileMap.java#L262). There are two extra field lengths in zip - one in central directory, and on in local file header. Current code uses extra field length in central directory, and it is not correct sometime, and the correct approach is to use one in local file header to calculate offset. I have pushed a [new commit](https://github.com/utzcoz/robolectric/commit/32708ead0abd6c8f0148221292217d17ec26c6b4) to fix it on wip branch. And it makes `AssetManagerTest#openFd_shouldProvideFileDescriptorForAsset ` pass based on above mentioned temp dirty modified AGP, and doesn't break any existing tests. If the AGP is ready, I will update this wip branch and send PR for this problem. So the next thing is to push the AGP to fix compressed problem for unit test. 

cc @hoisie .

**Comment by xunkai55** [comment] 2021-07-26 08:41
@utzcoz @hoisie May I know the current status? Is there any PR issued / merged?

Thanks!

**Comment by utzcoz** [comment] 2021-07-26 09:03
> @utzcoz @hoisie May I know the current status? Is there any PR issued / merged?
> 
> Thanks!

If AGP team fixes `noCompress` support for unit test, I will push Robolectric related changes to add support for it. But AGP team doesn't have response for it on issue-tracker now. I have tried to modify AGP to un-compress any asset file for unit test, but I think it doesn't meet AGP's code quality requirement. So I am struggling to add `noCompress` support for unit test at https://android-review.googlesource.com/c/platform/tools/base/+/1708138, but it is not ideal. Recently, I am finding more time time to investigate on it, because I am overtime working recent months. Hi @xunkai55 , could you or @hoisie help to push AGP team to check this problem? I'm not a googler, and what I can do is to post my debug result to issue-tracker and try to fix it myself, that is slow.

**Comment by xunkai55** [comment] 2021-07-28 04:38
Maybe @hoisie could help. I'm a stranger to Android's codebase.

Please forgive that I'm not really familiar with the whole Android toolchain, but I want to mention that I noticed bug when using Bazel + Robolectric. Do you know if AGP is playing any part in Bazel + Robolectric things? Thanks!

**Comment by utzcoz** [comment] 2021-07-28 07:37
> Please forgive me that I'm not really familiar with the whole Android toolchain, but I want to mention that I noticed bug when using Bazel + Robolectric. Do you know if AGP is playing any part in Bazel + Robolectric things? Thanks!

Hi @xunkai55 , sorry, I'm not familiar Bazel toolchain for Android. The Robolectric also has problem related to uncompressed asset file opening with fd. If Bazel supports `noCompress` related config correctly, I can send a new PR of [Robolectric's part fixing for this problem](https://github.com/utzcoz/robolectric/commit/32708ead0abd6c8f0148221292217d17ec26c6b4).  It maybe need @hoisie  to answer Bazel related problems.

**Comment by utzcoz** [comment] 2021-07-30 15:40
Before AGP team fixes `noCompress` support for unit test build, maybe we can add a new config for Robolectric to configure `noCompress` files, and Robolectric unzip and zip test apk to ensure `noCompress` files are not compressed to test apk before using apk to running any tests.  Hi @hoisie , what do you think this method?

**Comment by hoisie** [comment] 2021-07-30 16:45
I just pinged someone on the AGP team about this. I'd rather not work around AGP bugs in Robolectric unless it's absolutely necessary.

**Comment by hoisie** [comment] 2021-07-31 05:50
Looks like the AGP team fixed it! https://buganizer.corp.google.com/issues/186418206

**Comment by utzcoz** [comment] 2021-07-31 06:20
> Looks like the AGP team fixed it! https://issuetracker.google.com/issues/186418206

It will be released in 7.1.0-alpha08, but AGP 7.x needs Java 11 (https://android-developers.googleblog.com/2020/12/announcing-android-gradle-plugin.html). Could Robolectric bump to AGP 7.x with Java 11 requirement? Or could AGP team release it with 4.x version? I know their will be a 4.2.2 release (https://android-review.googlesource.com/c/platform/tools/base/+/1743394/comments/929d726c_1aaf917e).

**Comment by hoisie** [comment] 2021-07-31 16:37
I am OK with requiring users to update to AGP 7.x in order to get this fix. Using the latest AGP will fix the Jetifier ASM issue as well (https://github.com/robolectric/robolectric/issues/6521). I have not heard of anyone having issues switching from Java 8 to Java 11 for Robolectric. I personally have been using Java 11 for years with Robolectric already and it has been working great. Also, I am not sure what the bar is for backporting fixes to 4.2.2, but I imagine it would be high, and I am not sure if this issue would meet the cutoff.

**Comment by xunkai55** [comment] 2021-08-01 03:23
> I am OK with requiring users to update to AGP 7.x in order to get this fix. Using the latest AGP will fix the Jetifier ASM issue as well (#6521). I have not heard of anyone having issues switching from Java 8 to Java 11 for Robolectric. I personally have been using Java 11 for years with Robolectric already and it has been working great. Also, I am not sure what the bar is for backporting fixes to 4.2.2, but I imagine it would be high, and I am not sure if this issue would meet the cutoff.

@hoisie I wonder if there could be any problem when we update Robolectrics to Java 11 while tested libraries are compiled with `-source 7 -target 7` flags?

**Comment by hoisie** [comment] 2021-08-01 03:28
> -source 7 -target 7

Link? I was under the impression that Robolectric requires at least Java 8. I recall support for Java 1.7 was dropped years ago. Android Q and above requires Java 9, anyway, so unless you are targeting an old SDK version you will need Java > 8.

**Comment by xunkai55** [comment] 2021-08-01 04:23
We are compiling libraries that is designed to be compatible for major Android devices (min API >= 16).

Our project was part of TensorFlow, whose javacopts are declared here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/build_defs.bzl#L4

Or should those flags only be used for `java_library` rather than `android_library`?

**Comment by hoisie** [comment] 2021-08-01 04:45
Ahh I see what you are saying. I think you can continue using `-source 7 -target 7` for tensorflow library and tensorflow test code. You will just need JDK 11 when running tests in an Gradle/AGP environment.

**Comment by xunkai55** [comment] 2021-08-01 04:49
Thanks for your info, @hoisie - running tests with JDK 11 is totally ok for us.

**Closed** 2021-09-22 19:33 UTC

**Comment by utzcoz** [comment] 2021-09-23 02:33
Hi @xunkai55 , related PR is merged, could you help to test it with bazel building system? Thanks.
