### ISSUE TITLE
java.lang.UnsupportedOperationException: Failed to create a Robolectric sandbox: Android SDK 31 requires Java 9 (have Java 8)

### ISSUE THREAD

**Issue by ck1703** [robolectric/robolectric#6991] opened 2022-01-20 08:33 UTC
I am trying to use robolectric with Android 12 SDK. 
My gradle file has 

minSdkVersion 31
compileSdkVersion 31
targetSdkVersion 31

compileOptions {
      sourceCompatibility JavaVersion.VERSION_1_9
      targetCompatibility JavaVersion.VERSION_1_9
  }

 testImplementation "org.robolectric:robolectric:4.7.3"

And in command line i have set 
export JAVA_HOME=/home/test/Downloads/jdk-9.0.4

and running test from same command line. Still seeing error as

java.lang.UnsupportedOperationException: Failed to create a Robolectric sandbox: Android SDK 31 requires Java 9 (have Java 8)

2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]     java.lang.UnsupportedOperationException: Failed to create a Robolectric sandbox: Android SDK 31 requires Java 9 (have Java 8)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.robolectric.plugins.DefaultSdkProvider$DefaultSdk.verifySupportedSdk(DefaultSdkProvider.java:168)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:284)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:68)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:236)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:93)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-01-20T13:56:52.458+0530 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-01-20T13:56:52.459+0530 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-01-20T13:56:52.459+0530 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
2022-01-20T13:56:52.459+0530 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2022-01-20T13:56:52.459+0530 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2022-01-20T13:56:52.459+0530 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
2022-01-20T13:56:52.459+0530 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
2022-01-20T13:56:52.459+0530 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
2022-01-20T13:56:52.459+0530 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
2022-01-20T13:56:52.459+0530 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
2022-01-20T13:56:52.459+0530 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2022-01-20T13:56:52.459+0530 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2022-01-20T13:56:52.459+0530 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
2022-01-20T13:56:52.459+0530 [DEBUG] [TestEventLogger]         at java.lang.Thread.run(Thread.java:748)
2022-01-20T13:56:52.459+0530 [DEBUG] [TestEventLogger] 
2

Please help me to resolve this issue

**Comment by hoisie** [comment] 2022-01-20 08:39
Make sure `java --version` gives you >= 9. for some reason it is still picking up java 8. Closing this, it is. It a Robolectric issue.

**Closed by hoisie** 2022-01-20 08:39 UTC

**Comment by ck1703** [comment] 2022-01-20 12:11
$ java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
 
Still seeing the same issue

**Comment by utzcoz** [comment] 2022-01-20 12:21
> $ java -version java version "9.0.4" Java(TM) SE Runtime Environment (build 9.0.4+11) Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
> 
> Still seeing the same issue

Looks like gradle also use Java 8. Maybe you should ensure your `javac --version` also show it is Java 9.  If you are using Ubuntu/Debian, you can try https://computingforgeeks.com/how-to-set-default-java-version-on-ubuntu-debian/. I used this approach locally to manage OpenJDK version for different usage.

**Comment by ck1703** [comment] 2022-01-20 12:37
javac -version
javac 9.0.4
 javac version also 9.0.4. https://computingforgeeks.com/how-to-set-default-java-version-on-ubuntu-debian/ These steps already tried

**Comment by utzcoz** [comment] 2022-01-20 12:54
@ck1703 Checking whether you have defined `org.gradle.java.home` at your `gradle.properties`. There is an problem related to this occasion: https://stackoverflow.com/questions/18487406/how-do-i-tell-gradle-to-use-specific-jdk-version.

**Comment by ck1703** [comment] 2022-01-21 05:35
issue resolve . Thank you for the support

**Comment by hoisie** [comment] 2022-01-21 06:39
Also, I would recommend Java 11, 9 is fairly obsolete by now. Maybe the error should be update to say `> 9`.

**Comment by hoisie** [comment] 2022-01-21 06:44
@ck1703 out of curiosity what was the issue (in case others end up here using Google)

Another way to track down the issue is use `strace` to see which java is being executed, e.g. `strace <gradlew command> 2>&1 | grep java`

**Comment by ck1703** [comment] 2022-01-21 06:48
gradle was using java8 instead of java9. fixed it by setting toolchain
java {
    toolchain {
}
}
