### ISSUE TITLE
Application Class initialization problem with ThirdParty SDK

### ISSUE THREAD

**Issue by sideffect0** [robolectric/robolectric#1981] opened 2015-08-08 10:05 UTC
java.lang.IllegalStateException: `Parse#enableLocalDatastore(Context)` must be invoked before `Parse#initialize(Context)`

**Comment by erd** [comment] 2015-08-12 03:52
Can you give some more context on what's not working? This is going to be hard to debug without some additional information.

**Comment by sideffect0** [comment] 2015-08-12 09:30
Parse sdk warns about missing java cryptic libraries ( on http calls)
at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:140)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:433)

**Comment by StuStirling** [comment] 2015-08-19 14:16
Same issue here.

    java.lang.RuntimeException: java.lang.IllegalStateException: `Parse#enableLocalDatastore(Context)` must be invoked before `Parse#initialize(Context)`
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:244)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
    Caused by: java.lang.IllegalStateException: `Parse#enableLocalDatastore(Context)` must be invoked before `Parse#initialize(Context)`
	at com.parse.Parse.enableLocalDatastore(Parse.java:65)
	at com.mycompany.myapplication.MyApplication.onCreate(MyApplication.java:40)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:140)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:433)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:240)
	... 18 more

**Comment by AnthonyUccello** [comment] 2016-05-12 23:57
I have this same issue. Did you guys find a workaround?

**Comment by jongerrish** [comment] 2016-05-13 17:02
So even though you are calling  Parse.enableLocalDatastore() before Parse.initialize() you are getting that IllegalStateException?

I don't know what parse is but I think someone needs to run through that code with a debugger, just a cursory look at the source code suggests to me that it is not completing the initialization call correctly:-

https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/Parse.java#L380

**Comment by jongerrish** [comment] 2018-11-05 01:06
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

**Closed by jongerrish** 2018-11-05 01:06 UTC
