### ISSUE TITLE
ShadowHandler does not queue events properly

### ISSUE THREAD

**Issue by awrichar** [robolectric/robolectric#1198] opened 2014-07-14 18:20 UTC
Android's Handler class is by definition a queue, meaning that it will always finish processing one event before processing another. Robolectric's ShadowHandler is not, meaning that it's possible to have one event execute in the middle of another one. A simple example to reproduce:

```
private Handler mHandler = new Handler();
private boolean mTask1HasRun;

private Runnable mTask1 = new Runnable() {
    public void run() {
        mHandler.post(mTask2);
        mTask1HasRun = true;
    }
}

private Runnable mTask2 = new Runnable() {
    public void run() {
        if (mTask1HasRun) {
            ...
        }
    }
}
```

When you invoke `mHandler.post(mTask1)` in Android, the if() in mTask2 will always evaluate to true, because the second task is queued to execute after the first one finishes. When you invoke the same code from Robolectric, the if() will always evaluate to false, because the second task is executed inline immediately.

**Comment by kriegfrj** [comment] 2015-04-22 06:18
I think this is a duplicate of #1306?

**Comment by kriegfrj** [comment] 2015-04-24 05:30
On reflection, more of a duplicate of #919 perhaps.

**Comment by jongerrish** [comment] 2018-11-05 00:33
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

**Closed by jongerrish** 2018-11-05 00:33 UTC
