### ISSUE TITLE
android.support.v7.app.AlertDialog crash when try to open

### ISSUE THREAD

**Issue by marcouberti** [robolectric/robolectric#1736] opened 2015-04-28 10:18 UTC
Using the new support library with the material alert dialog, when the dialog try to open the test crash with this exception:

Robolectric version: 3.0-SNAPSHOT
Android Studio 1.2 RC3
emulateSDK = 21

Code:

```
android.support.v7.app.AlertDialog.show();
```

Stacktrace:

```
java.lang.IllegalStateException: Could not execute method of the activity
...
Caused by: java.lang.reflect.InvocationTargetException
..
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -9
    at java.lang.String.substring(String.java:1954)
    at org.robolectric.res.ResName.qualifyResName(ResName.java:51)
    at org.robolectric.res.Attribute.getStyleReference(Attribute.java:147)
    at org.robolectric.res.builder.XmlFileBuilder$XmlResourceParserImpl.getResourceId(XmlFileBuilder.java:786)
    at org.robolectric.res.builder.XmlFileBuilder$XmlResourceParserImpl.getStyleAttribute(XmlFileBuilder.java:769)
    at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:152)
    at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:51)
    at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:489)
    at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
    at android.content.Context.obtainStyledAttributes(Context.java:460)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
    at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:75)
    at android.support.v7.app.AlertController.installContent(AlertController.java:216)
    at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:240)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:373)
    at android.app.Dialog.show(Dialog.java:274)
    at org.robolectric.shadows.ShadowDialog.show(ShadowDialog.java:65)
    at android.app.Dialog.show(Dialog.java)
```

Dependency:

```
compile 'com.android.support:appcompat-v7:22.1.0'
```

**Comment by ubelab** [comment] 2015-04-28 16:10
Verified also with:

```
compile 'com.android.support:appcompat-v7:22.1.1'
```

**Comment by hidroh** [comment] 2015-05-07 10:34
I have the same issue, after switching my implementation from `android.apps.AlertDialog` to `android.support.v7.app.AlertDialog`. I use Robolectric 3.0-rc2, appcompat 22.1.0, sdk 21.

The stacktrace is a bit different in my case:

```
android.view.InflateException: XML file /.../build/intermediates/res/debug/layout/abc_alert_dialog_material.xml line #-1 (sorry, not yet implemented): Error inflating class android.support.v7.internal.widget.DialogTitle
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
	at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:75)
	at android.support.v7.app.AlertController.installContent(AlertController.java:216)
	at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:240)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:355)
	at android.app.Dialog.show(Dialog.java:260)
	at org.robolectric.shadows.ShadowDialog.show(ShadowDialog.java:65)
	at android.app.Dialog.show(Dialog.java)
    ...
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -9
	at java.lang.String.substring(String.java:1911)
	at org.robolectric.res.ResName.qualifyResName(ResName.java:51)
	at org.robolectric.res.Attribute.getStyleReference(Attribute.java:147)
	at org.robolectric.res.builder.XmlFileBuilder$XmlResourceParserImpl.getResourceId(XmlFileBuilder.java:789)
	at org.robolectric.res.builder.XmlFileBuilder$XmlResourceParserImpl.getStyleAttribute(XmlFileBuilder.java:772)
	at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:152)
	at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:51)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:489)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
	at android.content.Context.obtainStyledAttributes(Context.java:416)
	at android.support.v7.internal.widget.ViewUtils.themifyContext(ViewUtils.java:116)
	at android.support.v7.internal.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:75)
	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:782)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:810)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
	... 67 more
```

**Comment by ernestkamara** [comment] 2015-05-11 20:29
Same issue with robolectric 2.4 and appcompat 22.1.0.

**Comment by jaredsburrows** [comment] 2015-05-20 16:18
@ernestkamara  Upgrade to Robolectric 3.0+ already.

@ubelab Have you tried upgrading to Robolectric 3.0-rc2 or 3?

**Comment by ubelab** [comment] 2015-05-20 16:23
@jaredsburrows yes I tried with 3.0-rc2 and 3.0-SNAPSHOT.

**Comment by jaredsburrows** [comment] 2015-05-20 16:26
What does your test look like?

**Comment by ubelab** [comment] 2015-05-22 12:09
I think is not related to the specific test i'm doing. The problem is that this piece of code trigger an alert dialog to show.

```
@Test
    public void testIfPasswordAndValidatePasswordAreNotSameShouldNotRun() throws Exception {
        //Create mock asynctask
        activity.factory = ((RegisterActivity)activity).new TaskFactory(){
            @Override
            public RegisterActivity.RegisterTask getTask() {
                return ((RegisterActivity)activity).new RegisterTask() {
                    @Override
                    protected ServiceResult doInBackground(URL... params) {
                        ServiceResult result = new ServiceResult(HttpURLConnection.HTTP_CREATED, new JSONObject());
                        return result;
                    }
                };
            }
        };

        final Button okBtn = (Button)activity.findViewById(R.id.register_submit_btn);
        final EditText emailField = (EditText) activity.findViewById(R.id.email_field);
        final EditText passwordField = (EditText) activity.findViewById(R.id.password_field);
        final EditText verifyPasswordField = (EditText) activity.findViewById(R.id.verify_password_field);
        //TESTCASE 1: one field is empty
        activity.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                //set email field empty
                emailField.requestFocus();
                emailField.setText("");
                okBtn.performClick();
            }
        });

        Robolectric.flushBackgroundThreadScheduler();

        //No navigation to Success page
        assertNull(shadowOf(activity).getNextStartedActivity());

        //Email field should be with red text
        assertTrue(emailField.getCurrentTextColor() == Color.RED);
    }
```

**Comment by jaredsburrows** [comment] 2015-05-26 05:19
Where is the alert dialog in this test? Does it have to do with the button? 

I just switch to using the app compat dialog myself, I am try to see if I run into this same error.

**Comment by daj** [comment] 2015-06-17 16:33
I'm hitting this issue too - I would love to see a fix for this.  Does anybody know how much effort this would be, and what would be required to fix it?

**Comment by jaredsburrows** [comment] 2015-06-17 16:48
I still have not been able to reproduce this. All of my apps use an `AlertDialog` from AppCompat v7. Do you see think only after explicitly calling `show`?

**Comment by daj** [comment] 2015-06-17 17:21
Yes, the exception only happens after calling `.show` on the dialog.

Here are some snippets from my test, in case I have made any obvious mistakes!

```
@RunWith(CustomRobolectricRunner.class)
public class MyFragmentTest { 
    protected ActivityController<TestActivity> controller;      
    protected TestActivity activity;
     
    @Before     
    public void setUp() throws Exception { 
        MockitoAnnotations.initMocks(this);   
       
        controller = Robolectric.buildActivity(TestActivity.class);         
        activity = controller.get();         
        controller.create();          

        fragment = (MyFragment) Fragment.instantiate(activity, MyFragment.class.getName());                   
        activity.getFragmentManager().beginTransaction().replace(
                R.id.container, fragment, fragment.getClass().getSimpleName()).commit();
    }

    @Test 
    public void testEnableNoNFC() throws Exception {           
        when(packageManager.hasSystemFeature(PackageManager.FEATURE_NFC)).thenReturn(false);      
        fragment.myEnableMethod();
        ...
    }
}

public class MyFragment extends Fragment {

    ...

    private void showErrorDialog(String title, String message) {
        AlertDialog.Builder errorBuilder = new AlertDialog.Builder(getActivity());
        errorBuilder.setTitle(title).setMessage(message)
                .setPositiveButton(android.R.string.ok, new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        dialog.dismiss();
                    }
                }).create().show();
    }

    public void myEnableMethod() {
        if (!packageManager.hasSystemFeature(PackageManager.FEATURE_NFC)) {
            showErrorDialog(getString(R.string.my_title), getString(R.string.my_detail));
        }
        ...
    }
}

```

We're using `org.robolectric:robolectric:3.0-rc2`.

**Comment by jaredsburrows** [comment] 2015-06-17 17:23
@daj thank you so much for providing a clean cut example. I will try this soon!

**Comment by daj** [comment] 2015-06-17 18:00
FYI, I tried adding a call to `.visible()` based on the last section in the documentation (http://robolectric.org/activity-lifecycle/), but that didn't help.

**Comment by jaredsburrows** [comment] 2015-07-02 23:24
@ubelab @daj I was finally able to reproduce this one of applications.

**Comment by daj** [comment] 2015-07-14 18:35
I'm glad to hear it!  Do you have a rough plan when you might be able to fix this?  FYI, we also have a similar issue when loading an animation, and I was wondering if that will get fixed at the same time?  I tried to find an existing issue for it - https://github.com/robolectric/robolectric/issues/1793 seems similar, but I'm not sure if it is exactly the same.  Thanks!

**Comment by daj** [comment] 2015-08-05 20:52
If you create a feature branch outlining where the fix needs to go, and point me at a similar kind of fix, then we might be able to help make it?

**Comment by jaredsburrows** [comment] 2015-08-05 21:10
Currently to avoid Robolectric crashes, I have a try/cach around the Alertdialog.

**Comment by daj** [comment] 2015-08-07 01:33
A try...catch doesn't sound like much of a solution.  Here's what I'm doing to workaround the issue in the short term: http://stackoverflow.com/q/31868325/112705

**Comment by jaredsburrows** [comment] 2015-08-07 01:35
I never said it was a solution. This allows all of my other tests to pass.

**Comment by daj** [comment] 2017-07-06 19:35
Just wondering if this issue is likely to be fixed in any future Robolectric release?  Is there anything we can do to help?  If there is a similar fix you could point us at, then we could try and submit a pull request with the fix.  Thanks!

**Comment by xian** [comment] 2018-10-31 16:57
[Robolectric 4.0](http://robolectric.org/blog/2018/10/25/robolectric-4-0/) fixes many longstanding resource-related issues; could you check to see if this remains a problem?

If so, please feel free to reopen this issue and include a link to a public git repo demonstrating the problem to help us diagnose. Thank you!

**Closed by xian** 2018-10-31 16:57 UTC
Labels: defect
