### ISSUE TITLE
Testing onMeasure() on a ViewGroup, problem with measureChild().

### ISSUE THREAD

**Issue by tbruyelle** [robolectric/robolectric#794] opened 2013-10-28 10:07 UTC
I wrote a simple custom `ViewGroup` which has 2 `TextViews` as childs.

According to the width granted by its parent and the width of its childs, this custom `ViewGroup` will update the text of its childs.

The current version works as expected when running in a device or emulator.

The issue come when I wrote the junit to test this behavior. It seems Robolectric doesn't handle well the call to `measureChild`, which leads to childs never get measured. 
`getMeasured[Width|Height]()` always returns `0` after call to `measureChild()` inside my junit context.

I extracted and simplified as far as I can the context if someone wants to reproduce :
https://github.com/tbruyelle/Samples/blob/master/android

**Comment by jongerrish** [comment] 2015-06-30 23:57
The reason this happens is because in real Android a binder call to ViewRootImpl.Window.Stub.resized() gets called by the WindowManager which sets the mWinFrame values. This doesn't happen in Robolectric so the client window size remains at 0 x 0.

We need to implement this in Robolectric, we considered either force setting via reflection the mWinFrame dimensions or by invoking ViewRootImpl.dispatchResized() directly, which might be more preferable as it may set up things we require.

We tested this and verified that it works (but only when you specify a minWidth / minHeight I think).

To support the case where minWidth / minHeight is not specified, we probably need to shadow more of Paint which has native code to measure text size. We feel a better approach would be to include the layout lib along with Robolectric and migrate stuff like ShadowPaint / ShadowBitmap to use the Delegates instead. There maybe a possibility to auto-wire that stuff with the annotation processor.

https://github.com/android/platform_frameworks_base/tree/master/tools/layoutlib

**Comment by jongerrish** [comment] 2018-11-05 00:34
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

**Closed by jongerrish** 2018-11-05 00:34 UTC
