### ISSUE TITLE
SimpleDateFormat.parse() throws java.text.ParseException: Unparseable date

### ISSUE THREAD

**Issue by kamiox** [robolectric/robolectric#1030] opened 2014-04-04 18:24 UTC
Android version of SimpleDateFormat behaves differently than JDK version.
This simple test should pass, but we got:

 java.text.ParseException: Unparseable date: "2014-04-04T11:41:00+02:00"
        at java.text.DateFormat.parse(DateFormat.java:357)

``` java

import org.junit.Assert;
import org.junit.Test;

import java.text.SimpleDateFormat;

public class SimpleDateFormatTest {

    @Test
    public void testParse() throws Exception {
        Assert.assertEquals(1396604460000l, new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ").parse("2014-04-04T11:41:00+02:00").getTime());
    }
}
```

**Comment by koral--** [comment] 2015-04-28 17:43
If I understand everything correctly that error occurs due to `SimpleDateFormat` change between Java 6 and 7:
- http://developer.android.com/reference/java/text/SimpleDateFormat.html
- https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
eg. pattern letter `X` has been added and meaning of `z` has changed.
To fix that shadow of `SimpleDateFormat` should be added to Robolectric library or you should create a custom shadow.

**Comment by arahlf** [comment] 2015-09-08 17:24
Have there been any recent activity/updates on this?

**Comment by aliceresponde** [comment] 2015-12-18 20:27
Hi guys,   I  have the same problem Tring to parse String  to Date.

Its my code:

public Date getDateFromStringTime(String time) {
//                  SimpleDateFormat sdf = new SimpleDateFormat("h:mm a");
                    SimpleDateFormat sdf = new SimpleDateFormat("hh:mm a");
                    try {
                        //TODO alice
                        Log.i("time", "("+time+")");
                        return sdf.parse(time);
                    } catch (ParseException e) {
//                        e.printStackTrace();
                        Log.e("Error", "formating hour from string  " + e.getMessage());
                    }
                    return null;
                }

For example calling  that  method  for "9:30 AM" ,  is  crashing
The problem is  witg  physical device for lolipop.

**Comment by koral--** [comment] 2016-01-08 21:23
Not sure what is the relationship between robolectric and physical device?
Workaround for inconsistencies between robolectric and android runtime for things like `DateFormat` is not to test formatting but only if pattern is correct.
Similar issue with `DecimalFormat` https://github.com/robolectric/robolectric/issues/2071 and related [SO comment](http://stackoverflow.com/questions/32864889/test-android-decimalformat-with-robolectric#comment53565207_32866275).
Updating my previous comment, is not possible to shadow classes from `java.*` package.

**Comment by jongerrish** [comment] 2018-11-05 00:36
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

**Comment by lupsyn** [comment] 2019-08-12 16:28
This error is still valid with robolectric 4.3. The work around is to replace the ':' into the time zone before parsing.

**Comment by damoasda** [comment] 2021-01-06 17:17
I think we can close this issue with regard to pull request #4805.

**Comment by MGaetan89** [comment] 2024-05-29 06:47
Hey everyone,
This issue comes from the different JDK implementations between Android and your local JDK. There is nothing that Robolectric can do about it
We've added a [new documentation](https://robolectric.org/best-practices/#android-libcore-and-openjdk-have-different-implementations) for this to provide some tips. Please have a look, and don't hesitate to reopen this issue, or create a new one, if needed.

**Closed by MGaetan89** 2024-05-29 06:47 UTC
