### ISSUE TITLE
SwitchCompat can't inflate with switchStyle set (3.0-RC2)

### ISSUE THREAD

**Issue by shekibobo** [robolectric/robolectric#1649] opened 2015-04-01 17:21 UTC
I recently standardized all the `SwitchCompat` instances to use the same style applied by theme, and once I did that my tests that inflate `SwitchCompat` instances started failing. Everything still runs fine in the actual app. 

I also tried removing the `switchStyle` from the theme, but I still see the same problem. Seems Robolectric is unable to load a `SwitchCompat` without a style directly applied to the `SwitchCompat element`.

```
emulateSdk=21
reportSdk=21
```

Using API 22 for the build.

I changed my code from:

```xml
<!-- layout code -->
        <android.support.v7.widget.SwitchCompat
            style="@style/Custom.Widget.Switch"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:id="@+id/list_item_switch" />
<!-- layout code -->
```

to:

```xml
<!-- theme code -->
        <item name="switchStyle">@style/Custom.Widget.Switch</item>
<!-- theme code -->

<!-- layout code -->
        <android.support.v7.widget.SwitchCompat
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:id="@+id/list_item_switch" />
<!-- layout code -->
```

Here's the relevant stacktrace:

```
android.view.InflateException: XML file /app/build/intermediates/res/debug/layout/list_item_switch.xml line #-1 (sorry, not yet implemented): Error inflating class <unknown>
  at android.view.LayoutInflater.createView(LayoutInflater.java:633)
...
Caused by: java.lang.reflect.InvocationTargetException
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
  at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_createView(LayoutInflater.java:607)
  at android.view.LayoutInflater.createView(LayoutInflater.java)
  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:209)
  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:300)
  at android.view.LayoutInflater$FactoryMerger.$$robo$$FactoryMerger_55ff_onCreateView(LayoutInflater.java:177)
  at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java)
  at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_createViewFromTag(LayoutInflater.java:733)
  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
  at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_rInflate(LayoutInflater.java:806)
  at android.view.LayoutInflater.rInflate(LayoutInflater.java)
  at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_rInflate(LayoutInflater.java:809)
  at android.view.LayoutInflater.rInflate(LayoutInflater.java)
  at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_inflate(LayoutInflater.java:504)
  at android.view.LayoutInflater.inflate(LayoutInflater.java)
  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
  at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_inflate(LayoutInflater.java:414)
  at android.view.LayoutInflater.inflate(LayoutInflater.java)
  at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_inflate(LayoutInflater.java:365)
  at android.view.LayoutInflater.inflate(LayoutInflater.java)
  at android.view.View.$$robo$$View_17af_inflate(View.java:18415)
  at android.view.View.inflate(View.java)
  at com.android.internal.app.AlertController$AlertParams$3.$$robo$$3_14b3_onItemClick(AlertController.java:1017)
  at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java)
  at android.widget.AdapterView.$$robo$$AdapterView_13a9_performItemClick(AdapterView.java:300)
  at android.widget.AdapterView.performItemClick(AdapterView.java)
  at android.widget.AbsListView.$$robo$$AbsListView_2c0a_performItemClick(AbsListView.java:1143)
  at android.widget.AbsListView.performItemClick(AbsListView.java)

...

Caused by: java.lang.NullPointerException
  at android.graphics.PorterDuffColorFilter.update(PorterDuffColorFilter.java:103)
  at android.graphics.PorterDuffColorFilter.setColor(PorterDuffColorFilter.java:70)
  at android.graphics.drawable.Drawable.updateTintFilter(Drawable.java:1265)
  at android.graphics.drawable.NinePatchDrawable.onStateChange(NinePatchDrawable.java:570)
  at android.graphics.drawable.Drawable.setState(Drawable.java:598)
  at android.graphics.drawable.DrawableContainer.selectDrawable(DrawableContainer.java:462)
  at android.graphics.drawable.AnimatedStateListDrawable.onStateChange(AnimatedStateListDrawable.java:158)
  at android.graphics.drawable.Drawable.setState(Drawable.java:598)
  at android.support.v7.widget.SwitchCompat.drawableStateChanged(SwitchCompat.java:984)
  at android.view.View.refreshDrawableState(View.java:15931)
  at android.support.v7.widget.SwitchCompat.__constructor__(SwitchCompat.java:217)
  at android.support.v7.widget.SwitchCompat.<init>(SwitchCompat.java)
  at android.view.LayoutInflater.createView(LayoutInflater.java:607)
  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:209)
  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:300)
  at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
  at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
  at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
  at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
  at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
  at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
  at android.view.View.inflate(View.java:18415)
  at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1017)
  at android.widget.AdapterView.performItemClick(AdapterView.java:300)
  at android.widget.AbsListView.performItemClick(AbsListView.java:1143)
  at org.robolectric.shadows.ShadowAdapterView.performItemClick(ShadowAdapterView.java:62)
  at org.robolectric.shadows.ShadowAlertDialog.clickOnItem(ShadowAlertDialog.java:63)
  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
  at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
  at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:235)
  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
  at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:168)
  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
  at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
  at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
  at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
  at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
  at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
  at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
  at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
  ... 7 more

```

**Comment by pvtl-shane** [comment] 2015-04-14 21:12
We have noticed that inflating a view with a SwitchCompat through the Robolectric.buildActivity(...) method results in a SwitchCompat that works, and is testable.  

When inflating the view containing a SwitchCompat via LayoutInflater.inflate(viewId, ...) the above error occurs.  

note: we have not tried applying a custom theme to the switchCompat, just using it out of the box

**Comment by erd** [comment] 2015-04-17 16:40
@shekibobo Could you post the style definition for `@style/Custom.Widget.Switch`. I have a feeling I know what the fix is, but I'd like to test it with a real world scenario.

**Comment by shekibobo** [comment] 2015-04-17 17:07
```xml
    <style name="Custom.Widget.Switch" parent="Widget.AppCompat.CompoundButton.Switch">
        <item name="android:layout_height">wrap_content</item>
        <item name="android:layout_width">wrap_content</item>
        <item name="switchMinWidth">@dimen/control_switch_width</item>
        <item name="android:background">@android:color/transparent</item>
        <item name="track">@drawable/selector_control_switch_track</item>
        <item name="android:thumb">@drawable/selector_control_switch_thumb</item>
    </style>
```

**Comment by erd** [comment] 2015-04-17 18:49
I wasn't able to reproduce the exact problem (even with the custom style), but I was able to reproduce the NPE in `PorterDuffColorFilter.update` which is the cause of the stack trace. Once this is merged, let me know if it fixes your issue.

**Closed** 2015-04-17 19:13 UTC
Labels: 3.0, defect
