### ISSUE TITLE
Activity tests run in Android Studio but fail from CLI/CI

### ISSUE THREAD

**Issue by Philio** [robolectric/robolectric#3445] opened 2017-10-06 08:00 UTC
### Description

After upgrading an old project to the latest version of Robolectic and setting compile/target to 26, all activity tests fail when running from terminal or on CI with exception related to theme:

    java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

All activities are already using `Theme.AppCompat` or derivative themes.

### Steps to Reproduce

- Create a simple test for an activity, e.g.

        @RunWith(RobolectricTestRunner.class)
        @Config(constants = BuildConfig.class)
        public class MyActivityTest {
        
            private MyActivity activity;
        
            @Before public void setup() {
                activity = Robolectric.setupActivity(MyActivity.class);
            }
        
            @Test public void isNotNull() {
                assertThat(activity).isNotNull();
            }
        }

- Run from Android Studio - works
- Run from terminal - throws exception

### Robolectric & Android Version

Robolectric 3.4.2
SDK 26
Android Studio 2.3.3

**Comment by mathroule** [comment] 2018-02-21 13:42
I'm encountering the same issue, everything works well in Android Studio, but running tests using CLI fails with this error.

**Comment by setiawanp** [comment] 2018-04-16 09:49
Encountering the same issue after bumping up `compileSdkVersion` and `targetSdkVersion` to 26. But works fine if I still used 25.

**Comment by slott** [comment] 2018-06-25 16:18
Keeps failing here even at 25...

**Comment by setiawanp** [comment] 2018-06-26 06:36
I was able to solve this problem. The problem wasn't caused by Robolectric, it was caused by other libraries. In my case, the culprit was [AssertJ Android](https://github.com/square/assertj-android). The fix was removing AssertJ Android from my project completely and all the tests could run without errors after that. 

You guys might want to try to find the problematic libraries in your project first. Try to remove it and see how it is going.

**Comment by mathroule** [comment] 2018-06-27 21:58
Thanks @setiawanp! Indeed I was using AssertJ Android too. Removing it fixed the issue. Now I'm able to run my unit tests successful in Android Studio and through CLI.

**Comment by jongerrish** [comment] 2018-06-28 05:03
We should have the Truth Android extensions out this summer too, so you
have something to replace Assertj Android with.

**Comment by setiawanp** [comment] 2018-06-28 11:08
@mathroule Glad that it helped you!

@jongerrish Extending Truth to Android would be nice. I'm really excited to see it! Hope it will come as soon as possible

**Comment by jongerrish** [comment] 2018-10-31 17:54
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.

@setiawanp We launched some truth extensions as part of AndroidX Test 1.0 also

**Closed by jongerrish** 2018-10-31 17:54 UTC
