### ISSUE TITLE
SharedPreferences does not reload properly

### ISSUE THREAD

**Issue by roostertech** [robolectric/robolectric#3611] opened 2017-12-18 22:37 UTC
### Description
I'm trying to stage SharedPreferences data for a test and having trouble with reloading data. Am I missing something obvious?

### Steps to Reproduce

Test code
```
        SharedPreferences sharedPreferences = PreferenceManager.getDefaultSharedPreferences(RuntimeEnvironment.application);
        sharedPreferences.edit().putString("app_language_selection_pref_key", "us-en").commit();

        sharedPreferences = PreferenceManager.getDefaultSharedPreferences(RuntimeEnvironment.application);
        String check = sharedPreferences.getString("app_language_selection_pref_key", null);
        System.out.println(check);
```

After the commit
```
sharedPreferences = {android.app.SharedPreferencesImpl@3187} "android.app.SharedPreferencesImpl@5f5827d0"
 __robo_data__ = {java.lang.Object@3200} 
 mFile = {java.io.File@3197} "/var/folders/lj/g27q_z6x6lj3x3hjbpgy7bqw0000gn/T/robolectric-Method_testOnCreate2710164338150968268/org.robolectric.default-dataDir/shared_prefs/org.robolectric.default_preferences.xml"
 mBackupFile = {java.io.File@3201} "/var/folders/lj/g27q_z6x6lj3x3hjbpgy7bqw0000gn/T/robolectric-Method_testOnCreate2710164338150968268/org.robolectric.default-dataDir/shared_prefs/org.robolectric.default_preferences.xml.bak"
 mMode = 0
 mMap = {java.util.HashMap@3366}  size = 1
  0 = {java.util.HashMap$Node@3369} "app_language_selection_pref_key" -> "us-en"
   key = "app_language_selection_pref_key"
   value = "us-en"
 mDiskWritesInFlight = 0
 mLoaded = true
 mStatTimestamp = 0
 mStatSize = 0
 mWritingToDiskLock = {java.lang.Object@3202} 
 mListeners = {java.util.WeakHashMap@3203}  size = 0
```
Content of the xml, looks good
```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
<string name="app_language_selection_pref_key">us-en</string>
</map>
```

On the second call to getDefaultSharedPreferences -> startReloadIfChangedUnexpectedly. The map seems to have loaded properly. And then I saw a call to startLoadFromDisk.
```
this = {android.app.SharedPreferencesImpl@3187} "android.app.SharedPreferencesImpl@5f5827d0"
 __robo_data__ = {java.lang.Object@3200} 
 mFile = {java.io.File@3197} "/var/folders/lj/g27q_z6x6lj3x3hjbpgy7bqw0000gn/T/robolectric-Method_testOnCreate2710164338150968268/org.robolectric.default-dataDir/shared_prefs/org.robolectric.default_preferences.xml"
 mBackupFile = {java.io.File@3201} "/var/folders/lj/g27q_z6x6lj3x3hjbpgy7bqw0000gn/T/robolectric-Method_testOnCreate2710164338150968268/org.robolectric.default-dataDir/shared_prefs/org.robolectric.default_preferences.xml.bak"
 mMode = 0
 mMap = {java.util.HashMap@3366}  size = 1
  0 = {java.util.HashMap$Node@3369} "app_language_selection_pref_key" -> "us-en"
 mDiskWritesInFlight = 0
 mLoaded = true
 mStatTimestamp = 0
 mStatSize = 0
 mWritingToDiskLock = {java.lang.Object@3202} 
 mListeners = {java.util.WeakHashMap@3203}  size = 0
```

However when the instance was returned, the map is empty?
```
sharedPreferences = {android.app.SharedPreferencesImpl@3187} "android.app.SharedPreferencesImpl@5f5827d0"
 __robo_data__ = {java.lang.Object@3200} 
 mFile = {java.io.File@3197} "/var/folders/lj/g27q_z6x6lj3x3hjbpgy7bqw0000gn/T/robolectric-Method_testOnCreate2710164338150968268/org.robolectric.default-dataDir/shared_prefs/org.robolectric.default_preferences.xml"
 mBackupFile = {java.io.File@3201} "/var/folders/lj/g27q_z6x6lj3x3hjbpgy7bqw0000gn/T/robolectric-Method_testOnCreate2710164338150968268/org.robolectric.default-dataDir/shared_prefs/org.robolectric.default_preferences.xml.bak"
 mMode = 0
 mMap = {java.util.HashMap@3386}  size = 0
 mDiskWritesInFlight = 0
 mLoaded = true
 mStatTimestamp = 0
 mStatSize = 0
 mWritingToDiskLock = {java.lang.Object@3202} 
 mListeners = {java.util.WeakHashMap@3203}  size = 0
```

### Robolectric & Android Version
    compileSdkVersion 25
    targetSdkVersion 25
    testCompile "org.robolectric:robolectric:3.5.1"

### Link to a public git repo demonstrating the problem:
https://github.com/roostertech/roboplayground/blob/master/app/src/test/java/net/roostertech/roboplayground/SharedPrefTest.java

**Comment by roostertech** [comment] 2017-12-18 22:39
Seems like my issue is the same as #3510

**Comment by xian** [comment] 2017-12-18 23:24
Closing as dupe of #3510.

**Closed by xian** 2017-12-18 23:24 UTC
