### ISSUE TITLE
Testing color array attributes with RoboAttributeSet

### ISSUE THREAD

**Issue by SunhoY** [robolectric/robolectric#2524] opened 2016-06-21 08:29 UTC
I tried to make custom view using custom attributes such as array of colors, array of strings.
It worked fine with production code. 

For the test codes, primitive types such as integer, string works fine. 
But for the arrays, I got error below.

`java.lang.RuntimeException: huh? ResName{packagename:array/my_colors_array}`

The total codes are written below

```
MyActivity.java

List<Attribute> attributes = new ArrayList<>();
attributes.add(new Attribute("packagename:attr/count", "3", "packagename"));
attributes.add(new Attribute("packagename:attr/myHeight", "@dimen/my_height", "packagename"));
attributes.add(new Attribute("packagename:attr/myColors", "@array/my_colors", "packagename"));
attributes.add(new Attribute("packagename:attr/myStrings", "@array/my_strings", "packagename"));

Resources resources = RuntimeEnvironment.application.getResources();
ResourceLoader resourceLoader = shadowOf(resources).getResourceLoader();
AttributeSet attributeSet = new RoboAttributeSet(attributes, resourceLoader);

subject = new CustomView(RuntimeEnvironment.application, attributeSet);
```

```
attrs.xml

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <declare-styleable name="SingleStackedBar">
        <attr name="count" format="integer"/>
        <attr name="myHeight" format="reference"/>
        <attr name="myColors" format="reference"/>
        <attr name="myStrings" format="reference"/>
    </declare-styleable>
</resources>
```

```
arrays.xml

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <array name="myColors">
        <item>@color/color_a</item>
        <item>@color/color_b</item>
        <item>@color/color_c</item>
    </array>
    <array name="myStrings">
        <item>@string/string_a</item>
        <item>@string/string_b</item>
        <item>@string/string_c</item>
    </array>
</resources>
```
### Robolectric & Android Version

using robolectric 3.0 and using android Lollipop

**Comment by jongerrish** [comment] 2016-06-21 08:45
Robolectric 3.1 is out now. Can you try that?

Also, please post full stack trace.

**Comment by SunhoY** [comment] 2016-06-22 04:34
```
java.lang.RuntimeException: huh? ResName{com.sds.healthcare.wellnessmobile:array/single_stacked_bar_default_colors}

	at org.robolectric.shadows.Converter.convertAndFill(Converter.java:101)
	at org.robolectric.shadows.Converter.convertAndFill(Converter.java:50)
	at org.robolectric.shadows.ShadowResources.createTypedArray(ShadowResources.java:232)
	at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:209)
	at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:55)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:485)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
	at com.example.widget.SingleStackedBar.<init>(SingleStackedBar.java:31)
	at com.example.widget.SingleStackedBarTest.setUp(SingleStackedBarTest.java:45)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by xian** [comment] 2017-01-11 01:58
Dupe of #2631.

**Closed by xian** 2017-01-11 01:58 UTC
