### ISSUE TITLE
ServiceLoader fails with unhelpful error message for some internal failures

### ISSUE THREAD

**Issue by kriegfrj** [robolectric/robolectric#1766] opened 2015-05-04 15:13 UTC
Getting the following error on Windows (the same code seems to run fine in the Travis CI):

```
Running org.robolectric.TestRunnerSequenceTest
Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.076 sec <<< FAILURE!
shouldRunThingsInTheRightOrder(org.robolectric.TestRunnerSequenceTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: org.robolectric.internal.ShadowProvider: Provider org.robolectric.Shadows not a subtype
    at java.util.ServiceLoader.fail(ServiceLoader.java:239)
    at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
    at org.robolectric.internal.bytecode.InstrumentationConfiguration$Builder.build(InstrumentationConfiguration.java:115)
    at org.robolectric.TestRunnerSequenceTest$Runner.createClassLoaderConfig(TestRunnerSequenceTest.java:105)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:182)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:149)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.robolectric.TestRunnerSequenceTest.run(TestRunnerSequenceTest.java:85)
    at org.robolectric.TestRunnerSequenceTest.shouldRunThingsInTheRightOrder(TestRunnerSequenceTest.java:29)

whenNoAppManifest_shouldRunThingsInTheRightOrder(org.robolectric.TestRunnerSequenceTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: org.robolectric.internal.ShadowProvider: Provider org.robolectric.Shadows not a subtype
    at java.util.ServiceLoader.fail(ServiceLoader.java:239)
    at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
    at org.robolectric.internal.bytecode.InstrumentationConfiguration$Builder.build(InstrumentationConfiguration.java:115)
    at org.robolectric.TestRunnerSequenceTest$Runner.createClassLoaderConfig(TestRunnerSequenceTest.java:105)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:182)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:149)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.robolectric.TestRunnerSequenceTest.run(TestRunnerSequenceTest.java:85)
    at org.robolectric.TestRunnerSequenceTest.whenNoAppManifest_shouldRunThingsInTheRightOrder(TestRunnerSequenceTest.java:49)
```

Once the above test has run and failed, every subsequent test in the same run triggers the same exception as per above:

```
Running org.robolectric.shadows.ShadowAnimationUtilsTest
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0 sec <<< FAILURE!
loadAnimation_shouldCreateAnimation(org.robolectric.shadows.ShadowAnimationUtilsTest)  Time elapsed: 0 sec  <<< ERROR!
java.util.ServiceConfigurationError: org.robolectric.internal.ShadowProvider: Provider org.robolectric.Shadows not a subtype
    at java.util.ServiceLoader.fail(ServiceLoader.java:239)
    at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
        ...
```

Doesn't seem to happen when I run only a few tests at a time though, which will make it difficult to debug...

**Comment by lexs** [comment] 2015-05-04 17:52
I've seen this but it seemed to fix itself after cleaning, the error doesn't make much sense but I guess it has to do with old .class files or something similar.

**Comment by kriegfrj** [comment] 2015-05-05 04:11
Well whaddaya know - I pulled down the latest master, ran `mvn clean` and then `install-robolectric.bat`, and the above error went away. Thanks @lexs!

Now I'm down to just two failures and two errors in the main test run, which is probably as good a result as I have had since I started working on Robolectric! However, the dream of seeing all tests succeed on Windows still remains elusive...

**Comment by shubhamchaudhary** [comment] 2015-06-15 10:33
Facing the same problem on Linux

**Comment by kriegfrj** [comment] 2015-06-25 02:14
This happened again. Managed to figure out that this happens if there is a runtime error while loading & linking the shadow classes & executing their static initialisation. So it's a legitimate problem with a very misleading error message. It would be nice if we got a more helpful error message, but I suspect that responsibility for this lies buried within `java.util.ServiceLoader` somewhere. Perhaps the next best thing would be a unit test that tries to load the shadows outside of the `ServiceLoader` framework.

**Comment by blaksos** [comment] 2015-07-03 12:17
I'm experience this problem two on linux ubunutu + android studio 1.3 + robolectric 30-rc3. 

java.util.ServiceConfigurationError: org.robolectric.internal.ShadowProvider: Provider org.robolectric.httpclient.Shadows not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:231)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:181)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:369)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
	at org.robolectric.internal.bytecode.InstrumentationConfiguration$Builder.build(InstrumentationConfiguration.java:122)
	at org.robolectric.RobolectricTestRunner.createClassLoaderConfig(RobolectricTestRunner.java:129)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:182)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:149)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by kriegfrj** [comment] 2015-07-03 13:24
I had a bit of a look at this one the other day but didn't manage to solve it. What I did manage to deduce by looking at the source for `ServiceLoader` was that this happens when the loaded class is not assignment-compatible with the `ShadowProvider` interface. But it clearly does implement the ShadowProvider interface. The only way I can think of that this might happen is if, somehow, something went astray with the class loading, so that `ServiceLoader` loaded the `ShadowProvider` interface from one classloader and the `Shadows` implementation in the jar loaded from another classloader.

I haven't looked into this further because I have other priorities and it only seems to happen intermittently. Usually it clears up when you run install-robolectric.bat again. I think one trigger is when new jars are deployed to sonatype and you don't do a full re-install of your working copy. I have also managed to trigger it reliably when working on some changes to the `ShadowLooper`'s main looper intialisation. If I manage to get it to do that again, I will try and submit the code as a branch so that hopefully someone else can look at it if I can't.

**Comment by kriegfrj** [comment] 2015-07-06 11:35
Another observation: when this happens, it seems to be triggered by some other runtime exception. The pattern I typically see is that a test will fail with a particular error/runtime exception, and thereafter all the tests fail with the ServiceLoader exception stacktrace shown. I guess the desired behaviour would be that the Robolectric subsystem would be a bit more robust in the face of such failures so that it either managed to recover for subsequent tests, or at least to show the root cause exception rather than this seemingly unrelated exception.

**Comment by Praveen-Android** [comment] 2015-07-28 17:25
@kriegfrj @erd I see exactly the same pattern as described above. I could run tests in isolation but not as a package and my build fails as a consequence. Good to know that its being planned for 3.1. Not exactly sure what the error means but it seems to be a little misleading i suppose. Here is the stacktrace:

java.util.ServiceConfigurationError: org.robolectric.internal.ShadowProvider: Provider org.robolectric.shadows.httpclient.Shadows not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:231)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:181)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:369)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
	at org.robolectric.internal.bytecode.InstrumentationConfiguration$Builder.build(InstrumentationConfiguration.java:148)
	at org.robolectric.RobolectricTestRunner.createClassLoaderConfig(RobolectricTestRunner.java:132)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:185)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by kingargyle** [comment] 2015-10-22 18:26
For me this started happening when I added a new Global Broadcast receiver to the Android Manifest.  If I comment out the class.  What I found was that I had forgotten to register the class with Dagger for dependency injection and this error would be thrown instead of the actual underlying cause of the problem when running as a maven build.  When running the tests in IntelliJ it gave the actual cause of the issue, where when running with maven the above was thrown which gave no clue to what the actual cause was.

**Comment by emartynov** [comment] 2016-02-12 17:46
Also got this error today. Are there good explanation what happens?

**Comment by CDRussell** [comment] 2016-02-12 18:27
I had this issue when accidentally running tests in `release` instead of `debug`. I figured it was related to Proguard. I didn't investigate further as I don't need to run tests in `release` mode normally.

**Comment by kriegfrj** [comment] 2016-02-12 21:40
I haven't looked into this in depth for a while as I've had other priorities, but my theory is that this happens due to the multiple classloader environment. Under the right (wrong?) circumstances, the ServiceProvider interface gets loaded twice (by the InstrumentingClassLoader and the system ClassLoader). When ServiceLoader does its check for the right interface, it fails because the Class instance it is checking against came from a different ClassLoader.

**Comment by hzsweers** [comment] 2016-02-27 03:26
I started seeing this after trying Robolectric in our project, could that be a common denominator?

**Comment by ssoliwal** [comment] 2016-03-09 21:25
is this still broken?

java.lang.NoClassDefFoundError: android/content/pm/PackageInstaller

	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:75)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:449)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:247)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:154)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: android.content.pm.PackageInstaller
	at org.robolectric.internal.bytecode.InstrumentingClassLoader.getByteCode(InstrumentingClassLoader.java:192)
	at org.robolectric.internal.bytecode.InstrumentingClassLoader.findClass(InstrumentingClassLoader.java:147)
	at org.robolectric.internal.bytecode.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:122)
	... 21 more


java.util.ServiceConfigurationError: org.robolectric.internal.ShadowProvider: Provider org.robolectric.Shadows not a subtype

	at java.util.ServiceLoader.fail(ServiceLoader.java:231)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:181)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:369)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
	at org.robolectric.internal.bytecode.InstrumentationConfiguration$Builder.build(InstrumentationConfiguration.java:151)
	at org.robolectric.RobolectricTestRunner.createClassLoaderConfig(RobolectricTestRunner.java:132)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:186)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:154)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by jongerrish** [comment] 2016-03-09 21:30
@ssoliwal I doubt this is related, PackageInstaller was introduced in API 21, are you sure you're building a version of the sdk 21 or higher?

**Comment by ssoliwal** [comment] 2016-03-09 21:45
you are right, changed the sdk version to 21 and it worked.
@Config(constants = BuildConfig.class, sdk = 21)

Thanks @jongerrish

**Comment by kriegfrj** [comment] 2016-03-09 22:06
@jongerrish, @ssoliwal, it is not directly related, but this issue with the
ServiceLoader is always triggered by some other bug or underlying
misconfiguration (as it was in this instance). The real issue that this
thread will hopefully resolve is that the underlying issue is not made
obvious from the error message.

**Comment by jongerrish** [comment] 2016-03-09 22:17
Yeah, agreed. Seems like if there is an exception setting up the environment then all subsequent tests fail with that ServiceLoader message. We should clear that up.

**Comment by WonderCsabo** [comment] 2016-07-17 10:34
This is still happening for me in 3.1.1. Actually on the first test class, i got this message: https://github.com/robolectric/robolectric/issues/2562. Then on all the others, i got the `ServiceLoader` failures.

**Comment by zhenkhokh** [comment] 2016-07-17 20:57
`java.util.ServiceConfigurationError: org.robolectric.internal.ShadowProvider: Provider org.robolectric.Shadows not a subtype`

It happens when adding` resourceDir = "src/main/res"` in `@Config`.

**Comment by NeilConcur** [comment] 2016-07-20 17:20
I am also experiencing this problem. Any comment?


java.util.ServiceConfigurationError: org.robolectric.internal.ShadowProvider: Provider org.robolectric.Shadows not a subtype

	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.robolectric.internal.bytecode.InstrumentationConfiguration$Builder.build(InstrumentationConfiguration.java:151)
	at com.concur.mobile.corp.test.CorpTestRunner.createClassLoaderConfig(CorpTestRunner.java:39)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:191)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:159)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by jongerrish** [comment] 2016-07-20 17:27
I think it is this issue:-

https://github.com/robolectric/robolectric/issues/2526

Want to submit a PR, looks like a simple fix.

**Comment by slootzky** [comment] 2016-11-14 07:00
Hey , any news with this issue? 
Just upgraded from 3.0 to 3.1 and I see this error 229/230 failing tests (first one fails with a different exception of course)

**Comment by jongerrish** [comment] 2016-11-14 17:11
No, we haven't had a chance to work on it yet as there are other priorities.

As I've said before, this is a symptom of the environment not being set up
correctly in the first test and causing all other subsequent tests to fail
with this opaque error. So just take a look at the first failure as it
looks like you've already figured out.

We are as always happy to accept pull requests if someone wants to fix this
:-)

**Comment by YaroslavHavrylovych** [comment] 2016-12-06 14:06
I don't remember the details only that I saw same issue when one of my Shadow classes (e.g. I had ShadowMultiDex) wasn't public (package access).  Changed to public class and error disappear.

**Comment by jongerrish** [comment] 2016-12-06 16:12
This has been fixed by https://github.com/robolectric/robolectric/pull/2737

For any underlying issues causing this please file a separate specific pull request.

**Closed by jongerrish** 2016-12-06 16:12 UTC
Labels: 3.0, defect
