### ISSUE TITLE
CharArrayBuffer - NoSuchMethodError: java.lang.System.arraycopy([CI[CII)V

### ISSUE THREAD

**Issue by tehras** [robolectric/robolectric#1605] opened 2015-03-06 13:57 UTC
I get an error when CharArrayBuffer.expand() and CharArrayBuffer.append() is being called. 
The error is:
java.lang.NoSuchMethodError: java.lang.System.arraycopy([CI[CII)V
	at org.apache.http.util.CharArrayBuffer.expand(CharArrayBuffer.java:60)

I'm using the 3.0-SNAPSHOT version

**Comment by tehras** [comment] 2015-03-10 17:28
So apparently this is a SDK 20+ issue.
For now I put in @Config(emulateSdk = 19), and that it's working.

**Comment by erd** [comment] 2015-03-11 04:02
Does it happen with API 21 and 3.0-SNAPSHOT? We patched in some of the modified arraycopy methods, but we might have missed one. If so, I'll write up a test and get it fixed.

**Comment by tehras** [comment] 2015-03-11 17:40
Thanks. I just tried with API 21 and the for me it's failing at CharArrayBuffer, when i call EntityUtils:

java.lang.NoSuchMethodError: java.lang.System.arraycopy([CI[CII)V
	at org.apache.http.util.CharArrayBuffer.append(CharArrayBuffer.java:79)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:136)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:146)

**Comment by maksim88** [comment] 2015-03-30 15:52
Hey,
having the same problem with API level 21 

Part of the error:
```
java.lang.NoSuchMethodError: java.lang.System.arraycopy([CI[CII)V
	at org.apache.http.util.CharArrayBuffer.expand(CharArrayBuffer.java:60)
	at org.apache.http.util.CharArrayBuffer.ensureCapacity(CharArrayBuffer.java:187)
	at org.apache.http.message.BasicLineFormatter.doFormatRequestLine(BasicLineFormatter.java:207)
	at org.apache.http.message.BasicLineFormatter.formatRequestLine(BasicLineFormatter.java:185)
	at org.apache.http.message.BasicRequestLine.toString(BasicRequestLine.java:91)
	at java.lang.String.valueOf(String.java:2849)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at org.robolectric.tester.org.apache.http.FakeHttpLayer.findResponse(FakeHttpLayer.java:111)
	at org.robolectric.tester.org.apache.http.FakeHttpLayer.emulateRequest(FakeHttpLayer.java:120)
	at org.robolectric.shadows.ShadowDefaultRequestDirector.execute(ShadowDefaultRequestDirector.java:168)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
[...]
```

**Comment by erd** [comment] 2015-03-30 17:21
> Having the same problem with API level 21 (snapshot and rc1)

That's because the issue is still open and I have not yet committed a fix :)

**Comment by erd** [comment] 2015-04-08 22:20
It looks like the `java.lang.System.arraycopy` method is not getting re-written because it's in a package that we don't intercept by default (`org.apache.http.util`). I think this should be easy to fix.

**Closed** 2015-04-12 17:42 UTC
Labels: 3.0, enhancement

**Comment by alexstarkcitrix** [comment] 2015-04-23 09:23
When do we get a new build in the maven repo with this fix?

**Comment by erd** [comment] 2015-04-23 17:11
It should be included in the 3.0-SNAPSHOT build. I'm planning on making a 3.0-rc3 release, but not for another week or so.

**Comment by alexstarkcitrix** [comment] 2015-04-24 05:25
Would you please inform me when the new 3.0-rc3 release is out?
Thanks

**Comment by AbDaniel** [comment] 2015-05-15 08:41
Any updates on the rc-3 release? we too face the issue with rc2 and API 21.

**Comment by maksim88** [comment] 2015-05-22 16:36
rc3 is out.
just an info for you two

**Comment by niedzielski** [comment] 2016-07-06 20:52
This issue is still present in v3.1 on API 23 when using Html.fromHtml(String, Html.ImageGetter, Html.TagHandler).

**Comment by stari4ek** [comment] 2016-08-29 21:26
I get same with
```
	java.lang.NoSuchMethodError: java.lang.System.arraycopy([CI[CII)V
		at org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1508)
		at org.kxml2.io.KXmlParser.peekType(KXmlParser.java:1000)
		at org.kxml2.io.KXmlParser.next(KXmlParser.java:448)
		at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
```

**Comment by niedzielski** [comment] 2017-03-06 22:13
o/ This is still an issue in v3.3 with `sdk=24`:

```
java.lang.NoSuchMethodError: java.lang.System.arraycopy([CI[CII)V

	at org.ccil.cowan.tagsoup.HTMLScanner.save(HTMLScanner.java:679)
	at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:616)
	at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:450)
	at android.text.HtmlToSpannedConverter.convert(Html.java:758)
	at android.text.Html.fromHtml(Html.java:245)
	at org.wikipedia.util.StringUtil.fromHtml(StringUtil.java:136)
	at org.wikipedia.savedpages.ImageUrlMap$Builder.extractUrlsInSection(ImageUrlMap.java:125)
	at org.wikipedia.savedpages.ImageUrlMapTest.testNonClosedImgTag(ImageUrlMapTest.java:40)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:487)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:209)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by xian** [comment] 2017-03-07 00:12
@niedzielski, I can't reproduce the failure. Can you open a [new issue](https://github.com/robolectric/robolectric/issues/new) and include repro instructions (preferably a pull request with a failing test, or a git repo that exhibits the problem)? Thanks!

**Comment by niedzielski** [comment] 2017-03-07 04:16
:+1: @xian, this was more specific than I supposed :] Please see #2954.

**Comment by xian** [comment] 2017-03-07 22:04
Thanks @niedzielski!
