### ISSUE TITLE
MultiDex Installation Failed SDK 28

### ISSUE THREAD

**Issue by royspartyman** [robolectric/robolectric#4017] opened 2018-10-09 13:04 UTC
### Steps to Reproduce

Running unit tests

### Robolectric & Android Version

AS: 3.2
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

    testImplementation 'junit:junit:4.12'
    testImplementation 'org.powermock:powermock-module-junit4:1.6.6'
    testImplementation 'org.powermock:powermock-module-junit4-rule:1.6.6'
    testImplementation 'org.powermock:powermock-api-mockito:1.7.0'
    testImplementation 'org.powermock:powermock-classloading-xstream:1.6.6'
    testImplementation 'org.robolectric:robolectric:4.0-alpha-4-SNAPSHOT'
    testImplementation 'org.robolectric:shadows-multidex:4.0-beta-1'
    testImplementation 'org.robolectric:shadows-support-v4:3.3.2'
    testImplementation 'org.mockito:mockito-all:2.0.2-beta'

**Comment by xian** [comment] 2018-10-15 19:48
@royspartyman, can you attach a stacktrace? Also, could you change all of your `org.robolectric` dependencies to the same version (`4.0-beta-1` is the latest).

**Comment by jongerrish** [comment] 2018-10-15 19:52
Looks like a duplicate of https://github.com/robolectric/robolectric/issues/3946#issuecomment-426629820

We have a fix to the support multidex library and working on getting it out.

In the meantime you can work around it by following the instructions in my last comment on that bug

**Closed by jongerrish** 2018-10-15 19:52 UTC

**Comment by AlejandroHCruz** [comment] 2018-11-28 16:10
Hi, I'm seeing this very same problem using Robolectric 4.0.2 on Android Studio 3.3 with minSdk 18, target & compile SDKs set to 28. Has anyone else seen this issue after 4.0 too?
