### ISSUE TITLE
java.lang.VerifyError: Bad return type

### ISSUE THREAD

**Issue by DevDengChao** [robolectric/robolectric#5428] opened 2020-01-15 04:01 UTC
### Description
Unit tests pass when running by class, failed when running by module.

![reproduce](https://user-images.githubusercontent.com/16363180/72403117-02ca8f80-378c-11ea-985a-d6542b026657.gif)

Failure log: 
```
[Robolectric] com.xgtl.lbs.cell.CellModuleTest.provideCellReader: sdk=28; resources=BINARY
Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=28

java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    android/content/res/ResourcesImpl.$$robo$$android_content_res_ResourcesImpl$loadComplexColorForCookie(Landroid/content/res/Resources;Landroid/util/TypedValue;ILandroid/content/res/Resources$Theme;)Landroid/content/res/ComplexColor; @565: areturn
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'android/content/res/ComplexColor' (from method signature)
  Current Frame:
    bci: @565
    flags: { }
    locals: { 'android/content/res/ResourcesImpl', 'android/content/res/Resources', 'android/util/TypedValue', integer, 'android/content/res/Resources$Theme', 'java/lang/Object', 'java/lang/String', 'java/lang/Object', 'android/content/res/XmlResourceParser', 'android/util/AttributeSet', integer, 'java/lang/String' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0x0000000: 128a b800 903a 0519 0511 0437 b800 942c
    ......
  Exception Handler Table:
    bci [126, 342] => handler: 353
  Stackmap Table:
    append_frame(@61,Object[#4])
    full_frame(@165,{Object[#2],Object[#24],Object[#428],Integer,Object[#27],Object[#4],Object[#208],Null,Object[#929],Object[#1131]},{})
    append_frame(@196,Integer)
    same_frame(@229)
    append_frame(@288,Object[#208])
    full_frame(@327,{Object[#2],Object[#24],Object[#428],Integer,Object[#27],Object[#4],Object[#208],Object[#4],Object[#929],Object[#1131],Integer,Object[#208]},{})
    full_frame(@353,{Object[#2],Object[#24],Object[#428],Integer,Object[#27],Object[#4],Object[#208],Object[#4]},{Object[#335]})
    full_frame(@463,{Object[#2],Object[#24],Object[#428],Integer,Object[#27],Object[#4],Object[#208],Null},{})
    full_frame(@541,{Object[#2],Object[#24],Object[#428],Integer,Object[#27],Object[#4],Object[#208],Object[#4],Object[#929],Object[#1131],Integer,Object[#208]},{})

	at android.content.res.Resources.__constructor__(Resources.java:228)
	at android.content.res.Resources.<init>(Resources.java)
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1334)
	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1299)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1022)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1042)
	at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:47)
        ......    
```

[log.txt](https://github.com/robolectric/robolectric/files/4062988/log.txt)

### Steps to Reproduce
1. Right click the green 'java' folder, click 'Run tests in java with coverage', tests failed.
2. Right click failed test class and re-run test with coverage, tests pass.

You could try the demo module below.

### Robolectric & Android Version
Component | Version
--------------|---------
Robolectric | 4.3 
Gradle wrapper | gradle-6.1-rc-1-all
Android build plugin | 4.0.0-alpha08

Android Studio:
>Android Studio 4.0 Canary 8
Build #AI-193.5233.102.40.6107147, built on January 3, 2020
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1960M
Cores: 16
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: CMD Support, Gitflow, GradleDependenciesHelper, Key Promoter X, Lombook Plugin, Property Sorter, cn.yiiguxing.plugin.translate, com.vladsch.idea.multimarkdown, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, org.intellij.gitee, org.roana0229.android-xml-sorter, zielu.gittoolbox

### Link to a public git repo demonstrating the problem:
[lbs-service.zip](https://github.com/robolectric/robolectric/files/4062967/lbs-service.zip)

### Relative issue
#3756

**Comment by duchieu1307** [comment] 2020-03-06 08:57
Same here
Unit tests pass when running by class, failed when running by module.
Exception Details:
  Location:
    android/content/res/ResourcesImpl.$$robo$$android_content_res_ResourcesImpl$loadComplexColorForCookie(Landroid/content/res/Resources;Landroid/util/TypedValue;ILandroid/content/res/Resources$Theme;)Landroid/content/res/ComplexColor; @565: areturn
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'android/content/res/ComplexColor' (from method signature)
  Current Frame:
    bci: @565
    flags: { }
    locals: { 'android/content/res/ResourcesImpl', 'android/content/res/Resources', 'android/util/TypedValue', integer, 'android/content/res/Resources$Theme', 'java/lang/Object', 'java/lang/String', 'java/lang/Object', 'android/content/res/XmlResourceParser', 'android/util/AttributeSet', integer, 'java/lang/String' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0x0000000: 128a b800 903a 0519 0511 0437 b800 942c
    0x0000010: b401 b1c7 002a 1905 1104 38b8 0094 bb04
...

**Comment by hashmat100** [comment] 2020-04-03 05:32
Any solution ?

**Comment by gajayraghav** [comment] 2020-04-08 16:09
Similar situation here :-| 
Running tests on module works. But when i run with coverage, it fails with the same error. 
Robolectric 4.2

is there any work around ?

thanks

**Comment by faizandastgir-careem** [comment] 2020-04-19 07:48
I changed configurations to 
VM options: -noverify
change coverage runner to JaCoCo
worked for me

**Comment by hoisie** [comment] 2020-09-03 23:16
Are you still having this issue? I was not able to important that sample app. Can you verify that it imports from scratch?

**Comment by carstenhag** [comment] 2021-02-17 10:31
I just had this issue again (I had added an +1 many months ago). This is the run config. The tests only fail when running the tests with coverage enabled.
![Bildschirmfoto 2021-02-17 um 11 30 47](https://user-images.githubusercontent.com/3776997/108191603-9ef36280-7113-11eb-8895-b3b84c744ec8.png)

**Comment by carstenhag** [comment] 2021-02-17 10:38
@hoisie Here's a project with basically 1 activity, only a few test dependencies and 1 test where I can reproduce the issue :) https://github.com/carstenhag/robolectric-issue-5428

**Comment by utzcoz** [comment] 2021-02-17 12:03
> @hoisie Here's a project with basically 1 activity, only a few test dependencies and 1 test where I can reproduce the issue :). It's also broken with robolectric 4.5.1 btw. https://github.com/carstenhag/robolectric-issue-5428

I test it with `Android Studio` 4.1.2, and it reproduces the same verify error. But if I remove `@Config(sdk = [Build.VERSION_CODES.P])` from `ExampleUnitTest` in `robolectric-issue-5428` project, the error dismisses. But If I use `minSdk` or `maxSdk`, it also has the same problem. Looks like the `sdk` in `@Config` causes the problem directly.

**Comment by utzcoz** [comment] 2021-02-17 12:20
Another interesting found is that it shows `org.junit.AssumptionViolatedException: Robolectric doesn't support legacy mode after P
` error information after I change `sdk` version to `Q`.

**Comment by utzcoz** [comment] 2021-02-17 12:27
> Another interesting found is that it shows `org.junit.AssumptionViolatedException: Robolectric doesn't support legacy mode after P ` error information after I change `sdk` version to `Q`.

It also shows verify error after changing `sdk` version to `Q`, if I add the following config to `build.gradle`:

```groovy
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
```

**Comment by utzcoz** [comment] 2021-02-17 13:14
https://github.com/robolectric/robolectric/issues/3023 @carstenhag I found there is an old issue for this problem, maybe you can try it.

**Comment by carstenhag** [comment] 2021-02-17 13:31
The test coverage doesn't work when using JaCoCo, it's always at 0%.  
With the default IntelliJ runner and with `-ea -noverify` the test coverage works fine and therer's no error.

So I agree @utzcoz this ticket can be closed as it's a duplicate. I'll comment in 3023 further.

**Comment by utzcoz** [comment] 2022-02-24 05:11
@carstenhag Thanks. If anyone has similar problem, you can comment it at https://github.com/robolectric/robolectric/issues/3023. Feel free to reopen it if it has different root cause.

**Closed by utzcoz** 2022-02-24 05:11 UTC

**Comment by kesc11** [comment] 2022-08-08 07:13
> 我将配置更改为 虚拟机选项：-noverify 将覆盖跑步者更改为 JaCoCo 为我工作

I can run in idea, but I can't run it after it is packaged into jar. I got an error that may be Jackson's dependency. Your answer saved me, although I don't know what happened
