### ISSUE TITLE
Can't load fonts after updating to AndroidX Core 1.8

### ISSUE THREAD

**Issue by francescocervone** [robolectric/robolectric#7455] opened 2022-07-20 15:25 UTC
### Description
After updating AndroidX Core from 1.7 to [1.8](https://developer.android.com/jetpack/androidx/releases/core#1.8.0) Robolectric fails to load fonts obtained by `ResourcesCompat.getFont`.
The test crashes with the following error:
```
Font resource ID #0x7f080005 could not be retrieved.
android.content.res.Resources$NotFoundException: Font resource ID #0x7f080005 could not be retrieved.
	at androidx.core.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:574)
	at androidx.core.content.res.ResourcesCompat.getFont(ResourcesCompat.java:411)
        ...
```

### Robolectric & Android Version
Robolectric 4.8.1
Android 31

It works with Android 30

**Comment by utzcoz** [comment] 2022-08-02 12:37
Hi @francescocervone , could you provide a minimal reproduce app for this problem by following https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues? Thanks.

**Comment by francescocervone** [comment] 2022-08-03 15:56
Hi @utzcoz. Here is a sample:
https://github.com/francescocervone/RobolectricIssue7455

**Comment by neworld** [comment] 2022-08-30 15:18
It prevents us from upgrading almost any androidx library and dagger. 

After short investigation I found one method was changed:
```diff
--- <unnamed>
+++ <unnamed>
@@ -1,6 +1,6 @@
-private static Typeface loadFont(
-            @NonNull Context context, Resources wrapper, TypedValue value, int id, int style,
-            @Nullable FontCallback fontCallback, @Nullable Handler handler,
+    private static Typeface loadFont(
+            @NonNull Context context, Resources wrapper, @NonNull TypedValue value, int id,
+            int style, @Nullable FontCallback fontCallback, @Nullable Handler handler,
             boolean isRequestFromLayoutInflator, boolean isCachedOnly) {
         if (value.string == null) {
             throw new NotFoundException("Resource \"" + wrapper.getResourceName(id) + "\" ("
@@ -16,7 +16,8 @@
             }
             return null;
         }
-        Typeface typeface = TypefaceCompat.findFromCache(wrapper, id, style);
+        Typeface typeface = TypefaceCompat.findFromCache(wrapper, id, file, value.assetCookie,
+                style);
 
         if (typeface != null) {
             if (fontCallback != null) {
@@ -41,10 +42,11 @@
                     return null;
                 }
                 return TypefaceCompat.createFromResourcesFamilyXml(context, familyEntry, wrapper,
-                        id, style, fontCallback, handler, isRequestFromLayoutInflator);
+                        id, file, value.assetCookie, style, fontCallback, handler,
+                        isRequestFromLayoutInflator);
             }
             typeface = TypefaceCompat.createFromResourcesFontFile(
-                    context, wrapper, id, file, style);
+                    context, wrapper, id, file, value.assetCookie, style);
             if (fontCallback != null) {
                 if (typeface != null) {
                     fontCallback.callbackSuccessAsync(typeface, handler);

```

I have no idea what `value.assetCookie` is, but I suppose some shadowed method was overridden. Or maybe, because `TypefaceCompat.createResourceUid` changed generated ID

**Comment by hoisie** [comment] 2022-08-30 17:34
Weird how we didn't come across this issue yet.

This seems to be the root cause stack trace that is thrown and caught here:
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:core/core/src/main/java/androidx/core/graphics/TypefaceCompatApi29Impl.java;l=117-122?q=%22new%20Typeface.CustomFallbackBuilder(family)%22

```
android.graphics.fonts.FontFamily.getFont(FontFamily.java:179)
androidx.core.graphics.TypefaceCompatApi29Impl.findBaseFont(TypefaceCompatApi29Impl.java:59)
androidx.core.graphics.TypefaceCompatApi29Impl.createFromFontFamilyFilesResourceEntry(TypefaceCompatApi29Impl.java:155)
androidx.core.graphics.TypefaceCompat.createFromResourcesFamilyXml(TypefaceCompat.java:174)
androidx.core.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:639)
androidx.core.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:570)
androidx.core.content.res.ResourcesCompat.getFont(ResourcesCompat.java:411)
com.example.robolectricissue7455.FontUnitTest.fonts(FontUnitTest.kt:15)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by hoisie** [comment] 2022-08-30 20:11
FYI here is a more minimal repro of this issue.

Add to https://github.com/robolectric/robolectric/blob/master/integration_tests/ctesque/src/sharedTest/java/android/content/res/ResourcesTest.java

I am a little surprised AndroidX fonts ever worked at all...

```
  @Test
  @SdkSuppress(minSdkVersion = Q)
  @Config(minSdk = Q)
  public void fontFamily_getFont() throws Exception {
    Font platformFont = new Font.Builder(resources, R.font.vt323_regular).build();
    FontFamily fontFamily = new FontFamily.Builder(platformFont).build();
    assertThat(fontFamily.getFont(0)).isNotNull();
  }
  ```

**Comment by neworld** [comment] 2022-09-16 10:33
Sorry for interrupting you, but AFAIK this was fixed in #7574. When could we expect this to be released? It is a real blocker of upgrading many things, like a dagger.

**Comment by hoisie** [comment] 2022-09-17 13:47
Hi @neworld 4.9-aloha-1 was just released with this fix. Could you give that a try?

Also, you always have the ability to use custom shadows to work around the issue until a fix is released.

**Comment by francescocervone** [comment] 2022-09-19 10:37
Hi @hoisie. I tried the 4.9-alpha-1 in our project and in the sample provided. The issue is fixed.

**Comment by utzcoz** [comment] 2022-09-19 11:18
@francescocervone Thanks for confirmation. You can use current alpha release or later stable release to fix this issue. Feel free to reopen it if you have any questions.

**Closed by utzcoz** 2022-09-19 11:18 UTC
