### ISSUE TITLE
Robolectric unable to find typed array

### ISSUE THREAD

**Issue by lxquiroga** [robolectric/robolectric#1444] opened 2014-12-30 23:32 UTC
When declaring an array element resource, a call to getIntArray succeeds in the binary but fails in robolectric.  The Android documentation suggests using obtainTypedArray instead (http://developer.android.com/guide/topics/resources/more-resources.html).  This works fine but perhaps the robolectric tests should work like Android.

**Comment by xian** [comment] 2017-01-11 02:04
Dupe of #2064.

**Closed by xian** 2017-01-11 02:04 UTC
Labels: resources
