### ISSUE TITLE
Robolectric does not work with JDK 17

### ISSUE THREAD

**Issue by ZacSweers** [robolectric/robolectric#6721] opened 2021-09-17 01:57 UTC
### Description

Robolectric does not appear to be compatible with JDK 17

### Steps to Reproduce

Run a robolectric test using JDK 17, observe a trace like this

![image](https://user-images.githubusercontent.com/1361086/133711541-98f2eb64-6144-460f-a831-883a0070297e.png)

### Robolectric & Android Version

Robolectric 4.6.1, Android version N/A

**Comment by utzcoz** [comment] 2021-09-17 02:33
@ZacSweers Thank you to test `Robolectric` on JDK 17 so early, and report its compatibility problem. There is a continuing work for [JEP 403: Strongly Encapsulate JDK Internals](https://openjdk.java.net/jeps/403) to encapsulate JDK internals more strictly at JDK 17. I will check it to see whether there are some workarounds for it.

**Comment by hoisie** [comment] 2021-09-17 03:02
I believe all ProxyMaker usage has been removed in favor of reflector, so maybe it will work in the next release?

**Comment by ZacSweers** [comment] 2021-09-17 03:20
Ah great, happy to help test when the next release is out!

**Comment by utzcoz** [comment] 2021-09-17 03:26
Maybe we also need to upgrade ASM and Grade to support JDK 17, I have saw their disccussions at Grade issue.

**Comment by utzcoz** [comment] 2021-10-19 16:14
If we want to support JDK 17, we should use gradle 7.3+(only 7.3-rc-1 now). Robolectric also needs to skip errorprone because the version we used doesn't support JDK 17. After that, I also get failed building, caused by legacy `ProxyMaker`:

```
~/robolectric/robolectric/sandbox/src/main/java/org/robolectric/internal/bytecode/ProxyMaker.java:111: error: cannot find symbol
    final Class<?> proxyClass = UNSAFE.defineAnonymousClass(targetClass, bytecode, null);
                                      ^
  symbol:   method defineAnonymousClass(Class<T>,byte[],<null>)
  location: variable UNSAFE of type Unsafe
  where T is a type-variable:
    T extends Object declared in method <T>createProxyFactory(Class<T>)
```

After searching, `ShadowImpl#directlyOn` uses `ProxyMaker` indirectly. And `ShadowImpl#directlyOn` is used by many shadows. @hoisie will there be some PRs to remove it? Or those usages doesn't matter?

**Comment by utzcoz** [comment] 2021-11-05 16:26
Hi @ZacSweers , maybe you can try Robolectric with JDK 17 again after https://github.com/robolectric/robolectric/pull/6821 (created by @hoisie) merged. I think it will remove the last piece of `PorxyMaker` code used by Robolectric released library. And I think it will be released at next 4.7 alpha release.

**Comment by ZacSweers** [comment] 2021-11-05 16:29
Can do 👍

**Comment by utzcoz** [comment] 2021-11-06 04:11
> Can do +1

Sorry, looks like there are some legacy `directyOn` usage, I don't find. I think @hoisie is trying to migrating all those usage with latest PRs. At least, we can wait the next 4.7 alpha release.

**Comment by hoisie** [comment] 2021-11-06 06:35
Yeah there were only 4-5 remaining shadows that used the proxy directlyOn. I have PRs that migrate to reflector but haven't merged them yet. However, if your tests don't use those particular shadow methods, 4.7-alpha-1 should work fine. I'm hoping to get another release in this weekend with it fully migrated.

**Comment by eygraber** [comment] 2021-11-11 08:12
I tested with 4.7-alpha-2 and get the following errors:

```
java.lang.RuntimeException at Sandbox.java:45
        Caused by: java.lang.ClassNotFoundException at SandboxClassLoader.java:161
            Caused by: java.lang.IllegalArgumentException at ClassReader.java:189
```

**Comment by utzcoz** [comment] 2021-11-11 09:23
> I tested with 4.7-alpha-2 and get the following errors:
> 
> ```
> java.lang.RuntimeException at Sandbox.java:45
>         Caused by: java.lang.ClassNotFoundException at SandboxClassLoader.java:161
>             Caused by: java.lang.IllegalArgumentException at ClassReader.java:189
> ```

I think Robolectric should bump ASM version to 9.1 or 9.2 to support JDK 17.

**Comment by hoisie** [comment] 2021-11-11 15:14
Is there a full stack trace?

**Comment by utzcoz** [comment] 2021-11-11 15:54
> Is there a full stack trace?

I used a test app to test 4.7-alpha-2, and I got a full stack trace:

```
java.lang.NoClassDefFoundError: android/webkit/RoboCookieManager
	at org.robolectric.Shadows.reset(Shadows.java:2457)
	at org.robolectric.android.internal.AndroidTestEnvironment.resetState(AndroidTestEnvironment.java:622)
	at org.robolectric.RobolectricTestRunner.lambda$finallyAfterTest$0(RobolectricTestRunner.java:355)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:86)
	at org.robolectric.RobolectricTestRunner.finallyAfterTest(RobolectricTestRunner.java:353)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:283)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: couldn't load android.webkit.RoboCookieManager
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:161)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$loadClass$0(SandboxClassLoader.java:133)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.loadClass(SandboxClassLoader.java:133)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 11 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:189)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:156)
	at org.robolectric.internal.bytecode.ClassNodeProvider.createClassNode(ClassNodeProvider.java:24)
	at org.robolectric.internal.bytecode.ClassNodeProvider.getClassNode(ClassNodeProvider.java:16)
	at org.robolectric.internal.bytecode.InstrumentingClassWriter.typeInfo(InstrumentingClassWriter.java:115)
	at org.robolectric.internal.bytecode.InstrumentingClassWriter.getCommonSuperClass(InstrumentingClassWriter.java:36)
	at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202)
	at org.objectweb.asm.Frame.merge(Frame.java:1299)
	at org.objectweb.asm.Frame.merge(Frame.java:1207)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
	at org.objectweb.asm.MethodVisitor.visitMaxs(MethodVisitor.java:773)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at org.robolectric.internal.bytecode.ClassInstrumentor.instrumentToBytes(ClassInstrumentor.java:117)
	at org.robolectric.internal.bytecode.ClassInstrumentor.lambda$instrument$1(ClassInstrumentor.java:132)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.ClassInstrumentor.instrument(ClassInstrumentor.java:132)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:153)
	... 15 more
```

After bumping asm to 9.2(https://github.com/robolectric/robolectric/pull/6844), this problem disappears.

**Comment by utzcoz** [comment] 2021-11-12 08:33
Hi @ZacSweers @eygraber , I have tested Robolectric 4.7 stable release with a sample app, and it can work with JDK 17. Maybe you can give a try. I will close this issue. If there is any problem about JDK 17 at your projects, feel free to reopen this issue.

**Closed by utzcoz** 2021-11-12 08:33 UTC

**Comment by eygraber** [comment] 2021-11-15 03:29
Looks like it's working now. The following error gets printed a few times, but otherwise good:

```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
```

**Comment by ZacSweers** [comment] 2021-11-15 03:30
Looks good on our end with 4.7 👍
