### ISSUE TITLE
VideoView cannot be mocked since Robolectric 4.7

### ISSUE THREAD

**Issue by ganadist** [robolectric/robolectric#6858] opened 2021-11-15 04:56 UTC
### Steps to Reproduce
```
$ git clone https://github.com/ganadist/VersionCodeDemo -b video_view_mock
$ cd VersionCodeDemo

### run test with robolectric 4.7 and failed
$ ./gradlew :app:testDevelopDebugUnitTest

### run test with robolectric 4.6.1 and succeed
$ git checkout HEAD~1
$ ./gradlew :app:testDevelopDebugUnitTest
```

* [test result with robolectric 4.7](https://scans.gradle.com/s/qsf2sde4ft4ps/tests/:app:testDevelopDebugUnitTest/com.example.myapplication.ExampleUnitTest1/test1)
  * [mockito-inline was already added](https://scans.gradle.com/s/qsf2sde4ft4ps/dependencies?focusedDependency=WzAsOCw0MDgsWzAsOCxbNDA4XV1d&toggled=W1swXSxbMCw1XSxbMCw4XSxbMCw4LFs0MDhdXV0)

* [test result with robolectric 4.6.1](https://scans.gradle.com/s/4ph6x5idogksy/tests/:app:testDevelopDebugUnitTest/com.example.myapplication.ExampleUnitTest1/test1)

### Robolectric & Android Version
* Android Gradle Plugin : 7.0.2
* Robolectric 4.7
* TargetSdkVersion 30
* Mockito (core + inline) : both of 3.11.2 and 4.0.0

### Link to a public git repo demonstrating the problem:
* [ExampleUnitTest1.java](https://github.com/ganadist/VersionCodeDemo/blob/video_view_mock/app/src/test/java/com/example/myapplication/ExampleUnitTest1.java)
* [unittest library versions](https://github.com/ganadist/VersionCodeDemo/blob/video_view_mock/gradle/versions/libs.toml#L24-L34)
* [unittest configurations](https://github.com/ganadist/VersionCodeDemo/blob/video_view_mock/gradle/project_base.gradle#L68-L77)

**Comment by hoisie** [comment] 2021-11-15 07:07
If this works in 4.6 and fails in 4.7, it should supposedly be possible to do a git bisect to determine the problematic commit.

Oddly, if this exact test is added to [mockito-experimental](https://github.com/robolectric/robolectric/tree/master/integration_tests/mockito-experimental/src/test/java/org/robolectric/integrationtests/mockito/experimental) as a test case, it passes.

**Comment by hoisie** [comment] 2021-11-15 07:21
As a general rule, I always advise everyone to avoid mocking Android objects, especially complex objects like Android Views, and use Robolectric shadowing if you want custom behavior.

**Comment by hoisie** [comment] 2021-11-15 07:34
This is interesting:

* If `@Mock VideoView mView` is changed to `@Mock SurfaceView mView` (it's superclass), the issue is still there.
* If `@Mock View mView` is used, the problem goes away.

So it seems like Mockito-inline has issue mocking SurfaceView.

From a cursory glance I see that SurfaceView contains an inner class ` SurfaceViewPositionUpdateListener`:

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/view/SurfaceView.java;l=1448

This implements RenderNode.PositionUpdateListener (https://cs.android.com/android/platform/superproject/+/master:frameworks/base/graphics/java/android/graphics/RenderNode.java;drc=master;l=265), which contains default interface methods.

I wonder if this is related to https://github.com/robolectric/robolectric/commit/4fb4565e10ab1263599525a62704d3bc6ecf08fa. In 4.7 Robolectric started to instrument default interface methods, in order to be able to shadow them.

**Comment by hoisie** [comment] 2021-11-15 23:25
FYI I have started a git bisect. In one terminal, in the Robolectric checkout, I run:

`SKIP_JAVADOC=true SKIP_ERRORPRONE=true SKIP_NATIVERUNTIME_BUILD=true ./gradlew publishToMavenLocal`

And in that sample app, I added `mavenLocal()` to the repositories in the top-level gradle section, and use Roboelctric version 4.7-SNAPSHOT, and run:

`./gradlew :app:testDevelopDebugUnitTest`

Interestingly, it does not seem to be the default interface instrumentation change.

**Comment by hoisie** [comment] 2021-11-16 00:14
Nevermind, the default interface instrumentation change is the culprit:

```
fb4565e10ab1263599525a62704d3bc6ecf08fa is the first bad commit
commit 4fb4565e10ab1263599525a62704d3bc6ecf08fa
Author: Googler <noreply@google.com>
Date:   Tue Jul 20 14:18:43 2021 -0700

    Instrument default interface methods

    PiperOrigin-RevId: 385869474

 .../internal/bytecode/ClassDetails.java            |  5 ++-
 .../internal/bytecode/ClassInstrumentor.java       | 47 ++++++++++++----------
 .../bytecode/InstrumentationConfiguration.java     |  3 +-
 .../internal/bytecode/InstrumentedInterface.java   |  4 ++
 4 files changed, 35 insertions(+), 24 deletions(-)
 create mode 100644 sandbox/src/main/java/org/robolectric/internal/bytecode/InstrumentedInterface.java
```

**Comment by hoisie** [comment] 2021-11-16 22:43
@ganadist I have been trying to create a more minimal repro in order to file a bug against Mockito but I can't seem to repro outside of your project:

For instance, I have the exact same test here, and it passes: https://github.com/hoisie/MockitoIssue

I have also tried to repro the issue using a simple Java command-line program, but that also doesn't have the same issue.

I am not really sure what about the VersionCodeDemo project is causing issues.

I'd recommend filing a bug against Mockito and see if they have any thoughts.

**Comment by ganadist** [comment] 2021-11-17 00:39
After added `includeAndroidResources = true` option on [app/build.gradle](https://github.com/hoisie/MockitoIssue/blob/main/app/build.gradle), error can be raised.

```
$ git diff 
```
```
diff --git a/app/build.gradle b/app/build.gradle
index 43468da..f5bb045 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -25,6 +25,17 @@ android {
         sourceCompatibility JavaVersion.VERSION_1_8
         targetCompatibility JavaVersion.VERSION_1_8
     }
+
+    testOptions {
+        unitTests {
+           includeAndroidResources = true
+           all {
+               testLogging {
+                   events "standardOut", "started", "passed", "failed", "skipped"
+               }
+           }
+       }
+    }
 }
 
 dependencies {
```

```
./gradlew :app:testDebugUnitTest --no-build-cache

com.example.mockitoissue.ExampleUnitTest > test1 STANDARD_OUT
    resources.arsc in APK '/home/ganadist/.m2/repository/org/robolectric/android-all-instrumented/11-robolectric-6757853-i2/android-all-instrumented-11-robolectric-6757853-i2.jar' is compressed.

com.example.mockitoissue.ExampleUnitTest > test1 FAILED
    org.mockito.exceptions.base.MockitoException at ParentRunner.java:306
        Caused by: org.mockito.exceptions.base.MockitoException at TypeCache.java:153
            Caused by: java.lang.UnsupportedOperationException at InstrumentationImpl.java:-2

1 test completed, 1 failed
```

**Comment by hoisie** [comment] 2021-11-17 01:21
Thanks, very bizarre that enabling binary resources causes that issue.

I'll file a bug w/ Mockito tonight, perhaps they will have ideas or suggestions about how to debug it.

**Comment by hoisie** [comment] 2021-11-17 07:01
I may have randomly found a fix for this issue -- the issue may have been related to modifying interfaces to make them public: https://github.com/robolectric/robolectric/blob/master/sandbox/src/main/java/org/robolectric/internal/bytecode/ClassInstrumentor.java#L146. If that line is commented out, the test seems to pass. 

Such a weird issue..

**Comment by hoisie** [comment] 2021-11-17 16:37
Just FYI, the common denominator is that Mockito has issues mocking classes that extend package-private interfaces.

In the case of SurfaceView, it's SurfaceChangedCallback (https://cs.android.com/android/platform/superproject/+/android-11.0.0_r7:frameworks/base/core/java/android/view/ViewRootImpl.java;l=1734)

In the case of ObjectAnimator, the problematic one is AnimationHandler.AnimationFrameCallback, which is implemented by ValueAnimator: https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/animation/AnimationHandler.java;l=275

For whatever reason, when Robolectric changes these interfaces to be public, it confuses Mockito/ByteBuddy, and leads to the JVM issues.

Changing the public modifier is not necessary for the interface instrumentation, the main goal of that was just to rewrite default interface methods to support interceptors. This is because some interfaces in Android now call libcore-only methods (e.g. System.logW: https://cs.android.com/android/platform/superproject/+/master:libcore/luni/src/main/java/android/compat/Compatibility.java;l=167).

We can restrict the interface instrumentation to just rewriting method bodies.

There may be a deeper issue in Mockito, though, so I will probably still file an issue w/ them in case there's a bug there too.

**Comment by hoisie** [comment] 2021-11-17 20:57
Reopening for now, I'll close when 4.7.1 is out

**Comment by hoisie** [comment] 2021-11-18 03:55
4.7.1 is out and should fix this issue.

**Closed by hoisie** 2021-11-18 03:55 UTC
