### ISSUE TITLE
Robolectric 3.1 and AppCompatTheme error

### ISSUE THREAD

**Issue by awago** [robolectric/robolectric#2538] opened 2016-06-30 13:51 UTC
Can't setup activity. I have error:

```
java.lang.RuntimeException: Could not find any resource  from reference ResName{com.***.***:style/Theme_AppCompat_Light_NoActionBar} from style StyleData{name='AppTheme', parent='Theme_AppCompat_Light_NoActionBar'} with theme null

at org.robolectric.shadows.ShadowAssetManager$StyleResolver.getParent(ShadowAssetManager.java:525)
at org.robolectric.shadows.ShadowAssetManager$StyleResolver.getAttrValue(ShadowAssetManager.java:463)
at org.robolectric.shadows.ShadowAssetManager.getOverlayedThemeValue(ShadowAssetManager.java:748)
at org.robolectric.shadows.ShadowAssetManager.findAttributeValue(ShadowAssetManager.java:737)
at org.robolectric.shadows.ShadowAssetManager.buildAttributes(ShadowAssetManager.java:683)
at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:103)
at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:52)
at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:270)
at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:265)
at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:260)
at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
at android.app.Activity.onApplyThemeResource(Activity.java:3727)
at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:150)
at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:94)
at android.support.v7.app.AppCompatActivity.setTheme(AppCompatActivity.java:90)
at org.robolectric.shadows.ShadowActivity.setThemeFromManifest(ShadowActivity.java:94)
at org.robolectric.shadows.CoreShadowsAdapter$1.setThemeFromManifest(CoreShadowsAdapter.java:30)
at org.robolectric.util.ActivityController.attach(ActivityController.java:70)
at org.robolectric.util.ActivityController.of(ActivityController.java:32)
at org.robolectric.Robolectric.buildActivity(Robolectric.java:82)
at org.robolectric.Robolectric.buildActivity(Robolectric.java:78)
at org.robolectric.Robolectric.setupActivity(Robolectric.java:86)
at com.***.***.ui.activities.LoginActivityTest.setUp(LoginActivityTest.java:23)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:265)
at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:191)
at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:56)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:157)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

my Gradle:

```
compileSdkVersion 24
buildToolsVersion "24.0.0"
...
    minSdkVersion 15
    targetSdkVersion 23

sourceSets {
    main { java.srcDirs = ['src/main/java'] }
    test { java.srcDirs = ['src/test/java'] }
}

testCompile 'junit:junit:4.12'
testCompile 'org.assertj:assertj-core:1.7.1'

testCompile'org.robolectric:shadows-support-v4:3.1'
testCompile("org.robolectric:robolectric:3.1") {
    exclude module: 'classworlds'
    exclude module: 'commons-logging'
    exclude module: 'httpclient'
    exclude module: 'maven-artifact'
    exclude module: 'maven-artifact-manager'
    exclude module: 'maven-error-diagnostics'
    exclude module: 'maven-model'
    exclude module: 'maven-project'
    exclude module: 'maven-settings'
    exclude module: 'plexus-container-default'
    exclude module: 'plexus-interpolation'
    exclude module: 'plexus-utils'
    exclude module: 'wagon-file'
    exclude module: 'wagon-http-lightweight'
    exclude module: 'wagon-provider-api'
    exclude group: 'com.android.support', module: 'appcompat'
    exclude group: 'com.android.support', module: 'support-v4'
    exclude group: 'com.android.support', module: 'recyclerview-v7'
}

compile 'com.joshdholtz.sentry:sentry-android:1.4.1'
compile 'com.android.support:design:24.0.0'
compile 'com.android.support:recyclerview-v7:24.0.0'
compile 'com.android.support:support-v4:24.0.0'
compile 'com.android.support:appcompat-v7:24.0.0'
compile 'com.google.android.gms:play-services-auth:9.0.2'
compile 'com.google.android.gms:play-services-maps:9.0.2'
compile 'com.google.android.gms:play-services-location:9.0.2'
compile 'com.google.android.gms:play-services-analytics:9.0.2'
compile 'com.squareup.retrofit2:retrofit:2.0.2'
compile 'com.squareup.retrofit2:converter-jackson:2.0.2'
compile 'com.squareup.okhttp3:logging-interceptor:3.0.1'
compile 'com.squareup.picasso:picasso:2.5.2'
compile 'com.vk:androidsdk:1.3.9'
compile 'com.facebook.android:facebook-android-sdk:4.5.0'
compile 'com.alexvasilkov:gesture-views:2.1.1'
compile 'com.github.bumptech.glide:glide:3.6.1'
compile 'com.github.tajchert:nammu:1.1.1'
compile('com.sangcomz:FishBun:0.4.4@aar') {
    transitive = true
}
```

My LoginActivityTest:

```
@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 23)
public class LoginActivityTest {

    @Before
    public void setUp() {
        Robolectric.setupActivity(LoginActivity.class);
    }

    @Test
    public void testSholdNotBeNull() throws Exception {
        assertTrue(true);
    }
}
```

My Theme:

```
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">

    <item name="windowActionBar">false</item>
    <item name="windowNoTitle">true</item>
    <item name="android:windowBackground">@color/colorBackground</item>

    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="colorAccent">@color/colorAccent</item>

    <item name="android:textColorPrimary">@color/textColorPrimary</item>
    <item name="android:textColorSecondary">@color/textColorSecondary</item>
    <item name="android:textColorPrimaryInverse">@color/textColorPrimaryDisableOnly</item>

</style>
```

What i'm doing wrong?

Android Studio 2.1.2

**Comment by dazza5000** [comment] 2016-10-12 17:17
Having this issue too. Did you find a solution for it?

**Comment by jongerrish** [comment] 2016-10-12 17:32
Does your LoginActivity have a theme? Obviously it should have been applied based on your AndroidManifest.xml .... can you put a breakpoint in ShadowActivity.setThemeFromManifest() and let us know if what values from the AndroidManifest object its getting if any at all and if it is resolved to a resource ID?

**Comment by jbruchanov** [comment] 2017-06-05 14:19
@jongerrish any progress here ?
seems to be still issue in my case...

### Description
```
java.lang.RuntimeException: Could not find any resource from reference ResName{com.scurab.android.robolectric3:style/Theme_AppCompat_Light_DarkActionBar} from Style com.scurab.android.robolectric3:AppTheme with theme with no applied styles

	at org.robolectric.res.StyleResolver.getParent(StyleResolver.java:99)
	at org.robolectric.res.StyleResolver.getAttrValue(StyleResolver.java:33)
	at org.robolectric.res.ThemeStyleSet.getAttrValue(ThemeStyleSet.java:17)
	at org.robolectric.shadows.ShadowAssetManager.findAttributeValue(ShadowAssetManager.java:858)
	at org.robolectric.shadows.ShadowAssetManager.buildTypedValue(ShadowAssetManager.java:744)
	at org.robolectric.shadows.ShadowAssetManager.attrsToTypedArray(ShadowAssetManager.java:792)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:244)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
	at android.content.Context.obtainStyledAttributes(Context.java:362)
	at android.support.v7.widget.TintTypedArray.obtainStyledAttributes(TintTypedArray.java:49)
	at android.support.v7.app.AppCompatDelegateImplBase.__constructor__(AppCompatDelegateImplBase.java:129)
	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java)
	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java)
	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java)
	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
	at android.app.Activity.performCreate(Activity.java:5008)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:231)
	at org.robolectric.android.controller.ActivityController$1.run(ActivityController.java:140)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:366)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:137)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:147)
	at com.scurab.android.robolectric3.ExampleUnitTest.testRobo(ExampleUnitTest.java:23)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:491)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:209)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

### Steps to Reproduce
Create sample project with empty activity in Android Studio 3.0 Canary 3
Add following test
```java
@RunWith(RobolectricTestRunner.class)
@Config(manifest = "./app/src/main/AndroidManifest.xml")
public class ExampleUnitTest {
    @Test
    public void testRobo() throws Exception {
        Robolectric.buildActivity(AppCompatActivity.class).create().get();
    }
}
```

### Robolectric & Android Version
gradle:
```groovy
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.scurab.android.robolectric3"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:25.3.1'

    testImplementation 'junit:junit:4.12'
    testImplementation "org.robolectric:robolectric:3.4-rc2"
}
```

**Comment by ColoradoTim** [comment] 2017-09-30 16:54
With robolectric 3.1.4, gradle 2.14.1, gradle plugin 2.1.3 and these test annotations
`@RunWith(RobolectricTestRunner.class)  `
`@Config(manifest = "src/main/AndroidManifest.xml", sdk = 21)`
 all 125 of my tests pass.

Then I upgraded to gradle 3.3 & gradle plugin 2.3.3 (with *no* other changes to my dependencies or codebase).  75 of my tests now fail.  All tests fail with:
> java.lang.RuntimeException: Could not find any resource  from reference ResName{com.mycompany.android:style/Theme_AppCompat_Light} from Style com.mycompany.android:MyCompanyTheme with theme with no applied styles

Any ideas?

**Comment by ColoradoTim** [comment] 2017-10-01 16:14
Found the fix for my problem!  I changed my robolectric test config annotations to:
`@Config(constants = BuildConfig.class, sdk = 21)`
and all tests pass!  The OP already specified this config annotation so it doesn't solve their problem even though we had the same stack trace.

The sdk attribute is optional, but I need it because my targetSdk (25) is greater than the sdk supported by Robolectric 3.1.x (23).

**Comment by jongerrish** [comment] 2018-10-31 16:22
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.

**Closed by jongerrish** 2018-10-31 16:22 UTC
