### ISSUE TITLE
@ClassRule aren't being called

### ISSUE THREAD

**Issue by roubertedgar** [robolectric/robolectric#6615] opened 2021-07-13 22:47 UTC
I'm using Robolectric 4.5.1. I've been created a rule to deal with the startup and shutdown of my mock web server.
Running on the emulator, with espresso, my @get:ClassRule calls the before and after method normally. But, when i ran the tests with Robolectric, on JVM, the before and after methods are not called.
To avoid this problem, today, I need to use @BeforeClass and @afterclass annotation, which in my case is less reusable than a ClassRule.

**Comment by utzcoz** [comment] 2021-07-14 15:24
Hi @roubertedgar , this issue is duplicate of https://github.com/robolectric/robolectric/issues/2637, you can post your problem with Robolectric version to this issue. So I close this issue. If you think it is not so related, you can reopen it freely.

**Closed by utzcoz** 2021-07-14 15:24 UTC
