### ISSUE TITLE
ClassCircularityError when initializing URL object after calling URL.setURLStreamHandlerFactory

### ISSUE THREAD

**Issue by aberent** [robolectric/robolectric#1688] opened 2015-04-16 10:30 UTC
If I call URL.setURLStreamHandlerFactory in a test, and then create a URL object I get a ClassCircularityError. This appears to be coming from the Robolectic class loader.

My minimal code to generate this error is:

``` Java
// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package org.chromium.chrome.browser.media.remote;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLStreamHandler;
import java.net.URLStreamHandlerFactory;

@RunWith(RobolectricTestRunner.class)
@Config(manifest = Config.NONE)
public class RobolectricClassLoaderTest {

     private class DummyUrlConnection extends HttpURLConnection {

        protected DummyUrlConnection(URL u) {
            super(u);
        }

        @Override
        public void connect() throws IOException {
        }

        @Override
        public void disconnect() {
        }

        @Override
        public boolean usingProxy() {
            return false;
        }


    }

    /**
     * Class for plugging in DummyUrlConnection
     */
    private class DummyUrlStreamHandler extends URLStreamHandler {

        @Override
        protected URLConnection openConnection(URL u) throws IOException {
            return new DummyUrlConnection(u);
        }

    }
    /**
     * Class for plugging in DummyUrlStreamHandler and hence DummyUrlConnection
     */
    private class DummyUrlStreamHandlerFactory implements URLStreamHandlerFactory {

        @Override
        public URLStreamHandler createURLStreamHandler(String protocol) {
            return new DummyUrlStreamHandler();
        }

    }

    @Test
    public void testMediaUrlResolver() throws IOException {

        // Plug in the dummy networking.
        URL.setURLStreamHandlerFactory(new DummyUrlStreamHandlerFactory());
        URL requestUrl = new URL("http://example.com/test.mp4");
    }
}
```

The output is:

```
[ RUN      ] org.chromium.chrome.browser.media.remote.RobolectricClassLoaderTest.testMediaUrlResolver
WARNING: no system properties value for ro.build.date.utc
java.lang.ClassCircularityError: org/chromium/chrome/browser/media/remote/RobolectricClassLoaderTest$DummyUrlConnection
    at org.chromium.chrome.browser.media.remote.RobolectricClassLoaderTest$DummyUrlStreamHandlerFactory.createURLStreamHandler(RobolectricClassLoaderTest.java:66)
    at java.net.URL.getURLStreamHandler(URL.java:1150)
    at java.net.URL.<init>(URL.java:590)
    at java.net.URL.<init>(URL.java:482)
    at java.net.URL.<init>(URL.java:431)
    at java.net.JarURLConnection.parseSpecs(JarURLConnection.java:179)
    at java.net.JarURLConnection.<init>(JarURLConnection.java:162)
    at sun.net.www.protocol.jar.JarURLConnection.<init>(JarURLConnection.java:81)
    at sun.net.www.protocol.jar.Handler.openConnection(Handler.java:41)
    at java.net.URL.openConnection(URL.java:971)
    at java.net.URL.openStream(URL.java:1037)
    at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:1350)
    at org.robolectric.bytecode.AsmInstrumentingClassLoader.getResourceAsStream(AsmInstrumentingClassLoader.java:120)
    at org.robolectric.bytecode.AsmInstrumentingClassLoader.getByteCode(AsmInstrumentingClassLoader.java:170)
    at org.robolectric.bytecode.AsmInstrumentingClassLoader.findClass(AsmInstrumentingClassLoader.java:126)
    at org.robolectric.bytecode.AsmInstrumentingClassLoader.loadClass(AsmInstrumentingClassLoader.java:98)
    at org.chromium.chrome.browser.media.remote.RobolectricClassLoaderTest$DummyUrlStreamHandlerFactory.createURLStreamHandler(RobolectricClassLoaderTest.java:66)
    at java.net.URL.getURLStreamHandler(URL.java:1150)
    at java.net.URL.<init>(URL.java:590)
    at java.net.URL.<init>(URL.java:482)
    at java.net.URL.<init>(URL.java:431)
    at org.chromium.chrome.browser.media.remote.RobolectricClassLoaderTest.testMediaUrlResolver(RobolectricClassLoaderTest.java:76)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.chromium.testing.local.GtestComputer$GtestSuiteRunner.run(GtestComputer.java:46)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:24)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
    at org.chromium.testing.local.JunitTestMain.main(JunitTestMain.java:105)
[   FAILED ] org.chromium.chrome.browser.media.remote.RobolectricClassLoaderTest.testMediaUrlResolver (2562 ms)
```

**Comment by lexs** [comment] 2015-04-17 11:01
This seems to happen because Robolectric loads your class (which internally resolves an URL), this calls back into your code because you installed a stream handler factory and bad things happen.

**Comment by lexs** [comment] 2015-04-17 11:11
Seems like even if this would cause ClassCircularityError it would still fail to load the bytecode because all URLs will use the provided factory.

**Comment by jongerrish** [comment] 2018-11-05 00:33
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

**Closed by jongerrish** 2018-11-05 00:33 UTC
