### ISSUE TITLE
Issues with new SQLite implementation, FTS tables, and FTS functions

### ISSUE THREAD

**Issue by ivtoto** [robolectric/robolectric#8495] opened 2023-10-05 11:30 UTC
### Description
Having a project that uses FTS (Full Text Search) tables and related SQLite functions.
Upgrading Robolectric from v4.7.3 to the latest v4.10.3.
Some UTs started failing. All those are related to Providers and SQLite queries related to FTS tables and the MATCH function.

### Steps to Reproduce
Having an FTS Table in the DB (in my case "USING FTS4").
Having a query like this one:
`SELECT * FROM search_index WHERE search_index MATCH '(content:Joh* OR name:4A6F68* OR tokens:Joh*)'`
With 4.7.3 it returns the corresponding(matching) values.
With 4.10.3 it always returns nothing - empty Cursor/no rows, even having matching results.
 
### Robolectric & Android Version
Robolectric v 4.10.3
Project Android Target and Compile SDKs: 33
Robolectric UTs Config SDK: 27
AGP 8.1.1
Gradle 8.3
Kotlin 1.9.10

### Details from investigation
Note that the team is Working on Mac (Intel and M1/M2 processors) and our Build machines are also Macs but only on Intel chips.

With the latest release, all the above-mentioned tests are failing on all, Intel and M1/M2 Chips.
With the Robolectric v4.7.3 - those same tests are passing on Intel machines and Failing on M1/M2 Macs.
I also tried the 4.10.3 with the`@SQLiteMode(SQLiteMode.Mode.LEGACY)` flag with the following results:
- Intel - PASSING
- M1/M2 - FAILING - even more tests are failing (not only the FTS-related ones)

I also tried changing a bit the query and I got a correct result with the following changes:
`SELECT * FROM search_index WHERE (tokens MATCH 'Joh*' OR name MATCH '4A6F68*' OR content MATCH 'Joh*')`
(note that the last was done in debug mode evaluating code)

I would suppose this is related to the changes in versions 4.7 and 4.9:
- 4.7: Another big feature is support for Apple Silicon (Mac M1). Robolectric 4.7 now contains its own native implementation of the android.database.sqlite package. For Mac M1 machines, this SQLite mode is the default. For other OS's and architecture, use @SQLiteMode(NATIVE) to enable it. This new mode is currently only available for Mac and Linux. Native SQLite should be significantly faster, around 50-90% faster for SQLite operations, than the LEGACY SQLite mode. There were also several other performance improvements made for SQLite operations
- 4.9: "_4.9 also turns on NATIVE sqlite mode by default for Mac and Linux. Windows will continue to use the LEGACY SQLite mode._" and the previous introduction of the

**Comment by hoisie** [comment] 2023-10-23 00:08
It could be related to a SQLite build flag:

These are the latest in AOSP:
https://cs.android.com/android/platform/superproject/main/+/main:external/sqlite/dist/Android.bp;l=1

These is what is used by Robolectric:
https://android.googlesource.com/platform/external/sqlite/+/refs/heads/android12-hostruntime-dev/dist/Android.bp

Does it work in 4.11-beta-2?

**Comment by hoisie** [comment] 2023-10-24 15:48
Are you running on Windows:

I am using this test and it seems to work fine, at least on Linux x86_64. I'll try to run it on the M1:

```java
  @Test
  @Config(sdk=34)
  public void fts4() {
    database.execSQL("CREATE VIRTUAL TABLE documents USING fts4 (" +
        "id INTEGER PRIMARY KEY, " +
        "title TEXT, " +
        "content TEXT" +
        ")");
    ContentValues values = new ContentValues();
    values.put("title", "Title1");
    values.put("content", "Hello World");
    database.insert("documents", null, values);

    String[] columns = {"id"};
    String selection = "documents MATCH 'content:*Wor*'";
    Cursor results = database.query("documents", columns, selection, null, null, null, null);
    assertThat(results.getCount()).isEqualTo(1);
  }
```

**Comment by hoisie** [comment] 2023-10-24 16:06
@ivtoto Can you please provide a concise example of a test method that fails using FTS4? Otherwise I am not able to repro this issue.

**Comment by ivtoto** [comment] 2023-10-24 16:30
Thank you for looking at this issue.

I had no chance to test anymore, as I had to just ignore those failing tests and move on for now.
I was also not able to test with the 4.11-beta-2... I'll try to find some time, test these days, and post more details.

In the main description, I tried to put all my findings and I would like to stress again the part that I consider gives more value/details:

This is the exact query that is executed and FAILING:
`SELECT * FROM search_index WHERE search_index MATCH '(content:Joh* OR name:4A6F68* OR tokens:Joh*)'`

When this same query is slightly modified - it returns the correct results:
`SELECT * FROM search_index WHERE (tokens MATCH 'Joh*' OR name MATCH '4A6F68*' OR content MATCH 'Joh*')`

Here is the Table structure, pretty simple actually:
`CREATE VIRTUAL TABLE search_index USING FTS4 (contact_id INTEGER REFERENCES contacts(_id) NOT NULL, content TEXT, name TEXT, tokens TEXT)`

About versions that I was able to test when I hit the issue:
- With the latest release, all the above-mentioned tests are **failing on all, Intel and M1/M2 Chips**. (At the point of opening the issue it was the 4.10.3)
- With the Robolectric v4.7.3 - those same tests are **passing on Intel machines** and **Failing on M1/M2 Macs**.
- I also tried the 4.10.3 with the@SQLiteMode(SQLiteMode.Mode.LEGACY) flag with the following results:
  - Intel - PASSING
  - M1/M2 - FAILING - even more tests are failing (not only the FTS-related ones)

**Comment by hoisie** [comment] 2023-10-24 23:34
Interesting.

I modified my little test method to use the colon syntax to match against multiple columns. Depending on the parenthesis location, it will either pass or fail. This result is actually consistent with real Android, though, so it's also an issue with Android.


This query seems to work on Robolectric/Android emulator/SQLite Console:
`String selection = "documents MATCH ('content:*Wor* OR title:*Wor*')";`

But this one fails in both Robolectric and Android emulator, but passes in the SQLite console:
`String selection = "documents MATCH '(content:*Wor* OR title:*Wor*)'";`

Full test that passes:
```
  @Test
  @Config(sdk=34)
  public void fts4() {
    database.execSQL("CREATE VIRTUAL TABLE documents USING fts4 (" +
        "id INTEGER PRIMARY KEY, " +
        "title TEXT, " +
        "content TEXT" +
        ")");
    ContentValues values = new ContentValues();
    values.put("title", "Title1");
    values.put("content", "Hello World");
    database.insert("documents", null, values);

    String[] columns = {"id"};
    String selection = "documents MATCH ('content:*Wor* OR title:*Wor*')";
    Cursor results = database.query("documents", columns, selection, null, null, null, null);
    assertThat(results.getCount()).isEqualTo(1);
  }
```

Note that the version of SQLite in 4.7.3 is ancient and is not supported any more. It doesn't work on Mac M1.

**Comment by hoisie** [comment] 2023-10-25 00:00
FWIW I have filed an issue w/ the Android SQLite team about this

**Comment by ivtoto** [comment] 2023-10-25 08:23
Interesting findings.
Based on this, we'll have to retest and recheck the real app flows... as the above means that some of our app searches should be failing.
However, we have not observed issues or such client reports (yet).
Could you please post or send me a link to the filed report to Google?

**Comment by hoisie** [comment] 2023-10-25 15:36
@ivtoto so in summary:

These work:

```
documents MATCH 'content:*Wor* OR title:*Wor*'

documents MATCH ('content:*Wor* OR title:*Wor*')
```

But these fail:
```
documents MATCH '(content:*Wor* OR title:*Wor*)'

documents MATCH '(content:*Wor*) OR (title:*Wor*')
```

So there is potentially something happening processing the parenthesis inside of the match statement. I would avoid putting any parenthesis inside of the string of the match statement.

**Comment by hoisie** [comment] 2023-10-25 21:33
Thanks again for reporting this issue.

A member of the Android storage team promptly and thoroughly investigated the issue, and the root cause is the Android's SQLite is not compiled with the flag:

`-DSQLITE_ENABLE_FTS3_PARENTHESIS`

Without this flag, parenthesis are not supported in FTS queries.

The current build flags are here: https://cs.android.com/android/platform/superproject/main/+/main:external/sqlite/dist/Android.bp;l=1

See https://sqlite.org/fts3.html#full_text_index_queries for details.

Note that this flag has never been used in Android's SQLite, so if you have parenthesis in your match queries in a prod app, they will be ignored (along with everything inside of them I believe).

If Robolectric in the past supported parenthesis in FTS queries, it was incidental, and not consistent with real Android.

There will probably be discussion about whether or not to enable this flag. There are potential backwards compatibility issues, though, that will need to be considered.

**Comment by ivtoto** [comment] 2023-10-26 06:54
Thank you again @hoisie for the research and updates!
I appreciate the time you spent checking this and finding an explanation for the observed behavior.
I'll be checking in detail where exactly we use this and how no one has reported an issue yet :)
I have no further questions, so feel free to close this report as you see.

**Comment by hoisie** [comment] 2023-11-16 18:32
Closing as this is not a Robolectric issue (Android doesn't support advanced FTS query syntax)

**Closed by hoisie** 2023-11-16 18:32 UTC
