### ISSUE TITLE
PowerMock integration is still broken

### ISSUE THREAD

**Issue by hzsweers** [robolectric/robolectric#2429] opened 2016-04-23 22:10 UTC
### Description

PowerMock has been broken in master for some time. This was first observed in January but still persists today. With the upcoming release, I want to raise this again because it's a dealbreaker for many consumers of the library. I think it should be considered a blocker for releasing 3.1.

CC @jongerrish @karlicoss 
### Steps to Reproduce

See existing issue: #2208
Existing PRs: #2390, #2213
### Robolectric & Android Version

Robolectric 3.1-SNAPSHOT, all versions

**Comment by karlicoss** [comment] 2016-04-30 23:35
Yeah, agree. Unfortunately, I am kinda stuck in my PRs with some weird things I don't understand :( Would be great if someone more familiar with powermock core could take a look at https://github.com/robolectric/robolectric/pull/2390

**Comment by erd** [comment] 2016-05-19 02:34
I would like to fix this before finalizing 3.1, but I don't know much about PowerMock. Could someone else here help out with a PR?

**Comment by jongerrish** [comment] 2016-05-19 02:40
I have a theory that it is due to our caching of classloaders between tests.

I'd like to rewrite this code so that we start with a fresh classloader for each test (we can cache the class byte stream but not the class definition). I think this would also remove the need for @Resetter logic so would give a cleaner environment, it would also stop leakages on the heap I think in some cases.

I honestly think we should still push 3.1 regardless as I doubt most people are using Power Mock and a release is way over due, but we can plan on a 3.1 release with this fix in and also address the performance regressions reported.

Thoughts?

**Comment by hzsweers** [comment] 2016-05-19 03:01
We are using power mock and have ~120 engineers. I think it's a regression
and should be fixed, but I'm not sure how much of a say I have since I
don't really know what's required to fix it. We wouldn't be able to update
until power mock integration is fixed :/

**Comment by jongerrish** [comment] 2016-05-19 03:09
Ya, its definitely a regression.

We don't really use Power Mock right now, but I'd rather promote teams use Power Mock over writing custom shadows for their own code, so I'm certainly in the camp of fixing it asap.

The question is do we hold up an already very late 3.1 release on this issue as I'm guessing most teams not using Power Mock would want an updated non-snapshot version of RE. I want to fix it, and its next on  my list as soon as I've upgraded out test corpus to work with the latest snapshot, there are a lot of breakages due to the shadow code removed from Context/ShadowContext etc.

I'd like to get a major RE release to coincide with every Android release, then have regular minor releases with a clear deprecation policy and API change documentation.

**Comment by hzsweers** [comment] 2016-05-25 00:05
Actually there's still a Wiki page dedicated to use of powermock. I'd say that enough to call it officially supported: https://github.com/robolectric/robolectric/wiki/Using-PowerMock.

**Comment by kingargyle** [comment] 2016-06-02 14:08
I suggest that you push 3.1 and then target this for a 3.1.1 bug fix release and document it as a known issue for 3.1.

**Comment by hzsweers** [comment] 2016-06-07 18:11
Any plans to document it? Current release notes don't mention it

**Comment by karlicoss** [comment] 2016-06-07 21:08
Agree, should definitely be in the release notes

**Comment by erd** [comment] 2016-06-07 23:43
I added a "Known Issues" section with a link to this issue.

**Comment by mplacona** [comment] 2016-07-10 18:09
Has there been any updates or workarounds on #2429? This is really coming on the way now.

Appreciate any input.

**Comment by jongerrish** [comment] 2016-07-10 18:11
We'll be taking a look at this next on the list but there are a couple of
tasks to finish first.

**Comment by mplacona** [comment] 2016-07-10 18:13
Thanks @jongerrish! Any ideas if there are any suggested workarounds on the time being?

**Comment by jongerrish** [comment] 2016-07-10 18:17
You can refactor your code to not use statics, then you can inject objects
and mock them with regular Mockito.

**Comment by hzsweers** [comment] 2016-07-27 04:07
3.1.1 is out with no changelog, assuming this was not fixed in it?

**Comment by jongerrish** [comment] 2016-07-27 16:47
No it wasn't. There are other issues that we're working on first. I'd really welcome a contribution though to fix this, it is a priority and I'm happy to give guidance.

**Comment by hzsweers** [comment] 2016-07-27 16:56
What would you recommend someone looking into this do?

**Comment by jongerrish** [comment] 2016-07-27 19:28
Someone has already taken a look at this and got stuck, but there is an open PR they left...

https://github.com/robolectric/robolectric/pull/2390

I would sync with the author of this @karlicoss

I think the issue might be that we are caching the classloader between API versions and some of the mock class definitions are getting shared between them. Could be a good idea not to cache classloaders between tests although this will result in a performance regression, but there may be other ways to make that back to some degree, e,g: caching the class bytes read from disk before the classes are loaded, rather than then class definitions themselves?

**Comment by karlicoss** [comment] 2016-07-27 21:57
@jongerrish yeah, I've tried to fix this few months ago, but everything I figured out about the cause, I put in the comments. So yeah, it was some issue with classloaders caching, but that's where I stuck and kinda gave up.

**Comment by mohib-irshad-10p** [comment] 2016-12-07 11:24
Is this fixed? Really need to use Powermock.. :(

**Comment by abangkis** [comment] 2016-12-20 20:33
Is there any update for this issue? I see it still not assigned to anyone?

**Comment by jongerrish** [comment] 2016-12-20 20:48
Hi,

Sorry for the lack of activity on this issue. The update is that this is a priority for us and we'll get to it early January. Our #1 priority right now is the next major release which will deliver api 24 + 25 support as well as the resources fix for the issue that prevented using AppCompat on older runtimes. There is still a corner case bug in the resource handling that we are working on but once this is fixed we'll cut a new major release. 

This issue will be our #1 priority right after this which we will include in a point release.

Sorry for the delay, I understand its frustrating.

**Comment by kingargyle** [comment] 2016-12-20 21:10
@jongerrish  you probably want to take a look at the classloader fix that is reference in the Mockito 2.x compatiblity bug elsewhere.  It may fix the PowerMock issues here as well.

**Comment by jongerrish** [comment] 2016-12-20 21:23
@kingargyle - Thanks, yeah, I'm aware of it, I also suspect its related, we're going to work on both of these issues.

**Comment by xian** [comment] 2017-01-05 22:27
Dupe of: https://github.com/robolectric/robolectric/issues/2677

**Comment by xian** [comment] 2017-01-06 00:59
Dupe of #2208.

**Closed by xian** 2017-01-06 00:59 UTC
Labels: defect
