### ISSUE TITLE
Shadows-supportv4 not compatible with AGP 3.3.0

### ISSUE THREAD

**Issue by calvarez-ov** [robolectric/robolectric#4491] opened 2019-01-15 13:53 UTC
### Description
"Transformation hasn't been executed yet" after upgrading a project to use android gradle plugin 3.3.0.

### Steps to Reproduce
* Use gradle 4.10.2
* Use android gradle plugin 3.3.0
* Use androidx with jetifier
* Have a unit test which uses a shadow of an androidx `SwipeRefreshLayout`
```java
SwipeRefreshLayout swipeRefreshLayout = activity.findViewById(R.id.swipe_refresh_layout);
Shadows.shadowOf(swipeRefreshLayout);
```
* Run `./gradlew testDebugUnitTest`
  - Expected behavior: the test compiles and passes
  - Actual behavior: build error "Transformation hasn't been executed yet"

Upgrading to gradle 5.1 allows you to see a more relevant error message. You may (or may not) need to add `android.jetifier.blacklist = shadows-supportv4-4.1.jar`  to your root `gradle.properties`. Eventually you'll see this compilation error:
```
        Shadows.shadowOf(swipeRefreshLayout);
               ^
  class file for android.support.v4.widget.SwipeRefreshLayout not found
1 error
```

Note that there's no problem if you use android gradle plugin 3.2.1.

### Robolectric & Android Version
gradle 4.10.2 or 5.1
targetSdkVersion 28
```
implementation "androidx.appcompat:appcompat:1.0.2"
testImplementation "org.robolectric:robolectric:4.1"
testImplementation "org.robolectric:shadows-supportv4:4.1"
```

### Link to a public git repo demonstrating the problem:
https://github.com/libon/RobolectricJetifierIssue

The repo has a README with more details on the error message and attempts to resolve them.

**Comment by calvarez-ov** [comment] 2019-01-15 14:04
I have a workaround for this, tested in my real project (sorry it's not in the sample project). The workaround is to not use the robolectric `ShadowSwipeRefreshLayout` but to implement one: just copy/paste the robolectric one and change imports to use androidx.  This one is in kotlin:

```kotlin
import androidx.swiperefreshlayout.widget.SwipeRefreshLayout
import org.robolectric.annotation.Implementation
import org.robolectric.annotation.Implements
import org.robolectric.annotation.RealObject
import org.robolectric.shadow.api.Shadow
import org.robolectric.shadows.ShadowViewGroup

/**
 * With the upgrade to android gradle plugin 3.3.0, we're running into an issue similar to the
 * following, regarding the robolectric shadows dependency:
 * https://issuetracker.google.com/issues/118658603#comment5
 *
 * The jetifier plugin fails to jetify (convert android.support.v4 to androidx) classes in the
 * robolectric dependency. To be able to run tests, we add this to our root gradle.properties:
 *
 * android.jetifier.blacklist = shadows-supportv4-4.1.jar
 *
 * This conf allows us to run tests, but it doesn't allow us to use a shadow of the androidx
 * SwipeRefreshLayout.
 *
 * So, we make our own shadow, based on the robolectric one.
 */
@Implements(SwipeRefreshLayout::class)
class ShadowSwipeRefreshLayout : ShadowViewGroup() {
    @RealObject
    var realObject: SwipeRefreshLayout? = null
    private var listener: SwipeRefreshLayout.OnRefreshListener? = null

    @Implementation
    protected fun setOnRefreshListener(listener: SwipeRefreshLayout.OnRefreshListener) {
        this.listener = listener
        Shadow.directlyOn(realObject, SwipeRefreshLayout::class.java).setOnRefreshListener(listener)
    }

    /**
     * @return OnRefreshListener that was previously set.
     */
    fun getOnRefreshListener(): SwipeRefreshLayout.OnRefreshListener? {
        return listener
    }
}
```

The test uses `@Config(shadows = com.example.ShadowSwipeRefreshLayout.class)`

**Comment by calvarez-ov** [comment] 2019-01-15 17:46
For info, I've seen another problem which might be related. I don't have a sample app for this yet. But it appears that `ShadowLocalBroadcastManager` from robolectric is no longer used in my tests. I don't reference it directly from my test code, which is probably why I didn't see any build failures. But tests are failing due to the fact that the same `LocalBroadcastManager` instance is being used across tests: the core code for the `getInstance()` method is being called:
```java
    @NonNull
    public static LocalBroadcastManager getInstance(@NonNull Context context) {
        synchronized (mLock) {
            if (mInstance == null) {
                mInstance = new LocalBroadcastManager(context.getApplicationContext());
            }
            return mInstance;
        }
    }
```
This keeps a static reference across tests.
The robolectric shadow keeps track of one per application:
```java
  @Implementation
  protected static LocalBroadcastManager getInstance(final Context context) {
    return ShadowApplication.getInstance().getSingleton(LocalBroadcastManager.class, new Provider<LocalBroadcastManager>() {
      @Override
      public LocalBroadcastManager get() {
        return ReflectionHelpers.callConstructor(LocalBroadcastManager.class, ClassParameter.from(Context.class, context));
      }
    });
  }
```

My workaround for this is similar to the workaround for `ShadowSwipeRefreshLayout`: I just 
* copy/paste the code to `ShadowLocalBroadcastManager` into my project
* use the androidx instead of support imports
* use this shadow in my tests.

**Comment by calvarez-ov** [comment] 2019-01-15 18:34
I think this might be related: https://issuetracker.google.com/issues/119951660

**Comment by calvarez-ov** [comment] 2019-01-16 17:24
Comment from the [google issue tracker](https://issuetracker.google.com/issues/119951660) about this issue:

> robolectric will need to update its library to support AndroidX, as Jetifier is not able to jetify it (case (1) in comment #9 above).
> 
> Note that with AGP 3.2.1, Jetifier did not fail when jetifying the library, but with AGP 3.3.0+ it fails, because we have made Jetifier stricter (i.e., it jetifies a library only when it can guarantee correctness). See Issue 116745353 for more info.

**Comment by caarmen** [comment] 2019-01-19 11:13
I've built robolectric from master and still have the issue.

I think I've identified the root cause, but not sure what the solution would be.

In `processor/src/main/java/org/robolectric/annotation/processing/generator/ShadowProviderGenerator.java`:

```java
if (shouldInstrumentPackages) {
  writer.println("      " + Joiner.on(",\n      ").join(model.getShadowedPackages()));
}
```

This generates `./shadows/supportv4/build/generated/src/apt/main/org/robolectric/shadows/support/v4/Shadows.java`

with:
```java
  @Override
  public String[] getProvidedPackageNames() {
    return new String[] {
      "android.support.v4.content",
      "android.support.v4.media",
      "android.support.v4.widget"
    };
  }
```

Jetifier doesn't like this. Indeed its message complains 
> The given artifact contains a string literal with a package reference 'android.support.v4.content' that cannot be safely rewritten

If I comment out this `writer.println` (I didn't figure out how to more cleanly disable this option), then I have no problem using robolectric with agp 3.3.0.

**Comment by calvarez-ov** [comment] 2019-01-24 14:11
Note: In my real project, initially I just copied 2 of the shadows classes into my project (`ShadowSwipeRefreshLayout`, to prevent compile errors, and `ShadowLocalBroadcastManager` to not have the static reference to the same `Application` in each test).

This allowed tests to run and pass, but they were about 20% slower than before the AGP upgrade.

I then copied *all* of the support v4 shadow classes into my project (changing the imports for androidx), and the test time went back to normal.

**Comment by markchristopherng** [comment] 2019-03-21 05:05
I've been waiting for this to get fixed as well but looks like has been assigned to fix it.

**Comment by hhaouat** [comment] 2019-05-01 09:38
We currently encountering the same issues and depend heavily on Shadows on our tests. 
Do you have any updates that could help ? or any alternative to shadows on tests?

**Comment by cooldude77** [comment] 2019-05-21 10:07
Robo tests are not working at all :(

**Comment by milosmns** [comment] 2019-06-04 09:51
I have a workaround that.. worked.. somehow. 

So, disclaimer: I'm not 100% sure about what this brings in terms of consequences, but we definitely don't mind having both appcompat and androidx bundled at the same time **for tests** (if it makes our lives so much easier). Also, since we have 200+ tests with Robolectric (and another 1200 without it), all of them passing again is a good indication that we "fixed" the issue. 

-- DO AT YOUR OWN RISK --

The first thing to do is, don't Jetify the `shadows` jar at all.
You can do this in your `gradle.properties`:

```properties
android.jetifier.blacklist=shadows
```

Then, update Robolectric core to v4.3 (shadows are at v3.4-rc2).  
This is the latest at the time of writing. 

Add the AndroidX-Test dependency to get the `ApplicationProvider` class: http://robolectric.org/migrating/#androidxtest
Replace all usages of `RuntimeEnvironment.application` with `ApplicationProvider.getApplicationContext()`.

As far as I can tell, from now on you won't be Jetifying the shadows jar anymore (makes the test bundle bigger I guess?), and your latest Robolectric runner (and shadowed context) will be utilized correctly to fill the correct Android resources.

**Comment by goldy1992** [comment] 2019-06-17 21:55
@milosmns thank you so much you fixed my build https://github.com/goldy1992/Mp3Player/commit/9dd4100ec1ba5d34ce6598b7677e7ad59aa73e68

**Comment by utzcoz** [comment] 2023-03-18 10:04
shadows-supportv3 has been removed from Robolectric some version ago, so I will close this issue. If anyone has compatibility issues of Robolectric, please file a new issue.

**Closed by utzcoz** 2023-03-18 10:04 UTC
