### ISSUE TITLE
android.content.res.Resources$NotFoundException: Unable to find resource ID

### ISSUE THREAD

**Issue by adamstyrc** [robolectric/robolectric#1592] opened 2015-02-25 21:55 UTC
Hey, I'm using Robolectric 2.4 with Android Studio 1.1.0. I just unplugged Gradle Android Unit Testing Plugin.
I keep getting

>android.content.res.Resources$NotFoundException: Unable to find resource ID

Before crash comes I get warning:
>No manifest file found at ./src/main/AndroidManifest.xml.Falling back to the Android OS resources only.

I tried to set manifest manually:
>@Config(...manifest = "/src/main/AndroidManifest.xml")

(and others)
but it didn't help

When I debug RobolectricTestRunner class,  I can see that:
>FileFsFile manifestFile == "./src/main/AndroidManifest.xml" 

and has no canonicalFile.

I can fix it writing custom RobolectricTestRunner, e.g. GradleRobolectricTestRunner but I would like to skip it.

**Comment by erd** [comment] 2015-02-25 22:08
Specifically for Android Studio, you have to use a custom test runner that sets the correct path for resources, assets, and your manifest.

**Comment by adamstyrc** [comment] 2015-02-26 08:54
In addition these lines generate null
>     String manifestProperty = System.getProperty("android.manifest");
    String resourcesProperty = System.getProperty("android.resources");
    String assetsProperty = System.getProperty("android.assets");

**Comment by erd** [comment] 2015-03-15 17:38
If you are using Gradle / Android Studio, you need to create a custom test runner that will tell Robolectric where to find your merged assets, resources, and manifest. Please see the discussion here: robolectric/robolectric-gradle-plugin#142

**Closed by erd** 2015-03-15 17:38 UTC

**Comment by JacobJust** [comment] 2017-03-16 11:14
As an alternative you could try this, works for me: 
"If you are on Linux or on a Mac, you will probably need to configure the default JUnit test runner configuration in order to work around a bug where Android Studio does not set the working directory to the module being tested. This can be accomplished by editing the run configurations, Defaults -> JUnit and changing the working directory value to $MODULE_DIR$."

**Comment by kakopappa** [comment] 2017-04-20 05:42
this is the solution I came up with. Works with robolectric 3

if (!isRoboUnitTest()) {
    Stetho.initializeWithDefaults(this);
}

public static boolean isRoboUnitTest() {
    return "robolectric".equals(Build.FINGERPRINT);
}

**Comment by jakub-g** [comment] 2017-06-13 08:21
If you still have the issue after following parent's comment, and you use Android Studio 2.3, see also https://github.com/robolectric/robolectric/issues/2949#issuecomment-284439922: do not edit only defaults, *but also other existing JUnit configurations*.

Note that I'm on Windows. It's not Linux or Mac-specific.

**Comment by dharmendrainnovify** [comment] 2017-07-14 09:39
@JacobJust Defaults -> JUnit and changing the working directory value to $MODULE_DIR$." works for me but how to configure it for CI? I am using circle CI.

**Comment by IgorGanapolsky** [comment] 2017-09-05 16:09
This is probably the correct solution in 2017: https://stackoverflow.com/questions/45922916/robolectric-resourcesnotfoundexception-string-resource-id-with-android-gradle

**Comment by autonomousapps** [comment] 2017-10-26 23:06
I can confirm that setting `android.enableAapt2=false` in `gradle.properties` also fixes this. Thanks, @IgorGanapolsky !
