### ISSUE TITLE
Shadowing android.graphics.Picture

### ISSUE THREAD

**Issue by arahlf** [robolectric/robolectric#2015] opened 2015-09-01 12:24 UTC
My app uses an SVG library that works fine normally but throws errors when running tests with Robolectric.  I think it's the same problem raised in the following Google Groups post, but I don't see any replies to it: https://groups.google.com/forum/#!msg/robolectric/AxM7ePt0BVQ/H_QrBuVhkuYJ

Here's the stack trace:

```
Caused by: java.lang.RuntimeException
    at android.graphics.Picture.__constructor__(Picture.java:173)
    at android.graphics.Picture.<init>(Picture.java)
    at com.applantation.android.svg.SVGParser.parse(SVGParser.java:316)
    at com.applantation.android.svg.SVGParser.getSVGFromResource(SVGParser.java:120)
```

Is there a way to work around this?

**Comment by mag** [comment] 2015-09-01 14:51
I don't see any shadow for Picture, which is surprising...probably because most of Android's rendering sub-system is already mocked out with Robolectric.

The easiest thing would be to shadow it. It should be straightforward to create a custom shadow and put it into your project.  If you're never done this, it's surprisingly easy: see http://robolectric.org/custom-shadows/ for more info.

If it works out, consider a pull request! Thanks.

**Comment by snooplsm** [comment] 2016-01-04 21:16
I went ahead and wrote a shadow, still can't get around this error though.

**Comment by jongerrish** [comment] 2016-01-04 21:20
Code for your shadow?

**Comment by snooplsm** [comment] 2016-01-04 21:21
https://gist.github.com/snooplsm/3d249f096e0ddacea41e

**Comment by jongerrish** [comment] 2016-01-04 21:24
Not sure, is it really calling the right constructor?

Try:-

public void __constructor__(int nativePicture, boolean fromStream) { }

public void __constructor__(long nativePicture) { }

**Comment by jongerrish** [comment] 2018-11-05 00:36
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

**Closed by jongerrish** 2018-11-05 00:36 UTC
