### ISSUE TITLE
Increased test time with 3.1-SNAPSHOT

### ISSUE THREAD

**Issue by NicoloParolini** [robolectric/robolectric#2328] opened 2016-03-08 11:52 UTC
I'm working on a large project with around 3500 unit tests which is in the way of switching from 3.0 to 3.1 in order to be able to support API-23.

When I build on the API-21 branch with 3.0 the whole suite takes around 3 minutes, but after I switch to 3.1-SNAPSHOT and API-23 the test time rises to over 11 minutes. Same project, same machine (8 core MacMini).

Project is being built with Parallel mode on, 8 threads, no cap on test classes per thread.

Is this due to the different Shadow philosophy? Is there anything that could/should be done to gain some performance? This is a serious issue as older CI machines now fail building in the 60 minutes allotted window the same project they were building in 10.

Thank you

**Comment by mag** [comment] 2016-03-08 15:28
That's really interesting, thanks for pointing this out. I am trying to get 3.1-RC out the door and will play with API-23 as I test it against my project's test suite. I don't have any good ideas why things are so much slower :(

**Comment by jongerrish** [comment] 2016-03-08 15:36
Not sure why it is slower, can you profile your build?

**Comment by NicoloParolini** [comment] 2016-03-08 16:02
When running with --profile it just says almost all the time (>95%) is taken by testDevDebugUnitTest task, which is the test runner for that build. Is there any builtin utility to profile each test (short from manually run them one by one)?

**Comment by NicoloParolini** [comment] 2016-03-09 09:55
When running with --profile it just says almost all the time (>95%) is taken by testDevDebugUnitTest task, which is the test runner for that build. Is there any builtin utility to profile each test (short from manually run them one by one)?

**Comment by NicoloParolini** [comment] 2016-03-09 10:19
Update on this issue. I profiled one of the tests which was taking unusually long time to execute and discovered that ActivityController.visible() was taking 20 seconds to execute. Close second was View.findViewWithTag() with 13 seconds. Both methods take less than a second while running on Robolectric 3.0.

**Comment by srsudar** [comment] 2016-03-19 00:01
3.1-SNAPSHOT is much slower than 3.0 for me as well. Perhaps related, I can't run all my tests because I get Out of Memory errors. If I run test classes individually they pass. When I revert to 3.0 the tests are much faster (haven't timed them), but unfortunately I'm not able to explore the differences in detail as I am extensively using `DatePicker` so the tests fail when on 3.0.

**Comment by srsudar** [comment] 2016-03-19 03:59
Here is an example trace of the memory errors I am seeing. They appear to be related to layout and drawing, as this trace suggests. I sometimes see them associated with `sorry, not yet implemented` errors. Rerunning them they eventually pass, typically on the very next run. I'm inflating both `DatePicker` widgets and custom views in numerous places throughout the app.

(If people think this should be a separate issue and I shouldn't be piggybacking these comments on this one, happy to move it.)

```

java.lang.OutOfMemoryError: Java heap space
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2451)
	at java.lang.Class.getDeclaredMethod(Class.java:1954)
	at org.robolectric.shadows.ShadowView.scrollTo(ShadowView.java:430)
	at android.view.View.scrollTo(View.java)
	at android.widget.TextView.onMeasure(TextView.java:6700)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
	at android.view.View.measure(View.java:17430)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1260)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at android.widget.ScrollView.onMeasure(ScrollView.java:337)
	at android.view.View.measure(View.java:17430)
```

**Comment by NicoloParolini** [comment] 2016-03-19 09:06
I've had the same problem with memory consumption as well. A workaround solution is to use **forkEvery=X** parameter in your test configuration. This will force your process to restart after X test classes, thus freeing the memory and allowing your tests to pass. As you remark, this is not needed on 3.0.

**Comment by srsudar** [comment] 2016-03-19 21:25
Where do you set that value? I've tried adding:

```
    testOptions.unitTests.all {
        forkEvery = 5
    }
```
to my `android` closure in my `build.gradle` as suggested [here](https://discuss.gradle.org/t/running-unit-tests-with-android-plugin-in-parallel-mode-causes-error-while-reading-dependencies/15060) but it doesn't seem to make a difference, even turning it down as low as `1`.

**Comment by NicoloParolini** [comment] 2016-03-21 21:10
Do you have you tests in several classes or is it only one class? The purpose of thissetting is to limit the number of test classes run by a single thread before it is killed, so if just one test class is killing your machine you should consider breaking it up instead as this setting won't help you.

**Comment by srsudar** [comment] 2016-03-21 22:32
Multiple classes. Is this the correct place for it in the app's build.gradle?

```
android {
    [snip]
    testOptions.unitTests.all {
        forkEvery = 1
    }
}
```

**Comment by NicoloParolini** [comment] 2016-03-21 22:51
Yes. Can you check the size of your Java heap? Might be it is a little small? 2GB should be enough for running your tests.

**Comment by jongerrish** [comment] 2016-03-21 23:18
Use a Java profiler like YourKit or JProfiler, need to see more detail
rather than top level tasks.

Capture a trace both for timing and for heap usage.

The only thing that strategy wise changed could have been the invoke
dynamic / intrinsic feature added a few months ago and this can be turned
off with a system property.

**Comment by karlicoss** [comment] 2016-03-27 13:27
I confirm that. Just tried running my codebase (about 1000 tests) against 3.1-SNAPSHOT, it ended up consuming all of my CPU and some tests crashed due to out of memmory error.

@jongerrish I don't think invokedynamic is to blame, I was using snapshot cut at 2b83b7e (which is two commits after this invokedynamic thing) for about three month without any problems.

**Comment by srsudar** [comment] 2016-04-19 14:58
This remains an issue for me with `3.1-SNAPSHOT`.

**Comment by mountaineer** [comment] 2016-05-11 00:12
Seeing this issue on 3.1-rc1 as well.

**Comment by srsudar** [comment] 2016-05-11 00:18
I messed around with profilers for an hour or so  back in Mar/Apr and wasn't able to get them working to the point of figuring something out. If someone wants a project that exhibits this behavior I can point them to the repo (haven't had a reason to upload it yet, but happy to do so).

**Comment by vgrichina** [comment] 2016-05-17 23:48
For us upgrading from 3.1-rc1 to 3.0 increases test time in Gradle with Java 7  **from 2 minutes to 50 minutes**, i.e. 25x. Something is going **very** wrong here. Turning off invokedynamic explicitly doesn't seem to help.

**Comment by jongerrish** [comment] 2016-05-17 23:51
Again, it only really helps if you can include some profiling data with the issue.

**Comment by srsudar** [comment] 2016-05-18 01:18
Unfortunately I have no experience with profilers and wasn't able to get profile data. When I tried, the profiler seemed to be changing the behavior of the tests. I'm afraid I don't remember the specifics now.

I would consistently get out of memory errors. The guilty tests did appear to be associated with views, as suggested by @NicoloParolini when saying that `View.findViewWithTag()` was a culprit.

[This is the repo](https://github.com/srsudar/MamasDelRioAndroid) against which I was running tests.

**Comment by NicoloParolini** [comment] 2016-05-18 08:26
@vgrichina have a look at your code and see if you have some ActivityController.visible() which you do not need. We did that in our project, removed quite a lot of them and test time is back to acceptable values (i.e. 25% more than 3.0). Making activities visible seems to take almost 20x the time it took for 3.0.

**Comment by jvanderwee** [comment] 2016-05-24 12:10
Anyone else's builds taking even longer on 3.1-SNAPSHOT since May 19?

**Comment by bradley-curran** [comment] 2016-06-16 12:27
I've taken over the project @NicoloParolini was on (Googling the issue brought me here haha). 

I've attempted to upgrade to [3.1 proper](https://github.com/robolectric/robolectric/releases/tag/robolectric-3.1) but test time has blown out even more! It's been 20+ minutes and the tests still haven't completed. 

Honestly I'm thinking of moving our tests away from Robolectric. This isn't sustainable.

**Comment by jongerrish** [comment] 2016-06-16 14:32
Yes there is a fix for this in https://github.com/robolectric/robolectric/commit/72378b424407becc3506ef05ce4f12ecd0ff3723
@erd could we cut a 3.1.1 or 3.1.01 with this fix in it?

**Comment by saadfarooq** [comment] 2016-06-28 17:24
What's the ETA on 3.1.1? Need the fix badly.

**Comment by jongerrish** [comment] 2016-06-30 09:50
I'l try and push a release tomorrow, I'm on vacation sorry.

**Comment by saadfarooq** [comment] 2016-06-30 16:25
Thanks @jongerrish, much appreciated

**Comment by saadfarooq** [comment] 2016-07-02 04:52
@jongerrish I saw there was a new Snapshot today, but it was 3.2-gradle-SNAPSHOT and doesn't seem to work the same as 3.2-SNAPSHOT.

**Comment by saadfarooq** [comment] 2016-07-06 18:10
@jongerrish any update on 3.1.1 or snapshot?

**Comment by saadfarooq** [comment] 2016-07-08 17:12
The latest snapshot fixes this. 

Also, for anyone stumbling here, we found that the problem goes away in at least java version 1.8.0_65 and higher. Running on java 1.8.0_25 took 40 minutes for us. Running on java 1.8.0_65 took 5 minutes.

**Comment by jongerrish** [comment] 2016-07-08 17:26
@xian Probably why our JDK8 builds are around 50% slower than JDK7 builds. Travis reports using build 1.8.0_31-b13

**Comment by jongerrish** [comment] 2016-07-12 21:45
Robolectric 3.1.1 has been released including the fix for this performance
regression, please let me know how it goes.

Thanks, Jonathan

**Comment by saadfarooq** [comment] 2016-07-13 19:25
@jongerrish The update works as expected. However, if we update the version numbers of the entire robolectric family, we get these errors.

Error:Module 'org.robolectric:shadows-play-services:3.1.1' depends on one or more Android Libraries but is a jar
Error:Conflict with dependency 'com.google.guava:guava'. Resolved versions for app (19.0-rc2) and test app (19.0) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Error:Module 'org.robolectric:shadows-multidex:3.1.1' depends on one or more Android Libraries but is a jar

The second of these, of course, is a consequence of us using Guava in our main app and can be fixed with the ignore blocks. The other two I'm unsure about. Is this as intended?

**Comment by felipecsl** [comment] 2016-07-18 21:52
I'm getting the same error as @saadfarooq, app won't build:
```
Module 'org.robolectric:shadows-multidex:3.1.1' depends on one or more Android Libraries but is a jar
```

**Comment by felipecsl** [comment] 2016-07-18 21:54
BTW still having heavy performance degradation with 3.1.1

**Comment by jongerrish** [comment] 2016-07-19 00:48
I think these should be fixed at head. We can push another release (3.1.2)
this week if it helps?

For the performance degradation, some more profiling info would be helpful.

We do really care about performance and will dedicate a couple of sprints
to it soon, but specifics from your case would be helpful.

**Comment by kevineder** [comment] 2016-07-25 17:24
Another release to address this would be much appreciated @jongerrish

**Comment by felipecsl** [comment] 2016-08-08 17:48
Still experiencing this degradation with version 3.1.2

**Comment by jongerrish** [comment] 2016-08-08 21:39
If you could include some profiling data / heap dumps it would be helpful.

**Comment by menny** [comment] 2016-10-25 17:24
@jongerrish what kind of data are you looking for?

**Comment by jongerrish** [comment] 2018-11-05 00:51
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

FWIW binary resource support in Robolectric 4.0 should improve performance and memory usage

**Closed by jongerrish** 2018-11-05 00:51 UTC
