### ISSUE TITLE
Robolectric test hangs up when started - Transferring from sonatype

### ISSUE THREAD

**Issue by KonradSzewczuk** [robolectric/robolectric#3452] opened 2017-10-16 07:41 UTC
### Description
I have a problem with configuring Robolectric in my project. I am also using Kotlin, if it matters.
When i run the test, it hangs up and on the console appears message:

> Downloading: org/robolectric/android-all/o-preview-4-robolectric-0/android-all-o-preview-4-robolectric-0.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/ Transferring 68498K from sonatype

I was waiting for about 10-15 minutes and still nothing.
### Steps to Reproduce
Here is my build.gradle
```groovy
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

android {
compileSdkVersion 26


testOptions {
    unitTests {
        includeAndroidResources = true
    }
}
sourceSets {
    test.java.srcDirs += ['build/generated/source/apt/test/debug']
}

defaultConfig {
    minSdkVersion 15
    targetSdkVersion 26
    versionCode 1
    versionName "1.0"

    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

}

buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
}

ext.daggerVersion = '2.11'
ext.roomVersion = '1.0.0-alpha9'

dependencies {
implementation fileTree(dir: 'libs', include: ['*.jar'])
implementation 'com.android.support:appcompat-v7:26.1.0'

kaptTest "com.google.dagger:dagger-compiler:$daggerVersion"
testImplementation 'junit:junit:4.12'
testImplementation "org.robolectric:robolectric:3.4.2"
androidTestImplementation('com.android.support.test.espresso:espresso-core:3.0.1', {
    exclude group: 'com.android.support', module: 'support-annotations'
})
compile "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"

// RxJava
implementation 'io.reactivex.rxjava2:rxjava:2.1.0'
implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'

// Room
implementation "android.arch.persistence.room:runtime:$roomVersion"
implementation "android.arch.persistence.room:rxjava2:$roomVersion"
kapt "android.arch.persistence.room:compiler:$roomVersion"
compile "org.jetbrains.kotlin:kotlin-stdlib:1.1.51"
androidTestImplementation "android.arch.persistence.room:testing:$roomVersion"

//DAGGER
implementation "com.google.dagger:dagger:$daggerVersion"
implementation "com.google.dagger:dagger-android:$daggerVersion"
implementation "com.google.dagger:dagger-android-support:$daggerVersion"
kapt "com.google.dagger:dagger-compiler:$daggerVersion"
kapt "com.google.dagger:dagger-android-processor:$daggerVersion"

//Jackson
implementation 'com.fasterxml.jackson.core:jackson-core:2.9.1'
implementation 'com.fasterxml.jackson.core:jackson-annotations:2.9.0'
implementation 'com.fasterxml.jackson.core:jackson-databind:2.9.1'
}

repositories {
mavenCentral()
}
```

**Comment by oksett** [comment] 2017-10-16 10:26
I was waiting 30 minutes till it was downloaded. I also tried this on version 3.0 - was the same issue, but donwloaded slightly faster. 
But still is there a way to make it quicker? In the beginning i thought that it was an issue.

Issue can be closed

**Comment by jongerrish** [comment] 2017-10-16 19:17
I'm not sure. We use the Ant APIs for downloading the jars, ideally we
wouldn't download them at all.

You can configure Robolectric to use jars that you check in to your project
or otherwise store locally too if that helps?

**Comment by nirrottenberg** [comment] 2018-01-14 13:23
Hi, I have a similar problem with robolectric tests. When my CircleCi build gets to the step where it starts running robolectric tests, I get the following messages:

**Comment by KonradSzewczuk** [comment] 2018-01-14 13:51
@nirrottenberg It was really bad, but i was just waiting... It finally downloaded files like after 20-30 minutes. unfortunately.

**Comment by Glyd** [comment] 2018-02-09 16:59
Currently 1h30m+ into the download, nothing happened just yet and doesn't seem like it's doing anything. 

Internet speed is fine, but still hanging on: 

`Transferring 69884K from sonatype`

**Comment by dekzitfz** [comment] 2018-02-21 09:09
I'm here for this issue also, stuck on `Transferring 106949K from sonatype`

**Comment by hdrdavies** [comment] 2018-03-27 08:09
`Transferring 98508K from sonatype` :(

**Comment by sanat51289** [comment] 2018-05-05 09:59
I had similar issue on one of my CI servers where Robolectric would try to download all these dependencies:
`android-all/8.1.0-robolectric-r4458339/android-all-8.1.0-robolectric-r4458339.pom`
`android-all/7.1.0_r7-robolectric-0/android-all-7.1.0_r7-robolectric-0.pom`

And then would fail during one of the jar downloads by saying 
`Error transferring file: java.security.ProviderException: Could not derive key`

The way i fixed it was by forcing Robolectric to use only SDK 21 for all of my tests. Here's how it looked like:

```
android {
  testOptions {
    unitTests.all {
      systemProperty 'robolectric.enabledSdks', '21'
    }
  }
}
```

Saw this block from Robolectric website itself
http://robolectric.org/configuring/

**Comment by qwertyfinger** [comment] 2018-11-10 12:13
I had the same problem on several machines, although my tests had finally ran eventually. All subsequent tests run perfectly fine.
I don't know the time for the first machine, it was probably something like 10-15 min, maybe more.
For the second one it was up to 9 min.
Interestingly, tests on CI servers ran quickly from the first time.
Also, the fix above didn't eliminate the issue for me.

**Comment by erdeanmich** [comment] 2019-05-17 15:34
Hi guys, I had the same issue and managed to solve it in my case.
In my build.gradle I had set: 
`
testOptions{
        unitTests.includeAndroidResources = true
    }
`

And I noticed that the test runs without this option (maybe this should work out for some of you too), but I needed it for my test. 

After adding the line `android.enableUnitTestBinaryResources=true` to my gradle.properties the test runs like a charm. 

It's a very case-specific solution but maybe it can help some of you.

**Comment by guilhermesgb** [comment] 2020-02-21 16:42
Hello everyone, I'm also having the same issue where it took a long time for the download to finish. After it finished, I still didn't get to pass this 'hang up' stage, though - I keep stuck seeing this forever:

```
[Robolectric] <mypackage>.testInsert: sdk=29; resources=BINARY
Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=29
```

The same project is running fine on my work laptop.

I'm also seeing these warnings before the input above (that's showing up also on my work laptop even though there the tests are running) and I don't know if might be related and what's causing it either:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.robolectric.util.ReflectionHelpers$6 (file:/home/xibaca/.gradle/caches/modules-2/files-2.1/org.robolectric/shadowapi/4.3.1/a93e55b36c418aa3afc17c26eac82590a3bfb63e/shadowapi-4.3.1.jar) to method java.lang.ClassLoader.getPackage(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.robolectric.util.ReflectionHelpers$6
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Any thoughts? Thanks in advance for your time!

**Comment by dryaz** [comment] 2020-03-10 17:12
Potentially it's a network latency/connection issues depends on country or other network issues.
Had the same problem and network monitor shows ~200kbs network download activity.

After enabling VPN it shows ~100Mbs network activity and takes several seconds to download from sonatype.

**Comment by djubreel** [comment] 2020-04-07 13:35
Totally agree with @dryaz , switched my internet and it was done in no time.

**Comment by MFrat** [comment] 2020-05-30 22:09
Is there a official solution for this?

**Comment by lamster2018** [comment] 2020-07-20 07:42
same issue ,and  i just wait for over 30 minutes, some one can help me?

**Comment by hoisie** [comment] 2020-07-20 14:43
The 'Transferring from sonatype message' is how the Android Framework Jars are loaded during runtime from maven (https://repo1.maven.org/maven2/org/robolectric/android-all/). This is by design. Each Android framework JAR ranges in size from 25-120MB, I believe. If you have a slow internet connection it can take a while, unfortunately. Once a single android-all.jar is downloaded, it should be cached in the local maven repo and you shouldn't need to download it again.

I suppose you could pre-install the android-all jars into your local maven cache if you want to avoid doing it during test runtime.

**Comment by xubiping** [comment] 2021-01-27 12:13
Internet speed is fine, but still hanging on:

**Comment by ZSmallX** [comment] 2021-02-27 10:25
Inspired by sanat51289, I found a way to specific the maven repository from Robolectric doc(http://robolectric.org/configuring/).

By setup the proxy or mirror maven repo, and change the systemProperty. It takes less time accessing the library from internal network.

```
android {
  testOptions {
    unitTests.all {
      systemProperty 'robolectric.dependency.repo.url', 'https://local-mirror/repo'
      systemProperty 'robolectric.dependency.repo.id', 'local'
    }
  }
}
```

**Comment by utzcoz** [comment] 2022-12-13 13:44
As https://github.com/robolectric/robolectric/issues/3452#issuecomment-661083699 said, it is as designed and you can download android-all or android-all preinstrumented libraries with proxy/maven mirror before running tests. Also anyone who has this issue can refer  https://github.com/robolectric/robolectric/issues/3452#issuecomment-787050366 as a workaround.

**Closed by utzcoz** 2022-12-13 13:44 UTC
