### ISSUE TITLE
Not compatible with android plugin 1.5.0's data binding

### ISSUE THREAD

**Issue by brianguertin** [robolectric/robolectric#2143] opened 2015-11-13 14:01 UTC
I'm using Robolectric 3.0 with the Android gradle plugin v1.5.0, with data binding enabled via:

``` groovy
android {
  dataBinding {
    enabled = true
  }
}
```

http://developer.android.com/tools/data-binding/guide.html

However, when trying to inflate any XML file that has `<layout>` as a top-level element, I get this error:

```
android.view.InflateException: XML file build/intermediates/res/merged/debug/layout/account.xml line #-1 (sorry, not yet implemented): Error inflating class layout
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:257)
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
    at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:276)
    at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:261)
    at com.example.activities.AccountActivity.onCreate(AccountActivity.java:46)
    at android.app.Activity.performCreate(Activity.java:5933)
    at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
    at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
    at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
    at org.robolectric.util.ActivityController.create(ActivityController.java:118)
    at org.robolectric.util.ActivityController.create(ActivityController.java:129)
    at org.robolectric.util.ActivityController.setup(ActivityController.java:210)
    at com.example.test.AccountActivityTest.setup(AccountActivityTest.java:35)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ClassNotFoundException: android.view.layout
    at org.robolectric.internal.bytecode.InstrumentingClassLoader.getByteCode(InstrumentingClassLoader.java:168)
    at org.robolectric.internal.bytecode.InstrumentingClassLoader.findClass(InstrumentingClassLoader.java:123)
    at org.robolectric.internal.bytecode.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:95)
    at android.view.LayoutInflater.createView(LayoutInflater.java:571)
    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:665)
    at org.robolectric.shadows.RoboLayoutInflater.onCreateView(RoboLayoutInflater.java:51)
    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
```

It appears robolectric is trying to inflate the `<layout>` tag as if it were a custom view class.

**Comment by brianguertin** [comment] 2015-11-13 14:03
This was previously working when using Android gradle plugin 1.3.0 with the databinding library from the support repository
```groovy
dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
        classpath 'com.android.databinding:dataBinder:1.0-rc3'
}
```

**Comment by yigit** [comment] 2015-12-10 22:47
Looks like Robolectric is not reading the correct merged resource directory. 
DataBinding updates merge resources target directory so that it can inject an incremental task to update layout files. Seems like Robolectric is reading the previous version.

This behavior is changed in Android Gradle Plugin 1.5. Before that, DataBinding would override the layout files so Robolectric was working fine but that behavior breaks incremental merge resources task.

The new location is this:
build/intermediates/data-binding-layout-out

But it may change any time so Robolectric should be reading it from the AndroidModel (if it is not doing so already).

**Comment by nicks** [comment] 2015-12-11 22:07
I submitted a pull request to fix this problem.

Until this is fixed in robolectric proper, you can workaround it by forking `RobolectricGradleTestRunner`, applying the fix in https://github.com/robolectric/robolectric/pull/2177, and replacing  `@RunWith(RobolectricGradleTestRunner.class)` with `@RunWith(MyTestRunner.class)`

**Comment by brianguertin** [comment] 2015-12-12 05:25
Thanks, the fix in `#2177` worked perfectly for me :+1:

**Comment by jakubkrolewski** [comment] 2016-01-22 16:14
Are there any plans for releasing a new version with this fix, or do I have to rely on snapshots?

**Comment by erd** [comment] 2016-01-22 18:53
Snapshots for now. We'll probably release 3.1 in the next few months.

**Comment by erikcaffrey** [comment] 2016-03-19 18:22
I have the same problem Is coming soon new releasing with this fix?

**Comment by agrosner** [comment] 2017-07-25 21:31
well it appears that on 3.0.0-alpha8 (or potentially other versions of 3.0.0), the databinding layout out only outputs resources from the layout directory that it corresponds to. so no longer is this a reliable method for determining where final resources are used. I applied suggestions from https://github.com/robolectric/robolectric/issues/3169. I noticed that strings were not loading properly. I debugged deep into the issue and found this line:
```java
if (FileFsFile.from(buildOutputDir, "data-binding-layout-out").exists()) {
      // Android gradle plugin 1.5.0+ puts the merged layouts in data-binding-layout-out.
      // https://github.com/robolectric/robolectric/issues/2143
      res = FileFsFile.from(buildOutputDir, "data-binding-layout-out", flavor, type);
    }
```
Looking at generated databinding-layout-out in 3.0+:
![screen shot 2017-07-25 at 5 27 21 pm](https://user-images.githubusercontent.com/2117859/28594599-9355f766-715e-11e7-8973-87897a778054.png)

It contains none of the other assets, thus preventing them from loading into tests, triggering the `java.lang.NoSuchMethodError: android.content.res.Resources$NotFoundException.<init>(Ljava/lang/String;Ljava/lang/Exception;)V`

Somehow either a merger of these two directories need to happen or from what I can see, the outputted files in `databinding-layout-out` are identical to the ones that are in `res/merged/debug/layout` directory.

**Comment by agrosner** [comment] 2017-07-25 21:37
lastly if theres a way to override this, without forking robolectric to test it out it let me know. thank you

**Comment by jongerrish** [comment] 2017-07-26 04:18
We're releasing 3.4 tomorrow, but the preferred method of running unit tests with Gradle is using the new build system API. While we'd accept pull requests for fixing the paths in GradleManifestFactory it is not something we're going to support long term (because with aapt2 + forthcoming namespaces the intermediate merged resources folders will no longer exist).

See here for instructions:- http://robolectric.org/getting-started/

You'll can remove you @Config(constants = BuildConfig.class) also.

**Closed by jongerrish** 2017-07-26 04:18 UTC

**Comment by agrosner** [comment] 2017-07-26 14:24
by following your steps, Robolectric actually utilizes the `MavenManifestFactory` which points the directories to the wrong location, thus when I need to load an asset, it causes:
```
java.lang.NullPointerException
	at org.robolectric.shadows.ShadowAssetManager.open(ShadowAssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java)
```
Which is due to null asset file. Not sure if I should report that here or in new ticket. I am running 3.4-rc5, but maybe full 3.4 fixes this issue?

**Comment by jongerrish** [comment] 2017-07-26 15:02
Interesting, this suggests that you don't have /com/android/tools/test_config.properties on the classpath - can you confirm that?

You have your gradle config set up like this:-

testCompile "org.robolectric:robolectric:3.3.4_rc5"

android {
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}

**Comment by agrosner** [comment] 2017-07-26 18:48
I do not believe so. So I just need to add that file somewhere in my project?

**Comment by agrosner** [comment] 2017-07-28 16:08
@jongerrish is this something that the build system generates, or something we will now have to specify?

**Comment by waqas35** [comment] 2017-07-31 09:13
i am facing this error:
android.view.InflateException: XML file build\intermediates\data-binding-layout-out\debugTest\layout\activity_map.xml line #-1 (sorry, not yet implemented): XML file build\intermediates\data-binding-layout-out\debugTest\layout\layout_confirm_location.xml line #-1 (sorry, not yet implemented): Error inflating class Button
	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at com.project.activity.SliderActivity.setContentView(SliderActivity.java:400)

Gradle version: 2.3.3
robolectricVerion = '3.3.2'

can any one help!

**Comment by jongerrish** [comment] 2017-08-01 00:42
@agrosner - The build system generates this file but it doesn't look like it is doing in Alpha 8 which is why Robolectric falls back to alternatives. I've converted Deckard to use the new integration and seeing the same issue you are.... I'll follow up:-

https://github.com/robolectric/deckard/tree/build_with_as3.0

**Comment by jongerrish** [comment] 2017-08-01 00:43
@waqas35 We'll need a full stack trace to have any idea what is going on there.

**Comment by waqas35** [comment] 2017-08-01 05:53
@jongerrish thanks for the reply. here is the full stask trace

android.view.InflateException: XML file build\intermediates\data-binding-layout-out\debugTest\layout\activity_map.xml line #-1 (sorry, not yet implemented): XML file build\intermediates\data-binding-layout-out\debugTest\layout\layout_location_confirm.xml line #-1 (sorry, not yet implemented): Error inflating class Button
	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at com.careem.acma.activity.SliderActivity.setContentView(SliderActivity.java:400)
	at com.careem.acma.activity.MapActivity.onCreate(MapActivity.java:73)
	at android.app.Activity.performCreate(Activity.java:6251)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:231)
	at org.robolectric.android.controller.ActivityController$1.run(ActivityController.java:140)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:362)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:137)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:147)
	at org.robolectric.android.controller.ActivityController.setup(ActivityController.java:245)
	at com.careem.acma.activity.BaseActivityTests.initActivity(BaseActivityTests.java:24)
	at
 com.careem.acma.activity.MapActivityTest.testIfActivityFinishes_onConfirmLocation(MapActivityTest.java:88)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:488)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:209)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: android.view.InflateException: XML file build\intermediates\data-binding-layout-out\debugTest\layout\layout_location_confirm.xml line #-1 (sorry, not yet implemented): Error inflating class Button
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:831)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	... 50 more
Caused by: android.content.res.Resources$NotFoundException: File build\intermediates\data-binding-layout-out\debugTest\drawable-v21\selector_default.xml from drawable resource ID #0x7f0203d7
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2640)
	at android.content.res.Resources.loadDrawable(Resources.java:2540)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:231)
	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:57)
	at org.robolectric.shadow.api.Shadow.directlyOn(Shadow.java:55)
	at org.robolectric.shadows.ShadowResources.loadDrawable(ShadowResources.java:240)
	at android.content.res.Resources.loadDrawable(Resources.java)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
	at android.view.View.__constructor__(View.java:3954)
	at android.view.View.<init>(View.java)
	at android.widget.TextView.<init>(TextView.java)
	at android.widget.Button.<init>(Button.java)
	at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:109)
	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
	... 59 more
Caused by: org.xmlpull.v1.XmlPullParserException: XML file build\intermediates\data-binding-layout-out\debugTest\drawable-v21\selector_default.xml line #-1 (sorry, not yet implemented): <item> tag requires a 'drawable' attribute or child tag defining a drawable
	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:250)
	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:164)
	at android.graphics.drawable.RippleDrawable.inflate(RippleDrawable.java:421)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1215)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1124)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2630)

**Comment by soutoss** [comment] 2017-10-22 19:27
@waqas35 facing the same error. Did you manage to solve this problem?
