### ISSUE TITLE
android.view.InflateException: XML file build\intermediates\res\merged\debug\layout\activity_login.xml line #-1 (sorry, not yet implemented): Error inflating class EditText

### ISSUE THREAD

**Issue by YanYanLun** [robolectric/robolectric#2583] opened 2016-07-27 08:09 UTC
### Robolectric：3.1.1 & Android Version sdk 23

When I Runing this Test ，have this questions

android.view.InflateException: XML file build\intermediates\res\merged\debug\layout\activity_login.xml line #-1 (sorry, not yet implemented): Error inflating class EditText

	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:257)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
	at com.sparxo.checkin.activity.LoginActivity.onCreate(LoginActivity.java:55)
	at android.app.Activity.performCreate(Activity.java:5990)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:126)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:340)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
	at org.robolectric.util.ActivityController.create(ActivityController.java:123)
	at org.robolectric.util.ActivityController.create(ActivityController.java:133)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:227)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:96)
	at com.sparxo.checkin.activity.LoginActivityTest.setUp(LoginActivityTest.java:42)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:248)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:174)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:63)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:140)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NumberFormatException: For input string: "@0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:128)
	at android.content.res.TypedArray.getInt(TypedArray.java:322)
	at android.widget.TextView.__constructor__(TextView.java:1051)
	at android.widget.TextView.<init>(TextView.java)
	at android.widget.EditText.<init>(EditText.java)
	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java)
	at android.support.v7.internal.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:104)
	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:926)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:980)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
	... 41 more

I don't know how to solve,please help

**Comment by YanYanLun** [comment] 2016-07-27 08:10
@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class)
public class LoginActivityTest {
    private EditText mEmailView;
    private EditText mPasswordView;
    private TextView mEmailSignInButton;
    private EventSelectionFragment sampleFragment;
    private LoginActivity activity;

    @Before
    public void setUp() {
        activity = Robolectric.setupActivity(LoginActivity.class);
        mEmailSignInButton = (TextView) activity.findViewById(R.id.email_sign_in_button);
        mEmailView = (EditText) activity.findViewById(R.id.email);
        mPasswordView = (EditText) activity.findViewById(R.id.password);
//        sampleFragment = new EventSelectionFragment();
//        //此api可以主动添加Fragment到Activity中，因此会触发Fragment的onCreateView()
//        SupportFragmentTestUtil.startFragment(sampleFragment);
    }

    //邮箱输入为空验证
    @Test
    public void testEmailNull() {
        mEmailView.setText("");
        mPasswordView.setText("");
        mEmailSignInButton.performClick();
        Log.i("testEmailNull", "This field is required");
        assertEquals("This field is required", mEmailView.getError().toString());
    }
｝

**Comment by jongerrish** [comment] 2016-07-27 16:48
I'm pretty sure this is a duplicate of https://github.com/robolectric/robolectric/issues/2520

**Closed by jongerrish** 2016-07-27 16:48 UTC

**Comment by YanYanLun** [comment] 2016-07-29 03:12
I read the above answer, but still can not solve my problem, I project in the SDK is 23

**Comment by YanYanLun** [comment] 2016-07-29 03:27
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:design:23.3.0'
    compile 'com.zplesac:connectionbuddy:+'
    compile 'com.daimajia.androidanimations:library:1.1.3@aar'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.daimajia.easing:library:1.0.1@aar'
    compile 'com.dlazaro66.qrcodereaderview:qrcodereaderview:1.0.0'
    compile 'com.mcxiaoke.volley:library:1.0.19'
    compile 'com.google.code.gson:gson:2.2.+'
    compile 'com.androidadvance:topsnackbar:0.0.9'
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
    compile 'com.daimajia.swipelayout:library:1.2.0@aar'
    compile 'com.tencent.bugly:crashreport:2.1.3'
   
    // Unit test
    testCompile 'junit:junit:4.12'
    testCompile('org.robolectric:robolectric:3.1.1') {
        exclude module: 'commons-logging'
    }
}

**Comment by spacemase** [comment] 2017-02-17 05:21
This is not a duplicate of #2520.

**Comment by UmeshChakre** [comment] 2019-12-03 16:52
did anyone get solution??
