### ISSUE TITLE
activity.recreate() causes java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by hazems** [robolectric/robolectric#3095] opened 2017-05-16 03:41 UTC
### Description
After upgrading from Robolectric 3.0 to Robolectric 3.3.2, running the following simple test.

```
@RunWith(RobolectricTestRunner.class)
public class Test1 {

    private ActivityController<MyActivity> controller;
    private MyActivity activity;

    @Override
    protected void setUpTest() throws Exception {
        controller = Robolectric.buildActivity(MyActivity.class);
    }

    @After
    public void tearDown() {
        controller.destroy();
    }

    private void createWithIntent() {
        Intent intent = new Intent(RuntimeEnvironment.application, MyActivity.class);
        Bundle extras = new Bundle();
        intent.putExtras(extras);
        activity = controller
                .create()
                .start()
                .visible()
                .get();
    }

    @Test
    public void recreatesActivity() {
        createWithIntent();
        activity.recreate();
    }
}
```
Produces the following java.lang.RuntimeException: java.lang.reflect.InvocationTargetException exception.

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

	at org.robolectric.shadows.ShadowActivity$ActivityInvoker.with(ShadowActivity.java:589)
	at org.robolectric.shadows.ShadowActivity.recreate(ShadowActivity.java:524)
	at android.app.Activity.recreate(Activity.java)
	at com.test.ui.activities.MyActivity.recreatesActivity(MyActivity.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:488)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:209)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.shadows.ShadowActivity$ActivityInvoker.with(ShadowActivity.java:587)
	... 34 more
Caused by: java.lang.NullPointerException
	at android.widget.AbsListView$RecycleBin.getScrapView(AbsListView.java:6495)
	at android.widget.AbsListView.obtainView(AbsListView.java:2343)
	at android.widget.ListView.makeAndAddView(ListView.java:1864)
	at android.widget.ListView.fillDown(ListView.java:698)
	at android.widget.ListView.fillFromTop(ListView.java:759)
	at android.widget.ListView.layoutChildren(ListView.java:1673)
	at android.widget.AbsListView.onLayout(AbsListView.java:2148)
	at android.view.View.layout(View.java:15596)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15596)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15596)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15596)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15596)
	at android.view.ViewGroup.layout(ViewGroup.java:4966)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2072)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1829)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:165)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:31)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:126)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:313)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:152)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:141)
	at org.robolectric.shadows.ShadowMessageQueue.enqueueMessage(ShadowMessageQueue.java:147)
	at android.os.MessageQueue.enqueueMessage(MessageQueue.java)
	at android.os.Handler.enqueueMessage(Handler.java:631)
	at android.os.Handler.sendMessageAtTime(Handler.java:600)
	at android.os.Handler.sendMessageDelayed(Handler.java:570)
	at android.os.Handler.postDelayed(Handler.java:398)
	at org.robolectric.shadows.ShadowChoreographer.postCallbackDelayed(ShadowChoreographer.java:49)
	at android.view.Choreographer.postCallbackDelayed(Choreographer.java)
	at android.view.Choreographer.postCallback(Choreographer.java:291)
	at android.view.ViewRootImpl.scheduleTraversals(ViewRootImpl.java:1025)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:869)
	at android.view.View.requestLayout(View.java:17364)
	at org.robolectric.internal.bytecode.ProxyMaker$GeneratedProxy/936618636.requestLayout(Unknown Source)
	at org.robolectric.shadows.ShadowView.requestLayout(ShadowView.java:234)
	at android.view.View.requestLayout(View.java)
	at android.view.View.requestLayout(View.java:17364)
	at org.robolectric.internal.bytecode.ProxyMaker$GeneratedProxy/936618636.requestLayout(Unknown Source)
	at org.robolectric.shadows.ShadowView.requestLayout(ShadowView.java:234)
	at android.view.View.requestLayout(View.java)
	at android.view.View.requestLayout(View.java:17364)
	at org.robolectric.internal.bytecode.ProxyMaker$GeneratedProxy/936618636.requestLayout(Unknown Source)
	at org.robolectric.shadows.ShadowView.requestLayout(ShadowView.java:234)
	at android.view.View.requestLayout(View.java)
	at android.view.View.requestLayout(View.java:17364)
	at org.robolectric.internal.bytecode.ProxyMaker$GeneratedProxy/936618636.requestLayout(Unknown Source)
	at org.robolectric.shadows.ShadowView.requestLayout(ShadowView.java:234)
	at android.view.View.requestLayout(View.java)
	at android.view.View.requestLayout(View.java:17364)
	at org.robolectric.internal.bytecode.ProxyMaker$GeneratedProxy/936618636.requestLayout(Unknown Source)
	at org.robolectric.shadows.ShadowView.requestLayout(ShadowView.java:234)
	at android.view.View.requestLayout(View.java)
	at android.widget.AbsListView.requestLayout(AbsListView.java:1975)
	at android.widget.ListView.onFocusChanged(ListView.java:3597)
	at android.view.View.handleFocusGainInternal(View.java:4938)
	at android.view.ViewGroup.handleFocusGainInternal(ViewGroup.java:632)
	at android.view.View.requestFocusNoSearch(View.java:7648)
	at android.view.View.requestFocus(View.java:7627)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2618)
	at android.view.View.requestFocus(View.java:7594)
	at android.view.View.requestFocus(View.java:7573)
	at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:2858)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:679)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:679)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:679)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:679)
	at android.view.View.setFlags(View.java:9603)
	at android.view.View.setFocusableInTouchMode(View.java:6741)
	at android.widget.AdapterView.checkFocus(AdapterView.java:722)
	at android.widget.ListView.setAdapter(ListView.java:488)
	at com.test.ui.activities.MyActivity.setMyListView(MyActivity.java:106)
	at com.test.ui.activities.MyActivity.onCreate(MyActivity.java:89)
	at org.robolectric.shadows.ShadowActivity$ActivityInvoker.with(ShadowActivity.java:587)
	at org.robolectric.shadows.ShadowActivity.recreate(ShadowActivity.java:524)
	at android.app.Activity.recreate(Activity.java)
	at com.test.ui.activities.MyActivity.recreatesActivity(MyActivity.java:68)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:488)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:209)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	... 1 more
```

### Steps to Reproduce
Just run my test above.

### Robolectric & Android Version
Robolectric 3.3.2 and Android targetSdkVersion 25.

**Comment by kageiit** [comment] 2017-07-13 23:03
Can confirm. We are seeing this flake our tests on as well

```
Caused by: java.lang.NullPointerException
	at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:2005)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2058)
	at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:2694)
	at android.support.v4.app.FragmentController.saveAllState(FragmentController.java:125)
	at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:571)
	at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:509)
	at org.robolectric.shadows.ShadowActivity$ActivityInvoker.with(ShadowActivity.java:587)
	at org.robolectric.shadows.ShadowActivity.recreate(ShadowActivity.java:516)
	at android.app.Activity.recreate(Activity.java)
	at android.support.v7.app.AppCompatDelegateImplV14.updateForNightMode(AppCompatDelegateImplV14.java:208)
	at android.support.v7.app.AppCompatDelegateImplV14.applyDayNight(AppCompatDelegateImplV14.java:94)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:74)
	at org.robolectric.shadows.ShadowActivity$ActivityInvoker.with(ShadowActivity.java:587)
	at org.robolectric.shadows.ShadowActivity.recreate(ShadowActivity.java:524)
	at android.app.Activity.recreate(Activity.java)
	at android.support.v7.app.AppCompatDelegateImplV14.updateForNightMode(AppCompatDelegateImplV14.java:208)
	at android.support.v7.app.AppCompatDelegateImplV14.applyDayNight(AppCompatDelegateImplV14.java:94)
	at android.support.v7.app.AppCompatDelegateImplV14.onStart(AppCompatDelegateImplV14.java:113)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:179)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
	at android.app.Activity.performStart(Activity.java:5949)
	at org.robolectric.util.ReflectionHelpers$6.run(ReflectionHelpers.java:198)
	at org.robolectric.util.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:341)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:192)
	at org.robolectric.android.controller.ComponentController$1.run(ComponentController.java:75)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:362)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
	at org.robolectric.android.controller.ComponentController.invokeWhilePaused(ComponentController.java:72)
	at org.robolectric.android.controller.ActivityController.start(ActivityController.java:161)
	at org.robolectric.android.controller.ActivityController.setup(ActivityController.java:245)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:97)
```

**Comment by kageiit** [comment] 2017-09-15 22:18
This is happening on 3.4.2 as well. cc @jongerrish @xian

**Comment by xian** [comment] 2017-10-19 21:54
I'm able to reproduce this when I use a layout containing a fragment. Investigating, sorry for the delay!

```java
  @Test
  public void testRecreate() throws Exception {
    Robolectric.setupActivity(MyActivity.class).recreate();
  }

  public static class MyActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
      setContentView(R.layout.fragment_activity);
    }
  }
```

**Comment by xian** [comment] 2017-10-19 22:09
Per @kageiit, this is likely due to a race condition and happens about 5% of the time.

**Comment by nguyentruongtho** [comment] 2018-03-07 13:48
This is still happening on `3.7.1`, support-v4: `27.0.2`:

```
Caused by: java.lang.NullPointerException
	at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:2180)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2233)
	at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:2905)
	at android.support.v4.app.FragmentController.saveAllState(FragmentController.java:125)
```

**Comment by nguyentruongtho** [comment] 2018-03-07 15:56
Looking at the stacktrace, we can see that night mode has change from the first call to `Activity#recreate` to the second one to the same method. I suspect this issue caused when system clock just changed from DAY to NIGHT time, and night mode is set to AUTO.

**Comment by rahul-narkhede** [comment] 2019-10-01 15:53
This also happens on Robolectric 4.2 when androidx appcompat 1.1.0 is used.  Any ideas on how to fix?

**Comment by rahul-narkhede** [comment] 2019-10-10 14:08
Any ETA on the fix for this lifecycle problem?

**Comment by hoisie** [comment] 2020-10-20 22:41
I believe the fix for this is to use the new PAUSED looper mode.

**Closed by hoisie** 2020-10-20 22:41 UTC
Labels: defect, scheduler

**Comment by hiqua** [comment] 2021-02-18 16:52
For those like me who ended up on this issue while looking it up, see:
http://robolectric.org/blog/2019/06/04/paused-looper/
