### ISSUE TITLE
building a library of custom shadows

### ISSUE THREAD

**Issue by edwinvanderham** [robolectric/robolectric#5966] opened 2020-10-06 15:23 UTC
### Description

I am trying to build a library of custom shadows as explained on http://robolectric.org/extending/
The issue I am facing here is with the annotationProcessor directive. I am adding the processor library like so:

`annotationProcessor 'org.robolectric:processor:4.4'`

This seems to be the right thing to do but compilation fails with the following error:

```
Execution failed for task ':library:compileReleaseJavaWithJavac'.
> java.lang.RuntimeException: failed to open SDK 0 at /usr/local/google/home/hoisie/.gradle/caches/modules-2/files-2.1/org.robolectric/android-all/4.1.2_r1-robolectric-r1/8355a2da59fe0233ca45070ca32f08da98d0b806/android-all-4.1.2_r1-robolectric-r1.jar
```

Please note that hoisie is not my user name, it looks like the processor library contains a path to a local jar where it should have been a dependency on another robolectric library

### Steps to Reproduce

* create an android library containing some custom shadow implementations
* do a successful gradle build
* add the correct `javaCompileOptions` block
* add the `annotationProcessor 'org.robolectric:processor:4.4'` in the dependencies block
* observe the build fail with abovementioned error

### Robolectric & Android Version

robolectric 4.4

**Comment by hoisie** [comment] 2020-10-06 17:17
Looks like this has been going on for some time. There's some SDK validation logic in the processor that using a file sdks.txt bundled in Robolectric's processor.jar. We should definitely not be bundling this file with the release.

As a workaround you can clone the Robolectric git repo and run:

      ./gradlew generateSdksFile

That should generate a file `./processor/build/resources/main/sdks.txt`

Afterwards, you can pass this file location as a processor arg `org.robolectric.annotation.processing.sdks`:

https://github.com/robolectric/robolectric/blob/master/processor/src/main/java/org/robolectric/annotation/processing/RobolectricProcessor.java#L45

**Comment by edwinvanderham** [comment] 2020-10-07 08:07
It looks like simply providing the path to the `sdks.txt` is not enough. I get a `java.lang.RuntimeException: no such resource` error. 
https://github.com/robolectric/robolectric/blob/master/processor/src/main/java/org/robolectric/annotation/processing/validator/SdkStore.java#L89
I don't think you can reference a file outside of a jar file when using getResourceAsStream

I did find another workaround by copying the built `processor-4.4.jar` into the libs folder of my shadows project and directly referencing it.

```
repositories {
  flatDir {
    dirs 'libs'
  }
}

dependencies {
  annotationProcessor (name: 'processor-4.4', ext: 'jar')
  annotationProcessor 'com.google.code.gson:gson:2.8.2'
}
```

**Comment by hoisie** [comment] 2020-10-07 14:56
Ah, that's annoying. Glad you found a workaround.

I think we should disable the SDK checker outside the Robolectric project itself until there's a better way to download the SDKs for users.

Also, we should stop including the bogus sdks.txt in the processor jar.

**Comment by hoisie** [comment] 2020-10-07 22:06
Randomly discovered that this is a dupe of #4801

**Closed by hoisie** 2020-10-07 22:06 UTC

**Comment by edwinvanderham** [comment] 2020-10-08 07:23
For the record, as suggested in https://github.com/robolectric/robolectric/issues/4801, the following seems to work now:

```
android {
  javaCompileOptions {
    annotationProcessorOptions {
      className 'org.robolectric.annotation.processing.RobolectricProcessor'
      arguments = [
              'org.robolectric.annotation.processing.shadowPackage': 'com.shadows.custom',
              'org.robolectric.annotation.processing.sdkCheckMode': 'OFF'
      ]
    }
  }
}

dependencies {
    annotationProcessor 'org.robolectric:processor:4.4'
}
```
