### ISSUE TITLE
Grade build error

### ISSUE THREAD

**Issue by kuo-ren** [robolectric/robolectric#1802] opened 2015-05-13 18:59 UTC
After adding urban airship as part of the android project, test won't build and gives Task 'testClasses' not found in project ':urbanairship-lib-6.0.1'.

**Comment by jaredsburrows** [comment] 2015-05-16 18:43
Post your `build.gradle`. How can anyone reproduce this?

Have you tried rebuilding the project? `gradlew clean build` and then `gradlew test`?

**Comment by steveydee82** [comment] 2015-05-19 14:49
I had this issue as well - different library but (like urban airship) also a .aar library imported as a module into Android Studio. I'm not convinced this is a Roboelectric issue - looks more like an Android Studio problem.

I found that you can work round this by changing the pre-test-run step from Make to Gradle-aware Make. Have a look here:

http://tools.android.com/tech-docs/unit-testing-support

Follow step 9 of the instructions. Also speeds up the test run significantly.

Hope this helps.

**Comment by jademcosta** [comment] 2015-05-22 16:40
Did you managed to test with @steveydee82 solution? In my case, the urban airship lib performs a check, to see if their provider is set on the manifest. This generates an error :/

The error is described here: http://stackoverflow.com/questions/23810390/robolectric-doesnt-work-with-urbanairship

Anyone having the same problem?

**Comment by jaredsburrows** [comment] 2015-06-04 02:13
@jademcosta That stackoverflow post uses an older version of Robolectric. Can you post the test you are using that fails?

**Comment by jademcosta** [comment] 2015-06-08 15:35
Hi,

The error I receive is the same of the first message in this topic.
I'm using robolectric 3.0-rc3, using nenick [custom runner](https://github.com/nenick/AndroidStudioAndRobolectric/blob/master/app/src/test/java/com/example/myapplication/CustomRobolectricRunner.java). 

Every test that I try to run using Android Studio gives me this error. Even a Simple one that just test that the application is not null.

**Comment by jaredsburrows** [comment] 2015-06-09 01:06
What about using the Regular `RobolectricGradleTestRunner.class`?

**Comment by jaredsburrows** [comment] 2015-06-15 13:32
@erd Can we close this? The original owner has not replied since posting this. There aren't even enough details to reproduce this.

**Comment by jademcosta** [comment] 2015-06-15 17:38
Using the regular RobolectricGradleTestRunner class don't work on Mac...

**Comment by jaredsburrows** [comment] 2015-06-15 17:45
What? I am using a Mac and I use `RobolectricGradleTestRunner.class`. Your MacBook and the test runner are not the issue.

**Comment by jademcosta** [comment] 2015-06-15 19:34
Ok. I'll take another look on my project later. Thanks for the help :)
(Btw, as the issue creator is not me, fell free to close it)

**Comment by jaredsburrows** [comment] 2015-06-15 20:33
Since with both use Macbooks, I maybe able to help walk you through your issue.

I am not an "owner", so I can not close issues.

**Closed** 2015-06-16 01:55 UTC

**Comment by mrkma** [comment] 2015-09-03 10:18
A simple workaround (found here https://plus.google.com/wm/www.gif.ly-sucks-off-sam-breed/+NealSanche/posts/G8KwfxMMN9v)
is to just put in `task testClasses {}` at the end of your new library project's build.gradle
