### ISSUE TITLE
Error Unable to resolve artifact: Missing: org.robolectric:shadows-core:jar:16:3.0-SNAPSHOT

### ISSUE THREAD

**Issue by henrytao-me** [robolectric/robolectric#1647] opened 2015-03-31 07:46 UTC
There are some changes on here https://oss.sonatype.org/content/groups/public/org/robolectric/shadows-core/3.0-SNAPSHOT/ which cause this issue

```
Downloading: org/robolectric/shadows-core/3.0-SNAPSHOT/shadows-core-3.0-20150330.025101-320-16.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
Unable to locate resource in repository

Unable to resolve artifact: Missing:
----------
1) org.robolectric:shadows-core:jar:16:3.0-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.robolectric -DartifactId=shadows-core -Dversion=3.0-20150330.025101-320 -Dclassifier=16 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.robolectric -DartifactId=shadows-core -Dversion=3.0-20150330.025101-320 -Dclassifier=16 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) org.apache.maven:super-pom:pom:2.0
  	2) org.robolectric:shadows-core:jar:16:3.0-SNAPSHOT

----------
1 required artifact is missing.
```

I just double check, this file is gone from the repository `shadows-core-3.0-20150330.025101-320-16.jar`
Please help. Thanks.

Cheers,
Henry

**Comment by erd** [comment] 2015-03-31 15:41
Duplicate of #1643.

**Closed by erd** 2015-03-31 15:41 UTC
