### ISSUE TITLE
java.lang.NoClassDefFoundError: [Landroid/content/res/ApkAssets;

### ISSUE THREAD

**Issue by vsay01** [robolectric/robolectric#5082] opened 2019-06-03 19:39 UTC
## Description
I set up power mock with robolectric 4.3 and I got the error which i cannot find any similar existing issues, here is the error:

```
[Robolectric] WARN: Android SDK 10000 requires Java 9 (have Java 8). Tests won't be run on SDK 10000 unless explicitly requested.
[Robolectric] com.robolectric.MyTestRobolectric.addition_isCorrect: sdk=28; resources=BINARY

java.lang.NoClassDefFoundError: [Landroid/content/res/ApkAssets;

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at org.robolectric.util.reflector.ReflectorClassWriter.write(ReflectorClassWriter.java:96)
	at org.robolectric.util.reflector.Reflector.getBytecode(Reflector.java:151)
	at org.robolectric.util.reflector.Reflector.createReflectorClass(Reflector.java:105)
	at org.robolectric.util.reflector.Reflector.reflector(Reflector.java:64)
	at org.robolectric.util.reflector.Reflector.reflector(Reflector.java:48)
	at org.robolectric.shadows.ShadowArscAssetManager9.reset(ShadowArscAssetManager9.java:232)
	at org.robolectric.Shadows.reset(Shadows.java:2134)
	at org.robolectric.android.internal.AndroidTestEnvironment.resetState(AndroidTestEnvironment.java:486)
	at org.robolectric.RobolectricTestRunner.lambda$finallyAfterTest$0(RobolectricTestRunner.java:334)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.RobolectricTestRunner.finallyAfterTest(RobolectricTestRunner.java:332)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:261)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: android.content.res.ApkAssets
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more

java.lang.NullPointerException
	at org.robolectric.RobolectricTestRunner$RobolectricFrameworkMethod$TestExecutionContext.access$400(RobolectricTestRunner.java:693)
	at org.robolectric.RobolectricTestRunner$RobolectricFrameworkMethod.getSdk(RobolectricTestRunner.java:624)
	at org.robolectric.RobolectricTestRunner$RobolectricFrameworkMethod.hashCode(RobolectricTestRunner.java:678)
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.junit.runners.BlockJUnit4ClassRunner.describeChild(BlockJUnit4ClassRunner.java:93)
	at org.junit.runners.BlockJUnit4ClassRunner.describeChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:352)
	at org.junit.runner.Runner.testCount(Runner.java:41)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.getTestCount(DelegatingPowerMockRunner.java:169)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:125)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

## Sample Test
````
package com.robolectric

import android.content.Context
import androidx.test.core.app.ApplicationProvider
import io.realm.Realm
import io.realm.RealmConfiguration
import io.realm.RealmQuery
import io.realm.RealmResults
import io.realm.internal.RealmCore
import io.realm.log.RealmLog
import org.junit.Assert
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.powermock.api.mockito.PowerMockito.*
import org.powermock.core.classloader.annotations.PowerMockIgnore
import org.powermock.core.classloader.annotations.PrepareForTest
import org.powermock.core.classloader.annotations.SuppressStaticInitializationFor
import org.powermock.modules.junit4.PowerMockRunner
import org.powermock.modules.junit4.PowerMockRunnerDelegate
import org.powermock.modules.junit4.rule.PowerMockRule
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment


@RunWith(PowerMockRunner::class)
@PowerMockRunnerDelegate(RobolectricTestRunner::class)
@PowerMockIgnore("org.mockito.*", "org.robolectric.*", "android.*")
@SuppressStaticInitializationFor("io.realm.internal.Util")
@PrepareForTest(Realm::class, RealmConfiguration::class, RealmQuery::class, RealmResults::class, RealmCore::class, RealmLog::class)
class MyTestRobolectric {

    @get:Rule
    var rule = PowerMockRule()

    private lateinit var mockRealm: Realm
    private lateinit var context: Context

    @Before
    fun setup() {
        context = ApplicationProvider.getApplicationContext()

        // Setup Realm to be mocked. The order of these matters
        mockStatic(RealmCore::class.java)
        mockStatic(RealmLog::class.java)
        mockStatic(Realm::class.java)
        mockStatic(RealmConfiguration::class.java)
        Realm.init(RuntimeEnvironment.application)

        // Create the mock
        val mockRealm = mock(Realm::class.java)
        val mockRealmConfig = mock(RealmConfiguration::class.java)

        // TODO: Better solution would be just mock the RealmConfiguration.Builder class. But it seems there is some
        // problems for powermock to mock it (static inner class). We just mock the RealmCore.loadLibrary(Context) which
        // will be called by RealmConfiguration.Builder's constructor.
        doNothing().`when`(RealmCore::class.java)
        RealmCore.loadLibrary(context)

        // TODO: Mock the RealmConfiguration's constructor. If the RealmConfiguration.Builder.build can be mocked, this
        // is not necessary anymore.
        whenNew(RealmConfiguration::class.java).withAnyArguments().thenReturn(mockRealmConfig)

        // Anytime getInstance is called with any configuration, then return the mockRealm
        `when`(Realm.getDefaultInstance()).thenReturn(mockRealm)
    }

    @Test
    fun addition_isCorrect() {
        Assert.assertEquals(4, 2 + 2)
    }
}
````

## Robolectric & Android Version
```
powermockitoVersion = '2.0.2'
powermock  : [
                                junit4    : "org.powermock:powermock-module-junit4:$rootProject.powermockitoVersion",
                                junit4rule: "org.powermock:powermock-module-junit4-rule:$rootProject.powermockitoVersion",
                                mockito   : "org.powermock:powermock-api-mockito2:$rootProject.powermockitoVersion",
                                xstream   : "org.powermock:powermock-classloading-xstream:$rootProject.powermockitoVersion"
                        ]

Roboelectric 4.3
Android Studio 3.4
'compileSdk' : 28,
'minSdk' : 19,
'targetSdk' : 28
```

**Comment by vsay01** [comment] 2019-06-05 18:32
For those who has similar issue above,

I resolved that for now by using Robolectric 4.1 instead of 4.3.

Still i will leave this issue open so that we can track this issue in the latest (currently) Robolectric 4.3

**Comment by neyguvj** [comment] 2019-06-17 18:23
I have the same problem on 
Robolecric 4.1, 
Android studio 3.4.1, 
AGP 3.3.2,
Gradle 5.2.1 
minSdk 21,
CompileSdk 28
targetSdk 28

**Comment by vsay01** [comment] 2019-06-28 20:58
@neyguvj so changing to Robolectric 4.1 not helping for your case ? you might want to try other version as well and see if it's help.

**Comment by neyguvj** [comment] 2019-06-29 12:37
No, sometimes tests fail with strange NoClassDefFoundError

**Comment by ziakhalid** [comment] 2019-07-12 06:32
@vsay01  Thanks Robolectric 4.1 works for me.

**Comment by bonjourrohit89** [comment] 2019-08-21 07:20
Thank you very much Robolectric 4.1 save my day. it works for me.

**Comment by ionutbarau** [comment] 2019-09-27 19:47
Did you do something else besides changing robolectric version? I have done the same thing but it does not work for me. If I leave the rule and the @PowerMockRunnerDelegate I get "java.lang.LinkageError: loader constraint violation: when resolving overridden method".

If I remove the rule, I get org.powermock.api.mockito.ClassNotPreparedException

**Comment by AndrewGong2016** [comment] 2019-12-10 07:54
I have solve the issue by download an android-all-10-robolectric-5803371.jar and replace the one in my local repositoty. Hope this one will help someone.

It seems maven lost android.content.res.ApkAssets in my local repository, and I download android-all-10-robolectric-5803371 from https://www.mvnjar.com/org.robolectric/android-all/10-robolectric-5803371/detail.html ,and replace the whole android-all-10-robolectric-5803371.jar in local repository

BTW, you might  delete the whole  local '.m2' direcotry and re-download it when run your robolectric unit case.

**Comment by hoisie** [comment] 2020-10-20 06:33
This seems outdated and has likely been fixed. Please update to Robolectric 4.4. If the problem persists comment here.

**Closed by hoisie** 2020-10-20 06:33 UTC
Labels: help wanted

**Comment by realdadfish** [comment] 2020-11-02 17:29
Just had this on CI with 4.5-alpha-2. targetSdk of the project is 29 still, that I couldn't reproduce locally yet unfortunately:

```shell
[17:20:45] java.lang.NoClassDefFoundError: [Landroid/content/res/ApkAssets;
[17:20:45] at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
[17:20:45] at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
[17:20:45] at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3191)
[17:20:45] at java.base/java.lang.Class.getMethods(Class.java:1904)
[17:20:45] at org.robolectric.util.reflector.ReflectorClassWriter.write(ReflectorClassWriter.java:95)
[17:20:45] at org.robolectric.util.reflector.Reflector.getBytecode(Reflector.java:152)
[17:20:45] at org.robolectric.util.reflector.Reflector.createReflectorClass(Reflector.java:106)
[17:20:45] at org.robolectric.util.reflector.Reflector.reflector(Reflector.java:65)
[17:20:45] at org.robolectric.util.reflector.Reflector.reflector(Reflector.java:49)
[17:20:45] at org.robolectric.shadows.ShadowArscAssetManager9.reset(ShadowArscAssetManager9.java:234)
[17:20:45] at org.robolectric.Shadows.reset(Shadows.java:2324)
[17:20:45] at org.robolectric.android.internal.AndroidTestEnvironment.resetState(AndroidTestEnvironment.java:518)
[17:20:45] at org.robolectric.RobolectricTestRunner.lambda$finallyAfterTest$0(RobolectricTestRunner.java:349)
[17:20:45] at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
[17:20:45] at org.robolectric.RobolectricTestRunner.finallyAfterTest(RobolectricTestRunner.java:347)
[17:20:45] at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:272)
[17:20:45] at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
[17:20:45] at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[17:20:45] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[17:20:45] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[17:20:45] at java.base/java.lang.Thread.run(Thread.java:834)
[17:20:45] 
[17:20:45] Caused by:
[17:20:45] java.lang.ClassNotFoundException: android.content.res.ApkAssets
[17:20:45] at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:163)
[17:20:45] at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:129)
[17:20:45] at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$loadClass$0(SandboxClassLoader.java:115)
[17:20:45] at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
[17:20:45] at org.robolectric.internal.bytecode.SandboxClassLoader.loadClass(SandboxClassLoader.java:115)
[17:20:45] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[17:20:45] ... 21 more
```

**Comment by akruijff** [comment] 2021-01-04 17:19
For me this problem is in 4.4 but not 4.5-alpha-3.

**Comment by chaleao** [comment] 2021-06-23 15:01
@realdadfish were you able to find a solution for this? I'm seeing the same exception as you

**Comment by realdadfish** [comment] 2021-06-23 15:38
@chaleao No, unfortunately not. I guess it went away with a Gradle / AGP Update. Haven't seen it since anymore.
