### ISSUE TITLE
Robolectric incompatible with support library 24.X

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#2520] opened 2016-06-18 16:42 UTC
### Description

AppCompat 24.x utilizes the graphic support library which provides SVG backwards compatibility on pre Lollipop devices. The graphic support library takes advantage of a small unused "feature" of the Android resource system.

That is for calls to Resources.Theme.obtainStyledAttributes() Android will first check the XML (the AttributeSet object) for attributes with IDs matching those requested in the int[] array of attribute IDs, if found, that attribute is used to create the appropriate entry in the TypedArray, otherwise Android continues to search the theme etc.

Note that the information in the AttributeSet object abstracts the binary XML format generated by aapt at compile time which includes augmented data not available in the original raw XML files. In particular it includes the resource identifiers (R values) of the attributes. Since these are generated at compile time, the small unused "feature" referred to above is that a lower runtime version of Android will silently pass through attributes unknown to it that were added in a later version of Android if the attributes resource identifier (from the compiled XML) matches a value requested in the int[] array. The application can then interpret the attribute and value at its own risk. This is how the graphics support library provides backwards compatible SVG support by interpreting the attributes viewportHeight and viewportWidth (added in API 21) on earlier devices.

<vector android:viewportWidth="24.0" android:viewportHeight="24.0">

Robolectric doesn't do this at present so this functionality will need to be added. Specifically the implementation of ShadowResources.attrsToTypedArray() must change to first check for a match on each attribute in the XML using https://developer.android.com/reference/android/util/AttributeSet.html#getAttributeNameResource(int)

The second issue is that Robolectric incorrectly includes the resource table from the runtime Android framework as part of the applications resource table, here:-

https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/RobolectricTestRunner.java#L416

This is incorrect, because the trick used by AppCompat to work relies on resource identifiers for attributes unknown to the runtime environment being encoded in the XML from the compile time SDK, e.g: for android:viewportHeight (added in API 21) to have an anonymous match on a KitKat device, the resource value requested in the int[] array must match the resource identifer for AttributeSet.getAttributeNameResource().

As such, Robolectric needs to change the way it builds the ResourceLoader for the application to include resources and resource mappings from the compile time SDK version of Android, rather than the runtime framework version as follows:-

1) Detect the compile time SDK (Unfortunately not available in the android.jar version of Build.VERSION.SDK_INT = 0, maybe use a system property or fallback to the latest supported version)
2) Create a ResourceLoader/ResourceIndex pair for that version of Android.
3) ResourceIndex only contains public resource identifiers, i.e: those parsed from android.R class (i.e: not com.android.internal.R)

Robolectric needs to wire up these two separate ResourceLoader/ResourceIndex as follows:-

AssetManager.getSystem() - Runtime framework resources
All other instances - Application resources (includes dependency libraries + compile time sdk resources)

Robolectric must be changed so that accessing OxO1TTEEEE R values are directed to the system resources while 0x7FTTEEEE R values are directed to the apps resources.

This last change is the most difficult since ResourceLoaders leak their abstraction in many places as resources are managed both at the ShadowResources and ShadowAssetManager level. Where possible resource management should be pushed down into ShadowAssetManager. Several refactoring have been submitted that clean this up by reducing the abstraction leakage and the API surface area of these classes.

related issue: https://github.com/robolectric/robolectric/issues/2418
### Steps to Reproduce

Run a robolectric test compiling against SDK 24 using AppCompat libraries. Due to the limitations of our Maven build system, its not possible to set up an example test case, however this can be demonstrated once https://github.com/robolectric/robolectric/issues/2487 is completed.

Caused by: org.xmlpull.v1.XmlPullParserException: XML file /x/y/z/drawable/abc_ic_ab_back_material.xml line #-1 (sorry, not yet implemented): invalid drawable tag vector
    at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
    at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
    at android.content.res.Resources.loadDrawable(Resources.java:2092)
    ... 52 more
### Robolectric & Android Version

Robolectric: Head
Android: Compile time SDK API 24 (AppCompat 24), Runtime API <= 21

**Comment by jaredsburrows** [comment] 2016-06-25 20:09
Show an example test. All my builds are using the latest apis and run perfectly fine with api 24 and support libraries 24.0.0.

**Comment by gkylafas** [comment] 2016-07-06 09:30
@jaredsburrows 
Example: if you use the preference-v7 v24.0.0 library, any tests which use a PreferenceFragmentCompat will fail with error:
> java.lang.RuntimeException: Content has view with id attribute 'android.R.id.list_container' that is not a ViewGroup class
at android.support.v7.preference.PreferenceFragmentCompat.onCreateView(PreferenceFragmentCompat.java:264)

The reason is that [android.R.id.list_container](https://developer.android.com/reference/android/R.id.html#list_container) (0x0102003f) was added in API 24, so robolectric does not know about it and executing a findViewById() returns null.

If you use preferece-v7 v23.4.0, which uses R.id.list_container (0x7f110341), then there is no problem.

**Comment by mgoovaer** [comment] 2016-07-26 18:01
I'm encountering this issue too, was there a fix?

**Comment by paleozogt** [comment] 2016-09-20 22:44
I am seeing this issue with support/design/appcompat v24.2.1.  Here's the exception:
```
android.content.res.Resources$NotFoundException: File build/intermediates/res/merged/faceVoice/debug/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
	at android.content.res.Resources.loadDrawable(Resources.java:2096)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.internal.Shadow.directlyOn(Shadow.java:57)
	at org.robolectric.shadows.ShadowResources.loadDrawable(ShadowResources.java:225)
	at android.content.res.Resources.loadDrawable(Resources.java)
	at android.content.res.Resources.getDrawable(Resources.java:700)
	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:185)
	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:720)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
	at android.support.v7.app.AppCompatDelegateImplBase.__constructor__(AppCompatDelegateImplBase.java:127)
	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java)
	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java)
	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java)
	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:201)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:181)
	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:521)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
    ...
Caused by: org.xmlpull.v1.XmlPullParserException: XML file build/intermediates/res/merged/faceVoice/debug/drawable/abc_vector_test.xml line #-1 (sorry, not yet implemented): invalid drawable tag vector
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
	at android.content.res.Resources.loadDrawable(Resources.java:2092)
	... 73 more```

**Comment by jaredsburrows** [comment] 2016-09-20 22:47
Is `faceVoice` the product flavor? I am guessing this only has to do with product flavors.

**Comment by paleozogt** [comment] 2016-09-20 22:48
@jaredsburrows yes that's the flavor

**Comment by paleozogt** [comment] 2016-09-20 22:53
@jaredsburrows I'm not sure how flavors factor into this problem.  `abc_vector_test` is part of appcompat, and I've been able to test with flavors up until upgrading to `v24.x`

**Comment by jaredsburrows** [comment] 2016-09-20 22:54
All of my open source repos use the latest gradle, android gradle plugin and support libraries. For example: https://github.com/jaredsburrows/android-glide-giphy-example.

**Comment by paleozogt** [comment] 2016-09-20 23:38
@jaredsburrows I created a new project with AS v2.2 that reproduces the issue:
   https://github.com/paleozogt/BrokenRobolectric

It doesn't use flavors.  It does use `FloatingActionButton` from `com.android.support:design`, which is what I think is causing the problem.

The project using the latest `v24.2.1`, but if I downgrade to `v23.x` the tests will work.

**Comment by hidroh** [comment] 2016-09-21 00:19
@paleozogt I encountered a similar issue with `abc_vector_test.xml` and it ties to a test that has `@Config(sdk = 18)`. Removing SDK override and letting Robolectric test against SDK 21 (default for Robolectric 3.0) makes it go away, though you may encounter various other issues.

**Comment by jaredsburrows** [comment] 2016-09-21 00:33
@paleozogt @hidroh is correct. Try to use `sdk=23` or anything over API 21. I just tested this on your branch.

**Comment by paleozogt** [comment] 2016-09-21 17:03
@jaredsburrows @hidroh Using api 21 worked.  Thanks!

**Comment by jaredsburrows** [comment] 2016-09-21 17:35
Ideally all API levels should work since it is a support library but I always end up targeting the latest supported.

**Comment by gkylafas** [comment] 2016-09-26 07:31
@jaredsburrows What about https://github.com/robolectric/robolectric/issues/2520#issuecomment-230723655?
The problem is about the support **preference** library, so should I open a different issue?

**Comment by jongerrish** [comment] 2016-09-26 14:04
@gkylafas - what version of Robolectric are you using? I believe that error had been fixed at head last week.

**Comment by gkylafas** [comment] 2016-09-27 06:50
@jongerrish I am using 3.1.2. I just tried with 3.2-SNAPSHOT but I got the same error. However, I noticed that the exact snapshot versions were sth like "3.2-20160714", i.e. maybe they are too old?

**Comment by gkylafas** [comment] 2016-09-27 09:21
@jongerrish I ended up building my own 3.2-SNAPSHOT and manually added the jars and their dependencies. The result was that, indeed, the problem mentioned in https://github.com/robolectric/robolectric/issues/2520#issuecomment-230723655 is solved!
(If I am not mistaken, it was fixed by d1117d80e4486b9167f122f3f8eca01e837208a1, wasn't it?)
When can we expect a release (or a -SNAPSHOT) that includes the fix?

**Comment by jongerrish** [comment] 2016-09-28 01:07
Yeah, that's right, that was the fix and we do need to push a release,
there have been a lot of bug fixes to resource handling also.

I'll see if we can do so tomorrow.

**Comment by PatrickDattilio** [comment] 2016-10-06 18:57
@jongerrish Any chance we could this release pushed?

**Comment by jaredsburrows** [comment] 2016-10-07 02:05
@jongerrish Now that gradle is setup and the build is pretty stable now. We should have automatic snapshots?

**Comment by jongerrish** [comment] 2016-10-07 05:21
Sure, feel free to send a PR

**Comment by jaredsburrows** [comment] 2016-10-07 05:43
@jongerrish Even if I did, I do not have access to Travis or your Maven Central. I cannot add some hidden environment variables to travis to publish to maven central snaphots.

**Closed** 2016-12-01 01:11 UTC
