### ISSUE TITLE
Robolectric can not be used testing code which uses Libraries built on Guava 16

### ISSUE THREAD

**Issue by Schlud** [robolectric/robolectric#6806] opened 2021-10-29 12:30 UTC
### Description
We did update to the most recent Robolectric Version and have following problem situation:
Our Android-Project is using a lot of shared-legacy-libraries which internally using a very old Guava Version 16.
It is legacy Code and would be a huge effort to update all those libraries.

With the previous Robolectric Version 3.7.1 we have been able to compile them by setting the Android Project to Guava  version 19. (Therewith the affected methods are deprecated but are still present and working)

Compiling an Android Test-Project using Robolectric Version 4.6.1 seems to implicitly enforce a more higher Version than Guava V19.
We then are getting following errors:

`java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;
`

We previously used Robolectric Version 3.7.1, there the Guava 16 code in the Libraries has not been an issue.

Maybe it would be a possibility to configured this somehow with gradle, 
but in the migration there was not covered this topic

**So our Major Question is :**
Is there a possibility to run  Robolectric (4.6.1) -Tests on code, that uses libraries which make use of an old Guava Version e.g. V16 ?
Or is it possible to still use the latest Robolectric Version 4.6.1 without enforcing that implicitly the guava Verison will be 
elevated for the Code under Test?

Thanks in advance.

### Steps to Reproduce

 

1. Having code that uses an external  jar library, which makes use of Guava 16 classes/ Methods (that are not available in the later Guava version) and invokes methods like `com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()`

2. Setting up a Robolectric (4.6.1) Project invoking testcode, which invokes a method of  a jar library that internal makes use of Guava 16

3.  Running the test, and a above message appears

### Robolectric Version
Robolectric: 4.6.1

### Link to a public git repo demonstrating the problem:
n/a

**Comment by hoisie** [comment] 2021-10-30 04:00
You are welcome to configure the Gradle dependency using https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html.

I am guessing that you are using Guava from a JAR file? This means you will have two versions of Guava on the classpath. Robolectric does not do anything specifically to elevate any dependencies. If you refactor your code to use gradle to depend on V16 of Guava, then gradle will resolve the right version and you will be OK. However, if you use gradle from a JAR, you will have two versions on the classpath, and then you leave it up to the application class loader to select one.

Closing this as there is really nothing we can do :(

**Closed by hoisie** 2021-10-30 04:00 UTC

**Comment by Schlud** [comment] 2021-11-01 13:18
Hi hoisie

if I'm downgrading guava to the version that is being used by configuring that by gradle, with 
`testImplementation ("com.google.guava:guava:19.0"){
            force = true
        }`

then it can be compiled, but finally during runtime `org.robolectric.internal.bytecode.ShadowProviders` having a problem cause they need a newer guava version that 19. That I ment by the tern "elevated". it does elevate the requirements of the Library used in the code under test. Running the tests thenproduces a lot of failing tests with the message:

`java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.sortedCopyOf(Ljava/util/Comparator;Ljava/lang/Iterable;)Lcom/google/common/collect/ImmutableList;

	at org.robolectric.internal.bytecode.ShadowProviders.<init>(ShadowProviders.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
`

So configuring gradle like mentioned by you above, seems not be an option. It seams that the code under tests needs to align its guava version with the Guava Version of the testing Framework. That is very sad... It would be nicer, if it would not enforce those requirements for the code under test.

**Comment by hoisie** [comment] 2021-11-01 15:07
> It would be nicer, if it would not enforce those requirements for the code under test

The contract is that app code and libraries defer to Gradle for handling dependencies. So if your app has `implementation("com.google.guava:guava:16")` and Robolectric has `implementation("com.google.guava:guava:27")`, gradle will resolve the dependency and select Guava version 27, which will then be used in both your app and test code.

The issue is that your app code seems to have a jar file containing Guava, which causes two copies of Guava to exist on the classpath. This bypasses Gradle's ability to manage dependencies.

Another option is for you to `shade` the Guava dependency in your app (i.e. rename the Guava classes in your JAR). There are some tools like `jarjar` that can potentially do this.

If you feel strongly that Robolectric should adhere to Guava 19 APIs, you are welcome to scope out the work and see how much code will have to change.
