### ISSUE TITLE
Robolectric not recognized in Android Studio 2.2

### ISSUE THREAD

**Issue by almighty972** [robolectric/robolectric#2649] opened 2016-09-22 08:51 UTC
### Description

Hello,
In Android Studio 2.2 Stable, and I cannot run my tests. All Robolectric classes and annotations are in red. 
(JUnit annotations have been recognized since I updagred the buildToolsVersion to 24.0.2)

Here is my configuration:
Gradle plugin version: 2.2.0
Gradle version: 2.14.1
Build tools version: 24.0.2
JUnit 4.12
Robolectric 3.1.1
Mockito 1.10.19

JUnit, Mockito and Robolectric are declared testCompile.
### Steps to Reproduce

Install Android Studio 2.2 Stable with:
Gradle plugin version: 2.2.0
Gradle version: 2.14.1
Build tools version: 24.0.2
JUnit 4.12
Robolectric 3.1.2
Mockito 1.10.19

Launch your tests. Gradle won't find any unit test.
### Robolectric & Android Version

Robolectric 3.1.1 and 3.1.2, Android 23

**Comment by almighty972** [comment] 2016-09-22 13:04
Up, nobody ?

**Comment by aschelch** [comment] 2016-09-23 08:17
Same here.

I have : 
`
java.lang.NoClassDefFoundError: org/objectweb/asm/Opcodes

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:174)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:142)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.Opcodes
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
`

What about you ?

**Comment by jaredsburrows** [comment] 2016-09-25 20:48
What is this: `Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.Opcodes`? Post your `build.gradle`.

**Comment by emartynov** [comment] 2016-10-18 21:47
I think it is problem of Android Studio and not Robolectric. What error do you see if you run it in console?

**Comment by almighty972** [comment] 2016-10-19 06:43
Hi @emartynov !

I have no error and that's the problem. 
My testCompile libraries are just ignored, and thus not recognized within Android Studio (red import classes, red @Config annotations etc..).

And I think you are right, I created a test project from scratch with Android Studio 2.2, I integrated Robolectric 3.1.2 and Mockito as testCompile dependencies and the test classes have been recognized, and the tests just worked fine. Thus there is no problem with Robolectric and Android Studio. 

I still don't know why Robolectric and Mockito are not recognized on my project. Maybe it is because I imported my AS 2.1 project from AS 2.2. 

It is like, AS 2.2 has it selected test artifact always on instrumentation test, and thus can't recognize my testCompile dependencies.

Thank you for your help!

**Comment by KevinLeighCrain** [comment] 2016-11-05 17:44
@almighty972 Robolectric and Android studio 2.2 work fine on my side. Looks like you are missing a test dependency (`testCompile`) on your side, that is required for your setup

**Comment by DanDevine** [comment] 2016-11-08 00:59
Running into the same issue, seeing all tests fail with "cannot find symbol class RobolectricGradleTestRunner"

When using Task:  './gradlew clean testDebugUnitTest'

Broken with:
'com.android.tools.build:gradle:2.2.0'
gradle-wrapper.properties set to version 3.1

Fine with:
'com.android.tools.build:gradle:2.1.2'
gradle-wrapper.properties set to version 2.4


Able to switch back and forth between configs easily.  The base project has been stable with Robolectric 3.0 for months with hundreds of tests, so the success ratio is 'all or nothing'.

Don't think its' an AS problem, I'm running this from the command line.

Get really stupid "> Gradle version 2.10 is required. Current version is 3.1. " error message  if I try to advance the gradle version while keeping the tools version fixed.

**Comment by almighty972** [comment] 2016-11-09 09:47
Thank you all guys for your interest.
I solved my problem.
It has nothing to do with Robolectric, sorry the Robolectric guys for this erroneous issue.
It was a problem with my Jacoco gradle script and in particular with this DSL:

`sourceSets {
        androidTest {
            setRoot('src/test')
        }
        instrumentTest.setRoot('src/test')
    }
`

Since Android Studio 2.2, testCompile and androidTestCompile dependencies are detected automatically. (No need the experimental Unit Test artifact selection anymore)

By removing this bloc, all my tests work fine again!

Thank you all.

**Comment by IgorGanapolsky** [comment] 2017-06-26 17:35
@almighty972 I tried your approach, and still getting the Robolectric errors in Android Studio 3.0 Canary 4

**Comment by rakshith49kumar** [comment] 2018-02-05 10:51
I'm also facing same issue 

```
java.lang.RuntimeException: java.lang.NoSuchFieldException: sSystem

	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:192)
	at org.robolectric.shadows.ShadowAssetManager.reset(ShadowAssetManager.java:1036)
	at org.robolectric.Shadows.reset(Shadows.java:1696)
	at org.robolectric.Robolectric.reset(Robolectric.java:42)
```

**Comment by jongerrish** [comment] 2018-10-31 18:14
GradleRobolectricTestRunner has been removed, instead you can simply use RobolectricTestRunner. You also no longer need to specify @Config(constants = ..., manifest = ...)

We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.

**Closed by jongerrish** 2018-10-31 18:14 UTC
