### ISSUE TITLE
run with code coverage always failed with 4.7.3 

### ISSUE THREAD

**Issue by Abdul96881** [robolectric/robolectric#7034] opened 2022-02-07 16:23 UTC
### Description

Bad return type
Exception Details:
  Location:
    android/content/res/ResourcesImpl.$$robo$$android_content_res_ResourcesImpl$loadComplexColorForCookie(Landroid/content/res/Resources;Landroid/util/TypedValue;ILandroid/content/res/Resources$Theme;)Landroid/content/res/ComplexColor; @803: areturn
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'android/content/res/ComplexColor' (from method signature)
  Current Frame:
    bci: @803
    flags: { }
    locals: { 'android/content/res/ResourcesImpl', 'android/content/res/Resources', 'android/util/TypedValue', integer, 'android/content/res/Resources$Theme', '[Z', 'java/lang/Object', 'java/lang/String', 'java/lang/Object', 'android/content/res/XmlResourceParser', 'android/util/AttributeSet', integer, 'java/lang/String' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: b805 f53a 0512 90b8 0096 3a06 1905 1102
    0000010: 1a04 5419 0611 044f b800 9a2c b401 bbc7
    0000020: 0038 1905 1102 1b04 5419 0611 0450 b800
    0000030: 9abb 042f 59bb 0127 59b7 0128 1304 31b6
    0000040: 012e 2cb4 02c8 b601 91b6 0138 b704 3219
    0000050: 0511 021c 0454 bf19 0611 0454 b800 9a2c
    0000060: b401 bbb9 01bc 0100 3a07 1905 1102 1d04
    0000070: 5419 0611 0465 b800 9a01 3a08 1905 1102
    0000080: 1e04 5419 0611 0467 b800 9a14 01e0 1907
    0000090: b801 e919 0511 021f 0454 1906 1104 68b8
    00000a0: 009a 1907 1303 85b6 0389 9901 f019 0511
    00000b0: 0220 0454 1906 1104 6ab8 009a 2a19 071d
    00000c0: 2cb4 01b9 1304 34b6 03b7 3a09 1905 1102
    00000d0: 2104 5419 0611 046d b800 9a19 09b8 043a
    00000e0: 3a0a 1905 1102 2204 5419 0611 046f b800
    00000f0: 9a19 09b9 043d 0100 5936 0b05 a000 0d19
    0000100: 0511 0223 0454 a700 1d15 0b04 a000 0d19
    0000110: 0511 0224 0454 a700 0d19 0511 0225 0454
    0000120: a7ff c919 0611 0473 b800 9a15 0b05 9f00
    0000130: 2419 0511 0226 0454 1906 1104 74b8 009a
    0000140: bb03 b359 1304 3fb7 0440 1905 1102 2704
    0000150: 54bf 1906 1104 77b8 009a 1909 b904 4301
    0000160: 003a 0c19 0511 0228 0454 1906 1104 78b8
    0000170: 009a 190c 1304 45b6 01a4 9900 2819 0511
    0000180: 0229 0454 1906 1104 79b8 009a 2b19 0919
    0000190: 0a19 04b8 044b 3a08 1905 1102 2a04 54a7
    00001a0: 0042 1906 1104 7ab8 009a 190c 1304 4db6
    00001b0: 01a4 9a00 0d19 0511 022b 0454 a700 2519
    00001c0: 0511 022c 0454 1906 1104 7bb8 009a 2b19
    00001d0: 0919 0a19 04b8 0450 3a08 1905 1102 2d04
    00001e0: 5419 0611 047d b800 9a19 09b9 03be 0100
    00001f0: 1905 1102 2e04 5419 0611 0485 b800 9aa7
    0000200: 00fe 1906 1104 7eb8 009a 3a09 1905 1102
    0000210: 2f04 5419 0611 047f b800 9a14 01e0 b802
    0000220: 7319 0511 0230 0454 1906 1104 80b8 009a
    0000230: bb00 1659 bb01 2759 b701 2813 01c2 b601
    0000240: 2e19 07b6 012e 1304 52b6 012e 1d19 0511
    0000250: 0231 0454 1906 1104 82b8 009a b801 34b6
    0000260: 012e b601 38b7 013b 3a0a 1905 1102 3204
    0000270: 5419 0611 0483 b800 9a19 0a19 09b6 01d6
    0000280: 5719 0511 0233 0454 1906 1104 84b8 009a
    0000290: 190a 1905 1102 3404 54bf 1906 1104 87b8
    00002a0: 009a 1401 e0b8 0273 1905 1102 3504 5419
    00002b0: 0611 0488 b800 9abb 0016 59bb 0127 59b7
    00002c0: 0128 1301 c2b6 012e 1907 b601 2e13 039b
    00002d0: b601 2e1d 1905 1102 3604 5419 0611 048a
    00002e0: b800 9ab8 0134 b601 2e13 041f b601 2eb6
    00002f0: 0138 b701 3b19 0511 0237 0454 bf19 0611
    0000300: 048c b800 9a14 01e0 b802 7319 0511 0238
    0000310: 0454 1906 1104 8eb8 009a 1908 1905 1102
    0000320: 3904 54b0                              
  Exception Handler Table:
    bci [173, 496] => handler: 514
  Stackmap Table:
    append_frame(@87,Object[#1527],Object[#4])
    full_frame(@233,{Object[#2],Object[#24],Object[#438],Integer,Object[#27],Object[#1527],Object[#4],Object[#214],Null,Object[#957],Object[#1111]},{})
    append_frame(@265,Integer)
    same_frame(@281)
    same_frame(@291)
    same_frame(@338)
    append_frame(@418,Object[#214])
    same_frame(@447)
    full_frame(@481,{Object[#2],Object[#24],Object[#438],Integer,Object[#27],Object[#1527],Object[#4],Object[#214],Object[#4],Object[#957],Object[#1111],Integer,Object[#214]},{})
    full_frame(@514,{Object[#2],Object[#24],Object[#438],Integer,Object[#27],Object[#1527],Object[#4],Object[#214],Object[#4]},{Object[#339]})
    full_frame(@666,{Object[#2],Object[#24],Object[#438],Integer,Object[#27],Object[#1527],Object[#4],Object[#214],Null},{})
    full_frame(@765,{Object[#2],Object[#24],Object[#438],Integer,Object[#27],Object[#1527],Object[#4],Object[#214],Object[#4],Object[#957],Object[#1111],Integer,Object[#214]},{})

java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    android/content/res/ResourcesImpl.$$robo$$android_content_res_ResourcesImpl$loadComplexColorForCookie(Landroid/content/res/Resources;Landroid/util/TypedValue;ILandroid/content/res/Resources$Theme;)Landroid/content/res/ComplexColor; @803: areturn
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'android/content/res/ComplexColor' (from method signature)
  Current Frame:
    bci: @803
    flags: { }
    locals: { 'android/content/res/ResourcesImpl', 'android/content/res/Resources', 'android/util/TypedValue', integer, 'android/content/res/Resources$Theme', '[Z', 'java/lang/Object', 'java/lang/String', 'java/lang/Object', 'android/content/res/XmlResourceParser', 'android/util/AttributeSet', integer, 'java/lang/String' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: b805 f53a 0512 90b8 0096 3a06 1905 1102
    0000010: 1a04 5419 0611 044f b800 9a2c b401 bbc7
    0000020: 0038 1905 1102 1b04 5419 0611 0450 b800
    0000030: 9abb 042f 59bb 0127 59b7 0128 1304 31b6
    0000040: 012e 2cb4 02c8 b601 91b6 0138 b704 3219
    0000050: 0511 021c 0454 bf19 0611 0454 b800 9a2c
    0000060: b401 bbb9 01bc 0100 3a07 1905 1102 1d04
    0000070: 5419 0611 0465 b800 9a01 3a08 1905 1102
    0000080: 1e04 5419 0611 0467 b800 9a14 01e0 1907
    0000090: b801 e919 0511 021f 0454 1906 1104 68b8
    00000a0: 009a 1907 1303 85b6 0389 9901 f019 0511
    00000b0: 0220 0454 1906 1104 6ab8 009a 2a19 071d
    00000c0: 2cb4 01b9 1304 34b6 03b7 3a09 1905 1102
    00000d0: 2104 5419 0611 046d b800 9a19 09b8 043a
    00000e0: 3a0a 1905 1102 2204 5419 0611 046f b800
    00000f0: 9a19 09b9 043d 0100 5936 0b05 a000 0d19
    0000100: 0511 0223 0454 a700 1d15 0b04 a000 0d19
    0000110: 0511 0224 0454 a700 0d19 0511 0225 0454
    0000120: a7ff c919 0611 0473 b800 9a15 0b05 9f00
    0000130: 2419 0511 0226 0454 1906 1104 74b8 009a
    0000140: bb03 b359 1304 3fb7 0440 1905 1102 2704
    0000150: 54bf 1906 1104 77b8 009a 1909 b904 4301
    0000160: 003a 0c19 0511 0228 0454 1906 1104 78b8
    0000170: 009a 190c 1304 45b6 01a4 9900 2819 0511
    0000180: 0229 0454 1906 1104 79b8 009a 2b19 0919
    0000190: 0a19 04b8 044b 3a08 1905 1102 2a04 54a7
    00001a0: 0042 1906 1104 7ab8 009a 190c 1304 4db6
    00001b0: 01a4 9a00 0d19 0511 022b 0454 a700 2519
    00001c0: 0511 022c 0454 1906 1104 7bb8 009a 2b19
    00001d0: 0919 0a19 04b8 0450 3a08 1905 1102 2d04
    00001e0: 5419 0611 047d b800 9a19 09b9 03be 0100
    00001f0: 1905 1102 2e04 5419 0611 0485 b800 9aa7
    0000200: 00fe 1906 1104 7eb8 009a 3a09 1905 1102
    0000210: 2f04 5419 0611 047f b800 9a14 01e0 b802
    0000220: 7319 0511 0230 0454 1906 1104 80b8 009a
    0000230: bb00 1659 bb01 2759 b701 2813 01c2 b601
    0000240: 2e19 07b6 012e 1304 52b6 012e 1d19 0511
    0000250: 0231 0454 1906 1104 82b8 009a b801 34b6
    0000260: 012e b601 38b7 013b 3a0a 1905 1102 3204
    0000270: 5419 0611 0483 b800 9a19 0a19 09b6 01d6
    0000280: 5719 0511 0233 0454 1906 1104 84b8 009a
    0000290: 190a 1905 1102 3404 54bf 1906 1104 87b8
    00002a0: 009a 1401 e0b8 0273 1905 1102 3504 5419
    00002b0: 0611 0488 b800 9abb 0016 59bb 0127 59b7
    00002c0: 0128 1301 c2b6 012e 1907 b601 2e13 039b
    00002d0: b601 2e1d 1905 1102 3604 5419 0611 048a
    00002e0: b800 9ab8 0134 b601 2e13 041f b601 2eb6
    00002f0: 0138 b701 3b19 0511 0237 0454 bf19 0611
    0000300: 048c b800 9a14 01e0 b802 7319 0511 0238
    0000310: 0454 1906 1104 8eb8 009a 1908 1905 1102
    0000320: 3904 54b0                              
  Exception Handler Table:
    bci [173, 496] => handler: 514
  Stackmap Table:
    append_frame(@87,Object[#1527],Object[#4])
    full_frame(@233,{Object[#2],Object[#24],Object[#438],Integer,Object[#27],Object[#1527],Object[#4],Object[#214],Null,Object[#957],Object[#1111]},{})
    append_frame(@265,Integer)
    same_frame(@281)
    same_frame(@291)
    same_frame(@338)
    append_frame(@418,Object[#214])
    same_frame(@447)
    full_frame(@481,{Object[#2],Object[#24],Object[#438],Integer,Object[#27],Object[#1527],Object[#4],Object[#214],Object[#4],Object[#957],Object[#1111],Integer,Object[#214]},{})
    full_frame(@514,{Object[#2],Object[#24],Object[#438],Integer,Object[#27],Object[#1527],Object[#4],Object[#214],Object[#4]},{Object[#339]})
    full_frame(@666,{Object[#2],Object[#24],Object[#438],Integer,Object[#27],Object[#1527],Object[#4],Object[#214],Null},{})
    full_frame(@765,{Object[#2],Object[#24],Object[#438],Integer,Object[#27],Object[#1527],Object[#4],Object[#214],Object[#4],Object[#957],Object[#1111],Integer,Object[#214]},{})

	at android.content.res.Resources.__constructor__(Resources.java:309)
	at android.content.res.Resources.<init>(Resources.java)
	at org.robolectric.shadows.ShadowResources.getSystem(ShadowResources.java:81)
	at android.content.res.Resources.getSystem(Resources.java)
	at android.app.LoadedApk.__constructor__(LoadedApk.java:239)
	at android.app.LoadedApk.<init>(LoadedApk.java)
	at android.app.ContextImpl.createSystemContext(ContextImpl.java:2965)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.shadows.ShadowContextImpl$_ContextImpl_$$Reflector4.createSystemContext(Unknown Source)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:249)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$0(AndroidTestEnvironment.java:229)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$1(AndroidTestEnvironment.java:226)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at org.robolectric.RuntimeEnvironment.getApplication(RuntimeEnvironment.java:71)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:194)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:325)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:265)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Class transformation time: 3.502821979s for 4436 classes or 7.896352522542831E-4s per class
com.ford.msvpud.mobileservice.helper.SharedPreferenceTest > mockData FAILED
    java.lang.VerifyError at Resources.java:309
1 test completed, 1 failed
> Task :app:testDebugUnitTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:testDebugUnitTest'.
> There were failing tests. See the report at: file:///Users/abdulrahman/Documents/msvpud-android-app_lab/app/build/reports/tests/testDebugUnitTest/index.html
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.3.2/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 45s
33 actionable tasks: 6 executed, 27 up-to-date
9:47:37 pm: Task execution finished ':app:testDebugUnitTest --tests "com.ford.msvpud.mobileservice.helper.SharedPreferenceTest"'.

### Robolectric & Android Version 

Roboelectric 4.7.3 
minSdkVersion 26
targetSdkVersion 31

classpath 'com.android.tools.build:gradle:7.1.1'

testOptions {
        unitTests {
            includeAndroidResources  true
![Screenshot 2022-02-07 at 9 52 30 PM](https://user-images.githubusercontent.com/20418106/152828773-c5623088-935f-4e6a-88e2-cc8598452c84.png)

        }
    }
enabled this for accessing resources .eventhough cant able to access resources and asset files

**Comment by hoisie** [comment] 2022-02-07 18:03
Seems to be a dupe of https://github.com/robolectric/robolectric/issues/3023, so I'll close this in favor of that.

Like I mentioned in https://github.com/robolectric/robolectric/issues/3023#issuecomment-952584425, I am unable at the moment to personally look at this issue due to the complex and time-consuming nature, so if Jacoco coverage integration is important to you, I would encourage you to take the first dive and see what is going on.

**Closed as completed by hoisie** 2022-02-07 18:03 UTC

**Comment by grndvl1** [comment] 2022-07-18 19:26
I see this issue with mine too.

**Comment by SuyashFirstdata** [comment] 2023-10-09 15:47
I'm experiencing the same problem. Has anyone found a solution?
