### ISSUE TITLE
How to add PackageInfo in ShadowPackageManager?

### ISSUE THREAD

**Issue by ashishjohn1908** [robolectric/robolectric#6271] opened 2021-03-09 02:45 UTC
### Steps to Reproduce
PackageInfo packageInfo = new PackageInfo();
packageInfo.packageName = PACKAGE_NAME;
packageInfo.versionCode = 15050;

ShadowPackageManager mRBPakcageManger = shadowOf(ApplicationProvider.getApplicationContext().getPackageManager());
mRBPakcageManger.installPackage(packageInfo);

When I try to get version code for testing, it returns me back the versionCode given in the gradle file. How to mock this?

### Robolectric & Android Version
classpath 'com.android.tools.build:gradle:4.1.2'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'androidx.test.ext:junit-ktx:1.1.2'
    testImplementation 'androidx.test:core:1.3.0'
    testImplementation 'org.robolectric:robolectric:4.5.1'
    testImplementation 'org.robolectric:shadows-support-v4:3.3.2'
    testImplementation 'org.robolectric:robolectric-shadows:3.0'
    testImplementation 'org.mockito:mockito-all:1.9.0'

### Link to a public git repo demonstrating the problem:
https://stackoverflow.com/questions/66529165/how-to-add-packageinfo-in-shadowpackagemanager

**Comment by hoisie** [comment] 2021-03-11 05:55
First of all remove these dependencies:

```
testImplementation 'org.robolectric:shadows-support-v4:3.3.2'
testImplementation 'org.robolectric:robolectric-shadows:3.0'
```

Not sure where those are coming from, 3.0 is ancient.

**Comment by longv** [comment] 2021-12-01 16:15
Is there any update for this? I also want to change `packageInfo.versionCode` to another value in a test to verify some logic.

**Comment by utzcoz** [comment] 2021-12-01 17:18
Hi @longv @ashishjohn1908 , I have added related tests to check `versionCode` with `getPackageInfo` for  `installPackage` related `PackageInfo`(https://github.com/robolectric/robolectric/pull/6898). It looks fine with latest source code. Maybe you can follow https://github.com/robolectric/robolectric/issues/6271#issuecomment-796478574 to remove unnecessary dependencies , bump to latest Robolectric 4.7.3, and check again. If you also have this problem, please link an example project that can reproduce this problem. We can check the explicit situation that causes this problem.

**Comment by longv** [comment] 2021-12-01 17:43
Hi @utzcoz , tks a lot for your help. Using `shadowOf` helped with my issue. Basically I did this:
```
shadowOf(context.packageManager).getInternalMutablePackageInfo(context.packageName).versionCode = 1
```
Then the version code was changed successfully.

I'm new for Robolectric and having hard time reading the documents since there is just few of them. Also the link for [Robolectric plugin for Chrome](https://chrome.google.com/webstore/detail/pjepcinimnfnaoopahdkpkefnefdkdgh) didn't work. Do you happen to have any pointer?

**Comment by utzcoz** [comment] 2021-12-03 16:34
Hi @longv, it's very happy to hear that `shadowOf` can solve your problem. For Robolectric plugin for Chrome, you can fire a new issue for it. Sorry, I don't know the latest status of this plugin. Maybe @hoisie can help to answer your question at new issue or at here briefly.

**Comment by utzcoz** [comment] 2021-12-04 16:28
Hi @ashishjohn1908 , I will close this issue, and you can try https://github.com/robolectric/robolectric/issues/6271#issuecomment-983878322. Feel free to reopen this issue if it doesn't resolve your problem.

**Closed by utzcoz** 2021-12-04 16:28 UTC
