### ISSUE TITLE
Clarify usage of test-only Activities / addOrUpdateActivity

### ISSUE THREAD

**Issue by realdadfish** [robolectric/robolectric#4725] opened 2019-03-07 15:03 UTC
After updating from Robolectric 4.0.2 to 4.2, launching activities through Jetpack's `ActivityScenario` does no longer work. Mimicking the needed setup of an instrumentation test, I added a `TestActivity` into a `core-test` module and referenced this activity also in `core-test`'s `AndroidManifest.xml` file. I then `debugImplementation`-depended in my `feature` module on `core-test` to let androidx.test (and possibly Robolectric) see the Activity. This worked in 4.0.2.

Now, in 4.2 I read that the `ShadowPackageManager` implementation changed and gained a new `addOrUpdateActivity` method, with which I apparently need to stub the activity info I want the `PackageManager` to resolve to by hand.

Is this the correct approach or am I missing something?

**Comment by realdadfish** [comment] 2019-03-07 15:23
So this is what I'm using now:

```kotlin
        val appContext: Application = ApplicationProvider.getApplicationContext()
        val activityInfo = ActivityInfo().apply {
            name = TestActivity::class.java.name
            packageName = appContext.packageName
        }
        shadowOf(appContext.packageManager).addOrUpdateActivity(activityInfo)
        scenario = ActivityScenario.launch<TestActivity>(
            Intent(appContext, TestActivity::class.java)
        )
```

**Comment by jongerrish** [comment] 2019-03-07 22:07
Thanks for the report, yes, we're aware of the regression. It's actually the way that ActivityScenario is intended to work (Having a manifest entry is how it needs to behave on a real device) but we didn't realize that Android Studio Gradle plugin does not merge the contents of the 

yourmodule/src/test/AndroidManifest.xml

Are you saying that even with a core-test module (containing testing infrastructure such as AndroidManifest.xml <activiy name="com.my.TestActivity"/> and com.my.TestActivity itself) and depending on that with

testImplementation(project(":core-test"))

from the module, your manifest entries in the core-testing are not merged either?

**Comment by jongerrish** [comment] 2019-03-07 22:08
We're actually tracking this here:- #4727 so I'll close this and if you can follow up there would be great, thanks! :-)

**Closed by jongerrish** 2019-03-07 22:08 UTC

**Comment by mlemley** [comment] 2019-05-10 17:41
@realdadfish Thanks for your post regarding this issue.  I added the following to my `TestApplication` which implements `TestLifecycleApplication`

```java
    @Override
    public void onCreate() {
        super.onCreate();
        ShadowPackageManager shadowPackageManager = shadowOf(getApplicationContext().getPackageManager());
        ActivityInfo activityInfo = new ActivityInfo();
        activityInfo.name = TestableActivity.class.getName();
        activityInfo.packageName = getPackageName();
        shadowPackageManager.addOrUpdateActivity(activityInfo);
    }
```

This has resolved my issue for all tests that uses the dependency

```java
        scenario = ActivityScenario.launch(TestableActivity.class);
```

**Comment by realdadfish** [comment] 2019-05-14 08:36
@mlemley Nice find! Now if we'd have something similar running for instrumentation tests as well, it would be awesome, as it would free us from having to have a `TestActivity` in the `debug` (or else) variant of the production code, which triggers it's own can of worms. I hope Google is working on something here, otherwise UI tests will not be easily portable / executable on emulated and "simulated" (Robolectric) devices :)
