### ISSUE TITLE
If an animation is run on the same view twice, onAnimationEnd() is not called the second time.

### ISSUE THREAD

**Issue by erichaugh** [robolectric/robolectric#1809] opened 2015-05-14 17:43 UTC
Test case demonstrating the issue:

  @Test
  public void testTwoAnimations() {
    View view = new TextView(RuntimeEnvironment.application);

```
final AtomicBoolean listener1OnStartCalled = new AtomicBoolean();
final AtomicBoolean listener1OnEndCalled = new AtomicBoolean();
final AtomicBoolean listener2OnStartCalled = new AtomicBoolean();
final AtomicBoolean listener2OnEndCalled = new AtomicBoolean();

AnimatorListenerAdapter listener1 = new AnimatorListenerAdapter() {
  @Override
  public void onAnimationStart(Animator animation) {
    listener1OnStartCalled.set(true);
  }

  @Override
  public void onAnimationEnd(Animator animation) {
    listener1OnEndCalled.set(true);
  }
};
AnimatorListenerAdapter listener2 = new AnimatorListenerAdapter() {
  @Override
  public void onAnimationStart(Animator animation) {
    listener2OnStartCalled.set(true);
  }

  @Override
  public void onAnimationEnd(Animator animation) {
    listener2OnEndCalled.set(true);
  }
};
view.animate()
    .alpha(0f)
    .setDuration(400)
    .setListener(listener1).start();
view.animate()
    .alpha(1f)
    .setDuration(400)
    .setListener(listener2).start();

assertThat(listener1OnStartCalled.get(), is(true));
assertThat(listener1OnEndCalled.get(), is(true));
assertThat(listener2OnStartCalled.get(), is(true));
assertThat(listener2OnEndCalled.get(), is(true));
```

  }

**Comment by jongerrish** [comment] 2015-05-14 20:57
This case demonstrates exactly what @charlesmunger demonstates in his comment on https://github.com/robolectric/robolectric/pull/1727

Consider the Android code for ValueAnimator.AnimationHandler here:-

https://github.com/android/platform_frameworks_base/blob/master/core/java/android/animation/ValueAnimator.java#L736

There is a subtle interplay between run() and scheduleAnimation() which breaks the second animation and subsequent animations.

Real Android:-
1) mAnimationScheduled initial value is false;
2) scheduleAnimation() called
3) no animation scheduled so it posts itself to the Choreographer
4) sets mAnimationScheduled = true
5) on the next loop run() is executed
6) sets mAnimationScheduled = false;
7) executes the frame

Note: last mAnimationScheduled value = false

Robolectric:-
1) mAnimationScheduled initial value is false;
2) scheduleAnimation() called
3) no animation scheduled so it posts itself to the Choreographer
4) run() is executed immediately inline <----- Different behavior from here
5) sets mAnimationScheduled = false;
6) executes the frame
7) returns back into scheduleAnimation() sets mAnimationScheduled = true

Note: last mAnimationScheduled value = true

Because Robolectric eagerly executes the runnable inline it leaves the mAnimationScheduled value with an incorrect value that short circuits the execution of subsequent animations.

It is possible to work around this by explicitly pausing the UI Thread scheduler at the beginning of the test using ShadowApplication.getInstance().getForegroundThreadScheduler().pause(); and then before the last assertion call, do something like ShadowApplication.getInstance().getForegroundThreadScheduler().runOneTask(); to cause the animation to run.

So now the question is what to do about it :-)

The current Robolectric behaviour is very broken, because by the time you make the last assertion, all of the runnables have been executed, but because of the scheduling differences between what Android animation code expects and what Robolectric actually does, the last animation was only partly executed, in that its onAnimationStart() was called, but the animation itself did not run, neither was onAnimationEnd() called.

Users needing to know to pause the scheduler to avoid these breakages is bad, so I would rather the default behavior be as Charles requested in that runnables are just queued and its up to you as a test writer to sequence them around your assertions. If the test writer is feeling bold, they could just switch the scheduler into the current "non-paused" mode.

Having said that, I'm also worried about how many tests that could break :-/

Thoughts, comments and suggestions welcome

@erd @kriegfrj @charlesmunger @erichaugh

**Comment by kriegfrj** [comment] 2015-05-14 23:51
#1351 should prevent a runnable.from executing eagerly if one is already running - is it should stop this happening.

Given that the test starts with default Scheduler time, I think that this might simply be a manifestation of #1740. Fix that and I reckon this issue will go away without needing to change the default behaviour to paused and break all those tests you're worried about. This would be my preferred solution.

**Comment by jongerrish** [comment] 2015-05-15 00:23
I don't think that is the issue, #1351 is working as expected. The problem is here rather:-

https://github.com/robolectric/robolectric/blob/master/robolectric-utils/src/main/java/org/robolectric/util/Scheduler.java#L103

because paused == false &&  delayMillis == 0 the else condition is invoked which causes the Runnable to execute immediately inline, which in turn causes the internal state (ValueAnimator.AnimationHandler.mAnimationScheduled) to be inconsistent after execution (it MUST be false after the runnable has been run but it is left true).

@roman-mazur describes the issue succinctly in https://github.com/robolectric/robolectric/issues/1306 - we're trying to model Android's event loop onto a single, terminating thread of control in tests.

**Comment by kriegfrj** [comment] 2015-05-15 01:48
Yes, you're right. Having thought about it a bit more, #1740 affects the ordering of runnables only, in both the current (errant) behaviour and the desired behaviour the runnables still don't execute inline.

I have a couple of ideas, but given that this is essentially #1306 I think I will list future comments under that issue instead of here.

**Comment by kriegfrj** [comment] 2015-05-15 05:45
This looks like a duplicate of #1770, btw.

**Comment by utzcoz** [comment] 2022-10-23 16:44
Hi @erichaugh @kriegfrj , thanks for reporting this issue, but it's too old with a very old Robolectric version. Feel free to reopen it if you find that this issue still exists. Thanks.

**Closed by utzcoz** 2022-10-23 16:44 UTC
Labels: defect, scheduler
