### ISSUE TITLE
NoClassDefFoundError: ... R$styleable when using Robolectric with Android Library (AAR)

### ISSUE THREAD

**Issue by dwb357** [robolectric/robolectric#1796] opened 2015-05-12 15:09 UTC
We are developing a library that provides an Activity, and I would like to be able to perform some functional testing on the Activity.

My `build.gradle` contains:

```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 21
    buildToolsVersion "22.0.1"

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.+'

    testCompile 'org.mockito:mockito-core:1.+'
    testCompile 'junit:junit:4.12'
    testCompile('org.robolectric:robolectric:3.0-rc2') {
        exclude group: 'commons-logging', module: 'commons-logging'
        exclude group: 'org.apache.httpcomponents', module: 'httpclient'
    }
    testCompile('org.robolectric:shadows-httpclient:3.0-rc2') {
        exclude group: 'commons-logging', module: 'commons-logging'
        exclude group: 'org.apache.httpcomponents', module: 'httpclient'
    }
    testCompile('org.robolectric:shadows-support-v4:3.0-rc2') {
        exclude group: 'commons-logging', module: 'commons-logging'
        exclude group: 'org.apache.httpcomponents', module: 'httpclient'
    }
}
```

And my `LibraryActivityTest` includes:

```
@RunWith(RobolectricGradleTestRunner.class)
public class LibraryActivityTest {

    @Test
    public void testOnCreate() throws Exception {
        LibraryActivity libraryActivity = Robolectric.buildActivity(LibraryActivity.class).create().get();


    }
}
```

Finally, my robolectric.properties:

```
emulateSdk=19
constants=com.moxiesoft.mylibrary.BuildConfig
```

`MyRobolectricGradleTestRunner` overrides `getAppManifest` to restore the ability to specify a test-specific AndroidManifest.xml instead of using the application version.

When I attempt to run `testOnCreate` from Android Studio or gradle command line, I get a class def not found error for `android/support/v7/appcompat/R$styleable`:

```
android/support/v7/appcompat/R$styleable
java.lang.NoClassDefFoundError: android/support/v7/appcompat/R$styleable
    at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:109)
    at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
    at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
    at com.moxiesoft.mylibrary.LibraryActivity.onCreate(LibraryActivity.java:13)
    at android.app.Activity.performCreate(Activity.java:5133)
    at org.robolectric.util.ReflectionHelpers$3.run(ReflectionHelpers.java:144)
    at org.robolectric.util.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:241)
    at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:138)
    at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:309)
    at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:47)
    at org.robolectric.util.ActivityController.create(ActivityController.java:118)
    at org.robolectric.util.ActivityController.create(ActivityController.java:129)
    at com.moxiesoft.mylibrary.LibraryActivityTest.testOnCreate(LibraryActivityTest.java:20)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:235)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:168)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

How can I resolve this error?

**Comment by erd** [comment] 2015-05-12 15:56
Are you using 3.0-rc2 or 3.0-SNAPSHOT?

**Comment by dwb357** [comment] 2015-05-12 16:46
I've tried it with both and the behavior is the same.

**Comment by dwb357** [comment] 2015-05-12 16:48
Oh, and strike the comments about using a custom runner. That is no longer necessary as of gradle 1.2 and 3.0-rc2.

**Comment by nenick** [comment] 2015-05-12 17:42
I have an example for this kind which shows what is necessary to get this work https://github.com/nenick/AndroidStudioAndRobolectric/tree/library-with-aar

**Comment by dwb357** [comment] 2015-05-12 18:41
That seems to work as a workaround.

Any chance of an actual fix?

**Comment by erd** [comment] 2015-05-12 19:50
> Any chance of an actual fix?

What's the actual cause? If I knew that, I'd be happy to fix it :)

**Comment by dwb357** [comment] 2015-05-12 21:11
@nenick What I wound up using is below.  It seems to play better with Android Studio and seems to get things build more reliably:

    def package_namespace = "com.company.package"
    def package_namespace_path = package_namespace.replaceAll("\\.", "/")

    afterEvaluate { project ->
        android.libraryVariants.each { variant ->
            // workaround for missing R class for aar dependencies
            def copyTaskName = "copy${variant.name.capitalize()}AppCompat"
            task(copyTaskName, type:Copy) {
                dependsOn "process${variant.name.capitalize()}Resources"
                from { "build/generated/source/r/${variant.name}/$package_namespace_path" }
    //            into { "build/generated/source/r/${variant.name}/android/support/v7/appcompat" }
                into { "src/test/java/android/support/v7/appcompat" }
                include 'R.java'
                filter { line -> line.contains("package ${package_namespace};") ? 'package android.support.v7.appcompat;' : line }
                outputs.upToDateWhen { false }
            }
            System.out.println("adding ${copyTaskName}")
            tasks.getByName("compile${variant.name.capitalize()}UnitTestJava") dependsOn copyTaskName
        }
    }

@erd As far as the actual cause, I'm really not sure, new to much of this, but it seems like the R.java file isn't being handled correctly in the case of com.android.library.  It seems to work fine in the com.android.application case, as 2 R.java files get generated, one in android... and one in com...  With seemingly very different contents.  In the com.android.library case, it doesn't work, only one R.java is generated (in com...)  The workaround above just copies the generated R.java file into the test source tree, which means it has the wrong contents, but at least it has something that seems to start things working.  I'm quite willing to believe it's actually a defect in gradle, just a pain in the ass to work around, especially since, apparently generated java files for tests don't get picked up, so you have to put it in the src tree, not the build/generated tree.

**Comment by npike** [comment] 2015-05-15 01:13
Is this a Robolectric issue, a gradle issue, or an android gradle-plugin issue?

@dwb357 's work around is very helpful, but only gets us so far because it doesn't have any of the actual resources from src/test/res.

**Comment by mpost** [comment] 2015-05-27 15:27
We are having the same problem in 3.0-RC3. The R file from the appcompat library is not found.

**Comment by jaredsburrows** [comment] 2015-05-31 03:01
I am seeing the same with `3.0-RC3`:

<>.MainActivityTest > test FAILED
    java.lang.NoClassDefFoundError: android/support/v7/appcompat/R$styleable
        at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:118)
        at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
        at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
        at <>.BaseMainActivity.onCreate(BaseMainActivity.java:132)
        at android.app.Activity.performCreate(Activity.java:5933)
        at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
        at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
        at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:305)
        at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
        at org.robolectric.util.ActivityController.create(ActivityController.java:118)
        at org.robolectric.util.ActivityController.create(ActivityController.java:129)
        at <>.MainActivityTest.setUp(MainActivityTest.java:26)

        Caused by:
        java.lang.ClassNotFoundException: android.support.v7.appcompat.R$styleable
            at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
            at java.security.AccessController.doPrivileged(Native Method)
            at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
            at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
            at org.robolectric.internal.bytecode.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:97)
            at android.support.v7.app.AppCompatDelegateImplBase.$$robo$$onCreate(AppCompatDelegateImplBase.java:118)
            at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java)
            at android.support.v7.app.AppCompatDelegateImplV7.$$robo$$onCreate(AppCompatDelegateImplV7.java:146)
            at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java)
            at android.support.v7.app.AppCompatActivity.$$robo$$onCreate(AppCompatActivity.java:59)
            at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java)
            at <>.BaseMainActivity.onCreate(BaseMainActivity.java:132)
            at android.app.Activity.$$robo$$performCreate(Activity.java:5933)
            at android.app.Activity.performCreate(Activity.java)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:483)
            ... 7 more

**Comment by jcogilvie** [comment] 2015-10-02 21:30
Here's some code that works for arbitrary libraries by scanning exploded-aar.  It also does the same magic for /assets dirs.

```
afterEvaluate { project ->

    android.libraryVariants.each { variant ->
        def aars = new File(project.buildDir.absolutePath + "/intermediates/exploded-aar")
        def manifestFiles = new ArrayList<File>()

        // Iterate through the exploded-aars directory, finding the manifests
        aars.eachFileRecurse(FILES) {
            if (it.name.endsWith('AndroidManifest.xml') && !it.absolutePath.contains('aapt')) {
                manifestFiles.add(it)
            }
        }

        // TODO extract from our manifest?  Should be on the build variant
        def myPackageNamespace = ${INSERT YOUR PACKAGE NAMESPACE HERE, com.myapp.whatever}
        def myPackagePath = myPackageNamespace.replaceAll("\\.", "/")

        manifestFiles.each {
            def parsedManifestRoot = (new XmlParser()).parse(it.absolutePath)
            def targetPackageNamespace = parsedManifestRoot.@package
            def manifestDirectory = it.parent

            def targetPackageNamespacePath = targetPackageNamespace.replaceAll("\\.", "/")
            def copyRJavaTaskName = "copy${variant.name.capitalize()}" +
                    targetPackageNamespacePath.split("/").collect {
                        it.toString().capitalize()
                    }.join("")

            task(copyRJavaTaskName, type: Copy) {
                dependsOn "process${variant.name.capitalize()}Resources"
                from { "build/generated/source/r/${variant.name}/$myPackagePath" }
                into { "src/test/java/$targetPackageNamespacePath" }
                include 'R.java'
                filter { line -> line.contains("package ${myPackageNamespace};") ? "package ${targetPackageNamespace};" : line }
                outputs.upToDateWhen { false }
            }

            tasks.getByName("compile${variant.name.capitalize()}UnitTestJavaWithJavac") dependsOn copyRJavaTaskName

            def copyAssetsTaskName = "copy${variant.name.capitalize()}" +
                    targetPackageNamespacePath.split("/").collect {
                        it.toString().capitalize()
                    }.join("") + "Assets"

            task(copyAssetsTaskName, type: Copy) {
                dependsOn "process${variant.name.capitalize()}Resources"
                from { "${manifestDirectory}/assets" }
                into { "build/intermediates/bundles/${variant.name}/assets" }
                include '**/*'
                outputs.upToDateWhen { false }
            }

            tasks.getByName("test${variant.name.capitalize()}UnitTest") dependsOn copyAssetsTaskName

        }

    }
}
```

**Comment by srinisoundar** [comment] 2015-10-09 07:33
@jcogilvie what is FILES here ??? I'm getting an error on the below line
 aars.eachFileRecurse(FILES) {

Error:(54, 1) Execution failed 
> Could not find property 'FILES' on task ':discoverManifestFiles'.

**Comment by srinisoundar** [comment] 2015-10-09 07:52
@jcogilvie It worked !!!!!!!!!! thank you.. I added the below line which is missing 
import static groovy.io.FileType.FILES

**Comment by MartinRajniak** [comment] 2015-10-28 11:16
Have you actually tried this scenario without using Robolectric? I mean reference library resource in Android Unit Test but without Robolectric support? I have created a minimal test project to try it out and I am seeing exactly same issues. So it might be that this one is not on Robolectric. You can check out more here: https://groups.google.com/d/msg/adt-dev/RacBvzBTq9M/5fEv9QD2BwAJ

**Comment by shubhamchaudhary** [comment] 2015-10-30 14:18
Same issue with Robolectric 3.0

```

java.lang.NoClassDefFoundError: android/support/v7/appcompat/R$styleable

        at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:118)
        at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
        at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
        at com.shubhamchaudhary.boom.library.ui.base.BaseBoomActivity.onCreate(BaseBoomActivity.java:27)
        at android.app.Activity.performCreate(Activity.java:5933)
        at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
        at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
        at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
        at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
        at org.robolectric.util.ActivityController.create(ActivityController.java:118)
        at org.robolectric.util.ActivityController.create(ActivityController.java:129)
        at org.robolectric.util.ActivityController.setup(ActivityController.java:210)
        at org.robolectric.Robolectric.setupActivity(Robolectric.java:46)
        at com.shubhamchaudhary.boom.library.ui.base.BaseBoomActivityTest.setUp(BaseBoomActivityTest.java:29)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
        at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
        at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
        at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
        at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
        at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
        Caused by: java.lang.ClassNotFoundException: android.support.v7.appcompat.R$styleable
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.robolectric.internal.bytecode.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:97)
        at android.support.v7.app.AppCompatDelegateImplBase.$$robo$$onCreate(AppCompatDelegateImplBase.java:118)
        at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java)
        at android.support.v7.app.AppCompatDelegateImplV7.$$robo$$onCreate(AppCompatDelegateImplV7.java:146)
        at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java)
        at android.support.v7.app.AppCompatActivity.$$robo$$onCreate(AppCompatActivity.java:59)
        at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java)
        at com.shubhamchaudhary.boom.library.ui.base.BaseBoomActivity.onCreate(BaseBoomActivity.java:27)
        at android.app.Activity.$$robo$$performCreate(Activity.java:5933)
        at android.app.Activity.performCreate(Activity.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
        at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
        at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
        at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
        at org.robolectric.util.ActivityController.create(ActivityController.java:118)
        at org.robolectric.util.ActivityController.create(ActivityController.java:129)
        at org.robolectric.util.ActivityController.setup(ActivityController.java:210)
        at org.robolectric.Robolectric.setupActivity(Robolectric.java:46)
        at com.shubhamchaudhary.boom.library.ui.base.BaseBoomActivityTest.setUp(BaseBoomActivityTest.java:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
        at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
        at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
        at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
        at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)

```

**Comment by jongerrish** [comment] 2018-10-31 16:08
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.

**Closed by jongerrish** 2018-10-31 16:08 UTC
