### ISSUE TITLE
Getting Nullpointer in Android Studio Flamingo Stable

### ISSUE THREAD

**Issue by kenshin171** [robolectric/robolectric#8160] opened 2023-04-19 07:52 UTC
### Description
After upgrading to Android Studio Flamingo Stable, robolectric tests are getting nullpointer exception on ActivityThread, stack trace below

```
ShadowActivityThread.reset: ActivityThread not set
java.lang.NullPointerException: ShadowActivityThread.reset: ActivityThread not set
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at org.robolectric.shadows.ShadowActivityThread.reset(ShadowActivityThread.java:284)
	at org.robolectric.Shadows.reset(Shadows.java:2665)
	at org.robolectric.android.internal.AndroidTestEnvironment.resetState(AndroidTestEnvironment.java:657)
	at org.robolectric.RobolectricTestRunner.lambda$finallyAfterTest$0(RobolectricTestRunner.java:370)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:86)
	at org.robolectric.RobolectricTestRunner.finallyAfterTest(RobolectricTestRunner.java:368)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:298)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Steps to Reproduce
Just run robolectric tests

### Robolectric & Android Version
Robolectric: 4.10

Android Studio version
-------------------------------
Android Studio Flamingo | 2022.2.1
Build #AI-222.4459.24.2221.9862592, built on March 31, 2023
Runtime version: 17.0.6+0-17.0.6b802.4-9586694 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=777777
    ide.editor.tab.selection.animation=true
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=777777
    gradle.version.catalogs.dynamic.support=true

Non-Bundled Plugins:
    org.toml.lang (222.4459.17)
    idea.plugin.protoeditor (222.4459.16)
    org.intellij.plugins.markdown (222.4345.5)
    com.nbadal.ktlint (0.12.0)
    com.chrisrm.idea.MaterialThemeUI (7.14.2)

**Comment by utzcoz** [comment] 2023-04-19 08:03
@kenshin171 Please attach a minimal reproducable sample for this issue, I can run it with Flamingo to test its behavior.

**Comment by hoisie** [comment] 2023-04-19 16:38
There was a bug that caused failures in resetters to just be ignored, causing subtle bugs. This was fixed in [robolectric/src/test/java/org/robolectric/RobolectricTestRunnerTest.java.](https://github.com/robolectric/robolectric/commit/65654a76ce6f166301ab1efb2047bab1998f8949).

If you are seeing this issue, it means that there is a failure very early in test setup. Can you set a breakpoint at https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/android/internal/AndroidTestEnvironment.java#L133 and trace through `setUpApplicationState` and see where the exception is happening?

**Comment by kenshin171** [comment] 2023-04-21 02:52
seems to throw nullpointer at `provider.reset()` at `AndroidTestEnvironment.java`
```
  @Override
  public void resetState() {
    Locale.setDefault(initialLocale);
    for (ShadowProvider provider : shadowProviders) {
      provider.reset(); // thrown here
    }
  }
```

which leads to `ShadowActivityThread.java` class at
```
  @Resetter
  public static void reset() {
    Object activityThread = RuntimeEnvironment.getActivityThread();
    Objects.requireNonNull(activityThread, "ShadowActivityThread.reset: ActivityThread not set"); //thrown here
    reflector(_ActivityThread_.class, activityThread).getActivities().clear();
  }
}
```

**Comment by kenshin171** [comment] 2023-04-21 03:59
going back down to robolectric 4.8.2 seems to be ok.

**Comment by Ambeco** [comment] 2023-04-26 15:54
I had some tests with `@Config(qualifiers = "in")` which were failing because that didn't set the locale language like I'd intended. When I corrected these to `@Config(qualifiers = "+hi_IN")`, now the tests suddenly fail with this exception instead. I suspect the issue is that I never created an Activity in my test. My test has nothing to do with Activities.

**Comment by mlilienberg** [comment] 2023-04-27 13:49
We have same issue. For us the issue started to appear suddenly only on CI.

**Comment by utzcoz** [comment] 2023-04-27 15:03
Can anyone attach a reproducable sample for it by following https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues? If you don't provide the sample to reproduce it, it's difficult to us to investigate it.

**Comment by hoisie** [comment] 2023-04-27 16:30
If people are seeing `ShadowActivityThread.reset: ActivityThread not set`, it is a symptom, not the root cause, of the test failure. The issue is that the test is failing at a very early part of initialization, and then resetters run. Because the ActivityThread is not yet set, you are seeing this exception.

That being said, I think we should relax the ShadowActivityThread resetter to not throw an exception. I'll try prototyping that.

**Comment by icbaker** [comment] 2023-05-02 14:09
> If people are seeing `ShadowActivityThread.reset: ActivityThread not set`, it is a symptom, not the root cause, of the test failure. The issue is that the test is failing at a very early part of initialization, and then resetters run. Because the ActivityThread is not yet set, you are seeing this exception.

@hoisie Do you have any tips for discovering the 'true' root cause that is triggering this error? I'm seeing this on every test in https://github.com/androidx/media after upgrading from 4.8.1 to 4.10 but none of my teammates are, and I'm struggling to pin down what's different about my set up - it might help to be able to see the 'real' error to give me a hint.

**Comment by utzcoz** [comment] 2023-05-03 11:04
@icbaker It might related to your running Linux environment. We have encountered similar issues when running Robolectric 4.9 on old Linux environment. The `libconscrypt_openjdk_jni-linux*.so` might be compiled with `libstdc++.so.6`, but your running Linux doesn't have it. You can upgrade your toolchains.

**Comment by utzcoz** [comment] 2023-05-03 11:09
@icbaker Another solution you can use to avoid `java.lang.UnsatisfiedLinkError: /tmp/libconscrypt_openjdk_jni-linux-x86_6416831044223480000.so` is to disable `ConscryptMode` to use BouncyCastle as a workaround.

**Comment by icbaker** [comment] 2023-05-03 11:11
I think changing my JDK setting is good enough as a solution (is there a reason it shouldn't be?) - I'm now unblocked from this particular problem, thanks.

**Comment by utzcoz** [comment] 2023-05-03 11:13
@icbaker Thanks for your confirmation. I will close this issue as 4.10.1 fixes it. Feel free to reopen this issue if it still exists with 4.10.1 in your part.

**Closed by utzcoz** 2023-05-03 11:13 UTC

**Comment by hoisie** [comment] 2023-05-03 13:03
See https://github.com/google/conscrypt/issues/874 for details.
