### ISSUE TITLE
Issue inflating a view with a style referenced via an attribute

### ISSUE THREAD

**Issue by athkalia** [robolectric/robolectric#2641] opened 2016-09-14 10:17 UTC
I have a button that looks like this:

```xml
   <Button
            android:id="@+id/button_view_card_history"
            style="?attr/borderlessBrandButtonStyle"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/grid_view_circles"
            android:textColor="@color/purple"
            android:gravity="center|start"
            android:text="@string/mm_circles_card_button_view_history"
            android:paddingEnd="@dimen/padding_medium"
            android:paddingStart="@dimen/padding_medium" />
```

and my attrs.xml looks like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <attr name="borderlessBrandButtonStyle" format="reference" />
</resources>
```

and my theme looks like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Theme.Monitor" parent="Theme.AppCompat.Light.NoActionBar">
        <!--main colors-->
        <item name="colorPrimary">@color/purple</item>
        <item name="colorPrimaryDark">@color/purple_dark</item>
        <item name="colorAccent">@color/cyan</item>

        <item name="borderlessBrandButtonStyle">@style/BorderLessButton.Brand</item>
    </style>
</resources>
```

then finally the actual style looks like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:android="http://schemas.android.com/apk/res/android">
    <style name="BorderLessButton" parent="Widget.AppCompat.Button">
        <item name="android:background">?selectableItemBackground</item>
    </style>

    <style name="BorderLessButton.Brand">
        <item name="android:textColor">?colorPrimary</item>
    </style>
</resources>
```

Robolectric is giving me the usual exception:

```
android.view.InflateException: XML file build\intermediates\res\merged\qa\debug\layout\view_card_circles.xml line #-1 (sorry, not yet implemented): null

    at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
    at android.view.View.inflate(View.java:19784)
    at com.babylon.monitor.features.widgets.circles.view.CirclesCardWidget.init(CirclesCardWidget.java:66)
    at com.babylon.monitor.features.widgets.circles.view.CirclesCardWidget.<init>(CirclesCardWidget.java:55)
    at com.babylon.monitor.features.widgets.circles.view.CirclesCardWidgetTest.setUp(CirclesCardWidgetTest.java:50)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:265)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:191)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:56)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:157)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NullPointerException
    at org.robolectric.shadows.ShadowAssetManager.buildAttributes(ShadowAssetManager.java:654)
    at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:103)
    at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:52)
    at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:270)
    at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
    at android.content.Context.obtainStyledAttributes(Context.java:532)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
    ... 25 more
```

As soon as I remove the style line from my view

```
    style="?attr/borderlessBrandButtonStyle"
```

the exception goes away.

Is there a trick to this? I tried RoboAttributeSets like this

```java
RoboAttributeSet.create(context, new Attribute("package:attr/borderlessBrandButtonStyle", "@style/BorderLessButton.Brand", "package"))
```

but that didn't seem to do much. Is RoboAttributeSets only for custom attributes with values or for references as well?

Cheers,
Sakis

**Comment by caltseng** [comment] 2017-03-06 22:04
I have the same issue for the below style. 

`Caused by: java.lang.RuntimeException: no value for android:attr/indeterminateProgressStyle in theme with applied styles: [Style android:Theme_DeviceDefault (and parents) (forced), Style com.package.name:Theme_XXX (and parents) (forced)]`

```
  <ProgressBar
        android:id="@+id/blocking_progress_bar"
        style="?android:attr/indeterminateProgressStyle"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:indeterminate="true"
        android:interpolator="@android:interpolator/cycle" />
```

**Comment by annaparanycz** [comment] 2017-05-19 08:13
I have found a fix that worked for similar issue. 
The problem happens because the theme isn't loaded so the value is empty.
Depends on how the activity is defined in the test, but you might need to set the theme on the activity:
```
final FragmentActivity activity = Robolectric.setupActivity(FragmentActivity.class);
activity.setTheme(R.style.your_theme);
```
I guess if using an activity defined in manifest, then we need to make sure to provide appropriate manifest that will have the theme in xml.
This will load the value of the attribute from the supplied theme, otherwise its value is null

**Comment by WilliamXi** [comment] 2017-06-13 21:02
I got this issue too. And activity.setTheme() won't apply to my case. Just like [ShadowListViewTest](https://github.com/robolectric/robolectric/blob/master/robolectric/src/test/java/org/robolectric/shadows/ShadowListViewTest.java), in my test code, Activity is not initialized at all.

My code is below. Before using ?attr in layout, it worked well. Now it throws exception.
`View rowView = myListInstance.getView(0, null, new ListView(RuntimeEnvironment.application`

**Comment by TylerGoeringer** [comment] 2017-09-14 19:44
> I got this issue too. And activity.setTheme() won't apply to my case.

If the Theme isn't coming from the manifest (which it may not be, especially if you don't have an activity), it's likely coming from the context given by RuntimeEnvironment.application. Instead of using that you can actually just create a fake Activity (any activity is fine) and use that in place of RuntimeEnvironment.application.

I had the same issue when unit testing some custom GuidanceStylists and this worked for me.

**Comment by KevinLeigh** [comment] 2018-02-06 16:52
Does anyone have a solution to this issue?

**Comment by caltseng** [comment] 2018-02-06 17:05
@KevinLeigh I ended up creating a Shadow View and setting it for all tests that run into it.

**Comment by KevinLeigh** [comment] 2018-02-06 17:09
@caltseng Please could you provide me with a snippet of what the shadow view looks like with example usage?

**Comment by jongerrish** [comment] 2018-02-06 17:13
If someone can create a simple test in the Robolectric project I'll take a
look at this.

**Comment by caltseng** [comment] 2018-02-06 17:39
@KevinLeigh Take a look at what we did below. I've done a quick search for you and also included links that may be helpful. 

http://robolectric.org/javadoc/3.0/org/robolectric/shadows/ShadowView.html
http://robolectric.blogspot.com/2011/01/how-to-create-your-own-shadow-classes.html

```
/**
 * Shadow view for problematic view
 */
@Implements(value = CustomProgressView.class)
public class ShadowCustomProgressView extends ShadowView {
    @RealObject
    private CustomProgressView mCustomProgressView;

    // Overriding this to prevent inflation 
    @Implementation
    @LayoutRes
    protected int getLayoutToInflate() {
        return 0;
    }

    public void __constructor__(Context context, AttributeSet attrs, int defStyle) {
    }

    /**
     * Override the constructors to prevent layout of the CustomProgressView, which is incompatible with Robolectric
     */
    public void __constructor__(Context context, AttributeSet attrs) {
    }

    public void __constructor__(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
    }

}

// Add the shadow into your test configuration
@RunWith(CustomTestRunner.class)
@Config(shadows = {ShadowCustomProgressView.class}, sdk = Build.VERSION_CODES.M)
public class CustomFragmentUnitTests {

```

**Comment by KevinLeigh** [comment] 2018-02-06 18:28
@caltseng Thanks for the code snippet will test this and let you know if it works

**Comment by KevinLeigh** [comment] 2018-02-07 08:01
@caltseng The snippet of code you provided I updated to the view that is causing the issue and unfortunately I am still getting an issue as seen below.

Exception:
`android.view.InflateException: XML file build/intermediates/res/merged/debug/layout-v21/some_layout.xml line #-1 (sorry, not yet implemented): no value for com.superbalist.android:attr/indeterminateProgressStyle in theme with applied styles`

Should the code snippet you provided work for views inflated from the xml layout file?

**Comment by KevinLeigh** [comment] 2018-02-07 13:22
@caltseng Is there some way we can pass an instance of `Robolectric.buildAttributeSet()` to view that is going to be inflated via xml file?

**Comment by KevinLeigh** [comment] 2018-02-16 14:43
@athkalia @caltseng I have found a workaround to getting the exception `java.lang.RuntimeException: no value for android:attr/indeterminateProgressStyle in theme with applied styles`. 

Step 1) Create a `ShadowTheme` class extending `org.robolectric.shadows.ShadowResources.ShadowTheme`, as seen below:

```java
import android.content.res.Resources;
import android.content.res.TypedArray;
import android.util.AttributeSet;
import org.robolectric.Robolectric;
import org.robolectric.annotation.Implementation;
import org.robolectric.annotation.Implements;
import org.robolectric.shadows.ShadowResources;

@Implements(value = Resources.Theme.class)
public class ShadowTheme extends ShadowResources.ShadowTheme {


    @Implementation
    @Override
    public TypedArray obtainStyledAttributes(AttributeSet set, int[] attrs, int defStyleAttr, int defStyleRes) {
        try {
            return super.obtainStyledAttributes(set, attrs, defStyleAttr, defStyleRes);
        } catch (Throwable err) {
            AttributeSet attributeSet = Robolectric.buildAttributeSet()
                    .addAttribute(android.R.attr.layout_width, "0dp")
                    .addAttribute(android.R.attr.layout_height, "0dp")
                    .build();
            return super.obtainStyledAttributes(attributeSet, attrs, defStyleAttr, defStyleRes);
        }
    }
}
``` 

Step 2: Add shadow to `@RunWith` shadows annotation value, as seen below:

```java
import android.os.Build;
import com.superbalist.android.BuildConfig;
import com.superbalist.android.test.shadow.ShadowTheme;
import org.junit.runner.RunWith;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;

@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class,
        sdk = Build.VERSION_CODES.N_MR1,
        shadows = {ShadowTheme.class})
public class MyUnitTest {

}
```

**Comment by jongerrish** [comment] 2018-10-31 17:49
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.

**Comment by ElizAWard** [comment] 2018-11-01 15:32
This seems to still be an issue with Robolectric 4.0, Android Studio 3.1.2,

I just tried android.enableUnitTestBinaryResources=true in my gradle.properties, I'm still getting the InflateException with a custom style as an attribute. I'm using attribute because I need to be able to swap between a light and a dark theme.

**Comment by jongerrish** [comment] 2018-11-01 20:36
@ElizAWard What Context are you using? It is required that the context you are using has the correct theme set on it that contains that attribute.

This can be an Activity that is defined in your manifest, or even one that is not, if a theme is not defined for your activity it will default to the one set in your AndroidManifest.xml <application theme="...">

Note, that your Application context will always have the platform default theme, this is the same behavior on a real device.

**Comment by ElizAWard** [comment] 2018-11-01 20:49
Using "ApplicationProvider.getApplicationContext()" to get my Context
<addr>
@Before
public void setUp() throws Exception {
  View view = View.inflate(ApplicationProvider.getApplicationContext(), R.layout.sample_cardview, null);
}
</addr>

**Comment by jongerrish** [comment] 2018-11-01 22:53
@ElizAWard - Right, that is the problem, your application context will not have your applications theme set on it as declared in <Application theme="..."/> it will have the platforms default theme.

I know, I know this is very counter intuitive, but that is how it works on a real device :-)

You can do three things.

1)
Application app = ApplicationProvider.getApplicationContext();
app.setTheme(R.style.myTheme);

2)

Context context = new ContextThemeWrapper(ApplicationProvider.getApplicationContext(), R.style.myTheme)

3)

Activity activity = Robolectric.setupActivity(Activity.class);

Can you confirm that works for you?

**Comment by ElizAWard** [comment] 2018-11-02 15:40
I've tried all three, to no avail. I'm no longer certain I even want to chase this unit test.

**Comment by jongerrish** [comment] 2018-11-02 15:56
@ElizAWard are you sure that the attribute is in the theme you're specifying on the context you're passing into your view? 

If you can give more specifics about your case I'm happy to help.

**Comment by ElizAWard** [comment] 2018-11-02 17:49
That finally did the trick. Had to set the theme using the ContextThemeWrapper, and make sure that we used a theme that had that attr actually set in it. Thank you.

**Comment by jongerrish** [comment] 2018-11-05 00:12
Perfect, thanks for your patience working through the issue with me and glad you're unblocked :-)

Closing.

**Closed by jongerrish** 2018-11-05 00:12 UTC
Labels: resources

**Comment by ElizAWard** [comment] 2018-12-03 17:34
@caltseng I've got my setup that was required below. The TextView in the layout had a custom style on it like in the original post. I had to apply a theme to the activity/context as needed that the custom style could use.

```
FragmentActivity activity;
FragmentManager fragmentManager;

public void setup() {
    activity = Robolectric.setupActivity(TestActivity.class);
    activity.setTheme(R.style.MyLightTheme);
    fragmentManager = activity.getSupportFragmentManager();
    // fragmentManager used in other unit tests
}

@Test
public void testLabel() {
    Context context = new ContextThemeWrapper(ApplicationProvider.getApplicationContext(), R.style.MyLightTheme);
    View myView = View.inflate(context, R.layout.my_test_layout, null);
    TextView textView = (TextView)myView.findViewById(R.id.test_text);

    assertThat(textView.getText()).isEqualTo("Test");
}
```

**Comment by milosmns** [comment] 2019-06-04 10:01
@jongerrish 
```kotlin
context.setTheme(R.style.LightTheme)
```
☝️this works, tnx.

**Comment by geo-balazs-toth** [comment] 2019-09-03 11:07
I used this helper to create the context as I wasn't using an activity, was just testing the views. For most of the tests the application context works as is.
`private Context getContext() {
    Context appContext = ApplicationProvider.getApplicationContext();
    return new ContextThemeWrapper(appContext, R.style.GeoTheme);
  }`

**Comment by slott** [comment] 2020-04-21 12:37
I'm having this issue all of a sudden - and my solution was to add the theme when calling launchInContainer

example:

`FragmentScenario.launchInContainer(cls, bundle, R.style.AppTheme, new FragmentFactory() {...});`

Many thanks for the above comments - wouldn't have been able to nail this without it.

Hoping this will help others in a similar situation.
