### ISSUE TITLE
Unable to mix Espresso and Robolectric when verifying menu options

### ISSUE THREAD

**Issue by dmeng** [robolectric/robolectric#4862] opened 2019-04-06 00:43 UTC
### Description

Still writing more stuff for https://github.com/googlesamples/android-architecture/tree/todo-mvvm-live-kotlin, but now getting failures when trying to test menu options.

In TasksSingleScreenTest, both display tests error out with something like

```
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "TITLE1"
If the target view is not part of the view hierarchy, you may need to use Espresso.onData to load it from one of the following AdapterViews

...<the view hierarchy>...

	at java.lang.Thread.getStackTrace(Thread.java:1556)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:94)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:57)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:316)
	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:177)
	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:118)
	at com.example.android.architecture.blueprints.todoapp.tasks.TasksSingleScreenTest.viewActiveTasks(TasksSingleScreenTest.kt:116)
```

with line 116 being

```
onView(withText(R.string.nav_active)).perform(click())
```

while the delete tests fail with

```
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: com.example.android.architecture.blueprints.todomvvmlivekotlin.mock:id/menu_delete
If the target view is not part of the view hierarchy, you may need to use Espresso.onData to load it from one of the following AdapterViews

...<the view hierarchy>...

	at java.lang.Thread.getStackTrace(Thread.java:1556)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:94)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:57)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:316)
	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:177)
	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:118)
```

with the `perform()` call corresponding to
```
    onView(withId(R.id.menu_delete)).perform(click())
```

in the test.

TaskSingleScreenInstrumentedTest is in the code to show that doing the same verification works on emulator

### Steps to Reproduce

Run any of the tests inside TaskSingleScreenTest (though the delete examples may need to be run on their own) in the provided code

### Robolectric & Android Version

Robolectric: 4.3-alpha-2
Android SDK 28
Android Studio 3.3.2

### Link to a public git repo demonstrating the problem:

Pull down https://github.com/dmeng/android-architecture/tree/todo-mvvm-live-kotlin at commit 9107c289bf1aa9c3d4b6795a370f74ec1f802cac

**Comment by calvarez-ov** [comment] 2019-04-06 15:04
This may be a duplicate of https://github.com/robolectric/robolectric/issues/4354

**Comment by dmeng** [comment] 2019-04-16 20:49
Reopening as while the changes do address some problems, it doesn't fully address the specific example outlined here.

**Closed** 2019-04-18 21:35 UTC
Labels: codelab support
