### ISSUE TITLE
PendingIntent not equals() itself

### ISSUE THREAD

**Issue by alanharder** [robolectric/robolectric#2117] opened 2015-10-28 21:29 UTC
I found the following surprise when running under robolectric:

PendingIntent pending = PendingIntent.getService(null, 0, null, 0);
System.err.println(pending.equals(pending));

This prints false!  The same is true if getService is replaced with getActivity or getBroadcast.
Is this a bug in robolectric? (I'm having trouble testing some code that uses PendingIntent.equals(), so I hope so..).

**Comment by ened** [comment] 2015-11-24 07:50
Does it work on a device?

**Comment by jaredsburrows** [comment] 2015-11-24 18:36
Why are you comparing PendingIntents? Does this work on an actual device?

Here is the docs for `PendingIntent#equals`:

```
    /**
     * Comparison operator on two PendingIntent objects, such that true
     * is returned then they both represent the same operation from the
     * same package.  This allows you to use {@link #getActivity},
     * {@link #getBroadcast}, or {@link #getService} multiple times (even
     * across a process being killed), resulting in different PendingIntent
     * objects but whose equals() method identifies them as being the same
     * operation.
     */
    @Override
    public boolean equals(Object otherObj) {
        if (otherObj instanceof PendingIntent) {
            return mTarget.asBinder().equals(((PendingIntent)otherObj)
                    .mTarget.asBinder());
        }
        return false;
    }
```

**Comment by gugario** [comment] 2016-03-07 21:25
Just got stumped by this when converting some tests to Robolectric.

Yes, this does work on a real device when using AndroidTestCase.

To answer Jared's question, PendingIntent#equals() can be useful when you want to de-duplicate registrations from the same client app.  For instance, an app may register to you with a PendingIntent every time it's opened, and you'd end up with multiple registrations if you didn't use equals().

**Comment by jqln-0** [comment] 2016-05-05 11:21
I think this is an issue with how ShadowPendingIntent shadows the equals method. See here:

https://github.com/robolectric/robolectric/blob/78ef7facd8df6c2c2f8dafedfbc2d1af19f3558e/robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowPendingIntent.java#L134

It compares getClass() with o.getClass(), which won't quite work as expected. getClass() returns ShadowPendingIntent because that's the class we're in, but the object we're comparing to will still appear to be a completely ordinary PendingIntent and so the check will fail.

I'll put together a quick test case to double check and send a patch for this if I'm right.

**Comment by jongerrish** [comment] 2018-11-05 01:05
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

**Closed by jongerrish** 2018-11-05 01:05 UTC
