### ISSUE TITLE
Robolectric does not support API level 23

### ISSUE THREAD

**Issue by hiquanta** [robolectric/robolectric#2540] opened 2016-07-01 09:27 UTC
### Description
java.lang.UnsupportedOperationException: Robolectric does not support API level 23.

	at org.robolectric.internal.SdkConfig.<init>(SdkConfig.java:42)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:187)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
### Robolectric & Android Version
3.1  & 23

**Comment by jongerrish** [comment] 2016-07-07 16:40
Robolectric 3.1 does support API 23 - all of our own tests run against API 23.

Are you sure you are using Robolectric 3.1 or is there something unique about your configuration?

**Comment by NeilConcur** [comment] 2016-07-08 14:09
@jongerrish I am migrating my app to API 23 and am also using Robolectric 3.1. At the moment, 80% of my test cases are failing. Is there a migration guide? Please advise.

**Comment by jongerrish** [comment] 2016-07-08 15:23
Yes:-

https://github.com/robolectric/robolectric/wiki/3.0-to-3.1-Upgrade-Guide

If there are any errors outside of that let me know and we'll figure it out
and update the wiki

**Comment by NeilConcur** [comment] 2016-07-13 15:07
@jongerrish I tried the migration guide and 80% of the test cases are still failing. 
I do have this line above my class name:
@Config(application = CoreTestApplication.class, manifest = "AndroidManifest.xml", sdk = 21)

Do I need to change it to sdk = 23 first? I did that and all the test cases failed. If that is the right thing to do, I will change it to 23 first and try to debug. Please advise.

**Comment by xian** [comment] 2016-07-13 15:10
Are you still getting the same UnsupportedOperationException? Are you
certain you've got Robolectric 3.1 in your project?
On Wed, Jul 13, 2016 at 08:07 NeilConcur <notifications@github.com> wrote:

> @jongerrish <https://github.com/jongerrish> I tried the migration guide
> and 80% of the test cases are still failing.
> I do have this line above my class name:
> @Config <https://github.com/Config>(application =
> CoreTestApplication.class, manifest = "AndroidManifest.xml", sdk = 21)
>
> Do I need to change it to sdk = 23 first? I did that and all the test
> cases failed. If that is the right thing to do, I will change it to 23
> first and try to debug. Please advise.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/robolectric/robolectric/issues/2540#issuecomment-232385147>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AACdavfxlEy5i3VbrhWYtukJm5HlrIOLks5qVP8zgaJpZM4JC-KR>
> .
>
-- 
--X

**Comment by NeilConcur** [comment] 2016-07-13 15:22
@xian Thank you for your comment. I have testCompile 'org.robolectric:robolectric:3.1' as part of my dependency. 

The test cases failed for different reasons. Some failed because the assert conditions are false, some failed because of out of memory exception and others failed for other reasons; however, they were fine before I migrated the app to API 23. 

For the assert conditions being false ones, I noticed that if I set the state of an object to be true, it will stay true even if I set it to be false in a different test case. 

For example:
test1 {
setBoolean(true);
assertTrue(getBoolean());
}
test2 {
setBoolean(false);
assertFalse(getBoolean());
}
test1 passed but test2 failed. It seemed like the state is fixed once it has been set.

**Comment by jongerrish** [comment] 2016-07-13 15:25
You only need to set the sdk property if you want to be explicit about which version of Android you want your tests to run against. Otherwise I believe it pulls the latest supported version that corresponds to the targeted sdk property in your manifest.

The exception you are getting suggests to me you do not have the latest version. 3.1.1 had just been released.

**Comment by jongerrish** [comment] 2016-07-13 15:28
What does your CoreTestApplication look like? Do you keep static state on it? Robolectric will create a new instance for each test but maybe you are leaking memory between tests and / or state.

For unit tests try using a very minimum application.

**Comment by NeilConcur** [comment] 2016-07-13 16:58
I just updated my dependency from 3.1 to 3.1.1 and ran some test cases. I am getting:
java.util.ServiceConfigurationError: org.robolectric.internal.ShadowProvider: Provider org.robolectric.Shadows not a subtype

I override attachBaseContext like this:
@Override
    protected void attachBaseContext(Context base) {
        try {
            super.attachBaseContext(base);
        } catch (RuntimeException ignored) {
            // Multidex support doesn't play well with Robolectric yet
        }
    }

**Comment by NeilConcur** [comment] 2016-07-13 18:01
@jongerrish 
This is the first exception:

java.lang.NullPointerException
	at org.robolectric.manifest.MetaData.init(MetaData.java:55)
	at org.robolectric.manifest.AndroidManifest.initMetaData(AndroidManifest.java:374)
	at org.robolectric.res.builder.DefaultPackageManager.addManifest(DefaultPackageManager.java:449)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:82)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:237)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:174)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:63)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:140)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by jongerrish** [comment] 2016-07-13 18:11
Can you paste all the <meta-data> from your AndroidManifest.xml.

**Comment by NeilConcur** [comment] 2016-07-13 18:57
Hi, this is the manifest file. I removed the names for privacy reason. If this is not readable or there is something specific you are looking for, please let me know.

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package=""
    android:installLocation="internalOnly" >

    <supports-screens
        android:largeScreens="true"
        android:normalScreens="true"
        android:smallScreens="true"
        android:xlargeScreens="true" />

    <uses-feature
        android:name="android.hardware.touchscreen"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.location"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.location.network"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.location.gps"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera.autofocus"
        android:required="false" />
    <uses-feature
        android:glEsVersion=""
        android:required="true" />

    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.BROADCAST_STICKY" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />

    <application
        android:name=""
        android:allowBackup="false"
        android:icon="@drawable/launch"
        android:label="@string/app_name"
        android:logo=""
        android:theme=""
        tools:replace="theme, allowBackup, icon, label" >
        <activity
            android:name=""
            android:parentActivityName=""
            android:screenOrientation="portrait"
            android:theme="" >
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value="" />
        </activity>
        <activity
            android:name=""
            android:icon="@drawable/launch"
            android:theme="@style/Translucent.NoActionBar.Material" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        <activity
            android:name=""
            android:theme="@style/White.New" />
        <activity
            android:name=""
            android:theme="@style/White.New" />
        <activity
            android:name=""
            android:theme="@style/NoActionBar"
            android:windowSoftInputMode="adjustResize" />
        <activity
            android:name=""
            android:theme="@style/White.New" />
        <activity android:name="" />
        <activity
            android:name=""
            android:theme="@style/NoActionBar" />
        <activity
            android:name=""
            android:theme="@style/NoActionBar" />
        <activity
            android:name=""
            android:theme="@style/BaseTheme.New" />
        <activity
            android:name=""
            android:theme="@style/New" />
        <activity
            android:name=""
            android:configChanges="orientation"
            android:theme="@style/White.New" >
        </activity>
        <activity android:name="" />
        <activity
            android:name=""
            android:configChanges="orientation" />
        <activity
            android:name=""
            android:theme="@style/White.New" />
        <activity
            android:name=""
            android:configChanges="orientation" />
        <activity
            android:name=""
            android:configChanges="orientation"
            android:theme="@style/Translucent.NoActionBar" />
        <activity
            android:name=""
            android:theme="@style/Dialog"
            android:windowSoftInputMode="stateVisible" />
        <activity
            android:name=""
            android:parentActivityName=""
            android:theme="@style/White.ActionBarTabs"
            android:windowSoftInputMode="stateVisible" >
            <intent-filter>
                <action android:name="android.intent.action.SEARCH" />
            </intent-filter>

            <meta-data
                android:name="android.app.searchable"
                android:resource="@xml/searchable" />
        </activity>
        <activity
            android:name=""
            android:configChanges="orientation"
            android:theme="@style/Translucent.NoActionBar" />
        <activity
            android:name=""
            android:windowSoftInputMode="adjustResize" />
        <activity
            android:name=""
            android:screenOrientation="portrait"
            android:theme="@style/White.ActionBarTabs"
            android:windowSoftInputMode="adjustResize" />
        <activity
            android:name=""
            android:screenOrientation="portrait"
            android:theme="@style/White.ActionBarTabs" />
        <activity
            android:name=""
            android:screenOrientation="portrait"
            android:theme="@style/White.ActionBarTabs" />
        <activity
            android:name=""
            android:screenOrientation="portrait"
            android:theme="@style/White.ActionBarTabs" />
        <activity
            android:name=""
            android:theme="@style/White.ActionBarTabs" />
        <activity
            android:name=""
            android:screenOrientation="portrait"
            android:theme="@style/White.ActionBarTabs" />
        <activity
            android:name=""
            android:screenOrientation="portrait" />
        <activity android:name="" />
        <activity android:name="" />
        <activity
            android:name=""
            android:screenOrientation="portrait" />
        <activity android:name="" >
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value="Home" />
        </activity>
       
        <activity
            android:name=""
            android:windowSoftInputMode="adjustResize" />
        <activity
            android:name=""
            android:windowSoftInputMode="adjustResize" />
        <activity
            android:name=""
            android:windowSoftInputMode="adjustResize" />
        <activity
            android:name=""
            android:windowSoftInputMode="stateHidden" />
        <activity android:name="" >
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value="Home" />
        </activity>
        <activity
            android:name=""
            android:theme="@style/White.ActionBarTabs" >
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value="Home" />
        </activity>
        <activity android:name="" >
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value="Home" />
        </activity>
        <activity android:name="" >
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value="RequestListActivity" />
        </activity>
        <activity android:name="" >
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value="" />
        </activity>
        <activity android:name="">
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=""/>
        </activity>
        <activity android:name="" >
            <meta-data
                android:name="             android.support.PARENT_ACTIVITY"
                android:value="" />
        </activity>
      
        <activity
            android:name=""
            android:configChanges="orientation"
            android:theme="@style/Translucent.NoActionBar" />
        <activity
            android:name=""
            android:configChanges="orientation" />
        <activity android:name="" >
            <intent-filter>
                <action android:name="android.intent.action.SEND" />
                <action android:name="android.intent.action.SEND_MULTIPLE" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="image/*" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.CHOOSER" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="image/*" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.SEND" />
                <action android:name="android.intent.action.SEND_MULTIPLE" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="application/pdf" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.CHOOSER" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="application/pdf" />
            </intent-filter>
        </activity>
        <activity android:name="" />
        <activity
            android:name=""
            android:taskAffinity="" />
        <service
        android:name=""
            android:exported="false" />

        <receiver android:name="" >
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <category android:name="android.intent.category.HOME" />
            </intent-filter>
        </receiver>

        <activity
            android:name=""
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="" />
            </intent-filter>
        </activity>
        <service
            android:name=""
            android:label="PushNotificationRegService">
        </service>
        <service
            android:name=""
            android:label="PushNotificationService">
        </service>
        <receiver
            android:name=""
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>
        <service
            android:name=""
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>
        <service
            android:name=""
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.gms.iid.InstanceID" />
            </intent-filter>
        </service>

        <activity
            android:name=""
            android:theme="@style/New" >
        </activity>
        <activity
            android:name=""
            android:configChanges="orientation"
            android:theme="@style/NoActionBar" >
        </activity>
        <activity
            android:name=""
            android:theme="@style/NoActionBar" >
        </activity>
        <activity
            android:name=""
            android:theme="@style/White.New" >
        </activity>
        <activity
            android:name=""
            android:theme="@style/Translucent.NoActionBar.Material" >
        </activity>
        <activity
            android:name=""
            android:theme="@style/NoActionBar" >
        </activity>
        <activity
            android:name=""
            android:theme="@style/NoActionBar" >
        </activity>
        <activity
            android:name=""
            android:theme="@style/NoActionBar" >
        </activity>
        <activity
            android:name=""
            android:theme="@style/NoActionBar">
        </activity>
        <activity
            android:name=""
            android:theme="@style/NoActionBar">
        </activity>
        <activity
            android:name=""
            android:theme="@style/NoActionBar">
        </activity>
        <activity
            android:name=""
            android:theme="@style/NoActionBar">
        </activity>
        <activity
            android:name=""
            android:theme="@style/NoActionBar">
        </activity>
        <activity
            android:name=""
            android:theme="@style/BaseTheme" >
        </activity>
        <activity
            android:name=""
            android:theme="@style/BaseTheme" >
        </activity>
        <activity
            android:name=""
            android:theme="@style/BaseTheme.New" >
        </activity>

        <provider
            android:name=""
            android:authorities="@string/authority_config"
            android:enabled="true"
            android:exported="false"
            android:initOrder="1"
            android:label="@string/platform_config_provider_name"
            android:syncable="false" >
        </provider>
      
        <provider
            android:name=""
            android:authorities="@string/authority"
            android:enabled="true"
            android:exported="false"
            android:initOrder="1"
            android:label="@string/platform_provider_name"
            android:syncable="false" >
        </provider>
      
        <provider
            android:name=""
            android:authorities="@string/authority_travel"
            android:enabled="true"
            android:exported="false"
            android:initOrder="1"
            android:label="@string/platform_provider_name"
            android:syncable="false" >
        </provider>
        <meta-data
            android:name=""
            android:value="" />

        <activity
            android:name=""
            android:theme="@style/heme.Transparent" />

        <receiver android:name="" >
            <intent-filter>
                <action android:name="android.net.conn.CONNECTIVITY_CHANGE" />
            </intent-filter>
        </receiver>

        <meta-data
            android:name="API_KEY"
            android:value="" />

        <meta-data
            android:name="com.google.android.gms.version"
            android:value="" />

        <activity
            android:name="com.google.android.gms.ads.AdActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:theme="@android:style/Theme.Translucent" />

        <meta-data
            android:name="ApiKey"
            android:value=""/>
    </application>

</manifest>

**Comment by jongerrish** [comment] 2016-07-13 20:54
The problem is that Robolectric is not able to resolve your res/xml/searcahble.xml file

        <meta-data
            android:name="android.app.searchable"
            android:resource="@xml/searchable" />

Can you check if its there?

**Comment by NeilConcur** [comment] 2016-07-13 23:07
I don't have the file anymore and removed that meta-data block. I ran the test suite again and it gave me the same problem. Does the exception mean it is trying to find something specified in manifest and can't find it?

**Comment by jongerrish** [comment] 2016-07-13 23:13
The exception means that it can't find a resource that you referenced in
your meta-data, and the fact that it didn't exists explains that.

If you're saying you removed the reference and still get the error then I'm
not sure, it sounds like you're working with a stale version of the
manifest since that was the only occurrence that would cause that error in
your manifest.

Do you need to rebuild your project with gradle?

Otherwise can you put a breakpoint at the line where you see the npe and
tell me what the attribute name and value it fails are?

We should be defensive about this and throw a ResourceNotFoundException
instead of an npe I think. I'll send a PR for this.

**Comment by NeilConcur** [comment] 2016-07-14 15:22
@jongerrish 
I thought about what approach I should take in order to fix the test cases because I have roughly 350 of them. I decided to fix the ones that give me exceptions first. I am not sure how I got a NPE when getting a string, any comment?

java.lang.NullPointerException
	at android.content.ContextWrapper.getResources(ContextWrapper.java:87)
	at android.view.ContextThemeWrapper.getResources(ContextThemeWrapper.java:81)
	at android.support.v7.app.AppCompatActivity.getResources(AppCompatActivity.java:537)
	**at android.content.Context.getString(Context.java:409)**
	at MY_PERSONAL_NON-TESTCASE_CODE.getModule(Module.java:65)
	at com.concur.mobile.core.config.environments.EnvironmentSettingsUnitTests.environmentList_containsConcurAndExpenseItServers_nullCustomServerInfoModule(EnvironmentSettingsUnitTests.java:39)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:465)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:248)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:174)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:63)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:140)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by NeilConcur** [comment] 2016-07-14 17:37
@jongerrish 
What is the latest stable Robolectric I should use? I am using 3.1.1 per our conversation yesterday. I did some research and some people have success with org.robolectric:robolectric:3.0-rc2, some snapshots or 3.1-rc1. I would like to make sure I am using the right version first. Please advise.

**Comment by jongerrish** [comment] 2016-07-14 18:07
Use the latest version.

Did you see the migration guide? The NPE you're getting in ContextWrapper
is because there is not attached base context. Since we now use more real
Android code you need to have an attached base context. Create Activities
and Services using Robolectric.buikdActivity() for example.

**Comment by NeilConcur** [comment] 2016-07-14 19:07
@jongerrish 
I am doing it like this: Robolectric.buildActivity(Home.class).create().get()
Should I have it as Robolectric.buildActivity(Home.class)?

**Comment by jaredsburrows** [comment] 2016-07-16 21:46
Can we close this? Robolectric 3.1 and 3.1.1 both support API 23.

**Comment by jongerrish** [comment] 2016-07-17 13:59
@NeilConcur yes, that will give you an attached base context.

Closing this issue since Robolectric works with API 23.

Please see migration guide, if you're still stuck ask on the  group.

**Closed by jongerrish** 2016-07-17 13:59 UTC
