### ISSUE TITLE
Robolectric doesn't pass tests on Windows

### ISSUE THREAD

**Issue by jcogilvie** [robolectric/robolectric#2105] opened 2015-10-22 19:30 UTC
Win 7, java 8u65.  `SQLiteLibraryLoaderTest.shouldExtractNativeLibrary`:

```

  @Before
  public void deleteExtractedLibrary() {
    loader = new SQLiteLibraryLoader();
    loader.getNativeLibraryPath().delete();
  }

  @Before
  public void saveSystemProperties() {
    savedOs = System.getProperty("os.name");
    savedArch = System.getProperty("os.arch");
  }

  @After
  public void restoreSystemProperties() {
    System.setProperty("os.name", savedOs);
    System.setProperty("os.arch", savedArch);
  }

  @Test
  public void shouldExtractNativeLibrary() {
    File extractedPath = loader.getNativeLibraryPath();
    assertThat(extractedPath).doesNotExist();
    loader.doLoad();
    assertThat(extractedPath).exists();
  }
```

Fails because the @Before operation to delete the library fails.  Not sure why--maybe the resource is still locked from other tests?  (I noticed it was used in the GestureDetector tests for instance, which happened before this.)

**Comment by jcogilvie** [comment] 2015-10-22 21:02
I've changed the `.delete()` call to `java.nio.file.Files.delete()` and it's now throwing me an `AccessDeniedException` on the delete, which I suppose is progress.  

Are we sure nobody has dangling file references somewhere?  Maybe this is a multithreading issue since we're referencing the same file in several test classes?

In any case I'm going to try to get to the actual work I was planning on doing, so I'm marking the test @Ignore for now locally...

**Comment by kriegfrj** [comment] 2015-10-23 13:29
I develop on Windows 8.1 and I have always had the same tests failing. I simply ignore them because they pass under Unix and I haven't needed to use SQLite functionality (yet). Hey, it used to be worse until we fixed a couple of other Windows-specific issues more recently! (Mostly they were to do with the use of an incorrect path separator char).

I briefly looked into fixing these last couple of failing tests just to tidy up loose ends, but because they weren't trivial and not directly related to what I was working on I reprioritised. But I think the problem is due to different file locking behaviour between Windows and Unix - in Windows, an executable is locked while it is executing so you can't delete it even if you have full access rights (which would explain the `AccessDeniedException` when you used nio). I think this is one of the reasons Windows always asks you to shut down running applications and even reboot when updating/installing new software. Unix is not so restrictive - you can delete or overwrite a running executable. So it is probable that the JNI DLL is not being unloaded by the JVM before the test attempts to delete it.

**Comment by kriegfrj** [comment] 2015-10-23 13:51
Well, here's some robo-archaeology: this issue was mentioned in #873 and @roman-mazur came to the same conclusion that I did (can't delete DLL while it is open). It looks like the spin-off (#885) was essentially a duplicate of (or perhaps a superset of) this one and was closed prematurely.

**Comment by jcogilvie** [comment] 2015-10-23 13:58
I think there are two options.  We can either put our mocking hats on with a `Mockito.spy` and use a fake file path that won't already be locked, and then override some other stuff so SQLite never actually tries to load the DLL (thereby preventing the lock from ever being taken), or we can put in a junit assumption to conditionally ignore them on windows because of the file locking differences.  

One of these is certainly more straightforward, and the other is more robust.

**Comment by kriegfrj** [comment] 2015-10-23 14:19
Stopping it from loading is not an option, because the SQL implementation in Robolectric actually uses the library to implement its functionality. The only real solution is to either try and unload the library, or simply avoid deleting the DLL altogether. I thought that the latter would be the easiest course of action but never invested the time to figure out why Robolectric feels the need to make a copy of the DLL and then delete it. It's not obvious to me why this is necessary and I suspect it is unnecessary and could be dispensed with, but I didn't want to change this behaviour without having properly understood it first. :smile:

**Comment by jcogilvie** [comment] 2015-10-23 15:20
I think it is an option; here's why:  we're talking about a unit test that's designed to verify that the DLL is extracted from some path.  That's why the @Before wants to delete the file--so we can verify that it was created when we call the method that should create it.  We can easily verify that unit of functionality by stubbing out the rest.  The test, straightforward as it is, is not well-scoped.  It's probably only written the way it is for expediency.

Once we get into the actual SQLite lib-loading stuff, we're no longer testing robolectric code, so I think it's a good candidate to be stubbed (for this specific test case; not broadly).

**Comment by kriegfrj** [comment] 2015-10-24 11:55
Ahh thanks - so the only reason it tries to delete the DLL is for testing purposes. That changes things a bit; I thought that the deletion was required functionality of Robolectric at runtime. It is still a mystery to me why Robolectric needs to copy/extract the DLL (and might explain why Robolectric still seems to leave stray temp directories around, though some improvements have been made in that area it's still not perfect).

I still don't think it will be feasible to rely on an approach that prevents the DLL from loading. If this were a standalone unit test you *might* be able to do it, but there are other tests that will load the DLL as part of their ordinary operation and you can't guarantee that one of them won't run before the `SQLiteLibraryLoaderTest`. Some form of stubbing might work, on the other hand - if you're willing to invest the time I for one would certainly welcome any attempt to iron out this last wrinkle in Windows-based Robolectric development. :smile:

**Comment by jongerrish** [comment] 2018-11-05 00:59
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

**Closed by jongerrish** 2018-11-05 00:59 UTC
