### ISSUE TITLE
Robolectric does not support API level 26

### ISSUE THREAD

**Issue by MinkiPan** [robolectric/robolectric#3298] opened 2017-08-01 11:17 UTC
> java.lang.UnsupportedOperationException: Robolectric does not support API level 26

> testCompile 'org.robolectric:robolectric:3.4'
> testCompile 'org.robolectric:shadows-multidex:3.4-rc2'
> testCompile 'org.khronos:opengl-api:gl1.1-android-2.1_r1'

what am I doing wrong, I know it supposed to be working

**Comment by MinkiPan** [comment] 2017-08-01 11:19
![screen shot 2017-08-01 at 13 18 44](https://user-images.githubusercontent.com/24230677/28823027-f9b26924-76bb-11e7-8a03-2cff71506d98.png)

thats what I see in the SdkConfig, the odd line is `this.addSdk(10000, "o-preview-2", "0", "1.8", "O")`

**Comment by jongerrish** [comment] 2017-08-01 21:18
The problem is that Robolectric builds against O developer preview 2 where the API level was not final. We'll push out a 3.4.1 tomorrow with this fix.

**Comment by MinkiPan** [comment] 2017-08-03 09:05
is it released?

**Comment by jongerrish** [comment] 2017-08-03 09:18
Code has been submitted, expect a release tomorrow.

**Comment by MinkiPan** [comment] 2017-08-04 11:29
just tried 3.4.1 still the error...

**Comment by emartynov** [comment] 2017-08-04 11:45
Guys, please update handling `@Config` annotation, it should support API 26

**Comment by jongerrish** [comment] 2017-08-04 12:34
Yes, we made a mistake when adding support for 26 final. Fix is committed
and we'll push a release tomorrow.

Sorry about that.

J

On Aug 4, 2017 8:46 PM, "Eugen Martynov" <notifications@github.com> wrote:

Guys, please update handling @Config annotation, it should support API 26

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/robolectric/robolectric/issues/3298#issuecomment-320228872>,
or mute the thread

**Comment by emartynov** [comment] 2017-08-04 13:18
No issues! Thank you for quick fix

**Closed** 2017-08-08 19:23 UTC
