### ISSUE TITLE
Support API level 24

### ISSUE THREAD

**Issue by pbismobica** [robolectric/robolectric#2594] opened 2016-08-05 14:28 UTC
Would you be able to provide ETA, when Robolectric will support API level 24? 

Kind regards,
Przemek

**Comment by mvdan** [comment] 2016-08-11 16:51
Have you seen #2554?

**Comment by pbismobica** [comment] 2016-08-29 10:43
Yes, I did. It doesn't answer my question though.

**Comment by mvdan** [comment] 2016-08-29 10:47
The first rule of open source is not to ask for ETAs :)

**Comment by jaredsburrows** [comment] 2016-09-03 05:31
Duplicate of https://github.com/robolectric/robolectric/issues/2554.

**Comment by xian** [comment] 2017-01-05 02:55
Robolectric 3.2 supports API 24.

**Closed by xian** 2017-01-05 02:55 UTC
