### ISSUE TITLE
Support appcompat-v7 22.2.0

### ISSUE THREAD

**Issue by kluz88** [robolectric/robolectric#1859] opened 2015-06-02 08:16 UTC
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:122)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
	at de.psdev.stabbedandroid.StabbedAppCompatActivity.onCreate(StabbedAppCompatActivity.java:31)
	at com.purplemotion.app.purple.TrackingStabbedAppCompatActivity.onCreate(TrackingStabbedAppCompatActivity.java:27)
	at com.purplemotion.app.purple.PurpleBaseActivity.onCreate(PurpleBaseActivity.java:91)
	at com.purplemotion.app.purple.splash.SplashActivity.onCreate(SplashActivity.java:85)
	at android.app.Activity.performCreate(Activity.java:5133)
	at org.robolectric.util.ReflectionHelpers$3.run(ReflectionHelpers.java:144)
	at org.robolectric.util.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:241)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:138)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:309)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:47)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at com.purplemotion.app.purple.splash.SplashActivityTest.setup(SplashActivityTest.java:21)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:235)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:168)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by jaredsburrows** [comment] 2015-06-04 02:12
Example test to reproduce this:

package com.test.test;

import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.RobolectricGradleTestRunner;
import android.support.v7.app.AppCompatActivity;
import android.support.v4.app.FragmentActivity;
import static org.robolectric.util.SupportFragmentTestUtil.startFragment;
import static org.robolectric.util.SupportFragmentTestUtil.startVisibleFragment;

@RunWith(RobolectricGradleTestRunner.class)
public class MainFragmentTest {
  private MainFragment subject;

  @Before
  public void setUp() throws Exception {
    subject = new MainFragment();
  }

  @Test
  public void test() {
    startFragment(subject, AppCompatActivity.class);
  }
}

**Comment by JorgeCastilloPrz** [comment] 2015-06-23 11:11
Crashing for 2.4.
```java
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:122)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
	at com.oneupsports.coreapp.ui.MainActivity.onCreate(MainActivity.java:47)
	at android.app.Activity.performCreate(Activity.java:5008)
	at org.robolectric.internal.ReflectionHelpers$3.run(ReflectionHelpers.java:64)
	at org.robolectric.internal.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:114)
	at org.robolectric.internal.ReflectionHelpers.callInstanceMethodReflectively(ReflectionHelpers.java:59)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:115)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:268)
	at org.robolectric.util.ActivityController.create(ActivityController.java:111)
	at org.robolectric.util.ActivityController.create(ActivityController.java:122)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:202)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:1388)
	at com.oneupsports.coreapp.XmlConfigurationParserTest.setup(XmlConfigurationParserTest.java:24)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by jongerrish** [comment] 2015-06-23 11:37
I don't think there will be any bug fixes fit 2.4, can you try Robolectric
3?

**Comment by benmeiri** [comment] 2015-06-23 19:51
Any updates on this?
Happen to me also with 22.2.0 and AppCompatActivity

**Comment by jonchui** [comment] 2015-07-15 16:00
I'm trying to switch over to the v7 support lib version of PopupMenu.

just filed issue #1944 in case they're different issues

**Comment by jonneymendoza** [comment] 2015-07-28 16:00
how can we fix this issue?

**Comment by jaredsburrows** [comment] 2015-07-28 16:12
What is the original issue here?

**Comment by jonneymendoza** [comment] 2015-07-28 16:13
read the first post

**Comment by jaredsburrows** [comment] 2015-07-28 16:22
@JorgeCastilloPrz Upgrade to 3.0 already.

@jonneymendoza  I commented on this with a test case a long time ago. The example I made was not using a `theme`.

@erd @jongerrish  Can we close this?

**Comment by jonneymendoza** [comment] 2015-07-28 16:23
mine uses a theme and it does not work. close it when it is confirmed as fixed

**Comment by jaredsburrows** [comment] 2015-07-28 16:25
@kluz88  @jonneymendoza  Please provide details on how to reproduce.

**Comment by jonneymendoza** [comment] 2015-07-28 16:43
OK will do tomorrow

**Comment by jaredsburrows** [comment] 2015-08-05 16:59
@erd Can we close this? I use App Compat 22.2.1 just fine now.

**Comment by 2020gaurav** [comment] 2015-08-17 13:01
@jaredsburrows  I dont think its fixed here are my configs: 

app.gradle
    
    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        compile "com.android.support:appcompat-v7:22.2.1"
        compile 'com.android.support:recyclerview-v7:22+'
    
        compile 'de.hdodenhof:circleimageview:1.3.0'
        compile 'com.android.support:cardview-v7:22+'
        compile project(':libraries:libmagento')
        compile project(':libraries:viewpagerindicator')
        compile project(':libraries:libui')
        compile 'com.baoyz.swipemenulistview:library:1.2.1'
        compile ('com.fortysevendeg.swipelistview:swipelistview:1.0-SNAPSHOT@aar') {
            transitive = true
        }

Here is my Test Case

    @RunWith(RobolectricTestRunner.class)
    @Config( constants = BuildConfig.class, emulateSdk = 21 )
    public class ProductDetailsTest extends     ActivityUnitTestCase<ProductDetails> {

        private ProductDetails productDetailsActivity;
    
        public ProductDetailsTest()
        {
            super(ProductDetails.class);
        }

        @Before
        public void setup()  {
    
            productDetailsActivity = Robolectric.setupActivity(ProductDetails.class);
    
        }


        @Test
        public void shouldNotBeNull() {
            ScrollView scrollView = (ScrollView)     shadowOf(productDetailsActivity).findViewById(R.id.product_details_base);
            assertNotNull(scrollView);

        }
    
    }


Here is the exception i am getting (Same as reported in issue)


    java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
    	at             android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:124)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
	at com.stylefiesta.application.BaseActivityImpl.onCreate(BaseActivityImpl.java:91)
	at com.stylefiesta.product.productdetails.ProductDetails.onCreate(ProductDetails.java:86)
	at android.app.Activity.performCreate(Activity.java:5933)
	at org.robolectric.util.ReflectionHelpers$3.run(ReflectionHelpers.java:144)
	at org.robolectric.util.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:241)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:138)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:309)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:47)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:210)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:46)
	at com.stylefiesta.product.productdetails.ProductDetailsTest.setup(ProductDetailsTest.java:46)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:235)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:168)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)

**Comment by jaredsburrows** [comment] 2015-08-17 15:27
@2020gaurav Keep in mind this is not a support forum. You **entire setup is completely wrong**.

Please read and make the following changes:

1. You are using an outdated Robolectric, please use `org.robolectric:robolectric:3.0`
2. Use `@RunWith(RobolectricGradleTestRunner.class)` instead of `@RunWith(RobolectricTestRunner.class)`.
3. Use `@Config(constants = BuildConfig.class, sdk = 21)` instead of `@Config(constants = BuildConfig.class, emulateSdk = 21)`
4. Do not use `ActivityUnitTestCase<ProductDetails>`. That is for Android Instrumentation test cases.

**Comment by 2020gaurav** [comment] 2015-08-17 17:18
oops my apology, i land up wrong forum, Still thanks for replying. Will keep in mind next time.

**Comment by happybit** [comment] 2015-09-07 08:25
Hi,

I suppose my issue is similar to this one. Could anybody shed some light on my problem? Thanks a lot!

Test code:
~~~ java
@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class)
public class AboutFragmentTest {

    @Test
    public void clickOrigin_shouldStartDisplayOriginActivity() {
        final AboutFragment fragment = AboutFragment.newInstance();
        SupportFragmentTestUtil.startFragment(fragment);

        fragment.getView().findViewById(R.id.origin).performClick();

        Intent expectedIntent = new Intent(fragment.getActivity(), DisplayOriginActivity.class);
        assertThat(shadowOf(fragment.getActivity()).getNextStartedActivity()).isEqualTo(expectedIntent);

    }
}
~~~

MainActivity extends appcompat-v7 AppCompatActivity. Fragment code snippet:
~~~ java
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        final View view = inflater.inflate(R.layout.fragment_about, container, false);

        Toolbar toolbar = (Toolbar) getActivity().findViewById(R.id.toolbar);
        if (toolbar != null) {
            toolbar.getMenu().clear();
        }

        // Set title bar
        ActionBar supportActionBar = ((AppCompatActivity) getActivity()).getSupportActionBar();
        if (supportActionBar != null) {
            supportActionBar.setTitle(getActivity().getString(R.string.drawerlayout_menu_about));
            supportActionBar.setElevation(12.0f);
        }
}
~~~

Unit testing output:
~~~
java.lang.ClassCastException: org.robolectric.shadows.support.v4.SupportFragmentTestUtil$FragmentUtilActivity cannot be cast to android.support.v7.app.AppCompatActivity
	at in.xinyue.xinyue.ui.fragment.AboutFragment.onCreateView(AboutFragment.java:67)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:458)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:130)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:30)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:95)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:230)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:85)
	at org.robolectric.shadows.ShadowMessageQueue.enqueueMessage(ShadowMessageQueue.java:116)
	at android.os.MessageQueue.enqueueMessage(MessageQueue.java)
	at android.os.Handler.enqueueMessage(Handler.java:631)
	at android.os.Handler.sendMessageAtTime(Handler.java:600)
	at android.os.Handler.sendMessageDelayed(Handler.java:570)
	at android.os.Handler.post(Handler.java:326)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1407)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:637)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:616)
	at org.robolectric.shadows.support.v4.SupportFragmentTestUtil.startFragment(SupportFragmentTestUtil.java:17)
	at in.xinyue.xinyue.ui.fragment.AboutFragmentTest.clickOrigin_shouldStartDisplayOriginActivity(AboutFragmentTest.java:30)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)


Process finished with exit code -1
~~~

**Comment by jaredsburrows** [comment] 2015-09-07 17:01
@happybit Your error is different from the original issue.

What is `.onCreateView(AboutFragment.java:67)`?

Did your test fail after updating? Also `23.0.1` is the latest.

**Comment by happybit** [comment] 2015-09-08 14:25
Hi @jaredsburrows, thanks for your prompt response.

`.onCreateView(AboutFragment.java:67)` is this line:

    ActionBar supportActionBar = ((AppCompatActivity) getActivity()).getSupportActionBar();

Looks like `FragmentUtilActivity` in Roboletric cannot cast to `AppCompatActivity`. But I have to cast it in my fragment to get the `ActionBar`.

I just upgraded to `23.0.1`. Still encountered the same problem. Thanks!

**Comment by jaredsburrows** [comment] 2015-09-09 03:16
@happybit You are using `SupportFragmentTestUtil.startFragment(fragment)`, here is the source:


    public static void startVisibleFragment(Fragment fragment) {
       buildSupportFragmentManager(FragmentUtilActivity.class)
        .beginTransaction().add(1, fragment, null).commit();
    }

You are using a `FragmentUtilActivity`. You can create your own method or use: `startVisibleFragment(Fragment fragment, Class<? extends FragmentActivity> fragmentActivityClass, int containerViewId)`.

**Comment by happybit** [comment] 2015-09-09 05:58
Hi @jaredsburrows , you save my life!

I modified the code accordingly and met this "[Null contentprovider](https://github.com/robolectric/robolectric/issues/2020)" issue. Then I downgraded to `22.2.1`. It works like a charm.

Thanks a lot!!

**Closed** 2015-09-10 02:36 UTC
Labels: 3.0, enhancement

**Comment by abhisnypar** [comment] 2017-02-20 23:25
@jaredsburrows . I am using the latest API 25.1.1 and i am having the issue " You need to use a Theme.AppCompat theme (or descendant) with this activity." And in my Activity i am extending the AppCompatActivity. Roboelectric version 3.1. what is the solution you gave to them.

**Comment by jongerrish** [comment] 2017-02-21 01:51
Your resources also need to include the resources from AppCompat that's
where there error comes from.

What build system are you using and what configuration?

**Comment by abhisnypar** [comment] 2017-02-21 02:47
@jaredsburrows 
 compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        applicationId rootProject.ext.applicationID
        versionName rootProject.ext.versionName
        minSdkVersion 19
        targetSdkVersion 25
dependencies {
    //Remote Google Libraries
    compile 'com.android.support:support-v13:25.1.1'
    compile 'com.android.support:appcompat-v7:25.1.1'
    compile 'com.android.support:support-v4:25.1.1'
    compile 'com.google.android.gms:play-services-gcm:10.2.0'

    //Remote Cerner Libraries
    compile 'com.cerner.ion.android:cerner-volley:1.3.0'

    //Remote Third-Party Libraries
    compile 'commons-io:commons-io:2.4' // Apache
    compile 'ch.acra:acra:4.6.2' // ACRA Logging

    testCompile 'junit:junit:4.12'
    testCompile 'org.robolectric:robolectric:3.1'
    testCompile 'org.mockito:mockito-core:1.10.19'

    // Module dependency
    //compile project(":lib")

    // Local binary dependency
    compile fileTree(dir: 'libs', include: ['*.jar'])
}


My Code for Activity. 
________________________

 @Override
    protected void onCreate(final Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        TAG = getClass().getSimpleName();

        setContentView(R.layout.activity_webview);
        ensureDeviceIdStored();
        (new IrisAppVersionManager(this)).checkApplicationVersion();

        mSwipeLayout = initSwipeLayout(R.id.swipe_refresh_container);
        mWebView = initWebView(R.id.webView, R.id.progress_bar);

        mWebView.getSettings().setSupportMultipleWindows(true); // Enable tabbing
        mWebView.setWebChromeClient(new IrisPortalWebChromeClient());

        mWebView.setWebViewClient(new IrisBaseWebViewClient(this, mSwipeLayout, (IrisApplication) getApplication()));


__________________________________________
My test Classs


@RunWith(IrisRobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 21, manifest = "src/main/AndroidManifest.xml")
public class IrisPortalWebViewActivityTest {
    private ActivityController<IrisPortalWebViewActivity> mController;

    @Before
    public void setUp() {
        this.mController = Robolectric.buildActivity(IrisPortalWebViewActivity.class);
    }

    @After
    public void tearDown() {
        this.mController.pause().stop().destroy();
    }

    @Test
    /**
     * Tests that initial create will load login url
     */
    public void testOnCreateWithoutSavedBundle() {
        this.mController.create();

        ShadowWebView shadowWebView = Shadows.shadowOf(this.mController.get().mWebView);

        assertTrue(shadowWebView.getSettings().supportMultipleWindows());
        assertTrue(shadowWebView.getLastLoadedUrl().contains("/login"));
        assertThat(shadowWebView.getWebViewClient(), instanceOf(IrisBaseWebViewClient.class));
        assertThat(shadowWebView.getWebChromeClient(), instanceOf(IrisPortalWebViewActivity.IrisPortalWebChromeClient.class));
    }

**********************************
