### ISSUE TITLE
 class org.robolectric.res.ResourceTableFactory cannot access a member of class android.R$styleable 

### ISSUE THREAD

**Issue by TJJ123456** [robolectric/robolectric#8532] opened 2023-10-16 08:49 UTC
### Description
When I run test with Coverage in android studio encounter the exception
```
java.lang.IllegalAccessException: class org.robolectric.res.ResourceTableFactory cannot access a member of class android.R$styleable with modifiers "private static transient"
But I run with Jacoco is ok, Is there any way I can make "run with xxxTest with Coverage" successful.
```

### Steps to Reproduce
My code
```
public class Calculator {
    public int add(int a, int b) {
        return a + b;
    }
}
```
My test code
```
@RunWith(RobolectricTestRunner.class)
@PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*", "org.json.*", "sun.security.*", "javax.net.*"})
public class CalculatorTest {
    @InjectMocks
    private Calculator calculator;

    @Test
    public void should_correct_when_add_given_sample() {
        Assert.assertEquals(3, calculator.add(1,2));
    }
}
```

### Robolectric & Android Version
Robolectric version: 4.7.3
JDK version: 1.8
Android version: 33

**Comment by learner1999** [comment] 2023-10-16 08:56
I also encountered the same problem……

**Comment by hoisie** [comment] 2023-10-25 15:24
1) Robolectric 4.7.3 is many years old at this point, please update to 4.12-SNAPSHOT and see if the issue is still there.

2) Mockito-inline is the only officially supported agent-based mocking framework for Robolectric. If you are using others (e.g. PowerMock, Mockk), they may be interfering with the instrumentation Robolectric does on Android classes, and fixing these issues requires in-depth knowledge of the instrumentation that is performed by Powermock. Unfortunately we do not have the time and resources to debug these issues. However, if you'd like to take a deep dive and see what's going on, we'd be happy to provide support for Robolectric-based instrumentation.

**Comment by hoisie** [comment] 2023-11-16 18:31
Closing since there is no sample app or clear repro instructions using 4.12-SNAPSHOT.

**Closed by hoisie** 2023-11-16 18:31 UTC
