### ISSUE TITLE
Snackbar does not work with Robolectric

### ISSUE THREAD

**Issue by martijndebruijn** [robolectric/robolectric#1289] opened 2014-09-26 06:24 UTC
When testing a Snackbar in a Fragment with Robolectric the test fails due to an UnsupportedOperationException. Any idea how to solve this?

```
java.lang.UnsupportedOperationException: ugh, this doesn't work still?
    at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:290)
    at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:273)
    at org.robolectric.shadows.ShadowAssetManager.getResourceValue(ShadowAssetManager.java:85)
    at android.content.res.AssetManager.getResourceValue(AssetManager.java)
    at android.content.res.Resources.getValue(Resources.java:1114)
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2304)
    at android.content.res.Resources.getLayout(Resources.java:934)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:395)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
    at com.github.mrengineer13.snackbar.SnackBar.<init>(SnackBar.java:96)
    at com.myapp.MyFragment.showFailed(MyFragment.java:273)
    at com.myapp.MyFragmentRobolectricTest.showFailed_success(MyFragmentRobolectricTest.java:58)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:250)
    at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by jaredsburrows** [comment] 2015-05-20 16:32
@martijndebruijn  What is the status on this?

**Comment by jaredsburrows** [comment] 2015-07-02 22:46
@erd Can we close this? The user has not responded and this is deprecated because Google supports this in the Android "design" support library.

**Comment by erd** [comment] 2015-07-03 16:44
Just because there is a better alternative, doesn't mean that this is "deprecated". There is obviously a problem with `ShadowAssetManager` and certain kinds of resources (given the first entry in the stack trace). I would like to fix it.

**Comment by jaredsburrows** [comment] 2015-07-03 16:47
This was posted over a year ago. Are you going to try and reproduce this?

**Comment by nenick** [comment] 2015-11-08 11:20
Someone already wrote a shadow for this http://raptordigital.blogspot.de/search/label/snackbar

**Comment by jbrunton** [comment] 2016-01-10 14:51
Would anyone (including original author @kvandermast) be amenable to a pull request which adds the shadow described in that blogpost to Robolectric? I'd be happy to help. Or is there a reason it's not been added?

**Comment by jongerrish** [comment] 2016-01-11 01:35
I think we should try and understand and fix the root cause rather than adding a custom shadow to paper over cracks in Robolectric.

Can you post a test case that exposes the bug?

**Comment by jaredsburrows** [comment] 2016-01-11 01:39
@jongerrish  This not the `Snackbar` from the Support lib. It is `com.github.mrengineer13.snackbar.SnackBar`. He should just switch to the Android design support lib.

**Comment by hidroh** [comment] 2016-01-11 01:57
@jaredsburrows @jongerrish @erd Except for `support-v4` and `appcompat-v7`, which provide backward compatibility with Android SDK, I would propose not to add shadows for other support libraries (e.g. `design`, `recyclerview-v7` etc) into Robolectric. These libraries are updated much more frequently now, with changed/new UI components. With current release cycle of Robolectric it would be impractical to keep up to date with them.

The current shadowing mechanism should already be sufficient to shadow these. IMO a collection of gists of shadows that people make, listed in wiki or hosted via Github pages would be more manageable. Robolectric contributors can focus more on fixing the core issues, which would benefit all.

The problem reported in this issue seems to be related to `AssetManager` though.

**Comment by jaredsburrows** [comment] 2016-01-11 01:59
@hidroh I completed agree. What I am saying is I currently use `Snackbar` from the `Design support lib` and do not need shadows for it. I am simply saying for this user to switch to the Android support snackbar from Google.

**Comment by hidroh** [comment] 2016-01-11 03:12
:+1:

**Comment by kvandermast** [comment] 2016-01-11 08:40
@hidroh @jaredsburrows I'm open to think about either creating gists or an extension lib to extends shadowing of classes. The Snackbar shadow I created is far from complete, so all help is welcome.

**Comment by hidroh** [comment] 2016-01-11 09:06
:+1: A repo would better, as it would have full features compared to Gist, which is more like a paste bin. Same as your case, I also have a bunch of self-created shadows, but they are quite specific to my needs. Making a library of shadows would require some polishing and a more comprehensive implementation.

**Comment by mgoovaer** [comment] 2016-11-07 16:13
Was a repo ever created for the ShadowSnackbar?

**Comment by kvandermast** [comment] 2016-11-07 16:53
No, never had the chance or the time I'm afraid.

Op ma 7 nov. 2016 17:13 schreef Maxime Goovaerts <notifications@github.com>:

**Comment by mgoovaer** [comment] 2016-11-07 17:02
@kvandermast is there a "best practice" ShadowSnackbar implementation you could share? I'm seeing a lot of different ones out there

**Comment by kvandermast** [comment] 2016-11-07 17:57
@mgoovaer, what do you mean with "Best Practice"? The ShadowSnackbar "borrows" its logic from the ToastShadow implementation. What I tend to test is something alike:

```java
        Assert.assertNotNull(SnackbarShadow.getLatestSnackbar());
        Assert.assertEquals("Text on the Snackbar", SnackbarShadow.getTextOfLatestSnackbar());
        SnackbarShadow.reset();
```

**Comment by amrfarid140** [comment] 2017-04-06 10:18
I am unable to implement the shadow class mentioned in the blog post in @nenick comments. 

When I run the test using the custom TestRunner I get this error : 

```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Can not set static org.robolectric.internal.bytecode.ClassHandler field org.robolectric.internal.bytecode.RobolectricInternals.classHandler to org.robolectric.internal.bytecode.ShadowWrangler

	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:174)
	at org.robolectric.internal.bytecode.Sandbox.configure(Sandbox.java:52)
	at org.robolectric.internal.SandboxTestRunner.configureShadows(SandboxTestRunner.java:169)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:181)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

Also, the custom test runner overrides a deprecated function `createClassLoaderConfig()` .. any ideas how to create the SnackBar shadow class ?

**Comment by kvandermast** [comment] 2017-04-06 10:35
@amrfarid140, it helps to provide some detail on API levels, used libraries and things like that.

The example I wrote in the blog is outdated indeed. 

## Custom Gradle test runner

```java
package ...

import org.junit.runners.model.InitializationError;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;
import org.robolectric.manifest.AndroidManifest;
import org.robolectric.res.FileFsFile;
import org.robolectric.res.FsFile;

import java.util.Map;

@SuppressWarnings("Convert2streamapi")
public class RobolectricGradleTestRunner extends RobolectricTestRunner {

    public RobolectricGradleTestRunner(Class<?> testClass) throws InitializationError {
        super(testClass);
    }

    @Override
    protected AndroidManifest getAppManifest(Config config) {
        AndroidManifest appManifest = super.getAppManifest(config);
        FsFile androidManifestFile = appManifest != null ? appManifest.getAndroidManifestFile() : null;

            if (null == androidManifestFile || !androidManifestFile.exists()) {
            String moduleRoot = getModuleRootPath(config);

            androidManifestFile = FileFsFile.from(moduleRoot, "src/main/AndroidManifest.xml");
            //FsFile resDirectory = FileFsFile.from(moduleRoot, "src/main/res/");
            FsFile resDirectory = FileFsFile.from(moduleRoot, "./build/intermediates/res/merged/local/debug/");
            FsFile assetDirectory = FileFsFile.from(moduleRoot, "src/main/assets");

            appManifest = new AndroidManifest(androidManifestFile, resDirectory, assetDirectory, "<package name>");
        }

        final Map<String, Object> applicationMetaData = appManifest.getApplicationMetaData();

        //TODO: change this to lamda expression when hitting minimal API 24
        for (String k : applicationMetaData.keySet()) {
            if ("com.google.android.gms.version".equals(k)) {
                System.out.println("GMS version currently contains: <" + applicationMetaData.get(k) + ">");

                // this should be update based upon the version from the library
                applicationMetaData.put(k, "10298000");
            }
        }

        return appManifest;
    }

    private String getModuleRootPath(Config config) {
        String moduleRoot = config.constants().getResource("").toString().replace("file:", "");
        return moduleRoot.substring(0, moduleRoot.indexOf("/build"));
    }
}
```

Linking the shadow classes can be done using annotations on the test class, e.g

## Test Class
```java
package ...;

import org.junit.Before;
import org.junit.runner.RunWith;
import org.robolectric.annotation.Config;
import org.robolectric.shadows.ShadowLog;

import java.io.IOException;
import java.net.InetAddress;

import ...

@SuppressWarnings("WeakerAccess")
@Config(sdk = AbstractTestCase.SDK_VERSION,
        constants = BuildConfig.class,
        manifest = AbstractTestCase.MANIFEST,
        application = TestApplication.class,
        shadows = {SnackbarShadow.class, NetworkSecurityPolicyShadow.class},
        libraries = {
                "../../build/intermediates/exploded-aar/com.android.support/appcompat-v7/24.2.0",
                "../../build/intermediates/exploded-aar/com.android.support/design/24.2.0",
                "../../build/intermediates/exploded-aar/com.android.support/support-v4/24.2.0",
                "../../build/intermediates/exploded-aar/com.google.android.gms/play-services-base/9.4.0",
                "../../build/intermediates/exploded-aar/com.google.android.gms/play-services-gcm/9.4.0",
                "../../build/intermediates/exploded-aar/com.google.android.gms/play-services/9.4.0"
        })
@RunWith(RobolectricGradleTestRunner.class)
public class AbstractTestCase {
    public static final int HTTP_STATUS_CODE_SUCCESS = 202;
    public static final int SDK_VERSION = 22;
    public static final String MANIFEST = Config.NONE;
    private final static String TAG = AbstractTestCase.class.getSimpleName();

    protected static MockWebServer server;

    static {
        ShadowLog.stream = System.out;

        server = resetMockWebServer();
    }


    public AbstractTestCase() {
        //this.resetMockServer();
    }

    protected static MockWebServer resetMockWebServer() {
        try {
            if (null != server) server.shutdown();
        } catch (IOException e) {
            Logger.e(TAG, e);
        }

        server = new MockWebServer();
        try {
            server.start(InetAddress.getByName("localhost"), 56517);

            Logger.d(TAG, "Server started on %s:%d", server.getHostName(), server.getPort());
        } catch (IOException e) {
            Logger.e(TAG, e);

            throw new RuntimeException(e);
        }

        return server;
    }

    @Before
    public void doFirst() {
        server = resetMockWebServer();
    }
}
```

**Comment by amrfarid140** [comment] 2017-04-06 10:40
@kvandermast Thanks for the reply. I am using API level = 25 and main dependencies used are 

```
    compile 'com.android.support:design:25.2.0'
    compile 'com.google.dagger:dagger:2.0'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.0'
    compile 'com.android.support:support-v4:25.2.0'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.squareup.retrofit2:retrofit:2.2.0'
    testCompile 'junit:junit:4.12'
    testCompile 'org.robolectric:robolectric:3.3.2'
    testCompile 'org.robolectric:shadows-support-v4:3.0'
```

I will take the example provided as a guide and adapt the snackbar shadow to it. Hopefully, a solution would be found.

**Comment by kvandermast** [comment] 2017-04-06 10:50
@amrfarid140 first thing that catches my attention:

```gradle
    testCompile 'org.robolectric:robolectric:3.3.2' // version 3.3.2
    testCompile 'org.robolectric:shadows-support-v4:3.0' // version 3.0 => version 3.3.2
```
Version inconsistency. Might be what is causing the issue.
Dagger is at 2.8 too.

**Comment by swanson** [comment] 2017-10-23 20:25
I ran into this problem today and this blog post resolved my issues: https://medium.com/@jotaemepereira/android-tests-with-roboelectric-snackbarshadow-update-71681bc59e0f

**Comment by vedant1811** [comment] 2018-06-14 15:01
I wrote a much [simpler solution](https://stackoverflow.com/a/50860390/1396264)


    val textView: TextView? = rootView.findSnackbarTextView()
    assertThat(textView, `is`(notNullValue()))

Implementation:

    /**
     * @return a TextView if a snackbar is shown anywhere in the view hierarchy.
     *
     * NOTE: calling Snackbar.make() does not create a snackbar. Only calling #show() will create it.
     *
     * If the textView is not-null you can check its text.
     */
    fun View.findSnackbarTextView(): TextView? {
      val possibleSnackbarContentLayout = findSnackbarLayout()?.getChildAt(0) as? SnackbarContentLayout
      return possibleSnackbarContentLayout
          ?.getChildAt(0) as? TextView
    }
    
    private fun View.findSnackbarLayout(): Snackbar.SnackbarLayout? {
      when (this) {
        is Snackbar.SnackbarLayout -> return this
        !is ViewGroup -> return null
      }
      // otherwise traverse the children
    
      // the compiler needs an explicit assert that `this` is an instance of ViewGroup
      this as ViewGroup
    
      (0 until childCount).forEach { i ->
        val possibleSnackbarLayout = getChildAt(i).findSnackbarLayout()
        if (possibleSnackbarLayout != null) return possibleSnackbarLayout
      }
      return null
    }

**Comment by jongerrish** [comment] 2018-10-31 17:44
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.

**Closed by jongerrish** 2018-10-31 17:44 UTC
Labels: resources
