### ISSUE TITLE
Cannot correctly resolve string resource with escaped @ symbol

### ISSUE THREAD

**Issue by exusiaanother** [robolectric/robolectric#3416] opened 2017-09-22 20:11 UTC
### Steps to Reproduce
In Robolectric 3.4.2, if I have a textView with `android:text="@string/something"` pointing to a string resource such as `<string name="something">\@textnow.me</string>`, robolectric will throw error when trying to inflate this view.

I do not have this issue in 3.3.1. Haven't had a chance to check version between 3.3.1 and 3.4.2 though.

If I simply delete `android:text="@string/something"`, then this error is gone.

Sample Error
```
android.view.InflateException: XML file /<deleted>/fragment_sign_up.xml line #-1 (sorry, not yet implemented): Error inflating class TextView

	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at com.enflick.android.TextNow.activities.SignUpFragment.onCreateView(SignUpFragment.java:158)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:164)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:31)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:138)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:317)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:154)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:143)
	at org.robolectric.shadows.ShadowMessageQueue.enqueueMessage(ShadowMessageQueue.java:145)
	at android.os.MessageQueue.enqueueMessage(MessageQueue.java)
	at android.os.Handler.enqueueMessage(Handler.java:631)
	at android.os.Handler.sendMessageAtTime(Handler.java:600)
	at android.os.Handler.sendMessageDelayed(Handler.java:570)
	at android.os.Handler.post(Handler.java:326)
	at android.support.v4.app.FragmentManagerImpl.scheduleCommit(FragmentManager.java:1887)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1870)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:650)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:609)
	at org.robolectric.shadows.support.v4.SupportFragmentTestUtil.startFragment(SupportFragmentTestUtil.java:22)
	at com.enflick.android.TextNow.activities.SignUpFragmentTest.startSignUpFragment(SignUpFragmentTest.java:170)
	at com.enflick.android.TextNow.activities.SignUpFragmentTest.testCheckUserNameTaskAutofillUserNameAvailable(SignUpFragmentTest.java:414)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:497)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:228)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:64)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.RuntimeException: huh? ResName{com.enflick.android.TextNow:style/textnow_me}
	at org.robolectric.shadows.ShadowAssetManager.convertAndFill(ShadowAssetManager.java:156)
	at org.robolectric.shadows.ShadowAssetManager.buildTypedValue(ShadowAssetManager.java:766)
	at org.robolectric.shadows.ShadowAssetManager.attrsToTypedArray(ShadowAssetManager.java:792)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:244)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
	at android.widget.TextView.__constructor__(TextView.java:784)
	at android.widget.TextView.<init>(TextView.java)
	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:180)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
	... 62 more
```
**I think somehow robolectric treated the string after @ as a style?** 
```
Caused by: java.lang.RuntimeException: huh? ResName{com.enflick.android.TextNow:style/textnow_me}
```

The TextView itself does not have a style defined in the xml.

### Robolectric & Android Version
Robolectric 3.4.2 
Unit test sdk level 22
### Link to a public git repo demonstrating the problem:
N/A

**Comment by calvarez-ov** [comment] 2017-11-25 01:55
For info, the same error happens if you use `\u0040` instead of `\@` in the strings.

**Comment by loopyzort** [comment] 2018-03-09 17:29
I'm also seeing the exact same issue with an `\@` value referenced in a layout we inflate for a test:
`Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f1000c4`

Removing the `\@` fixes the test.

Robolectric: 3.6.1
Unit test sdk level: 25

I was going to try to submit a PR patch myself in a few weeks when I have time if no one has addressed this before then.

**Comment by xian** [comment] 2018-03-10 00:17
Is `\@` a valid resource reference? Why?

**Comment by jongerrish** [comment] 2018-03-10 00:52
No, it's not, is the problem that it's a valid string literal but we're
treating it as a resource?

If you can provide a small test case we can take a look.

**Comment by jongerrish** [comment] 2018-10-31 17:30
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.

**Closed by jongerrish** 2018-10-31 17:30 UTC
