### ISSUE TITLE
Resource not found for ShareActionProvider with AppCompat 22.1.0

### ISSUE THREAD

**Issue by hidroh** [robolectric/robolectric#1742] opened 2015-04-29 07:42 UTC
When trying to upgrade to latest appcompat v22.1.0, some of my tests fail with the below exception related to `android.support.v7.widget.ShareActionProvider`. I'm using Robolectric 3.0-rc2, testing against API 21. Unfortunately I ran into some other issues with Robolectric 3.0-SNAPSHOT so I could not verify this issue using latest snapshot. All my tests pass if I revert back to appcompat v22.0.0, or if I test against API 19 (which does not call `ContextCompatApi21.getDrawable(context, id)` as in the stacktrace).

```
android.content.res.Resources$NotFoundException: unknown resource 0
    at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:332)
    at org.robolectric.shadows.ShadowAssetManager.getResourceValue(ShadowAssetManager.java:93)
    at android.content.res.AssetManager.getResourceValue(AssetManager.java)
    at android.content.res.Resources.getValue(Resources.java:1229)
    at android.content.res.Resources.getDrawable(Resources.java:756)
    at android.content.Context.getDrawable(Context.java:402)
    at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:26)
    at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:319)
    at android.support.v7.internal.widget.TintManager.getDrawable(TintManager.java:137)
    at android.support.v7.widget.ShareActionProvider.onCreateActionView(ShareActionProvider.java:191)
    at android.support.v4.view.ActionProvider.onCreateActionView(ActionProvider.java:109)
    at android.support.v7.internal.view.menu.MenuItemImpl.getActionView(MenuItemImpl.java:630)
    at android.support.v7.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:168)
    at android.support.v7.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:429)
    at android.support.v7.internal.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1129)
    at android.support.v7.internal.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:91)
    at android.support.v7.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:207)
    at android.support.v7.internal.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:279)
    at android.support.v7.internal.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1021)
    at android.support.v7.internal.view.menu.MenuItemImpl.setSupportActionProvider(MenuItemImpl.java:661)
    at android.support.v4.view.MenuItemCompat.setActionProvider(MenuItemCompat.java:345)
    at android.support.v7.internal.view.SupportMenuInflater$MenuState.setItem(SupportMenuInflater.java:473)
    at android.support.v7.internal.view.SupportMenuInflater$MenuState.addSubMenuItem(SupportMenuInflater.java:485)
    at android.support.v7.internal.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:194)
    at android.support.v7.internal.view.SupportMenuInflater.inflate(SupportMenuInflater.java:118)
    at io.github.hidroh.materialistic.BaseListActivity.onCreateOptionsMenu(BaseListActivity.java:82)
    at io.github.hidroh.materialistic.test.TestListActivity.supportInvalidateOptionsMenu(TestListActivity.java:12)
    at io.github.hidroh.materialistic.BaseListActivity.openStory(BaseListActivity.java:250)
    at io.github.hidroh.materialistic.BaseListActivity.handleMultiPaneItemSelected(BaseListActivity.java:234)
    at io.github.hidroh.materialistic.BaseListActivity.onItemSelected(BaseListActivity.java:129)
    at io.github.hidroh.materialistic.BaseListActivityLandTest.testClearSelection(BaseListActivityLandTest.java:120)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:235)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:168)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by jaredsburrows** [comment] 2015-04-29 15:24
Are you using a custom runner?

**Comment by hidroh** [comment] 2015-04-30 01:47
I'm using the default `RobolectricTestRunner`

**Comment by jaredsburrows** [comment] 2015-04-30 01:54
Try using the `RobolectricGradleTestRunner`. This has worked for me.

**Comment by hidroh** [comment] 2015-04-30 02:41
Nope, same issue for me.

**Comment by jaredsburrows** [comment] 2015-05-16 22:50
@hidroh I finally ran into this same issue. I added `visible()` in an `Activity` test and it returned the same error. Can you post your example test?

**These work fine for me:**

    mainActivity = buildActivity(MainActivity.class).create().get();

    mainActivity = buildActivity(MainActivity.class).create().visible().get();

**These fail:**

    mainActivity = buildActivity(MainActivity.class).create().start().resume().visible().get();

    mainActivity = buildActivity(MainActivity.class).create().resume().visible().get();

**Comment by hidroh** [comment] 2015-05-17 00:36
According to @erd in #981, calling `visible()` will trigger `onCreateOptionsMenu()` and `onPrepareOptionsMenu()` for `Activity`. This does not seem to be true for `Fragment` with options menu though, as I have to manually trigger the menu callbacks.

**Comment by jaredsburrows** [comment] 2015-05-17 00:41
@hidroh I am using `buildActivity(MainActivity.class).create().start().visible().get()` for my `MainActivity` and it triggers the `Fragment's` `onCreateOptionsMenu`.

Here is my `onCreateOptionsMenu`:

    @Override
    public void onCreateOptionsMenu(final Menu menu, final MenuInflater menuInflater) {
        super.onCreateOptionsMenu(menu, menuInflater);
        menuInflater.inflate(R.menu.menu, menu);
    }

I could `mock` `MenuInflater` and `verify` that it is called in `onCreateOptionsMenu`, but I am using `JaCoCo` test coverage and it is being covered.

**Comment by hidroh** [comment] 2015-05-17 00:52
Ah yes, I think you're right. The only thing that does not seem to wire up is when I try to trigger an options menu item selection, which is part of the `Fragment`, not `Activity`. In `Activity` you can do `shadowOf(activity).clickMenuItem(itemId)` so I was expecting the same with `Fragment` inside an activity, but apparently it does not work (at least back when I tried it).

Anyway, back to your question, in my project I have 2 tests involving `ShareActionProvider`.

* One I test using the normal sequence of `Activity.create().start().resume().visible()`, which I have to force `emulateSdk=19, reportSdk=19` so it won't fail
* The other one I skip `visible()`, so I can call the menu callbacks directly, and it does not really inflate anything during that test, so nothing fails.

**Comment by jaredsburrows** [comment] 2015-05-17 01:02
Yeah, my previous comment is what I am doing to trigger the `Fragments` and what works for me.

Why not use `Activity.create().start().visible()` instead of `Activity.create().start().visible()` so you can use `visible` and emulate `21` sdk?

**Comment by hidroh** [comment] 2015-05-17 01:16
@jaredsburrows does that sequence trigger menu creation as well? But even if it works, we would be skipping `onResume()` then. Your suggestion would work, given I have no logic in `onResume()`. But what if my production code relies on some logic in `onResume()` before it hits `onCreateOptionsMenu()`?

**Comment by jaredsburrows** [comment] 2015-05-17 01:22
Yes it does skip `onResume`, but it crashes if I call that. So that is one thing I am not able to test using that method. I am not sure about that second case. Maybe generate two individual tests for both. One test using the `resume` and the other in order to invoke `onCreateOptionsMenu`.

**Comment by erd** [comment] 2015-05-18 15:29
> This does not seem to be true for Fragment with options menu though, as I have to manually trigger the menu callbacks.

I think this commit 7b82f57ff5709624a98468e3147eba96f32a0a6f might solve your issue. It should cause menu item clicks to be delegated to fragments if it is not handled by the activity.

**Comment by hidroh** [comment] 2015-05-20 11:45
Thanks @erd, `clickMenuItem()` now works with fragments after I upgrade to 3.0-rc3.

**Comment by jaredsburrows** [comment] 2015-05-20 14:47
Robolectric `3.0-rc3`? How come the readme is never updated? I do not see it here: http://mvnrepository.com/artifact/org.robolectric/robolectric.

**Comment by hidroh** [comment] 2015-05-20 14:49
I saw the new tag in my Github feed and checked jcenter: https://bintray.com/bintray/jcenter/org.robolectric%3Arobolectric/view

**Comment by jaredsburrows** [comment] 2015-05-20 14:51
Wow ok, May 19, 2015, just yesterday. Thanks.

**Comment by erd** [comment] 2015-05-20 15:54
> How come the readme is never updated?

The README points to the most recent released version. It'll get updated when 3.0 (final) is released.

**Comment by hidroh** [comment] 2015-05-20 23:37
Sorry can you reopen this issue? The original issue with `ShareActionProvider` is still there, only `clickMenuItem` issue is resolved.

**Comment by jaredsburrows** [comment] 2015-05-21 02:57
@hidroh  Atleast we were able to solve one of your issues :)

**Comment by jaredsburrows** [comment] 2015-05-31 01:22
@hidroh Ah, I thought we closed this? What was the issue you had left?

**Comment by hidroh** [comment] 2015-06-01 09:24
The one in the issue's title

**Comment by jaredsburrows** [comment] 2015-06-01 17:12
I'm using both App Comopat v7 22.2.0 and robolectric 3.0 rc3 and I do not see this error at all.

**Comment by hidroh** [comment] 2015-06-01 18:10
Yeah? I haven't upgraded appcompat yet, the title says 22.1.0. Let me try and report back later.

**Comment by hidroh** [comment] 2015-06-02 07:15
Sorry to say that the problem still persists.

* appcompat 22.2.0
* robolectric 3.0 rc3
* sdk=21

It works with lower target SDK though, as the stacktrace shows exception only happen to some API 21 specific logic.

**Comment by jaredsburrows** [comment] 2015-06-02 07:16
What problem? We have the same setup.

Are you referring to: https://github.com/robolectric/robolectric/issues/1742#issuecomment-102708491?

**Comment by hidroh** [comment] 2015-06-02 08:17
[This](https://github.com/robolectric/robolectric/issues/1742#issue-71803849)

**Comment by jaredsburrows** [comment] 2015-07-02 23:22
@hidroh After all this time, I think I finally figure out to reproduce your issue. I was working on a much smaller project and ran into this: https://github.com/robolectric/robolectric/issues/1915.

What does your `menu.xml` look like for your `ActionBar` or `Toolbar`? Are you specifying `app:showAsAction="ifRoom|withText"`?

**Comment by hidroh** [comment] 2015-07-03 02:55
No, it's `always`: https://github.com/hidroh/materialistic/blob/master/app/src/main/res/menu-w820dp-land/menu_list_land.xml

**Comment by jaredsburrows** [comment] 2015-07-03 03:13
That is what I am meant to say. `ifRoom` and `always`. Before, my menu items were set to `never`.

I believe it has to do with the visibility.

**Comment by xian** [comment] 2018-10-02 23:19
Please reopen if this is still an issue.

**Closed by xian** 2018-10-02 23:19 UTC
Labels: defect, resources
