### ISSUE TITLE
Robolectric can't inflate layout with custom TextViews. 

### ISSUE THREAD

**Issue by s73v3r** [robolectric/robolectric#2005] opened 2015-08-24 22:37 UTC
I am trying to test a RecyclerView Adapter, and I'm unable to test part of it because it can't inflate a layout with a custom TextView. If I comment out the custom TextView, or replace it with a regular TextView, it works fine, and the test passes. 

I'm using Robolectric 3.0, and the RobolectricGradleTestRunner.

``` Java
android.view.InflateException: XML file build/intermediates/res/merged/debug/layout/module_grid_layout.xml line #-1 (sorry, not yet implemented): Error inflating class com.my.app.widget.TypefaceTextView
    at android.view.LayoutInflater.createView(LayoutInflater.java:633)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
    at com.my.app.adapterdelegates.ModuleDelegate.onCreateViewHolder(ModuleDelegate.java:30)
    at com.my.app.adapterdelegates.ModuleDelegateTest.testDelegateReturnsCorrectViewHolderType(ModuleDelegateTest.java:72)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:607)
    at android.view.LayoutInflater.createView(LayoutInflater.java)
    at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:743)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
    at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:806)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java)
    at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:809)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java)
    at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:504)
    at android.view.LayoutInflater.inflate(LayoutInflater.java)
    at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:414)
    at android.view.LayoutInflater.inflate(LayoutInflater.java)
    at com.my.app.adapterdelegates.ModuleDelegate.onCreateViewHolder(ModuleDelegate.java:30)
    at com.my.app.adapterdelegates.ModuleDelegateTest.testDelegateReturnsCorrectViewHolderType(ModuleDelegateTest.java:72)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    ... 1 more
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.robolectric.res.StyleData
    at org.robolectric.shadows.ShadowAssetManager.resolveStyle(ShadowAssetManager.java:345)
    at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:149)
    at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:55)
    at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:485)
    at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
    at android.content.Context.obtainStyledAttributes(Context.java:472)
    at android.view.View.__constructor__(View.java:3677)
    at android.view.View.<init>(View.java)
    at android.widget.TextView.<init>(TextView.java)
    at com.my.app.widget.TypefaceTextView.<init>(TypefaceTextView.java:28)
    at com.my.app.widget.TypefaceTextView.<init>(TypefaceTextView.java:24)
    at android.view.LayoutInflater.createView(LayoutInflater.java:607)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
    at com.my.app.adapterdelegates.ModuleDelegate.onCreateViewHolder(ModuleDelegate.java:30)
    at com.my.app.adapterdelegates.ModuleDelegateTest.testDelegateReturnsCorrectViewHolderType(ModuleDelegateTest.java:72)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    ... 1 more
```

**Comment by MoizAli** [comment] 2015-09-03 15:05
Hey @s73v3r  any luck with this?

**Comment by rob-h-w** [comment] 2016-01-16 09:59
Does your custom TextView contain a style that has an inputType spanning multiple lines? I see the same problem with the following, and I have a workaround that works for me (tm).

+my fragment.xml
...
        <EditText
            android:id="@+id/note_content"
            style="@style/AppTheme.text.textEditor.multiline"
            android:hint="@string/descriptive_name_for_the_note_detail" />
...
-my fragment.xml

+my style.xml
...
    <style name="AppTheme.text.textEditor.multiline">
        <item name="android:singleLine">false</item>
        <item name="android:inputType">
            textMultiLine|textCapSentences|textAutoComplete|textAutoCorrect</item>
        <item name="android:textIsSelectable">true</item>
    </style>
...
-my style.xml

If I simply modify my input type to all be on 1 line, the error goes away:
<item name="android:inputType">textMultiLine|textCapSentences|textAutoComplete|textAutoCorrect</item>


When the error happens, waaay down in my call stack I see an error with looking up the textMultiLine enum value:

Caused by: java.lang.RuntimeException: no value found for 
            textMultiLine
	at org.robolectric.shadows.Converter$EnumOrFlagConverter.findValueFor(Converter.java:431)
	at org.robolectric.shadows.Converter$FlagConverter.fillTypedValue(Converter.java:408)
	at org.robolectric.shadows.Converter$FlagConverter.fillTypedValue(Converter.java:399)
	at org.robolectric.shadows.Converter.convertAndFill(Converter.java:157)
	at org.robolectric.shadows.Converter.convertAndFill(Converter.java:50)
	at org.robolectric.shadows.ShadowResources.createTypedArray(ShadowResources.java:232)
	at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:209)
	at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:55)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:485)
	at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.internal.bytecode.ShadowWrangler$ShadowMethodPlan.run(ShadowWrangler.java:437)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
	at android.widget.TextView.$$robo$$__constructor__(TextView.java:780)
	at android.widget.TextView.<init>(TextView.java)
	at android.widget.EditText.<init>(EditText.java)
	at android.widget.EditText.<init>(EditText.java)
	at android.widget.EditText.<init>(EditText.java)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at org.robolectric.shadows.RoboLayoutInflater.onCreateView(RoboLayoutInflater.java:41)
	at android.view.LayoutInflater.$$robo$$onCreateView(LayoutInflater.java:682)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:741)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at com.robwilliamson.healthyesther.fragment.BaseFragment.onCreateView(BaseFragment.java:48)
	at com.robwilliamson.healthyesther.fragment.edit.EditFragment.onCreateView(EditFragment.java:68)
	at android.support.v4.app.Fragment.$$robo$$performCreateView(Fragment.java:1962)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java)
	at android.support.v4.app.FragmentManagerImpl.$$robo$$moveToState(FragmentManager.java:1067)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.$$robo$$moveToState(FragmentManager.java:1248)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.$$robo$$moveToState(FragmentManager.java:1230)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.$$robo$$dispatchActivityCreated(FragmentManager.java:2042)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java)
	at android.support.v4.app.FragmentController.$$robo$$dispatchActivityCreated(FragmentController.java:165)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java)
	at android.support.v4.app.FragmentActivity.$$robo$$onStart(FragmentActivity.java:543)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java)
	at android.app.Instrumentation.$$robo$$callActivityOnStart(Instrumentation.java:1220)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java)
	at android.app.Activity.$$robo$$performStart(Activity.java:5949)
	at android.app.Activity.performStart(Activity.java)
	at sun.reflect.GeneratedMethodAccessor196.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.util.ReflectionHelpers$3.run(ReflectionHelpers.java:162)
	at org.robolectric.util.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:305)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:156)
	at org.robolectric.util.ComponentController$1.run(ComponentController.java:72)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ComponentController.invokeWhilePaused(ComponentController.java:69)
	at org.robolectric.util.ActivityController.start(ActivityController.java:143)
	at com.robwilliamson.healthyesther.edit.NoteEventActivityTest.newNoteIsAdded(NoteEventActivityTest.java:49)
	at com.robwilliamson.healthyesther.edit.NoteEventActivityTest.whenNewNoteIsAdded_createsNewNoteEvent(NoteEventActivityTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	... 1 more

I see you have "Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.robolectric.res.StyleData". It looks like we both have this failure due to a problem with Robolectric parsing our style tag content, right?

**Comment by jongerrish** [comment] 2018-10-31 18:11
GradleRobolectricTestRunner has been removed, instead you can simply use RobolectricTestRunner. You also no longer need to specify @Config(constants = ..., manifest = ...)

We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.

**Closed by jongerrish** 2018-10-31 18:11 UTC
Labels: resources
