### ISSUE TITLE
Calling getShadowApplication from thread returns null

### ISSUE THREAD

**Issue by mattott** [robolectric/robolectric#2001] opened 2015-08-20 23:35 UTC
I have a FutureTask that executes in a separate thread when `onAttachedToWindow()` is called in a  ViewGroup. The custom ViewGroup contains a CheckBox. Once the task isDone, the result is `post()`ed to the ViewGroup and `CheckBox.setChecked()` is called with the result of the task. The Task looks like this:

``` Java
public class LoadPrefsTask extends FutureTask<Boolean> {
    private final Context context;
    private final CheckBox checkBox;
    public LoadQuickStartPrefsTask(Context context, CheckBox checkBox) {
        super(new LoadPrefs(context));
        this.context = context;
        this.checkBox = checkBox;
    }
    @Override
    protected void done() {
        super.done();
        try {
            final boolean result = get();
            checkBox.post(new Runnable { public void run() { checkBox.setChecked(result); }});
            checkBox.postInvalidate();
        } catch (Exception e) {
            // Handle exception
        }
    }
    static class LoadPrefs implements Callable<Boolean> {
        private final Context context;
        LoadPrefs(Context context) {
            this.context = context;
        }
        @Override
        public Boolean call() throws Exception {
            return context.getSharedPreferences("MyPrefs", MODE_PRIVATE).getBoolean("MyKey", false);
        }
    }
}
```

The error points to the `get()` call.

``` Markdown
java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    **at my.package.LoadPrefsTask.done(LoadPrefsTask.java:13)**
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:380)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:247)
    at java.util.concurrent.FutureTask.run(FutureTask.java:267)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException
    at org.robolectric.internal.ShadowExtractor.extract(ShadowExtractor.java:5)
    at org.robolectric.Shadows.shadowOf(Shadows.java:941)
    at org.robolectric.shadows.ShadowContextWrapper.getShadowApplication(ShadowContextWrapper.java:297)
    at org.robolectric.shadows.ShadowContextWrapper.getSharedPreferences(ShadowContextWrapper.java:214)
    at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java)
    **at my.package.LoadPrefsTask$LoadPrefs.call(LoadPrefsTask.java:27)**
    **at my.package.LoadPrefsTask$LoadPrefs.call(LoadPrefsTask.java:20)**
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    ... 1 more
```

If I remove the call to `post()` and simply call `setChecked()`, then I get this error pointing to the `setChecked()` call:

``` Markdown
Exception in thread "Thread-3" java.lang.NullPointerException
    at org.robolectric.internal.ShadowExtractor.extract(ShadowExtractor.java:5)
    at org.robolectric.Shadows.shadowOf(Shadows.java:941)
    at org.robolectric.shadows.ShadowContextWrapper.getShadowApplication(ShadowContextWrapper.java:297)
    at org.robolectric.shadows.ShadowContextWrapper.getMainLooper(ShadowContextWrapper.java:293)
    at android.content.ContextWrapper.getMainLooper(ContextWrapper.java)
    at org.robolectric.shadows.ShadowAccessibilityManager.getInstance(ShadowAccessibilityManager.java:39)
    at android.view.accessibility.AccessibilityManager.getInstance(AccessibilityManager.java)
    at android.view.View.notifyAccessibilityStateChanged(View.java:6978)
    at android.widget.CompoundButton.setChecked(CompoundButton.java:117)
    **at my.package.LoadPrefsTask.done(LoadPrefsTask.java:14)**
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:380)
    at java.util.concurrent.FutureTask.set(FutureTask.java:229)
    at java.util.concurrent.FutureTask.run(FutureTask.java:270)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by kriegfrj** [comment] 2015-09-02 06:20
This might be related to issue #1879

**Comment by kriegfrj** [comment] 2015-09-29 03:22
Hi @mattott, I've marked off a couple of milestones in #1879 and was just having a look at some of the related issues to see if any might be fixed. I have a couple of suspicions at this stage - it could be a race condition due to the multi-threading (eg, the application may have already been cleaned up by the test harness before the future task exits), or it might be an implementation issue.

I think in your case we need a bit more information - it would help to see the actual test code that is failing (or better still, a trimmed-down version that still demonstrates the problem), in addition to seeing the code-under-test. That way we can reproduce it and debug it from there.

**Comment by zhangyanru** [comment] 2017-01-19 06:57
do you solve this problem?

**Comment by xian** [comment] 2017-03-06 22:15
@mattott -- I believe this is resolved in later versions of Robolectric. Please reopen if not. Thanks!

**Closed by xian** 2017-03-06 22:15 UTC
