### ISSUE TITLE
java.lang.NoSuchMethodError: android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener on 3.0-SNAPSHOT

### ISSUE THREAD

**Issue by WojciechKo** [robolectric/robolectric#1633] opened 2015-03-18 23:22 UTC
I am getting `NoSuchMethodError` while creating Activity in Robolectric 3.0-SNAPSHOT test.
Am I doing something wrong, or it is a bug?

Test
``` java
@RunWith(RobolectricTestRunner.class)
public class ActivityTest {

    private Activity activity;

    @Before
    public void setUp() {
        // ...
        activity = Robolectric.buildActivity(WalletDetailsActivity.class).create().start().restart().get();
    }
}
```

Stack trace  
```
java.lang.NoSuchMethodError: android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(Landroid/view/View;Landroid/support/v4/view/OnApplyWindowInsetsListener;)V
	at android.support.v7.app.ActionBarActivityDelegateBase.ensureSubDecor(ActionBarActivityDelegateBase.java:304)
	at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:225)
	at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
	at info.korzeniowski.walletplus.ui.BaseActivity.setContentView(BaseActivity.java:304)
	at info.korzeniowski.walletplus.ui.wallets.details.WalletDetailsActivity.onCreate(WalletDetailsActivity.java:46)
	at android.app.Activity.performCreate(Activity.java:5933)
	at org.robolectric.util.ReflectionHelpers$3.run(ReflectionHelpers.java:144)
	at org.robolectric.util.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:241)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:138)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:114)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:309)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:47)
	at org.robolectric.util.ActivityController.create(ActivityController.java:110)
	at org.robolectric.util.ActivityController.create(ActivityController.java:121)
	at info.korzeniowski.walletplus.test.ui.wallet.details.ActivityTest.setUp(ActivityTest.java:62)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:234)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:167)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

build.gradle
``` Groovy
    // Robolectric
    def robolectricVersion = '3.0-SNAPSHOT'
    testCompile "org.robolectric:shadows-support-v4:$robolectricVersion"
    testCompile "org.robolectric:robolectric:$robolectricVersion"
```

**Comment by polson** [comment] 2015-03-24 20:37
I'm also seeing this.  Not sure what the fix is.

**Comment by polson** [comment] 2015-03-24 21:52
Actually in my case we are stripping files from the v4 dependency to stay below the dex limit... so that was the cause of my issue.

Either way it seems like the v4 dependency is not getting fully built before the tests are being run.  I'd try doing something like `gradlew clean assemble test` when running on the CLI and see if that makes a difference.

**Comment by erd** [comment] 2015-03-30 02:40
I've seen this with certain versions (I think it was 21.0.2) of appcompat-v7. I honestly think that Google build the jar incorrectly which was why there was a 21.0.3. Could you try using version 22.0.0 and see if the problem persists?

**Comment by Manabu-GT** [comment] 2015-04-02 11:21
I am using version 22.0.0, but still seeing the same issue. Doing something like "gradlew clean assemble test" does not make any difference.

**Comment by menny** [comment] 2015-04-07 02:47
I see this exception with appcompat-v7 22.0.0
```
java.lang.NoSuchMethodError: android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(Landroid/view/View;Landroid/support/v4/view/OnApplyWindowInsetsListener;)V
	at android.support.v7.app.ActionBarActivityDelegateBase.ensureSubDecor(ActionBarActivityDelegateBase.java:316)
	at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:237)
	at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
```

I'm using `com.android.support:support-v4:22.0.0` and `com.android.support:appcompat-v7:22.0.0`

**Comment by erd** [comment] 2015-04-08 02:24
@menny Could you take a look at robolectric-samples/android-appcompat-v7? It's not very complex, but it uses `ActionBarActivity` without any issues. I'm curious what the difference could be.

**Comment by menny** [comment] 2015-04-09 01:16
I found the issue:
`testCompile 'com.squareup:fest-android:1.0.8'`

I removed that test-dependency from my `build.gradle` file, and I no longer see `NoSuchMethodError`.
I've added it to `robolectric-samples/android-appcompat-v7`, and BOOM, `NoSuchMethodError`.

**Comment by erd** [comment] 2015-04-10 02:52
That's bizarre. I can't image why having `fest-android` on the classpath would matter.

**Comment by menny** [comment] 2015-04-10 15:59
@erd, ya, so strange. I don't really know.
The only reason I tried it out was since I had a problem awhile ago, where a dependency brought in a wrong version of a library I was using. And that broke my app. Maybe, fest brings in an old version of support library?

**Comment by erd** [comment] 2015-04-24 00:40
We tried adding `testCompile 'com.squareup:fest-android:1.0.8'` to `android-appcompat-v7` and didn't see the failure. Is there anything else it could possibly be?

**Comment by vwmattr** [comment] 2015-04-24 00:48
@menny Another way to solve the issue that worked for me was just to exclude the 'support-v4' module from the fest dependency like this:
```
testCompile ('com.squareup:fest-android:1.0.8') {
        exclude module: 'support-v4'
}
```

**Comment by erd** [comment] 2015-04-24 17:08
`shadows-support-v` has a provided dependency on `support-v4` so it shouldn't be pulling in it's own version. I'm going to close this for now because I don't think there's anything we can do here.

**Closed by erd** 2015-04-24 17:08 UTC
Labels: 3.0, defect

**Comment by menny** [comment] 2015-04-24 17:16
Yes, @erd , I agree, there is nothing that can be done. At the workarounds should be acceptable.

**Comment by echodjb** [comment] 2015-05-12 02:25
@menny So can you tell me  how add it to robolectric-samples/android-appcompat-v7, thx

**Comment by menny** [comment] 2015-05-13 19:02
@echodjb , I don't understand. What is your question?

**Comment by Reegan01** [comment] 2015-11-02 11:49
I have the same problem in my Samsung phone others are well working . ..

**Comment by DavidMont** [comment] 2016-03-28 07:05
I have the same problem adding exclude on fest=android works!

```
testCompile ('com.squareup:fest-android:1.0.8') {
        exclude module: 'support-v4'
}
```

**Comment by ChenSiLiang** [comment] 2016-08-19 06:22
I try all the method but it **did not** work.
finally, I remove `start()` method, Bingo!
