### ISSUE TITLE
Issues when creating activity

### ISSUE THREAD

**Issue by dsharew** [robolectric/robolectric#2158] opened 2015-11-26 12:54 UTC
Here is my setup method: 

``` @Before
    public void setup() {

        activity = Robolectric.buildActivity(Main.class).create().start().visible().get();

    }
```

These are my tests:  ( on this run only `testMethodOne()` fails)  

```
 @Test
    public void testMethodOne() {
        Assert.assertTrue(Boolean.TRUE);
    }

    @Test
    public void testMethodTwo() {
        Assert.assertTrue(Boolean.TRUE);
    }

    @Test
    public void testMethodThree() {
        Assert.assertTrue(Boolean.TRUE);
    }

    @Test
    public void testMethodFour() {
        Assert.assertTrue(Boolean.TRUE);
    }
```

Sometime they pass sometimes they fail, when the fail I see random exception stacktrace I will try to post them as I get them:  

1) 

```
java.lang.IllegalStateException: immutable!
    at org.robolectric.res.ResBundle$ResMap.merge(ResBundle.java:212)
    at org.robolectric.res.ResBundle$ResMap.access$300(ResBundle.java:200)
    at org.robolectric.res.ResBundle.mergeLibraryStyle(ResBundle.java:162)
    at org.robolectric.res.OverlayResourceLoader.doInitialize(OverlayResourceLoader.java:24)
    at org.robolectric.res.XResourceLoader.initialize(XResourceLoader.java:29)
    at org.robolectric.res.XResourceLoader.getValue(XResourceLoader.java:52)
    at org.robolectric.res.OverlayResourceLoader.getValue(OverlayResourceLoader.java:51)
    at org.robolectric.res.RoutingResourceLoader.getValue(RoutingResourceLoader.java:31)
    at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:356)
    at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:352)
    at org.robolectric.shadows.ShadowAssetManager.getResourceText(ShadowAssetManager.java:70)
    at android.content.res.AssetManager.getResourceText(AssetManager.java)
    at android.content.res.Resources.getText(Resources.java:270)
    at org.robolectric.shadows.ShadowResources.getText(ShadowResources.java:358)
    at android.content.res.Resources.getText(Resources.java)
    at android.content.res.Resources.getString(Resources.java:360)
    at org.robolectric.shadows.ShadowContext.getString(ShadowContext.java:33)
    at org.robolectric.shadows.ShadowContextWrapper.getString(ShadowContextWrapper.java:81)
    at android.content.Context.getString(Context.java)
    at org.robolectric.util.ActivityController.getActivityTitle(ActivityController.java:108)
    at org.robolectric.util.ActivityController.attach(ActivityController.java:49)
    at org.robolectric.util.ActivityController$1.run(ActivityController.java:121)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
    at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
    at org.robolectric.util.ActivityController.create(ActivityController.java:118)
    at org.robolectric.util.ActivityController.create(ActivityController.java:129)
    at com.apposit.vms.mobile.test.unit.activity.LoginTest.setup(LoginTest.java:42)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

2) This time all the tests failed! with ff stacktrace.  

```
android.content.res.Resources$NotFoundException: String resource ID #0x7f05000a
    at android.content.res.Resources.getText(Resources.java:274)
    at org.robolectric.shadows.ShadowResources.getText(ShadowResources.java:358)
    at android.content.res.Resources.getText(Resources.java)
    at android.content.res.Resources.getString(Resources.java:360)
    at org.robolectric.shadows.ShadowContext.getString(ShadowContext.java:33)
    at org.robolectric.shadows.ShadowContextWrapper.getString(ShadowContextWrapper.java:81)
    at android.content.Context.getString(Context.java)
    at org.robolectric.util.ActivityController.getActivityTitle(ActivityController.java:108)
    at org.robolectric.util.ActivityController.attach(ActivityController.java:49)
    at org.robolectric.util.ActivityController$1.run(ActivityController.java:121)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
    at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
    at org.robolectric.util.ActivityController.create(ActivityController.java:118)
    at org.robolectric.util.ActivityController.create(ActivityController.java:129)
    at com.apposit.vms.mobile.test.unit.activity.LoginTest.setup(LoginTest.java:42)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

```

3) This time all test failed with the ff stacktrace:  

```

java.lang.RuntimeException: huh? ResName{com.apposit.vms.mobile:style/ActionBarStyle}
    at org.robolectric.shadows.Converter.convertAndFill(Converter.java:101)
    at org.robolectric.shadows.Converter.convertAndFill(Converter.java:50)
    at org.robolectric.shadows.ShadowResources.createTypedArray(ShadowResources.java:232)
    at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:209)
    at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:55)
    at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:485)
    at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:480)
    at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:475)
    at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
    at android.app.Activity.onApplyThemeResource(Activity.java:3673)
    at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:140)
    at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:85)
    at org.robolectric.shadows.ShadowActivity.setThemeFromManifest(ShadowActivity.java:85)
    at org.robolectric.shadows.CoreShadowsAdapter$1.setThemeFromManifest(CoreShadowsAdapter.java:35)
    at org.robolectric.util.ActivityController.attach(ActivityController.java:58)
    at org.robolectric.util.ActivityController$1.run(ActivityController.java:121)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
    at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
    at org.robolectric.util.ActivityController.create(ActivityController.java:118)
    at org.robolectric.util.ActivityController.create(ActivityController.java:129)
    at com.apposit.vms.mobile.test.unit.activity.LoginTest.setup(LoginTest.java:42)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by QuinnStephens** [comment] 2015-12-14 17:31
I'm having the same problem - I have a line in my setup method that sometimes produces the "immutable" exception:

`activity = Robolectric.buildActivity(LoginActivity.class).create().get();`

Sometimes the tests pass just fine, sometimes they crash. I can't figure out how to reproduce this consistently. I'm using robolectric 3.0 with junit 4.12, and my target android sdk version is 21.

Here's the stack trace:

```java.lang.IllegalStateException: immutable!
	at org.robolectric.res.ResBundle$ResMap.merge(ResBundle.java:212)
	at org.robolectric.res.ResBundle$ResMap.access$300(ResBundle.java:200)
	at org.robolectric.res.ResBundle.mergeLibraryStyle(ResBundle.java:162)
	at org.robolectric.res.OverlayResourceLoader.doInitialize(OverlayResourceLoader.java:24)
	at org.robolectric.res.XResourceLoader.initialize(XResourceLoader.java:29)
	at org.robolectric.res.XResourceLoader.getValue(XResourceLoader.java:52)
	at org.robolectric.res.OverlayResourceLoader.getValue(OverlayResourceLoader.java:51)
	at org.robolectric.res.RoutingResourceLoader.getValue(RoutingResourceLoader.java:31)
	at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:356)
	at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:352)
	at org.robolectric.shadows.ShadowAssetManager.getResourceText(ShadowAssetManager.java:70)
	at android.content.res.AssetManager.getResourceText(AssetManager.java)
	at android.content.res.Resources.getText(Resources.java:270)
	at org.robolectric.shadows.ShadowResources.getText(ShadowResources.java:358)
	at android.content.res.Resources.getText(Resources.java)
	at android.content.res.Resources.getString(Resources.java:360)
	at org.robolectric.shadows.ShadowContext.getString(ShadowContext.java:33)
	at org.robolectric.shadows.ShadowContextWrapper.getString(ShadowContextWrapper.java:81)
	at android.content.Context.getString(Context.java)
	at org.robolectric.util.ActivityController.getActivityTitle(ActivityController.java:108)
	at org.robolectric.util.ActivityController.attach(ActivityController.java:49)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:121)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at com.tablexi.fedtrak_android.activity.LoginActivityTest.beforeEach(LoginActivityTest.java:24)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by QuinnStephens** [comment] 2015-12-14 17:40
After splitting up the line, I found that it was the `create` method specifically that seems to be throwing the exception.

**Comment by jaredsburrows** [comment] 2015-12-15 08:29
@yamo21  What is `Main.java`?

**Comment by yamo21** [comment] 2015-12-16 06:34
@jaredsburrows   It my main Activity class.

**Comment by jaredsburrows** [comment] 2015-12-16 06:37
@yamo21 Yes, show us the code.

**Comment by yamo21** [comment] 2015-12-16 06:49
Main.java: 

```

package com.apposit.vms.mobile.activity;

import android.content.BroadcastReceiver;
import android.content.ComponentName;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.os.AsyncTask;
import android.os.Bundle;
import android.util.Log;
import android.view.Window;
import android.view.WindowManager;

import com.apposit.vms.mobile.ApplicationContextHolder;
import com.apposit.vms.mobile.Constants;
import com.apposit.vms.mobile.R;
import com.apposit.vms.mobile.WithNoWindowTitle;
import com.apposit.vms.mobile.dataprovider.SystemDataProvider;
import com.apposit.vms.mobile.security.SecurityProvider;

public class Main extends AbstractActivity implements WithNoWindowTitle {

	private static final String LOG_TAG = Main.class.getSimpleName();

	private static final int CONFIGURE_SETTINGS_REQUEST_CODE = 1;

	@Override
	protected void onCreate(Bundle savedInstanceState) {

		ApplicationContextHolder.setContext(this.getApplicationContext());

		if(savedInstanceState == null){
			savedInstanceState = new Bundle();
		}

		this.requestWindowFeature(Window.FEATURE_NO_TITLE);

		this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);

		super.onCreate(savedInstanceState);

		setContentView(R.layout.splash_screen);

		final PackageManager packageManager = getPackageManager();
		final ComponentName componentName = new ComponentName(this, Main.class);
		packageManager.setComponentEnabledSetting(componentName, PackageManager.COMPONENT_ENABLED_STATE_ENABLED, PackageManager.DONT_KILL_APP);

		launchApplication();
	}

	@Override
	protected void onResume() {
		super.onResume();
	}

	private void launchApplication() {

		new AsyncTask<Void, Void, Void>(){

			boolean isConfigured = false;

			Throwable exception;

			@Override
			protected Void doInBackground(Void... params) {

				try {

					isConfigured = SystemDataProvider.getInstance(Main.this).isConfigured(Main.this);

				}catch(Throwable th) {
					exception = th;
				}

				return null;
			}

			@Override
			protected void onPostExecute(Void result) {

				if(null != exception) {

					handleException(exception, null);

				} else if(isConfigured) {

					if (isLoggedOn())
						goToHome();
					else
						goToLogin();

				} else {

					Intent intent = new Intent(Main.this, Settings.class);

					startActivityForResult(intent, CONFIGURE_SETTINGS_REQUEST_CODE);
				}

				finish();
			}

		}.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR);
	}

	@Override
	protected void onActivityResult(int requestCode, int resultCode, final Intent data) {

		if(requestCode == CONFIGURE_SETTINGS_REQUEST_CODE) {

			launchApplication();

		}

	}


	@Override
	public void setContentView(int layoutResID) {
		super.setContentView(layoutResID);
	}

	@Override
	protected BroadcastReceiver getLoginSessionExpiredBroadcastReceiver() {
		return super.getLoginSessionExpiredBroadcastReceiver();
	}

	@Override
	protected BroadcastReceiver getLocaleChangedBroadcastReceiver() {
		return super.getLocaleChangedBroadcastReceiver();
	}
}


```

**Comment by phienkaka** [comment] 2015-12-27 08:05
I also got java.util.ConcurrentModificationException when try to build an Activity with Robolectric

My code
```java
FragmentActivity fragmentActivity = Robolectric.buildActivity(FragmentActivity.class).create().start().resume().get();
```

And when I check in the log, this exception happen in create() 

Here's the stack trace:

```
java.util.ConcurrentModificationException
	at java.util.ArrayList.sort(ArrayList.java:1456)
	at java.util.Collections.sort(Collections.java:141)
	at org.robolectric.res.ResBundle.put(ResBundle.java:32)
	at org.robolectric.res.ResBunch.put(ResBunch.java:12)
	at org.robolectric.res.ValueResourceLoader.processNode(ValueResourceLoader.java:36)
	at org.robolectric.res.XpathResourceXmlLoader.processResourceXml(XpathResourceXmlLoader.java:22)
	at org.robolectric.res.ValueResourceLoader.processResourceXml(ValueResourceLoader.java:19)
	at org.robolectric.res.XmlLoader.processResourceXml(XmlLoader.java:46)
	at org.robolectric.res.DocumentLoader.loadResourceXmlFile(DocumentLoader.java:47)
	at org.robolectric.res.DocumentLoader.loadFile(DocumentLoader.java:40)
	at org.robolectric.res.DocumentLoader.load(DocumentLoader.java:30)
	at org.robolectric.res.PackageResourceLoader.loadEverything(PackageResourceLoader.java:32)
	at org.robolectric.res.PackageResourceLoader.doInitialize(PackageResourceLoader.java:19)
	at org.robolectric.res.XResourceLoader.initialize(XResourceLoader.java:29)
	at org.robolectric.res.XResourceLoader.getValue(XResourceLoader.java:52)
	at org.robolectric.res.PackageResourceLoader.getValue(PackageResourceLoader.java:5)
	at org.robolectric.res.RoutingResourceLoader.getValue(RoutingResourceLoader.java:31)
	at org.robolectric.shadows.ShadowAssetManager.resolveStyle(ShadowAssetManager.java:343)
	at org.robolectric.shadows.ShadowAssetManager.applyThemeStyle(ShadowAssetManager.java:286)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.applyStyle(ShadowResources.java:461)
	at android.content.res.Resources$Theme.applyStyle(Resources.java)
	at android.app.ContextImpl.getTheme(ContextImpl.java:838)
	at android.content.ContextWrapper.getTheme(ContextWrapper.java:121)
	at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:135)
	at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:85)
	at org.robolectric.shadows.ShadowActivity.setThemeFromManifest(ShadowActivity.java:85)
	at org.robolectric.shadows.CoreShadowsAdapter$1.setThemeFromManifest(CoreShadowsAdapter.java:35)
	at org.robolectric.util.ActivityController.attach(ActivityController.java:58)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:121)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at pt.rocket.utils.CheckVersionTest.testShowDialogShouldShowUpdateLater(CheckVersionTest.java:77)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ffelini** [comment] 2016-01-22 09:53
I get in to the same issue. This happens very often.
Any updates here?

**Comment by scottkennedy** [comment] 2016-02-10 19:45
+1

**Comment by mquigley-ck** [comment] 2016-02-24 19:34
Yep this is happening a bunch.

```
java.lang.IllegalStateException: immutable!
	at org.robolectric.res.ResBundle$ResMap.merge(ResBundle.java:212)
	at org.robolectric.res.ResBundle$ResMap.access$300(ResBundle.java:200)
	at org.robolectric.res.ResBundle.mergeLibraryStyle(ResBundle.java:162)
	at org.robolectric.res.OverlayResourceLoader.doInitialize(OverlayResourceLoader.java:24)
	at org.robolectric.res.XResourceLoader.initialize(XResourceLoader.java:29)
	at org.robolectric.res.XResourceLoader.getValue(XResourceLoader.java:52)
	at org.robolectric.res.OverlayResourceLoader.getValue(OverlayResourceLoader.java:51)
	at org.robolectric.res.RoutingResourceLoader.getValue(RoutingResourceLoader.java:31)
	at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:356)
	at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:352)
	at org.robolectric.shadows.ShadowAssetManager.getResourceText(ShadowAssetManager.java:70)
	at android.content.res.AssetManager.getResourceText(AssetManager.java)
	at android.content.res.Resources.getText(Resources.java:270)
	at org.robolectric.shadows.ShadowResources.getText(ShadowResources.java:358)
```

**Comment by juanyanezgc** [comment] 2016-03-08 14:41
Any update on this one? I'm facing the same issue as well

**Comment by scottkennedy** [comment] 2016-04-07 16:54
This should be fixed now.

**Comment by jongerrish** [comment] 2018-10-31 16:17
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.

**Closed by jongerrish** 2018-10-31 16:17 UTC
