### ISSUE TITLE
Calls to java.lang.System are not intercepted

### ISSUE THREAD

**Issue by andymstone** [robolectric/robolectric#1786] opened 2015-05-06 19:40 UTC
In the latest 3.0-snapshot, `InstrumentationConfiguration` includes a list of methods to be intercepted - including `java.lang.System.nanoTIme`, `java.lang.System.currentTimeMillis` and `java.lang.System.arraycopy`.

But in `InstrumentationConfiguration.shouldAcquire` any names starting with `java.` are filtered out and so the methods are not intercepted when the class is loaded by `InstrumentingClassLoader`.

This means that calls to e.g. `System.currentTimeMillis` return different values to `SystemClock` (which is shadowed).

This probably explains why @tmrudick is still having problems with issue #1590.

**Comment by tmrudick** [comment] 2015-05-06 22:32
Thanks, @andymstone! This issue has fallen off my radar recently. Will look into submitting a patch this week if you don't get to it first.

**Comment by erd** [comment] 2015-05-06 23:21
The `java.lang.System` method replacement happens in `ShadowWrangler.getInterceptionHandler` rather than `InstrumentingClassLoader`.

**Comment by andymstone** [comment] 2015-05-12 21:09
To clarify - after another look today I realised that the calls to e.g. `System.currentTimeMillis` are intercepted when called by Android code (e.g. `(new Time()).setToNow()` will result in the `ShadowSystemClock` getting called), but calls are not intercepted when I call `System.currentTimeMillis` directly from my code.  I don't understand enough of the magic to know if this is by design or by accident.

**Comment by andymstone** [comment] 2015-05-13 08:12
Test case demonstrating the issue:

```
    @Test
    public void test()  {
        ShadowSystemClock.setNanoTime(3141592000000L);

        final Time t = new Time(); // android.text.format.Time
        t.setToNow();
        assertEquals(3141000, t.toMillis(true)); // Passes - currentTimeMillis is intercepted

        Calendar c = Calendar.getInstance(); // java.util.Calendar
        assertEquals(3141000, c.getTimeInMillis()); // Fails - currentTimeMillis is not intercepted
    }

```

**Comment by tomrozb** [comment] 2015-06-20 10:40
This causes problems with `ConditionVariable` which is stuck in an endless loop. 'System.currentTimeMillis' always returns 0. 

```
                long now = System.currentTimeMillis();
                long end = now + timeout;
                while (!mCondition && now < end) {
                    try {
                        this.wait(end-now);
                    }
                    catch (InterruptedException e) {
                    }
                    now = System.currentTimeMillis();
                }
                return mCondition;
```

**Comment by kriegfrj** [comment] 2015-06-24 02:15
Just curious @tomrozb, but were you running this code on the UI thread or another thread/async task? I don't think it would be good to use this on the UI thread because it would block the UI thread, which is a no-no if you want to maximise the app responsiveness. You'd be better off posting poll events to the UI thread and checking the results in the poll handler.

The reason I ask is because in the fixes I'm looking at for #1879 and the architecture I'm trying to put together, I can probably make this code work as-is without the need to shadow it, but it would only work (at least, only work easily) if called on a non-UI thread. This is a consequence of the fact that the test thread shares the UI thread. I'm thinking to actually make Robolectric assert if `wait()` or `sleep()` is called from the UI thread - not only will this greatly simplify the implementation, but it will also help developers find bugs in their code. The only other alternative would be to separate the UI thread from the test thread, but this would complicate the test implementation.

**Comment by tomrozb** [comment] 2015-06-24 17:46
@kriegfrj I'm unable to check it but it is possible that this code was blocking UI thread. A simple solution was to replace `ConditionVariable` with `CountDownLatch` which solved the problem.

**Comment by sibeliusseraphini** [comment] 2016-03-16 17:49
Why `currentTimeMillis` of `ShadowSystemClock` doesn't have an `@Implementation` annotation ? 

https://github.com/robolectric/robolectric/blob/master/robolectric-shadows%2Fshadows-core%2Fsrc%2Fmain%2Fjava%2Forg%2Frobolectric%2Fshadows%2FShadowSystemClock.java#L85

This question http://stackoverflow.com/questions/31659771/robolectric-3-0-mocking-system-currenttimemillis explains better the current behavior of the ShadowSystemClock

`SystemClock.setCurrentTimeMillis` changes ` ShadowSystemClock.currentTimeMillis()`, but not `System.currentTimeMillis()`

any progress on this or any workaround?

**Comment by kriegfrj** [comment] 2016-03-18 07:16
Hi @sibeliusseraphini, `ShadowSystemClock.currentTimeMillis()` doesn't have an `@Implementation` annotation because it is not actually implementing a method in the `SystemClock` class like a shadow normally does. As @erd noted in an earlier post in this thread, it is invoked via an interception handler, which redirects the method call on the caller's side rather than on the callee's side.

As I noted in my answer on StackOverflow, there is an `instrumentedPackages` option (which may not have been available when @andymstone first raised this issue) in the `@Config` annotation to specify additional packages to instrument. If you specify the package(s) that you are testing to this annotation, then they should get instrumented (disclaimer: I haven't tried it myself recently) - which means that when they call `System.currentTimeMillis()` they will retrieve the time from `ShadowSystemClock.currentTimeMillis()` instead of the real current system time.

Hope that this helps; let us know if you get stuck again.

**Comment by sibeliusseraphini** [comment] 2016-03-18 10:43
@kriegfrj thanks for the explanation

I've decided to create a `TimeProvider` interface to encapsulate calls to System.currentTimeMillis, then I can easily mock on my tests.

**Comment by kriegfrj** [comment] 2016-03-18 12:00
@sibeliusseraphini, if this works for you then go for it, but there are a couple of drawbacks to that approach. (It also strikes me as a bit of a "code smell" when we have to add extra layers of encapsulation for something as simple as calling a single method in the System class for no other reason than to make it testable.) Especially if you're working on an existing body of code, this will mean going back and retrofitting the `TimeProvider` interface to all the existing code, and if you miss one or two you might end up with inconsistent results. On a larger project with multiple developers you always run the risk of people forgetting to use the encapsulated interface and instead calling `System.currentTimeMillis()` directly.

Also, the `TimeProvider` interface approach will only work for simple unit tests. If you are trying to integrate your tests with third party libraries that rely on the current time (more complicated unit tests or integration tests), the `TimeProvider` interface approach will produce inconsistent results because they won't access the system time through the mocked interface.

The Robolectric approach doesn't suffer from either of these weaknesses.- it will work in both cases (provided you configure Robolectric to instrument the third party libraries also).

I'm not trying to tell you how to do it, but I thought to let you know of the options.

**Comment by sibeliusseraphini** [comment] 2016-03-18 12:09
That's true, I will try to test your approach as well.

I wonder why I can't `setCurrentTimeMillis` if a value lower than `now()`https://github.com/robolectric/robolectric/blob/master/robolectric-shadows%2Fshadows-core%2Fsrc%2Fmain%2Fjava%2Forg%2Frobolectric%2Fshadows%2FShadowSystemClock.java#L44

But I can set the nanoTime using setNanoTime, is this an inconsistency?

I think it is better (more readable) to use TimeUnit to convert among millis and nanos

**Comment by kriegfrj** [comment] 2016-03-18 12:13
Yes, it is an inconsistency. I have fixed this inconsistency on the branch in PR #2166. Unfortunately this PR has stalled for a while because the last couple of issues have proven more intractable than I had anticipated, and because of time pressures on my side. Hopefully soon...

**Comment by sibeliusseraphini** [comment] 2016-03-18 13:04
thanks for your great help, I will wait until this PR or that issue is fixed

**Comment by jongerrish** [comment] 2018-11-05 00:55
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.

**Closed by jongerrish** 2018-11-05 00:55 UTC
