### ISSUE TITLE
Convert build system to Gradle

### ISSUE THREAD

**Issue by erd** [robolectric/robolectric#1854] opened 2015-05-30 20:49 UTC
Quite a bit of work was done on the `build-with-gradle` branch, but there were some differences between how Maven sets up the classpath for multi-module projects that were different from what Gradle does that prevented us from finishing it up. We also couldn't find a good apt and velocity plugin for Gradle.

**Comment by erd** [comment] 2015-05-30 20:50
Conversation that was extracted from #1830.

>For instance, 4 Gradle modules:
>
>org.robolectric:robolectric-core:3.0 // <-- all modules rely on the "core"
>org.robolectric:robolectric-shadows-support-v4:3.0
>org.robolectric:robolectric-shadows-httpclient:3.0
>org.robolectric:robolectric-shadows-maps:3.0
>
>I would just hate to spend a lot of time converting this project to Gradle and then it get rejected.
>
>Also, consider merging @lexs PR here, #1840. Before I work on moving to gradle. It is quite large.

**Comment by erd** [comment] 2015-05-30 20:52
> Also, consider merging @lexs PR here, #1840. Before I work on moving to gradle. It is quite large.

That's not getting merged until after 3.0 is released.

**Comment by erd** [comment] 2015-05-30 20:57
> For instance, 4 Gradle modules

Unless there is a really good reason to change how the modules are split up, I'd like to preserve the existing structure. Changing the structure and converting to Gradle are separate concerns.

**Comment by jaredsburrows** [comment] 2015-05-31 00:47
+1 :)

**Comment by jaredsburrows** [comment] 2015-06-13 16:43
I want to start looking into this soon. I have been updating a lot of my apps lately.

**Comment by jaredsburrows** [comment] 2015-06-28 21:44
I am taking a look at this: https://github.com/jaredsburrows/robolectric/tree/build-with-gradle

**Comment by sibeliusseraphini** [comment] 2016-03-16 15:45
:+1:

**Comment by jongerrish** [comment] 2016-06-14 18:33
Closing as a duplicate of https://github.com/robolectric/robolectric/issues/2487

**Closed by jongerrish** 2016-06-14 18:33 UTC
Labels: 3.1
